### ISSUE TITLE
Crowdsale with automatic refunds over the cap

### ISSUE THREAD

**Issue by konr4d** [OpenZeppelin/openzeppelin-contracts#1018]
## 🎉 Description

I would like to propose a variant of CappedCrowdsale allowing purchases over the cap, but automatically returning the value over back to the sender.

- [x] 📈 This is a feature request.

## 📝 Details

The changes would probably involve:
- creating a new extensible internal view _getWeiAmountToBook(msg.value) in Crowdsale.sol,
- creating a new public view weiToCap(),
- overriding _forwardFunds().

## 🔢 Example snippets of code

Changes in Crowdsale.sol:
```
function _getWeiAmountToBook(uint256 _weiAmount) 
    internal view returns (uint256)
{
    return _weiAmount;
}

function buyTokens(address _beneficiary) public payable {

    uint256 weiAmount = _getWeiAmountToBook(msg.value);
    ...
}
```

In the new contract:
```
function _getWeiAmountToBook(uint256 _weiAmount)
    internal view returns (uint256)
{
    uint256 _weiRaisedSum = weiRaised.add(_weiAmount);
    if (_weiRaiseSum > cap) {
        uint256 _weiOverCap = _weiRaisedSum.sub(cap);
        return _weiAmount.sub(_weiOverCap); 
    } else {
        return _weiAmount;
    }
}

function _forwardFunds() internal {
    uint256 _weiAmountToBook = _getWeiAmountToBook(msg.value);
    wallet.transfer(_weiAmountToBook);
    uint256 _weiOverCap = msg.value.sub(_weiAmountToBook);
    if (_weiOverCap > 0) {
        msg.sender.transfer(_weiOverCap);
    }
}
```

Please, let me know if this makes sense and if yes, I will provide a PR.

**Comment by shrugs** [comment]
My main opposition to this is that it's additional logic in the smart contract that could (should?) be part of the client. A client software for investing in a crowdsale should look at the cap, look at what's been raised, and then only allow someone to invest up to that amount. Now, this gets annoying towards the end of a popular crowdsale, sure, but I'm still not certain that this sort of logic belongs in the contract.

**Comment by frangio** [comment]
Closing as crowdsale contracts are no longer a part of the library.
