### ISSUE TITLE
ECRecover for mutisig

### ISSUE THREAD

**Issue by NoahMarconi** [OpenZeppelin/openzeppelin-contracts#1051]
## Description

Working on a use case where we need to verify multiple signatures. To stick with the convention of passing bytes, we'd like to use a tightly packed array of signatures (no array metadata, simply a dynamic bytes array with signatures back to back).

Would be great to have an addition in ECRecover as the only public example I can find is GPL encumbered.

- [x] 📈 This is a feature request.

## 🔢 Example

```
// message
"adsadasdasd"
// hashed message
0x4e33c339c1af7f4b7eb22280578a3dee028405fb29d890fb569f7de6466711b1

// address
0x143d7089F744A31A3A328C39eA832597003b90e8
// sig
0x453ae00ea53702bd30de3769cb5944c3ea28c9808345065fffa043e5b78d8a3315506d1bec9e711c8b15d1410d1bf9252fa6e48e66350476a2d106f688beb5781b

// wallet
0xa6Fa92f4Bd47c9aAB5DF93aDAcAd6536759479EE
// sig
0xe4d08f573371fb6f39e0e06d3e8be8878d1c87aac4e9aaad879c1c752b67c4b61786ee49910782ba1df1c3b78c102c36bd1c5676f8950ff44c7473f165a6c9461b


// combined
0x453ae00ea53702bd30de3769cb5944c3ea28c9808345065fffa043e5b78d8a3315506d1bec9e711c8b15d1410d1bf9252fa6e48e66350476a2d106f688beb5781be4d08f573371fb6f39e0e06d3e8be8878d1c87aac4e9aaad879c1c752b67c4b61786ee49910782ba1df1c3b78c102c36bd1c5676f8950ff44c7473f165a6c9461b
```

**Comment by Amxx** [comment]
IMO, multisigs contract should implement ERC1271. This means each multisig will be responsible of the way they verify signatures. [Third parties can then ask the multisig if a signature is recognized as valid.](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/SignatureChecker.sol#L21-L35)
