### ISSUE TITLE
File Import Callback not Supported

### ISSUE THREAD

**Issue by breckinridge22** [OpenZeppelin/openzeppelin-contracts#1067]
## 🎉 Description

I am using the Open Zeppelin Erc20 interface to create a token contract. When trying to import those dependencies and compile the contract I get a File Import Call Back not supported error. 

- [ X] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- I am using the most recent version of open zeppelin.?
- I am deploying to test rpc.
- Using truffle.

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here.

## 🔢 Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

```
truffle unbox webpack
<create new token contract and import open zepellin ERC20 interface>
truffle compile 
```

**Comment by cameel** [comment]
This error means simply that the compiler could not find the file you import (and yeah, the error message could be better; https://github.com/ethereum/solidity/issues/11413). You might have forgotten to install OpenZeppelin with npm or maybe `node_modules/` is in a location where Truffle cannot find it.

If you still have this problem I could help you solve it but given that this bug report is ancient now it's more likely that you already moved on and this should be closed instead :)

**Comment by Amxx** [comment]
Hello @breckinridge22 

Thank you for your issue, and for trying to include code to reproduce the bug. The thing, what you shared doesn't reproduce anything unless we know what you did in "<create new token contract and import open zepellin ERC20 interface>"

I've personnally build many erc20 using both truffle and hardhat, which no issue. My guess is that either the our package is not installed, or you are not providing the right path to it.

Could you share a link to a repo that contains your ERC20 contract, so we can actually have a look and try reproducing the issue on our side ?
