### ISSUE TITLE
Add testing guide

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#1077]
We should have a readme in the `test` directory, explaining how OZ tests are structured, linking to relevant truffle docs and maybe including a couple of frequent errors.

**Comment by LincolnZeng** [comment]
Hi , I find the TESTING.md in file test folder mentions "please reference OpenZeppelin’s Testing Guide." , Can I ask where I can find it?

**Comment by nventuro** [comment]
We don't have one yet, looks like that document is wrong. I intend to work on this very soon though.

**Comment by ianbrtt** [comment]
@nventuro can I help you with this? I would like to learn more about the testing process while writing documentation

**Comment by nventuro** [comment]
@ianbrtt go ahead! Do note that some tests still need refactoring and are not up to snuff, but you can take a look at some of the newer ones for inspiration (e.g. `Pausable`, the `Escrow` tests, `RefundablePostDeliveryCrowdsale`).

**Comment by projectoblio** [comment]
How do i even run a test, node won't compile it

I just want to run the "getBouncerSigner" function but I can't figure out how.... Babel won't even recursively compile it

**Comment by ianbrt** [comment]
Hi @projectoblio, Ive been learning about these tests and started writing a guide in the [zeppelin forum]( https://forum.zeppelin.solutions/t/testing-guide/150/18). You can search there maybe it helps what I learnt and if you have any questions you can do them there, so we all learn from each other. Hope it helps

**Comment by nventuro** [comment]
Hey @projectoblio, what issue are you having precisely? You shouldn't require Babel to run our suite, `npm test` (after an `npm install` should just work).

**Comment by frangio** [comment]
The [Moloch Testing Guide](https://github.com/MolochVentures/moloch/tree/master/test#readme) is pretty good and aligned with the style we have always tried to follow, so please refer to this guide when writing tests for this project.
