### ISSUE TITLE
Extend Escrows to use tokens

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#1099]
Currently, the [Escrow](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/release-v1.11.0/contracts/payment/Escrow.sol) contracts can only be used to transfer Ether. #1010 introduced a contract very similar to a [ConditionalEscrow](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/release-v1.11.0/contracts/payment/ConditionalEscrow.sol), with the added bonus of also allowing tokens to be transferred.

Do we want to extend the current `Escrow` so that it can also use tokens? The original intent behind it was to enable [async payments](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/release-v1.11.0/contracts/payment/PullPayment.sol), which is not required for an ERC20 token (since in both cases it'd boil down to a `transfer` call). It is when `ConditionalEscrow`s are considered that the benefits emerge: we could have [refund payments](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/release-v1.11.0/contracts/payment/RefundEscrow.sol) with tokens, the aforementioned timelock, etc.

If there's interest in this idea, I can try out some designs and come back with a more concrete proposal (in terms of implementation details).

**Comment by nedodn** [comment]
The `Timelock` contract was originally written as an extension to `TokenTimelock` to handle tokens and Ether, and I would agree with frangio that it is fundamentally different than an Escrow. The Timelock contracts seem to me to be more for one time payments to a single person, while the Escrows seem more suitable for multiple payments to different people. I think those use cases are different enough to warrant two separate contracts to avoid confusion. 

Extending the `Escrow` contracts to support tokens would probably be important, I think the issues that will arise from that will be whether or not you want them to generically support many tokens or only support one type. Also that as far as I know, there's no way to track incoming token transfers in contract, like you can with ether, so you won't really know who's transferring what into the contract.

**Comment by nventuro** [comment]
@frangio The Escrows are a payment system: assets are handled to the Escrow, which then decides what to do with them based on a condition (e.g. give them immediately to the payee, refund the payer if a condition is met, release the funds after a certain date, etc.). Extending the current Ether-only implementation to tokens feels like a natural step forward to me.

@nedodn For random tokens, sure, you won't be able to tell, but any compliant (e.g. ERC20) token should have something akin to a `Transfer` event.

Regarding one-off vs multiple payments, I don't see a reason to support both when the former is (by definition) doable with the latter. Pragmatically, I'd expect the deployment cost of a `Timelock` to be (much) higher than the transaction cost to register a payment in a `TimelockedEscrow`, though I don't have data for this yet.

I'll try out a sample API I have in mind soon, and come back with the aforementioned data and a more concrete proposal.

**Comment by nedodn** [comment]
@nventuro  True about the `Transfer` event but you would have to run some sort of server or watcher off-chain in order to keep track of how many tokens were sent. I don't think there's any on-chain way to monitor those transfers, so the only information you'd have about a contract would be its total token balance. This may or may not be an issue depending on what you're using the `Escrow` for though it may be difficult to keep track of multiple payees and payers with tokens. Might make sense to have the payer approve the contract and then have the contract pull the tokens from the payer, so you'd know how many were supposed to be sent. 

There is probably less gas used with a `TimelockedEscrow` transaction but you'd still have to deploy that as well wouldn't you? Unless you have one general contract for everyone keeping track of each transactions' deadlines as well as the amount. Which wouldn't be too difficult, I wrote something similar a while ago that basically does that.

**Comment by nventuro** [comment]
Approving and pulling wouldn't work, since nothing prevents the payer from transferring all of their tokens into a separate account: this is similar to #901, and the whole reason why Escrows were introduced in the first place.

Your gas costs comment is correct in that there is indeed a (higher?) cost of deploying the Escrow itself, but since it's a one-off thing, it should be amortized over time.

There are two somewhat orthogonal issues being discussed here:
 1. Should Escrows be extended to use tokens?
 1. Should Escrows replace the 'old' `Timelock` and `TokenTimelock`?

`1` is what I intend for us to answer here (including a tentative API). 

Regarding `2`, I've been convinced offline that a one-off Escrow deserves being a thing, simply because the attack surface vector is smaller, as well as the risk (i.e. it will only contain funds for _one_ payment, preventing a DAO-hack style attack). I'm not sure what these contracts should look like (since they will pretty much share the Escrow's logic), maybe inheritance adding these restrictions? Anyway, this is not the place for that discussion: we should open a separate issue.

**Comment by nventuro** [comment]
https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1595 requires these to exist, so we probably want to revisit this conversation soon.

**Comment by nventuro** [comment]
#1 and #239 both have use-cases for timelocked-ether: a feature we already have for tokens, that could be easily implemented via `ConditionalEscrow`.

**Comment by nventuro** [comment]
An ether timelock came up again in #443.

**Comment by ramikalai** [comment]
Hey @nventuro, is there any progress/effort being made on the tokenescrow contracts? I believe this could definitely be useful.

**Comment by nventuro** [comment]
Hey @ramikalai! While we're still definitely interested in having this in OpenZeppelin, there's noone that I know of currently working on it. 

The actual implementation and tests are probably not too hard, but we'd really like to get the design and API right, which is way trickier.

**Comment by ramikalai** [comment]
@nventuro I'm happy to help if there's anything I can look at?

**Comment by frangio** [comment]
> I believe this could definitely be useful.

@ramikalai I'm curious to hear your use case! It will help prioritize this for us.

**Comment by ramikalai** [comment]
@frangio We are looking at building escrow wallets for ERC20 tokens. I think if done properly (as part of openzeppelin), then this could be built in a way that is extendable to multisig wallets/multiownable contracts for ERC20.

Effectively, what I think needs to be built is 
- An abstract mulit-ownership contract (Similar to Ownable.sol).
- An abstract escrow contract: This would define the approval mechanisms for the child's different methods. Effectively a modifier that checks a condition is true, and an approval function that takes into account multiple approvals as per multi-ownable.
- Implement the ERC20 token escrow by inheriting the above contracts.

The first contract can be reused elsewhere for ERC20 multisig wallets for example.
The second can be reused for Ether escrow.

Let me know your thoughts on this and how we can progress things.

**Comment by frangio** [comment]
>An abstract mulit-ownership contract (Similar to Ownable.sol).

Generally we believe that complex authorization mechanisms like multisig should be separate from the contract they manage. So the contract should only have a single owner which is a itself a multisig wallet. Have you found scenarios where this doesn't work well?

>An abstract escrow contract: This would define the approval mechanisms for the child's different methods.

I don't understand this idea very well. Can you give an example of an approval mechanism? Would this work _without_ multi-ownable?

**Comment by ramikalai** [comment]
Hi @frangio, sorry got caught up at work.

On your first point, yes I agree that could definitely work.

An example of approval mechanisms are a simple toggle of approval that each owner can interact with. Other mechanisms can be added as well such as  m of n if ownership is implemented through a multisig wallet. Approval can be on a transaction basis, meaning that parties approve a certain transaction and then approval is reset until the next transaction

**Comment by frangio** [comment]
Escrows removed in 5.0.
