### ISSUE TITLE
Facilities for smart accounts or identity contracts

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#1104]
Smart accounts came up in https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1005. They came up in the context of `SignatureBouncer` because the contract is designed to work with ECDSA signatures by externally owned accounts, and thus doesn't support smart accounts. I proposed that instead of changing `SignatureBouncer` we first look into generalizing `ECRecovery` or building an intermediate abstraction.

It seems to me like we need a function `isSignedBy(bytes message, address account, bytes signature) returns (bool)` that does ECDSA verification for EOAs, and calls `account.isValidSignature(signature, message)` for contracts.

I started going through all the identity ERCs to see if there is a function like `isValidSignature` already proposed... but there are a lot of related ERCs and I got a bit lost. I don't think I saw anything like this function though. I'd appreciate some thoughts from someone more interiorized in this space. Pinging @PhABC since he brought it up initially.

I'm nore sure what facilities other than this we could provide.

**Comment by PhABC** [comment]
Done! See https://github.com/ethereum/EIPs/pull/1258

**Comment by shrugs** [comment]
affected by: https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1272

**Comment by nfurfaro** [comment]
Hello. Has there been any progress on this front?

**Comment by abcoathup** [comment]
Hi @nfurfaro,

The roadmap includes redesigning access control https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2068 though I am not aware of anything specific to smart accounts/identity contracts.

I suggest posting in the Community Forum with what your needs are as this would be great for thinking about future additions to OpenZeppelin Contracts: https://forum.openzeppelin.com/

**Comment by thegostep** [comment]
I'd like to bump this - would be useful to have a reference implementation

**Comment by frangio** [comment]
@thegostep What are interested in specifically?

**Comment by thegostep** [comment]
@frangio added an example in #2424

**Comment by frangio** [comment]
My updated thinking is that the scope of this is too big for OpenZeppelin Contracts to tackle, since a complete system of smart accounts needs a lot of supporting infrastructure.
