### ISSUE TITLE
Introduce BurnableERC721Token contract

### ISSUE THREAD

**Issue by dougiebuckets** [OpenZeppelin/openzeppelin-contracts#1126]
## 🎉 Description

Does it make sense for us to introduce a BurnableERC721Token Contract similar to the BurnableToken contract we have for ERC20s? For ERC20 we simply subtract tokens from the balances mapping in StandardToken whereas for the proposed BurnableERC721Token contract we would need to ensure that the specific token ID or index is eliminated. Pulling from this [article](https://medium.com/blockchannel/walking-through-the-erc721-full-implementation-72ad72735f3c) the steps might look like:

- First, we clearApproval(), then remove the token from ownership via removeTokenFrom() and use the Transfer event to alert this change on the front end.
- Next, we eliminate the metadata associated with that token by deleting what is mapped to that particular token index.
- Lastly, much like removing a token from ownership, we rearrange our allTokens array so that we replace the _tokenId index with the last token in the array.

- [x] 📈 This is a feature request.

**Comment by shrugs** [comment]
We need it, yes!

We have an implementation stuck in https://github.com/OpenZeppelin/openzeppelin-solidity/pull/957 which has unfortunately been put on hold because of a wide variety of blockers that will eventually be resolved, but if you'd like to cherry-pick the burnable parts of that PR into this one (keeping Vittorio's commit authorship), that would be ❤️

**Comment by Aniket-Engg** [comment]
I think we have a similar contract now in 2.0, so this can be closed.

**Comment by frangio** [comment]
We have [`ERC721Burnable`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f4898a2e3aa6e8138fdda516cc6a830daed06e93/contracts/token/ERC721/extensions/ERC721Burnable.sol) now.
