### ISSUE TITLE
Improve test suite descriptions

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#1157]
The description of each tests (i.e. the text in the `describe`, `context` and `it` blocks) is a bit inconsistent, we should move towards a more standard structure.

I suggest:
 * `contract`(<ContractName>)
 * `describe`(<feature/function>)
 * `context`(<context (!), e.g: once deployed, in refund period, when disabled, etc>)
 * `it`(<verb in present simple, e.g. 'accepts payments', 'allows owner to transfer ownership' // avoid using 'should do x', go for 'does x' instead>)
    * Describe what you're testing, not what you're trying to prove: e.g. if testing a transaction fails from a non-owner account, write 'rejects non owners', instead of 'requires an owner account'. 
    * Use the terms 'null address' for address 0, 'zero-valued' for txs that don't transfer ether, and 'null [role]' for a role assigned to the null address (e.g. 'allows setting a null owner') 

This will allow us to write test chains that read very naturally, e.g.
`PausableToken transfer when paused reverts`

**Comment by frangio** [comment]
I like the proposal!

**Comment by singhj1234** [comment]
Hi, I want to help improve test descriptions. Can I change a few then submit a pull request so it can be reviewed.  I saw what was done in #1204 , #1195 and #1237 so I have an idea of what changes need to be done.

**Comment by nventuro** [comment]
@singhj1234 please do! I haven't been tackling this due to prioritizing other tasks, but these definitely need some love.
