### ISSUE TITLE
SafeMath.sol inconsistent coding convention

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/openzeppelin-contracts#1164]
## 🎉 Description

SafeMath.sol:
```
function mul(uint256 _a, uint256 _b) internal pure returns (uint256 c) {
function div(uint256 _a, uint256 _b) internal pure returns (uint256) {
function sub(uint256 _a, uint256 _b) internal pure returns (uint256) {
function add(uint256 _a, uint256 _b) internal pure returns (uint256 c) {
```

I suggest removing that `c` and declare it inside the function, as in all other contracts.

- [ ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using?
- What network are you deploying to? Ganache? Ropsten?
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here.

## 🔢 Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

```
insert short code snippets here
```

**Comment by nventuro** [comment]
This is part of the testing consistency effort, but was not covered in any single issue, thanks @barakman!

**Comment by DeltaBalances** [comment]
@nventuro 
This is actually more than a coding style issue.

Declaring that c inside the function body actually increases the gas cost.

This change just slightly increased the gas cost of every `mul()` and `add()` operation. It might just be about 5-10 gas per use, but that can still add up in a complicated function.

It was mentioned before that ideally the compiler should handle this, but it is still valid as of now, even up to the newest compilers 0.4.25 and 0.5.0-nightly.

**Comment by barakman** [comment]
@DeltaBalances:
Have you conducted this measurement also when the compilation flags `--optimized` and `--optimized-runs=<some large value>` are used?

**Comment by DeltaBalances** [comment]
Used the test cases from #894 with the newer compilers in the Remix Javascript VM, set with optimization at the standard 200 runs.  The exact gas difference will differ per compiler version but the general improvement stays the same.

I did not try on Ropsten yet as I'm not sure how well everything has recovered from the Constantinople split.

Back then I only proposed this different style for SafeMath as this code is heavily used, and it would be quite an effort to check all other Zeppelin contracts to see if this pattern can apply there too.

**Comment by barakman** [comment]
@DeltaBalances:
AFAIK, they've fixed all these cases as part of 'unified coding convention' fix (regardless of any runtime issue, such as the one that you've mentioned).

**Comment by nventuro** [comment]
Hey @DeltaBalances, thanks for spotting this! Do you know what it is inside the compiler that causes that style to be cheaper? I'd rather not include these sort of changes of the basis of "I've tried them and they cost less gas", since that may unexpectedly change in the future. If, however, we had a deeper understanding on the codegen that allowed us to develop good rules of thumb, that'd be a great addition!

**Comment by barakman** [comment]
@nventuro:

Using `solc 0.4.24`, I executed `solc --asm <ContractName>.sol` on each of the following 3 contracts:

**Contract 1:**
```
pragma solidity 0.4.24;

contract MyContract2 {
    function mul(uint256 a, uint256 b) external pure returns(uint256) {
        return a * b;
    }
}
```
**Contract 2:**
```
pragma solidity 0.4.24;

contract MyContract1 {
    function mul(uint256 a, uint256 b) external pure returns(uint256 c) {
        c = a * b;
    }
}
```
**Contract 3:**
```
pragma solidity 0.4.24;

contract MyContract3 {
    function mul(uint256 a, uint256 b) external pure returns(uint256) {
        uint256 c = a * b;
        return c;
    }
}
```

The assemblies of contracts 1 and 2 are identical, while the assembly of contract 3 appears to contain a few more instructions.

More precisely, this (in contracts 1 and 2):
```
      dup2
      dup4
      mul
      swap1
      pop
```
Is replaced with this (in contract 3):
      dup1
      dup3
      dup5
      mul
      swap1
      pop
      dup1
      swap2
      pop
      pop
```

When adding the `--optimize` flag to the compilation command-line, all the assemblies are identical.

And it all makes sense, if you think about it:
Declaring and assigning an additional local variable would naturally yield a few more instructions which the compiler is not likely to opt-out unless explicitly instructed to (via the `--optimize` compilation flag).

Since you (as a library / utility distributor) cannot assume that every user will use `--optimize`, the best solution would be to avoid declaring and assigning a variable just for the sake of returning a value (as is the case in some of the `SafeMath` library functions).

The downside is, of course, that your code might turn out slightly "less pretty" (I suppose that you chose to use that `c` variable just in order to achieve the same "pattern" (or coding-style if you will) in each one of the `SafeMath` library functions).

Alternatively, you can choose to assume that if somebody cares about 5 or 10 gas units, then they should probably compile their code with optimization enabled.

In your place, I would actually choose the latter option, since it's not your responsibility to worry about performance, most certainly in such a basic utility such as `SafeMath` (to be honest, whenever performance is an issue, `SafeMath` calls should be replaced with a one-time input checking at a higher level of the code).

**Comment by nventuro** [comment]
You really couldn't have phrased it better @barakman, I agree completely on all your points :) Thanks!
