### ISSUE TITLE
Add descriptions to beforeEach blocks

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#1260]
As noted [here](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1247#discussion_r213747409), some tests would benefit from a description in their `beforeEach` blocks (specially when paired up with `context` blocks).

**Comment by frangio** [comment]
This is too big and will never get prioritized. We should add descriptions for new beforeEach blocks that are added and as existing tests are gradually improved.
