### ISSUE TITLE
Automatically generate Role contracts

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#1290]
The 2.0 release will introduce `MinterRole`, `SignerRole`, etc.: these are all manually generated, as are their tests, mocks, etc. We should have some sort of automatic code generation step in our build process to both make it easier to add new roles, and reduce the potential for human error.

**Comment by celeduc** [comment]
Instead of a code generator to avoid human error I humbly request that we instead change the architecture to not require that everyone include the same duplicate code. At best, this will be expensive (with gas) error prone (typos) and hard to upgrade and maintain.

**Comment by nventuro** [comment]
Hey @celeduc! Is there any such architecture you have in mind? We've tried a couple things (e.g. the old `RBAC`), but they each had their own issues (#1090). Maintainability, extensibility and usability are definitely things we strive for, and this was the most minimal example we were happy with.

**Comment by celeduc** [comment]
Wow, I didn't know about #1090.  Yuck.

Implementing a role with this scheme costs a substantial amount of coding (43 lines of Solidity contact and 11 lines of JavaScript test), not to mention the gas to deploy it.   Implementing a new role with RBAC was a one-liner, and all of the access methods were orthogonal (making meta-coding and Web3 coding a lot easier).

With C++ I'd use a template class to implement RBAC with whatever datatype is passed in, so if you wanted integer-based, cool, if you want strings, cool. But of course Solidity [doesn't have generics](https://github.com/ethereum/solidity/issues/869) yet. But there is `enum` which at least gives a modicum of type safety.

In any case, experience tells me that whenever I see the words "code generator" or "code wizard" I think "architecture problem" and "maintenance nightmare". Windows. Rails scaffolds. Etc.

**Comment by nventuro** [comment]
The problem with `enum` is that we have no way of accessing each of the values from the outside, e.g. if we did 

```solidity
enum Roles {
  Minter,
  Pauser, 
  Signer
}
```

we'd have to hardcode the values in JavaScript, since they are not included in the artifact (the `Role.json` file). 

That said, I fully agree with your concerns regarding code generation, and would much prefer not using it, should we find a better alternative.

**Comment by celeduc** [comment]
I've finally read all the way through 1090 and understand why it is the way it is. Although it may be right within the scope of this project I'm afraid it won't be maintainable in my dependent project, plus it'll make the code super clumsy, so I'll just fork out RBAC and stay with that until something better comes along.  Thanks! (and please don't write a code generator ;)

**Comment by nventuro** [comment]
If you don't mind, could you expand a bit on why the current `Roles` solution is not fit for your project? Do you require a dynamic number of rules? We try to cater to as many use cases as possible, and would much prefer it if we could prevent you from doing that extra work yourself :)

**Comment by celeduc** [comment]
I have _n_ different related permissions to manage, Record101, Record102, Record103 in which one account may have Record rights for 101 and 102 but not 103, etc.  With RBAC I can set up _n_ permissions.  I *thought* I was going to append the number to the string, but that turns out to be expensive (string support is *still* terrible). So instead I might just use [integers and bitmasking](https://solidity.readthedocs.io/en/v0.4.25/types.html#integers). Those are fast, and the `const` variables are accessible through Web3.  Will append working code when working :/

**Comment by nventuro** [comment]
Please do! I'm very interested in looking at it :)

**Comment by nventuro** [comment]
Awesome! Indeed, if that `index` isn't a problem in your application, using `Roles` sounds like a good idea :) `MinterRole` and friends exist to make it easier for users to get started using roles without much fanfare, but they might not be suited to all use cases.

**Comment by nventuro** [comment]
With the release of `AccessControl` in v3.0 this no longer applies.
