### ISSUE TITLE
IncreasingPrice Crowdsale

### ISSUE THREAD

**Issue by workspace-asia** [OpenZeppelin/openzeppelin-contracts#1327]
This may be a feature request. I want an increasingprice crowdsale but based on the amount of weiraised, and not on the time. Is it possible?

**Comment by nventuro** [comment]
Hey there @workspace-asia! This is actually being developed right now, see #1072.

**Comment by tgoeminne** [comment]
Nice, Thanks

**Comment by frangio** [comment]
Closing as crowdsales are no longer a part of the library.
