### ISSUE TITLE
Refundable Crowdsale

### ISSUE THREAD

**Issue by Paradox-AT** [OpenZeppelin/openzeppelin-contracts#1336]
## 🎉 Description

- [x] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- OpenZeppelin: RC2
- Network: Ganache
- Geth: 1.8.15-stable

## 📝 Details

I am trying to use the refundable crowdsale contract but when I am sending ethers to the contract it is reverting. Even if I am trying to deploy the refundable mockup contract I am getting the same error. While backtracing I found out that the error is in [Escrow](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/3e55408cb5590dc5095ebd766756ca2da356e1d8/contracts/payment/Escrow.sol#L32) contract. If I comment line 32 the transaction is successful.

## 🔢 Code To Reproduce Issue [ Good To Have ]
[Contract](https://github.com/Paradox-AT/Temp)

**Comment by nventuro** [comment]
Hey @Paradox-AT, thanks for reporting this. Most likely this is probably an issue on your end, since both the Refundable Crowdsale and Escrow are thoroughly tested, but I can help you figure this out. Could you share the code that causes a transaction to revert? A failing test case would be great. Thanks!

**Comment by Paradox-AT** [comment]
Hi, @nventuro I've uploaded the code [here](https://github.com/Paradox-AT/Temp)

**Comment by nventuro** [comment]
I only see a migration script on that file, where is it that you get an error?

**Comment by Paradox-AT** [comment]
You have to install the node package then deploy it.

I am getting while sending ethers to the contract i.e while calling the fallback function defined in the Crowdsale contract.

**Comment by nventuro** [comment]
Are you sure the crowdsale has started (i.e. the opening time has already passed) by the time you use it? Take a look at the [`RefundableCrowdsale` tests](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/4b21fcf5af6b411d6c39b0616e25d91c811d0768/test/crowdsale/RefundableCrowdsale.test.js) to see how to use it.

**Comment by frangio** [comment]
Crowdsales are no longer included in the library.
