### ISSUE TITLE
Publish a cheat-sheet of upgrading from v1.x to v.2.0.0

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/openzeppelin-contracts#1478]
**🧐 Motivation**
Due to API-breaking changes introduced in v.2.0.0, make it easier for OZ users to upgrade their system (on-chain code and off-chain code) to this version.

**📝 Details**
I am using only a small subset of OZ infrastructure, so I've encountered only a few required changes, and was able to complete the process pretty fast.

So I shall post these changes below, and hopefully others can extend it in order to provide a good-enough guide for upgrading:

1. Find/Replace `Claimable` to `Ownable`
2. Find/Replace `StandardToken` / `BurnableToken` / `MintableToken` to `ERC20`
3. Instead of calling `burn(value)`, call `_burn(msg.sender, value)`
4. Instead of calling `mint(to, value)`, call `_mint(to, value)`
5. Instead of calling `super.transfer(to, value)`, call `_transfer(msg.sender, to, value)`
6. Instead of updating `totalSupply_` and `balances` directly, update them via `_burn` and `_mint`

**Comment by kennblvnp** [comment]
Yeah what is the replacement of StandardToken.sol? I am using ERC20.sol for the meantime

**Comment by nventuro** [comment]
Thanks @barakman! We'll include such a guide in the revamped docsite (as well as documenting how `ERC20` is supposed to be used).

I'm wondering though, why did you replace `MintableToken` for `ERC20`? We created `ERC20Mintable` as its replacement, since they're not equivalent: the `Mintable` variant allows external accounts (that have the proper permissions) to mint tokens, while the barebones `ERC20` only has the `internal` `_mint` function.

**Comment by barakman** [comment]
@nventuro: Hi.

On our system, minting is internal by the definition of our product, meaning that we are the only ones with minting-permission, and moreover, we perform it internally as a result of some specific conditions (i.e., not even from the off-chain).
Therefore, not only do we not need the functionality of `ERC20Mintable` as you describe it, we also need to override the functionality of `MintableToken` in order to ensure that it is internal to us (well, we needed that in the previous OZ version, where it was public if I remember correctly).

I have assumed this to be the case on every system, so I posted it as one of the steps in the proposed cheat-sheet.

I now understand that there may be other use-cases, so I guess that this step can be omitted (or rephrased if you find it useful in some way).

Thanks

**Comment by interfect** [comment]
On-chain token code obviously can't be upgraded to the new `ERC20` contracts---at least, not without changing the addresses of all the contracts and making everybody trade in their old tokens for new ones.

What's the recommended practice for upgrading a project's OpenZeppelin version, for new contract development, with minimal changes to the source of contracts that are already deployed? Any upgrade-to-2.0 guide ought to address this issue, beyond listing the source changes that are required.

In novakdistributed/macroverse I have a deployed token written against `StandardToken`, and I'm now wanting to upgrade to the latest OpenZeppelin to add some new contracts to the project that use new features. But when I upgrade from `zeppelin-solidity@1.3.0` to `openzeppelin-solidity@2.0.0`, I need to replace `StandardToken`-using code in my source tree with code that uses one of the new `ERC20` variants, with different internal APIs.

I can go ahead and rewrite my token code in my source tree, but that won't change what's on chain, so it's possible I'll see different gas usage and even different behavior between the token contract I use for testing future contracts and the token contract my future contracts will actually have to talk to on mainnet.

I can also copy in bits of the old OpenZeppelin into my codebase, but that could result in hard-to-debug contract name collisions.

**Comment by nventuro** [comment]
>On-chain token code obviously can't be upgraded to the new ERC20 contracts---at least, not without changing the addresses of all the contracts and making everybody trade in their old tokens for new ones.

Not unless you use an upgradeability solution, such as [ZeppelinOS](https://zeppelinos.org/) ;) The [`openzeppelin-eth`](https://github.com/OpenZeppelin/openzeppelin-eth/) EVM package can be used for precisely this (documentation is a bit lacking at the moment, but feel free to ask questions or open issues and we'll promptly give you a hand!).

>What's the recommended practice for upgrading a project's OpenZeppelin version, for new contract development, with minimal changes to the source of contracts that are already deployed?

I take it you want to use the latest OpenZeppelin release to develop new contracts, while keeping the source of the ones you've already deployed to continue interacting with them. The short answer is that you shouldn't have two versions of OpenZeppelin installed at the same time, and will therefore 'lose' the original source code if you upgrade. Note however that this isn't exclusive to OpenZeppelin: if you were to upgrade your Solidity compiler you'd run into a similar issue, with the source code matching but the generated bytecode being different. 

For such a scenario, what I recommend is keeping not the original source code but the original _artifacts_ (the .json files in `build/contracts` if you're using truffle), which have all of the information required to interact with your deployed contracts (the ABI, original source code, bytecode, compiler version and setings, etc.).

**Comment by frangio** [comment]
More than a year later, I doubt anyone needs this guide anymore. We really should've published it along with the release.

We've since learnt to always include a "how to upgrade" guide for all non-trivial releases of OpenZeppelin projects. Thanks for chiming in everyone!
