### ISSUE TITLE
Implement Blacklistable property

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-contracts#1479]
**🧐 Motivation**
See this code for inspiration:
https://github.com/centrehq/centre-tokens/blob/ab8d8ce11320915ca4c384e08a1ef4cde15d5f58/contracts/Blacklistable.sol

**📝 Details**
Not sure if this can already be implemented with RBAC, it probably can. But it would be nice to have a simpler subset of RBAC just to implement a blacklist.

**Comment by frangio** [comment]
I'd like to hear a few use cases for this feature before going ahead with an implementation.

Also see https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1292 for a related discussion about `Whitelist`.
