### ISSUE TITLE
Rename 'investor' account in tests to something else

### ISSUE THREAD

**Issue by thomasvds** [OpenZeppelin/openzeppelin-contracts#1500]
When testing Crowdsale functionalities, we usually have an `investor` account that represents an account that will be receiving the tokens when they are bought, e.g.:

```
it('should assign tokens to sender', async function () {
   await this.crowdsale.sendTransaction({ value: value, from: investor });
   (await this.token.balanceOf(investor)).should.be.bignumber.equal(expectedTokenAmount);
});
```

Given the current regulatory uncertainties and the thin line that sometimes exists between security and utility tokens, I think many projects have gone wary of using the word investor in any of their conversation and written material describing their project. Code should be no exception (even in tests),  and I believe it would thus make sense to rename `investor` to something else such as `participant`.

Note that we also have the `purchaser` account, which is then one providing the funds to buy tokens for the participant in the case of a low-level purchase.

This issue could likely be fixed together with issue #1357 that also aims to change a name in the tests.

**Comment by nventuro** [comment]
Thanks for spotting this @thomasvds! I agree, our nomenclature could be better. We also have a slight issue in that `beneficiary` means the recipient of tokens, which is IMO sort of unintuitive (I'd expect the `beneficiary` to be the recipient of funds, and would call the buyers `participants`). However, that'd require changing the argument of one of the `Crowdsale` events, which may be considered a breaking API change :/

**Comment by frangio** [comment]
Closing as crowdsales are no longer a part of the library.
