### ISSUE TITLE
Rollback to VM infrastructure for Travis

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-contracts#1538]
Travis is [deprecating their container based infrastructure](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration). This means removing the `sudo: false` entry in `travis.yml`, or rolling back #1199. 

Note that if we don't do anything, it seems that Travis will switch us automatically, though it's better to do it manually in case something breaks due to the change. Also, this change should be replicated to `openzeppelin-eth`.

**Comment by frangio** [comment]
We're now using GitHub Actions.
