### ISSUE TITLE
Find median of an array of uints

### ISSUE THREAD

**Issue by hacker-DOM** [OpenZeppelin/openzeppelin-contracts#1548]
**🧐 Motivation**

We are building a reliable price oracle for a decentralized exchange (the DutchX). We would like to take the last n prices, and output the median price. So we need an algorithm that is able to find the median of an array of, say, uints.

**📝 Details**

A function that takes an array and returns its median. Signature:

`function findMedian(uint[] memory array)
public
Pure
Returns (uint)`

**Comment by nventuro** [comment]
Unless the array is sorted (which I assume it isn't :stuck_out_tongue:), this will be at least O(n)-time. Will that array be arbitrarily long?

I'm also curious as to how it is built: does it come from queries to another contract, or from local storage? If it's the former, we may want to consider retrieving the values here, to make it more gas efficient.

**Comment by dteiml** [comment]
Yes, it is unsorted. There is an algorithm to find median (even more generally the nth smallest term) described [here](https://stackoverflow.com/a/28822243) that I think could be a good reference. Ideally, we would parameterize the pivot as well. If it is completely random, you can choose `array[0]` as the pivot, for our case, choosing the (chronologically) middle value would probably be more performant.

The elements come from n different calls. I agree it would be cheaper to do it in the other contract, unfortunately that exchange is already deployed.

Thanks,

**Comment by frangio** [comment]
I agree that the pivot should be an argument, and a front-end should choose it in a smart way so as to result in cheap execution. Otherwise the function runs the risk of running out of gas.

**Comment by dteiml** [comment]
Ended up implementing this by myself :) To avoid moving around large arrays in evm, I used a linked list. The code is here https://github.com/gnosis/dx-price-oracle/blob/fcf2dd0fac65754ed1f99f899cb95799892f5d5a/contracts/DutchXPriceOracle.sol#L80

To make it reusable, all that has to be done is: 
- Replace the message calls by loading the next array element
- Collapse the use of two arrays of data into one (we use two, one for numerators and one for denominators, because our data are fractions)

Just my two cents ✌️

**Comment by Amxx** [comment]
Digging up this old topic just to propose an implementation:
```
function median(int256[] memory array, uint256 length) internal pure returns(int256) {
	// insertion sort
	for (uint256 i = 1; i < length; ++i) {
		int256 temp = array[i];
		uint256 j;
		for (j = i; j > 0 && temp < array[j-1]; --j) {
			array[j] = array[j-1];
		}
		array[j] = temp;
	}
	// odd/even length management
	return length % 2 == 0 ? Math.average(array[length/2-1], array[length/2]) : array[length/2];
}
```

**Comment by frangio** [comment]
We are probably adding sorting (#3475) but it will only be recommended for small arrays. Median can be extracted from there and should probably only be done for small arrays as well. Closing in favor of that approach.
