### ISSUE TITLE
wrong import statement in docs

### ISSUE THREAD

**Issue by startgeek** [OpenZeppelin/openzeppelin-contracts#1560]
the import statment has wrong path in documents 
![image](https://user-images.githubusercontent.com/18519287/50036730-65e57200-0020-11e9-9118-3ba6e6439fbf.png)

**Comment by startgeek** [comment]
also half the doc's use single quotes(') and other half use double quotes(")

**Comment by frangio** [comment]
This is about our old documentation site so no longer applies.
