### ISSUE TITLE
Make roles iterable.

### ISSUE THREAD

**Issue by MicahZoltu** [OpenZeppelin/openzeppelin-contracts#1602]
**🧐 Motivation**
When I am reviewing a live contract, I want to be able to easily identify who, if anyone, has a particular role.  The only way to do that right now is to write a script that walks all of history (since contract instantiation) looking for logs that indicate a role was added/removed and using that to construct a collection of role owners.  It would be much better if I could just iterate over the current set of role holders.

**📝 Details**
Provide a mechanism to iterate over all of the holders of a particular role.  The "easy" way to do this would be to store the roles in a linked list instead of a mapping, but there are of course other solutions with different trade offs.  Role changes should be infrequent and on-chain access is unlikely to be necessary, so a linked list feels like a good fit.

**Comment by nventuro** [comment]
Hey there @MicahZoltu! While I do think there's value in walking through the logs, enumerability does indeed make sense in many scenarios.

Could you share a short snippet ilustrating your proposed linked-list implementation? I was originally considering having a companion array for the mapping, and removing elements using a swap-and-pop strategy (same as how we do `ERC721Enumerable`.

**Comment by MicahZoltu** [comment]
So I went digging through some old source code, it appears the one we wrote for Augur was back when we were using Serpent.  😬

🤔 more on this, if the number of roles is expected to be small, then a sparse array is probably "good enough" realistically.  In this case, you would just insert new members of a role into the first empty slot in the array, so if additions/deletions are relatively well distributed the array will tend to have few holes.  This strategy is really only a problem if you end up doing a large number of insertions, followed by a large number of deletions you can end up with a big gap in the middle.

A linked list is better if you need ordering (which I don't think you do in this case) or if you are worried about large holes in the sparse array.

Here is an example of a sparse array solution.  Note: I just threw this together so probably buggy, but consider it Unlicensed or CC0 if you want to use it as a base to work from.  😄 
```solidity
pragma solidity 0.5.2;
contract Role {
    address[] public members;

    function addUserToRole(address user) public {
        for (uint256 i = 0; i <= members.length; ++i) {
            if (i == members.length) {
                members.push(user);
                return;
            }
            if (members[i] == address(0)) {
                members[i] = user;
                return;
            }
        }
    }
    
    function removeUserFromRole(address user) public {
        for (uint256 i = 0; i < members.length; ++i) {
            if (members[i] != user) continue;
            if (i == members.length - 1) members.pop();
            else delete members[i];
        }
    }
    
    function isMember(address user) public view returns (bool) {
        for (uint256 i = 0; i < members.length; ++i) {
            if (members[i] == user) return true;
        }
        return false;
    }
    
    function getUser(uint256 index) public view returns (address) {
        uint256 count = 0;
        for (uint256 i = 0; i < members.length; ++i) {
            if (members[i] == address(0)) continue;
            if (count == index) return members[i];
            ++count;
        }
        return address(0);
    }
    
    function numUsers() public view returns (uint256) {
        uint256 count = 0;
        for (uint256 i = 0; i < members.length; ++i) {
            if (members[i] == address(0)) continue;
            ++count;
        }
        return count;
    }
}
```

**Comment by nventuro** [comment]
I take it the purpose of the sparse array is to avoid having to memmove the tail of the array when deleting an element. If that's the case, why not go with something more straightforward like this? Do let me know if I'm missing something here!

```
contract Roles {
  address[] private users;

  function addRole(address account) {
    users.push(account);
  }

  function removeRole(address account) {
    for (uint256 i = 0; i < users.length; ++i) {
      if (users[i] == account) {
        if (i < users.length - 1) {
          users[i] = users[users.length - 1]; 
        }
        users.pop();
        return;
      }
    }
  }
}
```

**Comment by MicahZoltu** [comment]
Your solution is better, go with that.  😁

**Comment by vdrg** [comment]
@nventuro I think it could be better if you stored the indexes in a mapping:

**Comment by vdrg** [comment]
@nventuro I think it could be better if you stored the indexes in a mapping, so you don't need to iterate through the array in order to remove an account (could get too costly if there are too many accounts and you want to remove the last one).

**Comment by nventuro** [comment]
That'd also work, at the cost of an extra `SLOAD`. Thanks! I'll try out different approaches when I get to this :)

**Comment by nventuro** [comment]
While interesting and not super hard to introduce, this causes multiple issues with [`openzeppelin-eth`](https://github.com/OpenZeppelin/openzeppelin-eth) because it changes the layout of the `Roles` struct, and an upgrade would require a difficult migration in order to be correct (i.e. one where all current role bearers are passed so that they can be added into the array.

Tagging this as an idea for the next breaking release.

**Comment by nventuro** [comment]
This will probably be built on top of `EnumerableSet`. We may want to extend it with `length` and `get(index)` to add `view` functions with pagination (for large queries).

**Comment by albertocuestacanada** [comment]
Hi @nventuro, would you like me to have a go at this issue?

I've got in my mind to propose some things regarding [Role Based Access Control](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1889), and this would be a nice issue for me to get 100% comfortable with your Roles implementation.

**Comment by nventuro** [comment]
@albertocuestacanada as mentioned in [this issue](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1772#issuecomment-579964308), we're considering multiple alternatives for the new `AccessControl` library. 

I invite you to instead join the discussion on [Redesigning Access Control](https://forum.openzeppelin.com/t/redesigning-accesscontrol-for-the-openzeppelin-contracts/2177), so we can gather ideas and settle on a high-level design, at which point we'll be able to begin working  on the code. Depending on how we choose to approach this, making the roles iterable will look very different.
