### ISSUE TITLE
Make ERC165.supportsInterface public

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#1614]
**🧐 Motivation**
The function has been `external` since it was included for seemingly no reason. I found the need for it in openzeppelin-eth, where it was in fact [already made public](https://github.com/OpenZeppelin/openzeppelin-eth/blob/b047d28476e274bca2a6091c280a7f55afe74e10/contracts/introspection/ERC165.sol#L39-L42).

**Comment by Amxx** [comment]
This function is currently public.
