### ISSUE TITLE
Add CREATE2 contract factory

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#1644]
As discussed with @cwhinfrey, @jamesyoung and @spalladino, it'd be interesting to include a factory such as [archanova's](https://github.com/archanova/solidity/blob/08f8f6bedc6e71c24758d20219b7d0749d75919d/contracts/contractCreator/ContractCreator.sol) (by @stanislaw-glogowski, which uses CREATE2, making it possible to predict the contract's address) into OpenZeppelin, possibly expanding upon it to cover more use cases.

One aspect in particular I'd like to discuss is constructor arguments: the linked implementation has a fixed bytecode, but it shouldn't be too difficult to come up with a scheme where these initial values are injected.

**Comment by elopio** [comment]
Here is a nice example of a factory by @miguelmota, based on @stanislaw-glogowski's code:
https://github.com/miguelmota/solidity-create2-example

**Comment by marekkirejczyk** [comment]
I think there are two types of CREATE2 factories one might want to consider:
1) standard on chain factory
2) factory with support for metal-transactions

There is a significant difference in implementation, interface, and security, so I created a separate ticket for that #1651

**Comment by cwhinfrey** [comment]
It may also be possible to have the factory contract in #1651 extend a base contract that only has `internal` functions like the one @stanislaw-glogowski created in [archanova](https://github.com/archanova/solidity/blob/08f8f6bedc6e71c24758d20219b7d0749d75919d/contracts/contractCreator/ContractCreator.sol)

**Comment by AugustoL** [comment]
Ive been playing with CREATE2, taking this issue, going to submit a PR with a simple CREATE2 factory. Later we can extend it to a factory with meta txs support.

**Comment by spalladino** [comment]
@AugustoL keep an eye on the [proxy factory we built for zOS](https://github.com/zeppelinos/zos/blob/master/packages/lib/contracts/upgradeability/ProxyFactory.sol), we could reuse some of that code.

**Comment by frangio** [comment]
We have this in a feature branch with some pending work. See #2013.
