### ISSUE TITLE
Create a Master minter address on MinterRole 

### ISSUE THREAD

**Issue by Vulturio** [OpenZeppelin/openzeppelin-contracts#1654]
**🧐 Motivation**

This is a problem that we have with a Minter contracts, we need minters but they can add another one because the onlyMinter modifier allows that, we need an ultra mega minter who can add or delete them by default.
**📝 Details**

A minter can add another minter, should be a Master minter address with an exclusive modifier to add or delete minters.

**Comment by nventuro** [comment]
Hello @UncleVultur! What is it that you don't like about the current implementation? Any minter can mint whatever tokens they desire, so being able to also give that power to another account doesn't seem too farfetched.

**Comment by frangio** [comment]
This issue is no longer relevant to the current roles implementation in `AccessControl`.
