### ISSUE TITLE
Improve ECDSA tests

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#1667]
https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1622 introduced some changes to the `ECDSA` contract, and made it clear that our test suite for that particular contract is somewhat lacking. We should refactor it so that:

- it's easy for users to understand how to use the contract (i.e. how to generate signatures e.g. using `web3.eth.sign`)
- all cases are properly covered (all combinations of valid and invalid `s` and `v` values)

**Comment by frangio** [comment]
Your first point we should tackle with documentation rather than tests IMO, but both things will help.
