### ISSUE TITLE
Clean up the organization and maintainers team

### ISSUE THREAD

**Issue by elopio** [OpenZeppelin/openzeppelin-contracts#1685]
Currently the active maintainers of OpenZeppelin are @frangio and @nventuro.
To handle permissions in a clearer and safer way in this repo and in the organization, I will remove everybody else that hasn't been active for a while.

@spalladino and I (@elopio) will remain as admins to help when the maintainers need a hand with the repo settings.

If somebody needs access to one repo, or (even better) wants to return as an active maintainer, please reply here. You can also ping the maintainers team with @OpenZeppelin/maintainers.

And there are multiple ways to contribute with the project, not only as maintainers. If you are interested, please join our forum: https://forum.zeppelin.solutions/

cc: @ajsantander @AugustoL @demibrener @eordano @federicobond @fiiiu @izqui @jcarpanelli @maraoz @martintel @martriay @rrecuero @shrugs @tinchoabbate

**Comment by Aniket-Engg** [comment]
> If somebody needs access to one repo, or (even better) wants to return as an active maintainer, please reply here.
Is this only for the present maintainers?

**Comment by frangio** [comment]
@Aniket-Engg This specific message was for present/past maintainers, yes. However, we are interested in growing the group of maintainers. Please join the Zeppelin forum and [send us a message](https://forum.zeppelin.solutions/g/oz-maintainers) so we can talk about it!

**Comment by Aniket-Engg** [comment]
@frangio I have joined the forum but it is not allowing me to send message because I am a new user.

**Comment by martriay** [comment]
@Aniket-Engg hi! That's weird, I'm seeing your profile and everything looks normal

**Comment by frangio** [comment]
@martriay It's sorted. Thanks.
