### ISSUE TITLE
ERC20Typos adding discussion

### ISSUE THREAD

**Issue by k06a** [OpenZeppelin/openzeppelin-contracts#1690]
**🧐 Motivation**

I developed TypoToken ERC20 extension to solve a problem of typos in destination addresses and want to know if OZ maintainers think it is a good idea to add this extension to the library.

**📝 Details**

The idea is pretty simple:

1. Anyone whose destination address contains mistakes can reclaim lost funds
2. Anyone who sends tokens to wrong smart contract address can reclaim lost funds

I made implementation for Hack.Summit Virtual Blockchain Hackathon 2018: https://github.com/k06a/TypoToken

Usage:

```solidity
contract MyToken is ERC20, ERC20Typos(3) {
    ...
}
```

**Comment by Skyge** [comment]
Hi, I think [ERC223](https://github.com/ethereum/eips/issues/223) and [ERC777](https://github.com/ethereum/eips/issues/777) are similar to your contract, so what are the differences between yours and them?

**Comment by k06a** [comment]
@Skyge in case of receiver is a wallet not a contract ERC20Typos allows to recover sent token.

**Comment by Skyge** [comment]
oh, I see, but does this mean that the balance of your wallet may be not accurate, because recovering sent token may occur at any time. In order to ensure a exact address, there is a [ERC681](https://github.com/ethereum/EIPs/blob/30385fef6fc23e3ac896fea254ea61bd85f4ea92/EIPS/eip-681.md) which propose `URL Format for Transaction Requests` provides for the wallet, besides that, I am not sure whether we can combine [ERC137](https://github.com/ethereum/EIPs/blob/035a0211685145c8951bab9f439880894c5d0cdf/EIPS/eip-137.md) with the wallet, if possible, then we can decrease destination addresses spelling mistakes.
Of course, all my thoughts are how to prevent this happen, your propose is to remedy.I think it is good.

**Comment by Amxx** [comment]
Not sure if this request is still relevant. 

The proposed implementation relies on a `sent_` mapping that is very expensive to maintain (one more sstore per transfer). Maybe the induced cost was ok when this issue was raised in early 2019, but 2.5 years later its really not the case.

**Comment by k06a** [comment]
@Amxx in terms of gas it is the same effort. But I am not sure this ERC20Typos makes any sense nowadays, meanwhile the issue of typos still exist, IDK.

**Comment by frangio** [comment]
I think the concept is very interesting, but I don't feel very comfortable giving an account the ability to take the balance away from another account.

**Comment by Amxx** [comment]
The `reclaimByReceiver` is interesting and does not cause a meaningful security threat if the "distance" is not high (quasi collisions are still super hard to purposefully produce).

`reclaimBySender`, in addition to being super gas expensive, allows any sender to cancel a past transfer in a way that I don't think is acceptable. Its just to easy to transfer to someone and then remove the tokens from it: think of cancelling a transfer to a smart contract, but keeping what you paid for (LP, NFT, ...)

I wonder, however, if the ERC20 contract is where that should happen. Any of these modules would only be implemented by a small fraction fo the future ERC20, making it really non standard ...
... on the other hand, maybe be could imagine a third party contract, that would act as an escrow in transfers:

- anyone could deposit tokens on it for someone else to withdraw
- you could add this "distance" mechanism for receiver withdrawals
- you could also add a sender withdrawal mechanism, with the needed arbitration logic in case of conflicts.

That wouldn't be as seamless as building it into the ERC20 contract, but it would support all past and future ERC20 instances. It would also be opt-in.
