### ISSUE TITLE
Add ERC721 _safeMint and _safeTransferFrom

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#1736]
`ERC721` has `safeTransferFrom` that forces a receiver contract to implement the `onERC721Received` function. Just like our other ERC implementations, we should have an internal `_safeTransferFrom` that does the same thing without requiring anything of `msg.sender`. Note that we already have an internal `_transferFrom`.

Similarly, we should add `_safeMint` as an alternative to `_mint`, with the addition that it also call `onERC721Received` on a contract receiver.

***

Original issue:

> `ERC721` transfers are required to call `onERC721Received` if the receiver is a contract. I don't know if this is specified in the EIP, but we might have to do the same in `_mint`. Currently we are not.
>
> This needs some discussion because it would be a breaking change. Additionally, it may not be obvious that `_mint` will call an external contract, and as always this opens up the possibility for reentrancy.
>
> Thanks @alcuadrado for pointing this out.

**Comment by nventuro** [comment]
From the [EIP](https://eips.ethereum.org/EIPS/eip-721):

>Creating of NFTs (“minting”) and destruction NFTs (“burning”) is not included in the specification. Your contract may implement these by other means. Please see the event documentation for your responsibilities when creating or destroying NFTs.

(the events documentation only discusses emitting a` Transfer` event, which we do)

Note that only `safeTransferFrom` is required to call `onERC721Received`, `transferFrom` does **not** have that requirement. We could add a new `_safeMint` function that performs the check.

As a workaround until this issue is fixed, a contract minting tokens may achieve this behaviour in the following way:

```solidity
function _safeMint(address to, uint256 tokenId) internal {
  _mint(address(this), tokenId);
  safeTransferFrom(address(this), to, tokenId);
}
```
```

**Comment by frangio** [comment]
>only `safeTransferFrom` is required to call `onERC721Received`

Good point.

> We could add a new `_safeMint` function that performs the check.

I like this idea! Makes a lot of sense to me.

**Comment by frangio** [comment]
Hm, we don't have an internal `_safeTransferFrom`... We should add both `_safeTransferFrom` and `_safeMint`. Does this sound ok?

**Comment by nventuro** [comment]
Yes, given that we _do_ have `_transferFrom`. Note that we should go for the variant with the `data` parameter.

**Comment by alanarvelo** [comment]
Hi guys @nventuro @balajipachai I think I understood what is required to fix this issue. What is the state of things? May I move forward?

**Comment by nventuro** [comment]
@alanarvelo there is an open PR (https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1748), but it hasn't received attention for some time now. I'd suggest taking a look at it and at the review comments - if I recall correctly some bugs were introduced by it. Other than that, by all means go ahead! 🎉

**Comment by frangio** [comment]
https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1748 was just closed as stale. The PR is mostly good but it has some changes to the existing functions that are incorrect and should be reverted.

Whoever wants to pick this up please do!

**Comment by logeekal** [comment]
I am picking it up and will get back with more questions.

Thank you.

**Comment by alanarvelo** [comment]
Hi @logeekal, I submitted a PR two days ago tackling this. Feel free to take a look at it and shoot questions or suggestions

**Comment by alanarvelo** [comment]
Hi @frangio should we close this issue? Any other particular issue that I can help on? 
Thanks.

**Comment by frangio** [comment]
Yes thanks for pointing it out!
