### ISSUE TITLE
Add ERC777 transfer and transferFrom tests

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#1753]
As discussed in https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1751, the tests that include send and receive hooks are only performed on `send` and `operatorSend`, skipping `transfer` and `transferFrom`. 

These are in the 'send and receive hooks' `describe` block, with the actual tests in the behavior functions `shouldBehaveLikeERC777SendBurnWithSendHook` and `shouldBehaveLikeERC777SendBurnMintInternalWithReceiveHook`.

We should probably create two additional functions, similar to these, with two main differences: these calls should not fail when the recipient is a contract that doesn't implement the interface, and both `userData` and `operatorData` are empty.

**Comment by frangio** [comment]
We must also test that allowances are updated before calling the received hook.

**Comment by ernestognw** [comment]
Hey @balajipachai, I'd consider this as not needed anymore since ERC777 is not supported anymore by our library.
I'm closing since I think we just didn't put attention here. Thanks for flagging
