### ISSUE TITLE
featuring OpenZeppelin in Docusaurus

### ISSUE THREAD

**Issue by nickbui729** [OpenZeppelin/openzeppelin-contracts#1756]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) page.

If you are okay with it, are you able to provide a logo we can use? Additional information can be found [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by Skyge** [comment]
Why should OpenZeppelin do this? if not, what are the disadvantages?

**Comment by nickbui729** [comment]
There are no disadvantages! We are trying to expand Docusaurus by showing new users different projects that use Docusaurus for their templating.

**Comment by Skyge** [comment]
I know `Docusaurus` is for running a website easily, and I also know `docsify` has some similar action, so what are the differences? 
I think your proposal is acceptable, because with this, we can look through contracts easily.

**Comment by frangio** [comment]
@nickbui Yes, that would be nice. I'll get back to you with a logo!

**Comment by frangio** [comment]
@nickbui729 Unfortunately we've migrated away from Docusaurus to Antora.
