### ISSUE TITLE
Remove ERC20._burnFrom

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#1766]
`ERC20._burnFrom` doesn't really fit with the standard for other `internal` functions, both in that it uses `msg.sender` and in that it is not really a reasonable primitive. It should disappear, and `ERC20Burnable` should implement `burnFrom` in terms of `_burn` and `_approve`.

**Comment by frangio** [comment]
I'm not sure this is as clear cut as you put it. If it's not a reasonable primitive, why is `_transferFrom` reasonable? I'm starting to think perhaps having constraints on `msg.sender` in the internal functions would be the right thing. Should a contract be able to change completely the rules of the parent contracts?

**Comment by nventuro** [comment]
>If it's not a reasonable primitive, why is _transferFrom reasonable?

It isn't, which is why it doesn't exist :stuck_out_tongue: 

What do you mean by 'change the rules'? A contract writes their own rules, we simply provide rules for them to do so. I think having implicit arguments in these `internal` functions (`msg.sender`) makes it easy to misuse them, and this behavior can always be replicated by explicitly passing `msg.sender`, if needed.

**Comment by frangio** [comment]
>What do you mean by 'change the rules'?

For example, we could say that one of the rules of `ERC20` is that only the `msg.sender` (or someone with allowance) can move their own tokens. By providing `_transfer(from, to, amount)` we are allowing a child contract of `ERC20` to change that rule, allowing token movements to happen outside of those contraints. I understand this may be desirable in some cases, but in general I feel it might be better to fully encapsulate those rules in the parent contract.

**Comment by nventuro** [comment]
I believe that would land us on a design too stiff to be useful. IMO we should simply provide useful and correct primitives that can be used to build upon, as opposed to being _too_ opinionated regarding what end user contracts should look like.

And even an invariant as basic as the `transfer` one would be broken by `_mint` and `_burn`, which are legitimate mechanisms used in multiple projects.
