### ISSUE TITLE
Unable to import "github/OpenZeppelin/openzeppelin-solidity/contracts/math/SafeMath.sol": File not found

### ISSUE THREAD

**Issue by nsingh3905** [OpenZeppelin/openzeppelin-contracts#1824]
**🧐 Motivation**
Yes, the problem is related to how the contract interacts with the remix ide

**📝 Details**

find a way to import the contracts into the chosen smart contract without issues

**Comment by abcoathup** [comment]
Hi @nsingh3905

You can import OpenZeppelin Contracts with Remix using the prefix `https://github.com/OpenZeppelin`

Using the [example ERC20 contract](https://docs.openzeppelin.org/v2.3.0/tokens#constructing-an-erc20-token-contract) from the OpenZeppelin documentation you can import OpenZeppelin as follows: 

```solidity
import "https://github.com/OpenZeppelin/openzeppelin-solidity/contracts/token/ERC20/ERC20.sol";
import "https://github.com/OpenZeppelin/openzeppelin-solidity/contracts/token/ERC20/ERC20Detailed.sol";

contract GLDToken is ERC20, ERC20Detailed {
    constructor(uint256 initialSupply) ERC20Detailed("Gold", "GLD", 18) public {
        _mint(msg.sender, initialSupply);
    }
}
```

For support questions you can ask in the community forum: https://forum.zeppelin.solutions/

**Comment by nventuro** [comment]
Note that you should only use code published in an official release, but Remix pulls from `master` directly. You can take a look at our [Getting Started](https://docs.openzeppelin.org/v2.3.0/get-started) guide for information on how to setup a development environment.

**Comment by nsingh3905** [comment]
Hi I've looked into this method and the transaction on the ethereum ropsten
testnet has failed due to exceeding the gas limit

**Comment by abcoathup** [comment]
@nsingh3905 
I was getting a gas estimation failed error message until I logged into MetaMask.
I updated my sample contract to specify versions of the contract to import. (Thanks @nventuro for the reminder).

For support questions you can ask in the community forum: https://forum.openzeppelin.com/

**Comment by Skyge** [comment]
@nventuro 
> Note that you should only use code published in an official release, but Remix pulls from master directly. You can take a look at our Getting Started guide for information on how to setup a development environment.

When I click your  recommending `Getting Started` guide, it shows `Page Not Found`, so maybe we should correct it to `https://docs.openzeppelin.com/contracts/2.x/`

**Comment by nventuro** [comment]
You're correct @Skyge, thanks! I've updated the link in my original comment to https://docs.openzeppelin.com/contracts/2.x/.

I think we can close this now since the original issue has been resolved, and the [forum](https://forum.openzeppelin.com/) is the preferred medium for support.
