### ISSUE TITLE
Custom error messages as a third parameter to SafeMath functions

### ISSUE THREAD

**Issue by elch-yan** [OpenZeppelin/openzeppelin-contracts#1827]
**🧐 Motivation**
It would be nice to have an option to add custom error message as a 3rd parameter to SafeMath contract functions.

**📝 Details**
One such example where it would be convenient is this:
`uint256 finalFund = funds[msg.sender].sub(amount, "No enough funds!");`

**Comment by nventuro** [comment]
Hey there @elch-yan, thanks for this! 

I've been thinking about this very feature for some time now, it's great to see that more people also consider it useful. Many people drop SafeMath checks in order to get a custom error message, so providing a way to do this makes a lot of sense.
