### ISSUE TITLE
Provide function(s) that verify an address is an EOA

### ISSUE THREAD

**Issue by Austin-Williams** [OpenZeppelin/openzeppelin-contracts#1850]
**🧐 Motivation**
It can be useful to verify that a given address is:

1. For-sure an EOA
2. For-sure an EOA that is _not_ a one-time-use EOA

We could provide this functionality in the `Address` library.

**📝 Details**
I suggest adding two functions to the Address library.

The first would be: `isEOA(address account, bytes32 hash, bytes memory signature)`. This would accept an arbitrary hash, verify the signature, use `recover` (from the ECDSA library) to recover the account of the signer, and return `true` only if the recovered address matched the `account` parameter. Thus, if `isEOA` returns `true` then we know for-sure that `account` is an EOA because it was able to sign a message. (Though if it returns `false` we get no information at all).

However, there are also important cases where being an EOA is not enough -- and we also want to verify that a given address is not a _one-time-use_ EOA (such as those created using [Nick Johnson's method](https://medium.com/@weka/how-to-send-ether-to-11-440-people-187e332566b7)). So for that I suggest the following general function:

`isNonOneTimeUseEOA(address account, bytes32 hash1, bytes memory signature1, bytes32 hash2, bytes memory signature2)`. This would verify both signatures, verify that `hash1 != hash2`, use `recover` on both signatures, then return `true` only if the recovered addresses and the `account` parameter were all equal to each other. What this is doing is verifying that the `account` is able to sign two _distinct_ messages -- ensuring that it cannot be a one-time-use EOA (since one-time-use EOAs can only ever create a single signature). Thus, if `isNonOneTimeUseEOA` returns `true` then we know for-sure that `account` is an EOA but not a one-time-use EOA. (Though if it returns `false` we get no information at all).

**Comment by nventuro** [comment]
Hey @Austin-Williams, thanks for this suggestion!

>The first would be: isEOA(address account, bytes32 hash, bytes memory signature). This would accept an arbitrary hash, verify the signature, use recover (from the ECDSA library)

A long standing issue with `recover` is that receiving a hash may cause people to think that a hash and signature are proof enough, we should probably change this eventually so that the `recover` call hashes its input. See the warning on [`recover`'s docs](https://docs.openzeppelin.com/contracts/2.x/api/cryptography#ECDSA-recover-bytes32-bytes-).

>However, there are also important cases where being an EOA is not enough -- and we also want to verify that a given address is not a one-time-use EOA (such as those created using Nick Johnson's method). 

Could you expand a bit on which cases these are?

**Comment by Austin-Williams** [comment]
> A long standing issue with recover is that receiving a hash may cause people to think that a hash and signature are proof enough, we should probably change this eventually so that the recover call hashes its input. See the warning on recover's docs.

Oh this is a really good point! Yes, the functions would need to accept the message and perform the hash themselves.

> However, there are also important cases where [...] we also want to verify that a given address is not a one-time-use EOA [...] Could you expand a bit on which cases these are?

Yes. But I'll DM them to you because some of them relate to vulnerabilities that haven't been made public yet. (Once they are public, I'll update this comment with a link to those vulns so that everyone else can see them).

**Comment by frangio** [comment]
>Sending ETH/tokens to such an EOA can be effectively the same as sending it directly to the contract.

It's a great point. One way of thinking about this is that a one-time-use EOA is essentially a counterfactual contract.

**Comment by Austin-Williams** [comment]
That's a good way of putting it.

**Comment by crazyrabbitLTC** [comment]
As a question @Austin-Williams what is the purpose of preventing ETH/tokens from being sent directly to a contract? Is there an example case? I'm curious because I've been thinking more of a future where users interact with wallets that are contracts so they can be meta-transaction enabled, rather than using a 'real' wallet like Metamask. I assume this would preclude these types of users from using these kinds of wallets? 
Of course, I guess maybe we could think of it in the opposite, like you want to be sure ETH/tokens can only go to contract addresses?

**Comment by Austin-Williams** [comment]
@crazyrabbitLTC I generally agree that sending ETH from to/from contracts is a great thing.

There are very special cases when we'd want to prevent it. These are mostly cases where we are designing a mechanism in which we don't want the users to be able to make _strategic commitments_ (aka [strategic moves](https://en.wikipedia.org/wiki/Strategic_move)) that might undermine the mechanism.

A specific example is when creating token timelocks for incentive-alignment. If the beneficiary of the token timelock is able to make strategic commitments, then they are able to [bypass the token timelock](https://blog.openzeppelin.com/bypassing-smart-contract-timelocks/).

In practice, strategic commitments are often very difficult to achieve (in the blockchain setting) without the use of a contract to enforce the commitment. So if, as a mechanism designer, you can prevent the use of contracts (in a particular settings) you can sometimes _effectively_ eliminate large classes of potentially malicious behavior.

**Comment by AlbertSu123** [comment]
Has this issue been resolved? Or is there another way to ensure that tokentimelock addresses are externally owned accounts and not contract addresses?

**Comment by nventuro** [comment]
Note that, if [EIP 3074](https://eips.ethereum.org/EIPS/eip-3074) were to come out (and it seems extremely likely that it will), this sort of check would be irrelevant (except to e.g. validating user input by checking addresses expected to be contracts indeed hold code).

**Comment by Austin-Williams** [comment]
I agree. As far as I can tell, EIP 3074 would make this class of timelocks always bypassable.

**Comment by Amxx** [comment]
I might me missing something, but I have a few question

- Appart from checking tx.origin == msg.origin or doing crazy assumption about gasLimit, is it even possible to distinguish EOA calls from 3074 relayed calls ? They are designed to be indistinguishable
- What is the issue why users using smart wallets instead of EOA ? Why would you prevent that.

Composability is an amazing feature of ethereum and I'm not sure how rejecting an entier class of users would be of any benefit.

**Comment by Austin-Williams** [comment]
@Amxx see this article for motivation: https://blog.openzeppelin.com/bypassing-smart-contract-timelocks/

Tl;dr: the ability to require only-EOAs can be used to prevent users from making credible strategic commitments that can be used to bypass some economic mechanisms.

**Comment by Austin-Williams** [comment]
So even after 3074, one can verify whether an address is an EOA by requiring that it pass any two distinct signed messages when interacting with the contract. Then the target contract can verify that the two signed messages are distinct and that they both ecrecover to the same address.

This could also be done with a _single_ signed message, as long as the message itself is not chosen by the user (see article for details).

**Comment by Austin-Williams** [comment]
In any case, I think this issue can be closed.
In the 2 years since I’ve opened I haven’t seen any demand for token timelocks that cannot be economically bypassed, so it’s probably safe to say that there is no need for this in OZ Contracts.

**Comment by AlbertSu123** [comment]
In that case, what would be a possible(temporary) solution to the prevention of token time locks from being bypassed?

**Comment by Austin-Williams** [comment]
The simplest way I can think of: When you first register the recipient addresses with the timelock, make sure you have seen/verified a signed message (of your choosing) from that address before registering it.

E.g.: Have them sign the message “Chancellor on brink of second bailout for banks”. If the message verifies, then the address that signed it is an EOA that cannot be used to bypass a timelock.

**Comment by Amxx** [comment]
I'd go further and say "When you first register the recipient address with the timelock, make sure you have either seen/verified a signed message (of your choosing) from that address or verified that it is a legitimate contract to use as a personal smart wallet."

**Comment by frangio** [comment]
I agree with the recommendation to ask for a signed message. This can be encoded in the smart contract by inheriting `TokenTimelock` and checking the signature in the constructor, but we don't intend to have this by default in the library.
