### ISSUE TITLE
Fix code sample in Access Control guide

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-contracts#1856]
On the [Access Control guide for 2.x](https://docs.openzeppelin.com/contracts/2.x/access-control), the code snippet does not compile.

- [x] `DetailedERC20` in the constructor should be `ERC20Detailed`. (Fixed in #1792)
- [x] `minters` and `namers` should be `_minters` and `_namers`. (Fixed in #1792)
- [ ] The `rename` function attempts to change name and symbol, but these are private in `ERC20Detailed` and cannot actually be changed. A different example should be used instead.

(reported via Intercom)

**Comment by ristosaar** [comment]
Hello,

I see this issue is still open. I'm new to Solidity and would like to contribute.
I propose replacing the rename function with the default burn function in ERC20 and rename _namers with _burners.  
Let me know if this is an acceptable solution.

**Comment by abcoathup** [comment]
Hi @ristosaar,

Welcome to Solidity.  Great that you want to contribute.  

Your solution to the code example sounds fine.

**Comment by ristosaar** [comment]
Thank you,

I'm not entirely sure how I should incorporate the change though. 
docs/modules/ROOT/pages/access-control.adoc seems to be the right file but do I also have to create tests for the new example contract and commit them somewhere? The guidelines are a bit vague on documentation files.

**Comment by nventuro** [comment]
Hello @ristosaar! Indeed, for a change that only affects documentation, just editing the `.adoc` files is enough. Once the PR is open, you'll see a preview of the generated documentation site, and check that way if your changes are correct.
