### ISSUE TITLE
Typo in Arrays.sol

### ISSUE THREAD

**Issue by Dinslinger90** [OpenZeppelin/openzeppelin-contracts#1859]
On this line:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Arrays.sol#L12

Change the word stictly to strictly.

**Comment by abcoathup** [comment]
Thanks @Dinslinger90 :pray:

I created a pull request with the typo corrected.

**Comment by Dinslinger90** [comment]
> Thanks @Dinslinger90 🙏
> 
> I created a pull request with the typo corrected.

Welcome 👍 . You can close this once reviewed.
