### ISSUE TITLE
Typo in ReentrancyGuard.sol

### ISSUE THREAD

**Issue by Dinslinger90** [OpenZeppelin/openzeppelin-contracts#1861]
On this line:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/ReentrancyGuard.sol#L7

Change word aplied to applied.

**Comment by abcoathup** [comment]
Thanks @Dinslinger90 :pray:

For typo's you can create a Pull Request rather than having to create an Issue.

**Comment by Dinslinger90** [comment]
> Thanks @Dinslinger90 🙏
> 
> For typo's you can create a Pull Request rather than having to create an Issue.

Roger that. 👍
