### ISSUE TITLE
Docs: Add links to source code in API documentation

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-contracts#1871]
**🧐 Motivation**
I browse through the documentation everyday and then have to browse to the source code.  
I want to make my life easier :smile:

**📝 Details**
ZeppelinOS documentation had source code links in the API documentation which made it easy to get to the appropriate version of the code.

I also post links to the code in replies in the forum and on stackexchange/stackoverflow and it would be nicer to post links to API documentation which also has a link to the code.

**Comment by frangio** [comment]
Agreed! I believe this should be added in the template for rendering a contract's docs: [`contract.hbs`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/docs/contract.hbs). The template item `{{file.path}}` might be what we need. I'm not sure how we 

It may be necessary to

**Comment by frangio** [comment]
(Closed accidentally. :man_facepalming:)

Agreed! I believe this should be added in the template for rendering a contract's docs: [`contract.hbs`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/docs/contract.hbs). The template item `{{file.path}}` might be what we need.

We should make the links go to the tag for the latest release, and I'm not sure how we can do this in the template.

**Comment by frangio** [comment]
Fixed earlier this year. Contracts docs include a link to GitHub now.
