### ISSUE TITLE
ERC20.sol TYPO

### ISSUE THREAD

**Issue by Dinslinger90** [OpenZeppelin/openzeppelin-contracts#1872]
I was told to pull request for typos. But not sure how to do those stuffs yet. So requesting issue.

On the line number 220. Change word Destoys to Destroys. Thanks you 👍 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol

**Comment by obernardovieira** [comment]
Hello,
in case you don't know, you can create a direct link to a specific line, by clicking at the line number when looking at the code at your browser url will change, then, just copy it
Here's an example https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L220

About the PR, here are the guidelines https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CONTRIBUTING.md
Although I'm not part of the openzeppelin team, I would say, don't be afraid, just follow the instructions and open a PR. If it doesn't work or it's not correct, try again. Nobody will blame you.

Welcome :tada:

**Comment by Dinslinger90** [comment]
Thanks for your guidance @obernardovieira . Will look into it 👍.

**Comment by frangio** [comment]
Welcome @Dinslinger90!

Look for the pencil icon in the [`ERC20.sol`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol) page, just above where the file starts. GitHub will allow you to edit the file and submit a pull request from the web interface.
