### ISSUE TITLE
Updating CONTRIBUTING.md?

### ISSUE THREAD

**Issue by Luiserebii** [OpenZeppelin/openzeppelin-contracts#1876]
Something I noticed is that the `CONTRIBUTING.md` and the instructions in making a PR differ, and the former has a command that might not run. 

The steps for running tests and the linter are:
```
npm test
npm linter
```

However, `npm linter` errors, and I imagine it is supposed to be `npm run lint`. The PR comments ask for running `npm run lint:sol` and `npm run lint:fix`, though I think that since `npm run lint` encompasses the `sol` linting script, perhaps it should be:

```
npm test //or perhaps even just npm t
npm run lint
npm run lint:fix
```

Would love to hear thoughts on this!

Thank you,
Luiserebii~

**Comment by abcoathup** [comment]
I would just change `npm linter` to `npm run lint` as this will report on linting issues. 
There currently isn't a fix option for Solidity linting.

**Comment by Luiserebii** [comment]
Ok, great, just made a PR! Let me know if this looks good.
