### ISSUE TITLE
Add an Ethereum name or address to package.json

### ISSUE THREAD

**Issue by lastmjs** [OpenZeppelin/openzeppelin-contracts#1893]
**🧐 Motivation**

I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have Ethereum addresses in their package.json files. I'm not quite ready to share the project, but I'd love to see an Ethereum address in this project's package.json file.

**📝 Details**

I would like to see an Ethereum name or address added to the `ethereum` field of the package.json file. This will allow consumers of the project to know a cannonical address to send funds to, for example donations.

**Comment by crazyrabbitLTC** [comment]
Hello @lastmjs, couldn't you use ENS for this? It would be more secure than using just plain Ethereum Addresses. Maybe embedding the ethereum address into the package.json file isn't the right way to go? Not sure, but I like the idea very much.

**Comment by lastmjs** [comment]
I think a better idea now is to put the Ethereum address or name into the `FUNDING.yml` file for GitHub Sponsors. Like so:

```yml
custom: ['ethereum/0xyour-address']
```

You can see a couple of examples of this integration with GitHub Sponsors below:

https://github.com/lastmjs/sustainus

**Comment by frangio** [comment]
Hi @lastmjs! Interesting project! Thank you for the suggestion.

As I mentioned in #1888, accepting donations is not a priority for us right now, and before choosing a particular donation method we would like to evaluate the other options. We'll come back to this later!
