### ISSUE TITLE
Gas optimisation in Ownable contract

### ISSUE THREAD

**Issue by sobolev-igor** [OpenZeppelin/openzeppelin-contracts#1905]
**🧐 Motivation**
I was discovering `Ownable` contract and noticed that `OwnershipTransferred` event is emitted with `_owner` passed as second argument. However, this adds one `SLOAD` operation. 
**📝 Details**
If `_owner` is replaced with the `msg.sender` the cost of deployment slightly reduces. The same issue can be found for example in `Secondary` contract's constructor.

Or are there any incetives to leave `_owner` as an argument?

**Comment by nventuro** [comment]
Hm, interesting! The fact that `SLAOD`'s cost is about to increase x4 means that this change will be even greater.

**Comment by frangio** [comment]
Here's the relevant code for reference:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/d864228624e3661eaf10b7d00995110116e51094/contracts/ownership/Ownable.sol#L21-L24

We should introduce a local variable to avoid the SLOAD. Pull requests welcome!
