### ISSUE TITLE
Documentation Request: in-depth guide on ERC777 operators

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-contracts#1909]
**🧐 Motivation**
Documentation currently says:
> Stay tuned for an upcoming in-depth guide on ERC777 operators!
https://docs.openzeppelin.com/contracts/2.x/tokens#_constructing_an_erc777_token_contract

**📝 Details**
A community member recently asked for the in-depth guide on ERC777 operators.  

I pointed them in the interim to the simple ERC777 token example in the forum.  
https://forum.openzeppelin.com/t/simple-erc777-token-example/746

**Comment by frangio** [comment]
Closing this since we haven't seen demand for more documentation about ERC777.

**Comment by ragibayon** [comment]
please give more documentation about ERC777 on how to develop a smart contract which will transact (send tokens) on behalf of a token holder.
