### ISSUE TITLE
Support testing with an in-process ethereum provider

### ISSUE THREAD

**Issue by cgewecke** [OpenZeppelin/openzeppelin-contracts#1918]
**🧐 Motivation**

solidity-coverage is being [rewritten](https://github.com/sc-forks/solidity-coverage/pull/372) so that it has fewer quirks and problems. One element of the new design is that it listens to the ethereumjs-vm opcode step emitter of an in-process ganache instance. In Truffle terms, it runs on a network which looks like:

```javascript
const ganache = require("ganache-cli")

modules.exports = {
  networks: {
    ganache: {
      provider: ganache.provider(options),
      network_id: "*"
    }
  }
}
```
Have been testing it on Zeppelin and the only issue is that some GSN tests rely on an [oz-gsn utility run in test.sh](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/scripts/test.sh#L66-L70) which connects to ganache-cli as a stand-alone server. 

I'm wondering if anyone has any views are about moving away from `test.sh` towards an in-process provider approach. 

I think the main changes this would involve are:

+ Putting the accounts keys and balances into their own file so they can be JS required. 
+ Writing an oz-gsn deploy relay hub test helper that uses an in-process provider
+ Launching the tests with ganache.provider by default.

**Pros**
+ Less shell script
+ There are interesting tools written to consume the client this way
  + NomicLabs is actively working on some...
  + 0xProject tooling 

**Cons/Caveats**
+ It runs a little more slowly. ([ganache-core 481](https://github.com/trufflesuite/ganache-core/issues/481) requests info about this)
+ Maintaining compatibility with a solution for #355?

Happy to help with PRs etc if this is something you're interested in.

**Comment by nventuro** [comment]
Hello @cgewecke! We of course will want to try out the new `solidity-coverage` once it comes out, and should modify our setup accordingly. I'm curious though, where does the need to have an in-process ganache come from? Will the new implementation be coupled to truffle, or is there some more generic API that can be used?

**Comment by cgewecke** [comment]
Hi @nventuro! 

> where does the need to have an in-process ganache come from?

Good question! An in-process ganache lets us access the VM directly and listen to a "step" event it emits each time an opcode is run. Solidity-coverage instruments contracts with statements which push a bytes32 data hash onto the evm stack. By watching the evm step we can detect the hash and mark it as a line or branch hit in a coverage map.

We need to collect opcode trace data for both `calls` and `sends`. At the moment ganache only provides a trace RPC endpoint for `sends` (debug_traceTransaction). 

0xProject's trace tools get around this restriction by replaying `calls` *as transactions* so their data is 'available' and then reverting the chain. However they also reported that there's a lot of data-transfer overhead using debug_traceTransaction and there has been a [reluctance at ganache](https://github.com/trufflesuite/ganache-core/issues/47#issuecomment-455560108) to fix that by making the trace method filterable.

Using an in-process provider tries to avoid that complexity...  fwiw it should be possible to adapt SC's design to work with a client like Parity which supports both traceTransaction and traceCall, although filtering might be necessary there as well.

> Will the new implementation be coupled to truffle, or is there some more generic API that can be used? 

It is strongly decoupled from Truffle. When the new version is released it will be available as both a Buidler and Truffle plugin and the API should allow integration with any JS ethereum dev stack or build process.

**Comment by nventuro** [comment]
(this is mostly me being curious)

Ohh, I see. And I'm guessing it is not possible to listen to `step` events on `ethereumjs-vm` when it is running as a separate process? I guess `solidity-coverage` needs more than just the ganache provider in order to work, is there a gist of the planed API available somewhere?

**Comment by cgewecke** [comment]
@nventuro 

> I'm guessing it is not possible to listen to step events on ethereumjs-vm when it is running as a separate process?

Like a websocket subscription or something? That would be really cool and has [been proposed at ganache](https://github.com/trufflesuite/ganache-core/issues/381) but not sure  what its status is.


> there are instances where we find it valuable to run tests on a standalone ganache instance,

I am curious about this - that seems very important. What do you see as the differences between in-process and standalone? 

The exposed API will be something like the `app` class in [this file](https://github.com/sc-forks/solidity-coverage/blob/truffle-plugin/lib/app.js#L52-L194). It's not finalized but it should be something very simple like
```
coverage.attachToProvider(provider) 
coverage.instrument(files) 
coverage.report()
```

**Comment by cgewecke** [comment]
@nventuro Thanks so much for your advice in this thread - incredibly helpful. 

Have now modified solidity-coverage to run ganache as an http server and added async hook options that allow the user to launch whatever external processes they want and connect to the coverage server as required. 

Have opened #1923 upgrading solidity-coverage using this approach for GSN. It's not exactly what you suggested but it preserves the stand-alone server launch for regular tests. . . 

Closing here in favor #1923.
