### ISSUE TITLE
Support for ERC677

### ISSUE THREAD

**Issue by LiorRabin** [OpenZeppelin/openzeppelin-contracts#1922]
**🧐 Motivation**

Implement `transferAndCall` ([ERC677](https://github.com/ethereum/EIPs/issues/677)) on top of ERC20.

**📝 Details**
* ERC20 [`transfer`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/54182bf31c78fb1b16dfdce40fc9a6a177cb3bca/contracts/token/ERC20/ERC20.sol#L62) function emits [`Transfer`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/54182bf31c78fb1b16dfdce40fc9a6a177cb3bca/contracts/token/ERC20/ERC20.sol#L160) event with `(sender, recipient, amount)`
* ERC677 `transferAndCall` emits `Transfer` event with `(sender, recipient, amount, data)`.

If I'm listening to Transfer events on some oracle I don't have a way to distinguish them.

Is there planned support for this in the future?

**Comment by abcoathup** [comment]
Hi @LiorRabin,

You may want to consider using ERC777 where the standard is final and has an OpenZeppelin implementation: https://docs.openzeppelin.com/contracts/2.x/tokens#ERC777

There have been some discussion in the community forum around draft ERC20 extensions ERC1003 and ERC827: https://forum.openzeppelin.com/t/erc1003-erc827-erc20-extensions-for-sending-tokens-to-smart-contracts/789

**Comment by LiorRabin** [comment]
Thank you @abcoathup, I will look into this

**Comment by frangio** [comment]
Thanks for reaching out!

We generally don't implement ERCs that are Drafts, and we're unlikely to support ERC677 for now. However, we encourage you to extend our ERC20 token through inheritance to add any functionality that you need.

**Comment by khokho1986** [comment]
0x975525d5CC92D872564535d0D5E8930bAc024Ff8
