### ISSUE TITLE
Add Documentation: ERC20Pausable, SafeERC20, TokenTimelock

### ISSUE THREAD

**Issue by deadpine** [OpenZeppelin/openzeppelin-contracts#1928]
These contracts' functions don't have explanations:

https://docs.openzeppelin.com/contracts/2.x/api/token/erc20#ERC20Pausable
https://docs.openzeppelin.com/contracts/2.x/api/token/erc20#SafeERC20
https://docs.openzeppelin.com/contracts/2.x/api/token/erc20#TokenTimelock

**Comment by GuillaumeCz** [comment]
According to the documentation, it seems that these function are actualy explained. 
@blancoagostina Can you please provide more details about what's mssing ? ;) 
...or maybe this issue is kind of outdated ?

**Comment by abcoathup** [comment]
Hi @GuillaumeCz,
Thanks for querying.
An example is: 
https://docs.openzeppelin.com/contracts/2.x/api/token/erc20#ERC20Pausable-transfer-address-uint256-

Compared to:
https://docs.openzeppelin.com/contracts/2.x/api/token/erc20#IERC20-transfer-address-uint256-

**Comment by GuillaumeCz** [comment]
Hi @abcoathup 
My bad ! I was looking to the contract's description itself instead of the functions ! 
Is anyone working on this issue ? 
I'm quite interested in having a try ;)

**Comment by abcoathup** [comment]
Hi @GuillaumeCz!  

Thanks for offering to contribute, it is really appreciated.  
OpenZeppelin Contracts 3.0 is currently being developed, so best to wait for the project owner to advise on this.

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the proposed changes beforehand.  We don’t want you to waste your time!

**Comment by GuillaumeCz** [comment]
I would be proud to contribute to this nice project ! 

Please ping me when it's ok on your side ;)

**Comment by nventuro** [comment]
Hey there @GuillaumeCz, thank you very much for the offer!

ERC20Pausable was simplified and now has proper docs, while TokenTimelock was removed from the library in the v3.0 release. If you're up to it, an area where better docs would definitely make a difference is ERC721: while there is some documentation, it is subpar. 

I'd recommend starting with the interfaces (IERC721, IERC721Metadata, IERC721Enumerable) and then going to ERC721, using the docs for ERC20 and ERC777 as guidelines regarding format, phrasing, etc. 

Thanks again!

**Comment by GuillaumeCz** [comment]
I would be glad to do it ! ;)

**Comment by GuillaumeCz** [comment]
@nventuro 
This is quite new for me, shall I create a new branch from master or shall I work with docs-v3.x branch ?

**Comment by nventuro** [comment]
Work directly on master, `docs-v3.x` is only used to actually deploy the site, to prevent unreleased features from showing up.

**Comment by frangio** [comment]
@GuillaumeCz Feel free to open a draft PR if you need any advice along the way.

**Comment by GuillaumeCz** [comment]
Owing to the fact that ERC721 interfaces documentation are done, can I start working on ERC721 contracts documentation ? ;)

**Comment by nventuro** [comment]
Of course! Look forward to your next PR :)

**Comment by nventuro** [comment]
We should also improve the ERC777 docs: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2212/files#r414772213

**Comment by frangio** [comment]
Of these `SafeERC20` is still missing. Moving to a separate issue tracker for content.
