### ISSUE TITLE
Error message exceeds max length of 76 characters in ERC777.sol

### ISSUE THREAD

**Issue by sshelton76** [OpenZeppelin/openzeppelin-contracts#1949]
Having a linting issue in ERC777.sol related to the length of one of the error messages.

**💻 Environment**
All

Current master branch

**📝 Details**

Lint is reporting the error message is too long for line 472 of ERC777.sol

```
require(!to.isContract(), "ERC777: token recipient contract has no implementer for ERC777TokensRecipient");
```
Exact message is 
>"error-reason: Error message exceeds max length of 76 characters"

Fix is to shorten the error message to something like...
```
require(!to.isContract(), "ERC777: token recipient missing ERC777TokensRecipient");
```

**Comment by nventuro** [comment]
Hello @sshelton76, thanks for raising this! Could you expand on which linter you are using that is failing with that error?

**Comment by frangio** [comment]
FWIW, I like the shorter message that @sshelton76 proposed.

**Comment by nventuro** [comment]
Me too, but I'd like to know if there's a particular reason why that linter chose to limit the maximum length to 76. From what I recall, the deployment cost of a contract increases steeply for every 32 bytes of revert string, so I wonder where the 76 comes from.

**Comment by abcoathup** [comment]
Hi @sshelton76, 

Which linter did you use which gave the maximum length of 76 characters?  As would be great to know where this came from.

Labelling as on hold whilst waiting for a reply.

**Comment by cameel** [comment]
I think it was Ethlint: https://github.com/duaraghav8/Ethlint/blob/v1.2.5/lib/rules/error-reason.js#L75-L80. But the project seems dead - no new commits since 2019.

**Comment by frangio** [comment]
Closing as stale. We hope to move to custom errors as soon as Web3.js and Ganache support them.
