### ISSUE TITLE
ERC777 operators should be internal not private

### ISSUE THREAD

**Issue by sshelton76** [OpenZeppelin/openzeppelin-contracts#1951]
**🧐 Motivation**

The current ERC777 code has a flaw that impacts security and usability.

Here is the code in question.
```
// This isn't ever read from - it's only used to respond to the defaultOperators query.
    address[] private _defaultOperatorsArray;

    // Immutable, but accounts may revoke them (tracked in __revokedDefaultOperators).
    mapping(address => bool) private _defaultOperators;
```

This design makes it impossible to extend the contract by adding or removing default operators and it appears that this is by design, but the thinking behind it is flawed and introduces a security problem.

**📝 Details**

Operators especially default operators allow us to extend contracts in interesting and meaningful ways.  However the use cases are limited because you either need to declare the operators upfront or convince the individual users to individually approve / reject operators on a case by case basis.

This is a safety issue as well.  At present there is no way to blacklist an operator if it is later found to be misbehaving except for each user to reject them one by one.

Making _defaultOperatorsArray and mapping(address => bool) private _defaultOperators internal instead of private would allow for contracts which could add or remove default operators while still providing the user the ability to individually blacklist operators they do not want to interact with.

I realize the logic behind the current design is that users should not be forced to accept new default operators at any random time.  Judging from the current design, the thinking appears to be that the users have the option to code review all operators prior to interacting with the ERC777 token.

Ostensibly that is true, but digging deeper it is easy to see many ways this could be abused.
  
The default operators list could be pre-populated at construction time with either addresses from the developer's own wallet or contract addresses based on forward projecting future contract addresses using something like this https://ethereum.stackexchange.com/questions/24248/how-to-calculate-an-ethereum-contracts-address-during-its-creation-using-the-so

This moots the idea that the user would have complete information prior to interacting with an ERC777 contract and thus it is providing users with a false sense of security, while limiting actual security. This is because, the lack of ability to remove a default operator except on a user by user basis means that if an operator contract is found to be buggy or misbehaving one would need to expend a HUGE amount of effort to reach out to each user to individually blacklist said operator.  A lot of damage could be done in the interim.

To wit, I would ask that rather than change the ERC777 standard, we make two small modifications to the existing ERC777.sol which allow contracts to extend ERC777 by simply taking these private vars and declaring them internal.

From there the contract creators can determine best how to add/remove and replace default operators and users will still maintain the ability to veto any operator they are uncomfortable with, but the devs can have an inbuilt process to deal with operators gone awry or adding new operators as opportunities to expand the use of the contract arise.

**Comment by sshelton76** [comment]
Alternatively adding the following lines to the official ERC777.sol would work as well

```
    function _addDefaultOperator(address operator) internal{
        _defaultOperatorsArray.push(operator);
        _defaultOperators[operator] = true;
        emit AuthorizedOperator(operator, address(this));
    }

    function _removeDefaultOperator(address operator) internal{
        _defaultOperators[operator] = false;
        
        for(uint x = 0; x <= _defaultOperatorsArray.length - 1; x++){
            if(_defaultOperatorsArray[x] == operator){
                _defaultOperatorsArray[x] = _defaultOperatorsArray[_defaultOperatorsArray.length - 1];
                _defaultOperatorsArray.pop();
                break;
            }
        }
        emit RevokedOperator(operator, address(this));
    }
```

**Comment by frangio** [comment]
Hi @sshelton76. Thank you for your report.

We implemented default operators in this way because the ERC777 standard quite unambiguously says so:

>The token MAY define default operators. A default operator is an implicitly authorized operator for all holders. AuthorizedOperator events MUST NOT be emitted when defining the default operators. The rules below apply to default operators:
>
> * The token contract MUST define default operators at creation time.
> * The default operators MUST be invariants. I.e., the token contract MUST NOT add or remove default operators ever.

Have you raised this concern with the authors of the standard?

I disagree with your following point though:

>This moots the idea that the user would have complete information prior to interacting with an ERC777 contract and thus it is providing users with a false sense of security

Prior to interacting the user can definitely see that they have only partial information regarding default operators if any of them either have empty bytecode (except if they've selfdestructed) or even if the source code is not available. Based on this they can decide either not to interact with the token or to revoke these operators before doing so. I don't see how any user can be particularly mislead here.

Let me know your thoughts.

**Comment by sshelton76** [comment]
>We implemented default operators in this way because the ERC777 standard quite unambiguously says so

Ok I get that, it doesn't make it less of a hassle though.  It means you're going to end up with forks each solving this in their own way rather than having the reference implementation address the underlying issue.

>Have you raised this concern with the authors of the standard?

No but it sounds like I probably need to.  Honestly though I'm unsure how to reach them and the fact this is a standard already means this ship has probably sailed already, but it is what it is I guess.

>Prior to interacting the user can definitely see that they have only partial information regarding default operators if any of them either have empty bytecode (except if they've selfdestructed) or even if the source code is not available. Based on this they can decide either not to interact with the token or to revoke these operators before doing so. I don't see how any user can be particularly mislead here.

You're missing the point.  Yes a *highly* technical user can easily check to see if the bytecode of a default operator exists and decide whether or not that is something they care to interact with.  However even a slightly less than *highly* technical user is not going to have this ability and probably wouldn't even think to check beyond looking at the Etherscan abi front end.  

Let's look at facts.  Nearly all users are already relying on the devs to properly vet any default operators beforehand.  The way it is right now, it doesn't solve the problem it's trying to solve (ensuring that only fully vetted code can touch the contract) and this introduces a false sense of security to the end users.  It also ties the dev's hands in the future.  That's what I meant by being mislead.  If the users are aware that default operators can change because there's already "addDefaultOperator" and "removeDefaultOperator" functions in the ABI then the stakes are much clearer upfront without requiring a full on code dive.

However this is probably a discussion that needs to be had with the authors of the standard.  As it stands now you're trying to retain strict compliance with a standard that has a hole in it big enough to drive a Mack truck through because the authors appear to have missed the human element when considering the elements of security.

**Comment by frangio** [comment]
>probably wouldn't even think to check beyond looking at the Etherscan abi front end.

I don't see how this is a problem for ERC777s in particular, and not for ERC20s or any other contract. The same goes for vetting the bytecode of a contract: it's already the case that only highly technical users can do it. And it's already the case that some contracts may have external actors with superpowers, be it operators, minters, owners, etc., that those vetting a contract have to pay attention to.

I don't agree with your points but I'd encourage you to bring it up in https://ethereum-magicians.org. I am also curious about other people's opinion.

**Comment by nventuro** [comment]
>You're missing the point. Yes a highly technical user can easily check to see if the bytecode of a default operator exists and decide whether or not that is something they care to interact with. However even a slightly less than highly technical user is not going to have this ability and probably wouldn't even think to check beyond looking at the Etherscan abi front end.

I agree with @frangio and this is not only true for ERC777 but also for _all_ smart contracts. The _vast_ majority of users will not read a contract's source code, and will rely on other people (presumably experts that they trust) to do their due diligence. This is not very different from how open source software is used.

That said, I do agree that the limitations the standard places on how the default operator list can be interacted with is too restrictive: the case you brought up where a malicious operator needs to be blacklisted neatly illustrates this point. I am unsure however as to how we should proceed in this regard, since deviating from the standard can have its unforeseen consequences. Perhaps we could add warnings on the documentation of the proposed additional functions?

>The default operators list could be pre-populated at construction time with either addresses from the developer's own wallet or contract addresses based on forward projecting future contract addresses using something like this https://ethereum.stackexchange.com/questions/24248/how-to-calculate-an-ethereum-contracts-address-during-its-creation-using-the-so

Note that it is possible to prove that an address belongs to an externally owned account by signing data using its private key, which contract's lack.

**Comment by frangio** [comment]
Closing this as an issue with the standard and not our implementation.
