### ISSUE TITLE
Not running tests because of Truffle issue

### ISSUE THREAD

**Issue by vittominacori** [OpenZeppelin/openzeppelin-contracts#1952]
Not running tests.
It is because of an issue with Truffle [#2461](https://github.com/trufflesuite/truffle/issues/2461#issuecomment-543298328).

Also your CircleCI [job](https://circleci.com/gh/OpenZeppelin/openzeppelin-contracts/1278?utm_campaign=vcs-integration-link) is not running tests at all.

**🔢 Code to reproduce bug**

Just `npm run test` will produce `0 passing`.

**Comment by frangio** [comment]
Wow... Indeed, though the check was green in #1947 the CI had actually executed 0 tests, and we didn't realize.

![image](https://user-images.githubusercontent.com/481465/67044385-92679000-f102-11e9-86bc-06f2e366d8f2.png)

Thanks @vittominacori!
