### ISSUE TITLE
ERC20 Approval event conformance

### ISSUE THREAD

**Issue by k06a** [OpenZeppelin/openzeppelin-contracts#1955]
[ERC20 Token Standard](https://eips.ethereum.org/EIPS/eip-20) tells:
> **Approval**
> MUST trigger on any successful call to `approve(address _spender, uint256 _value)`.

But current ERC20 implementation emits `Approval` event on every `allowance` change. Is there any practical reason for this or just a bug?

Original discussion started here: https://github.com/makerdao/dss/issues/76

**Comment by nventuro** [comment]
This has been discussed extensively in the past, and was a concious design decision. You can read more about the motivation on this issue (and associated PR): https://github.com/OpenZeppelin/openzeppelin-contracts/issues/707. The short version is that not emitting those events makes it impossible to reconstruct the state from events only.

Is this causing any issues in your application?

**Comment by k06a** [comment]
@nventuro that makes sense 👌
