### ISSUE TITLE
ERC20.sol file's 'function _transfer ' is different from github file

### ISSUE THREAD

**Issue by skqksh** [OpenZeppelin/openzeppelin-contracts#1966]
ERC20.sol file's 'function _transfer ' is different from github file

1. npm install @openzeppelin/contracts
2. checke contracts/token/ERC20/ERC20.sol of '_transfer ' function

in my 'ERC20.sol'
        _balances[sender] = _balances[sender].sub(amount);

but github
    _balances[sender] = _balances[sender].sub(amount, "ERC20: transfer amount exceeds balance");

**Comment by abcoathup** [comment]
Hi @skqksh,

The difference is that with the package you are using the latest release version which is 2.3
https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v2.3.0

Whilst on GitHub you are looking at the master branch.
You should always use code from a release version.

2.3 version:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/token/ERC20/ERC20.sol#L156

master version:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L158

For questions it is best to ask in the Community Forum as anyone from the community can help.
https://forum.openzeppelin.com/

**Comment by frangio** [comment]
This particular change was introduced in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1828 and is part of the 2.4 release.

This release has been in beta for a few months (longer than normal) but will be finally released next week.
