### ISSUE TITLE
ERC777: _burn should be internal

### ISSUE THREAD

**Issue by MicahZoltu** [OpenZeppelin/openzeppelin-contracts#1979]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/19a65903062293a3ed67ff10fd80572b798caf93/contracts/token/ERC777/ERC777.sol#L373-L380

Similar to `_mint`, the `_burn` method may need to be called by a particular token's implementation when various events occur.  One _could_ work around this by making the token be its own operator, but that just seems silly and is a waste of gas.

**Comment by frangio** [comment]
Hi @MicahZoltu! Thanks for reporting this issue.

We have an open PR (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1908) tackling this that has become stuck but I would like to move it forward.

Can you let me know your thoughts on the concern I expressed there before we implement this?

> My only concern with this PR is that it allows passing an arbitrary `operator`. This would be consistent with the current `_mint` function, but I feel that may have been an oversight. In my mind it would make much more sense to automatically set either `this` (or `msg.sender`?) as the operator in the `internal` functions. Otherwise the events emitted could be "lying". I realize this may be too much of a detail but I want us to think about it a bit before merging.

**Comment by frangio** [comment]
Was fixed in #1908.
