### ISSUE TITLE
SafeMath library functions for Solidity v0.5

### ISSUE THREAD

**Issue by AhirBudhnya** [OpenZeppelin/openzeppelin-contracts#1991]
Hi there, 

Saw that there is a version of the SafeMath library function for Solidity v0.5 here in this repository. 

For our Smart Contract with earlier v0.4 version, we had used a version of SafeMath library which had the following additional functions in the SafeMath library that is not present in the repository here:

    function max64(uint64 a, uint64 b) internal constant returns(uint64) {
        return a >= b ? a : b;
    }

    function min64(uint64 a, uint64 b) internal constant returns(uint64) {
        return a < b ? a : b;
    }

    function max256(uint256 a, uint256 b) internal constant returns(uint256) {
        return a >= b ? a : b;
    }

    function min256(uint256 a, uint256 b) internal constant returns(uint256) {
        return a < b ? a : b;
    }

    function assert(bool assertion) internal {
        if (!assertion) {
            throw;
        }
    }

Can you let us know if these functions require any porting to be used in v0.5 compiler as compared to v0.4 compiler and if so what would be the required changes? 

Thanks in advance for your inputs.

**Comment by frangio** [comment]
Hi @AhirBudhnya! We have moved the `max` and `min` functions to [the `Math` library](https://docs.openzeppelin.com/contracts/2.x/api/math#Math).

They are implemented only for `uint256` types. They will also work with `uint64`, although the output will always be `uint256`. Is this what you're looking for?

**Comment by AhirBudhnya** [comment]
Yes. Thanks for your prompt reply. Appreciate much!
