### ISSUE TITLE
ERC777 : Change visibility of transferFrom, transfer and approve functions from external to public.

### ISSUE THREAD

**Issue by arindamghosh4995** [OpenZeppelin/openzeppelin-contracts#1994]
**🧐 Motivation**
I am trying to move from a previous implementation of ERC20 to ERC777 with a few custom checks that need to be made before allocating allowances and transfer of tokens.

**📝 Details**
The current implementation of ERC777 makes moving from ERC20 to ERC777 difficult, since functions like ERC777.transferFrom cannot be called from any child class extending ERC777 contract.

**Comment by frangio** [comment]
Would you like to submit a PR?
