### ISSUE TITLE
Improve extensibility of ERC1155

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#2003]
@KaiRo-at suggested that our current contract is not extensible enough due to using `external` functions.

They also suggested to add an internal function that implements transfers to have a central extensibility point. I think this is fine but I would like to see the internal function use `msg.sender` rather than having a `sender` argument like we did in ERC20.

**Comment by KaiRo-at** [comment]
Seems like the [Augur implementation](https://github.com/AugurProject/augur/blob/master/packages/augur-core/source/contracts/libraries/token/ERC1155.sol) does have that internal function structure already. I think its naming of functions is not completely congruent with previous OpenZeppeling token implementations, and it implements some non-standard (but useful) extensions like totalSupply tracking, so it also could not be taken 1:1 but it can inspire for what to do.

**Comment by KaiRo-at** [comment]
This may be mostly bogus now as Solidity 0.6 and OpenZeppelin 3.0 seems to be geared towards WET rather than DRY (due to explicit overrides on Solidity's side and reducing library complexity on the OpenZeppelin side) and any changes that are not strictly extensions to the default OpenZeppelin implementation need copying of the whole contract code for other tokens as well from how I understand it.

**Comment by nventuro** [comment]
One of our top goals is definitively avoiding code repetition and users copy-pasting the library sources, this issue remains relevant.

We've already removed `external` from all other functions in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2162 and introduced _hooks_ as an extensibility point with this very goal in mind (see [the code for ERC777 for example](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v3.0.0-rc.1/contracts/token/ERC777/ERC777.sol#L405)), so it'd simply be a matter of implementing these on ERC1155: design work should be ready.

**Comment by KaiRo-at** [comment]
Hmm, if enough `virtual`s are spread throughout this and people can override those functions (I forgot for a moment that functions marked `virtual` do not actually require an override), then it may still work and be helpful, yes.

**Comment by KaiRo-at** [comment]
I've been pointed to https://twitter.com/xanderatallah/status/1232124941425881089 today and that makes me wonder if there is a generic way to do at least an `internal` implementation of `_exists()` like we have in ERC721, but that's not really easy the way ERC1155 is built in general.
It can be done in some specific implementations, though.

**Comment by frangio** [comment]
(@KaiRo-at I edited your comment just to add diff highlighting.)

I like the idea that specific projects may be able to define a notion of "exists", but for now I'm inclining towards not encoding that in our base contract because it's something rare and that would be simple to add on top.

**Comment by KaiRo-at** [comment]
@frangio the problem is that quite a few functions that use a `require(_exists())` pattern are probably `view` functions that are not declared `virtual` and therefore cannot be overridden easily, like the example of `uri()` I'm giving there. (...and thanks for the diff highlighting!)

**Comment by frangio** [comment]
Aha! That's super interesting. Do you know of any projects that are using or considering to include this notion of `exists`?

**Comment by KaiRo-at** [comment]
You mean, other than the one I'm working on right now? ;-)
Unfortunately, I can't make it public atm, but I'll be using all the ERC1155 patches I posted here and this `exists()` stuff in addition, in a project that is to be released "soon".
Also, having that notion of `_exists()` would match the OpenZeppelin ERC721 implementation.

**Comment by KaiRo-at** [comment]
I thought about this whole thing some more and I'm taking the suggestion to its own PR at #2185 - I figured it's probably best if we have an actually working `_exists()` there and figured a simple way we can do this (and not need the `view virtual` stuff), see there.

**Comment by Cybourgeoisie** [comment]
Hey all - I'd like to propose setting `virtual` to `uri` and `isApprovedForAll` in the ERC1155.sol file. OpenSea currently relies on an override to the default `isApprovedForAll` to permit use of a proxy address, and `uri` need to return the `id` value concatenated to the URI.

**Comment by abcoathup** [comment]
Hi @Cybourgeoisie, 
There is also a general discussion on making meta data view functions virtual:
https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2154

**Comment by frangio** [comment]
This issue has been fixed now that functions are both public and virtual.
