### ISSUE TITLE
Discuss adding version and copyright info to each contract

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-contracts#2006]
**🧐 Motivation**
More and more we see contracts being installed individually, instead of as part of the npm package. A recent example is the VS code plugin extension by the Microsoft Azure blockchain team: this extension allows a user to choose a contract by name, and it just downloads the solidity file (and its dependencies) to a local folder.

This has the problem that any project-wide information, such as copyright, license, or package version is lost. Though we could ask to every tool to add this information as they download the contracts, it may be easier to just add it at the source.

**📝 Details**
Add a comment header to every contract with something along the lines of:
```solidity
/**
 * @openzeppelin/contracts@X.Y.Z
 * Copyright zOS Global Limited, licensed under MIT
 * See https://github.com/OpenZeppelin/openzeppelin-contracts/
 */
 ```

And modify the release script so the version identifier on each contract is automatically updated, possibly just by using `sed -i`.

**Comment by abcoathup** [comment]
I really like the idea, especially when viewing verified contract source code in Etherscan where mostly contracts are flattened to a single file it is hard to determine where the code actually came from.

Also with decentralized projects like https://smartcontract.codes/ making it easier to find deployed contracts, could then filter for up to date (or outdated) contracts.

**Comment by nventuro** [comment]
This is related to https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1716, where it was brought up that a header on the source should not be taken as any sort of guarantee of security. A hint to where the code comes from does sound like a good idea however.

Regarding implementation, this would be done as a new script in `scripts/release`, called from [version.sh](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/scripts/release/version.sh) (see [synchronize-versions.js](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/scripts/release/synchronize-versions.js) for a similar one).

**Comment by abcoathup** [comment]
>header on the source should not be taken as any sort of guarantee of security
We could add a hash but that feels more like giving a false sense of security.  
Appropriate testing and audits are what we should teach the community to look for.

I think version and a link to the repository would be great.
