### ISSUE TITLE
ERC721: operator query for nonexistent token

### ISSUE THREAD

**Issue by gustech-omni** [OpenZeppelin/openzeppelin-contracts#2043]
After deploy ERC-721 Contract, when I am trying to use transferFrom or any function it's showing 

Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
gas required exceeds allowance (8000000) or always failing transaction

**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by abcoathup** [comment]
Hi @gustech-omni,

I suggest posting in the Community Forum with as much detail as you can: https://forum.openzeppelin.com/c/support/contracts/18

That way anyone in the community can more easily answer.

If you can include the contract, along with the snippet where you are attempting to transferFrom that would be helpful.

One potential issue to check for:
>https://docs.openzeppelin.com/contracts/2.x/api/token/erc721#IERC721-transferFrom-address-address-uint256-
Requirements: - If the caller is not `from`, it must be approved to move this NFT by either `approve` or `setApprovalForAll`.

**Comment by abcoathup** [comment]
Hi @gustech-omni,

I am closing this Issue as it is appears to be a support question.  

If you still have questions please post in the Community Forum so that the community can help: https://forum.openzeppelin.com/c/support/17
