### ISSUE TITLE
Add 'Available since...' note for new features in docs

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#2054]
Because we have a single unified site for all 2.x versions, we do what I call _content-versioning_: the documentation content itself provides information about different versions. For example, the docs for [`Address.toPayable()`](https://docs.openzeppelin.com/contracts/2.x/api/utils#Address-toPayable-address-) indicate it's only available starting from v2.4.0.

We should add the same notes for all new features in the upcoming v2.5.0 release: see the [changelog](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CHANGELOG.md#250-unreleased) for what these are.

**Comment by frangio** [comment]
See https://github.com/OpenZeppelin/solidity-docgen/issues/131
