### ISSUE TITLE
Directory and naming cleanup in next major release

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#2060]
It would be nice to do some cleanup in the next major release.

Here's my personal wishlist. Everything is open to discussion.

- Move `Pausable` from `lifecycle` into `utils`. There is only one contract in lifecycle and I'm not sure that we'd want to add any other contracts under that category.
- Remove `drafts` directory. It didn't work the way we wanted it to. Either graduate stuff to be properly supported, or create [feature branches](https://github.com/OpenZeppelin/openzeppelin-contracts/pulls?q=is%3Apr+is%3Aopen+label%3Ameta) (but we should work on them to finish them proper!).
- Rename `Secondary` into something else. It's a really bad name.

**Comment by nventuro** [comment]
Fixed via #2120 and #2122.
