### ISSUE TITLE
Cannot use command npx openzeppelin init

### ISSUE THREAD

**Issue by FouadHanoun** [OpenZeppelin/openzeppelin-contracts#2076]
Hello,

I have just started to take a look on open zeppelin and I have been unable to start with the tutorial.
My problem is that I cannot run `npx openzeppelin init` command.

What I did was: new folder, go to that folder then run `npm init`, I have node on v13.6.0 and npm on 6.13.4

I also ran `npm install @openzeppelin/contracts`

When I run `npx openzeppelin init` I get the following:

> npm ERR! code E404
> 
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/openzeppelin - Not found
> 
> npm ERR! 404
> 
> npm ERR! 404 ‘openzeppelin@latest’ is not in the npm registry.
> 
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> 
> npm ERR! 404
> 
> npm ERR! 404 Note that you can also install from a
> 
> npm ERR! 404 tarball, folder, http url, or git url.

I am working on MacOS 10.15.2 Catalina.
I have no clue what to do or where that is coming from. Any help?

**Comment by abcoathup** [comment]
Hi @FouadHanoun,

I have replied to your question in the forum: https://forum.openzeppelin.com/t/cannot-even-start-using-open-zeppelin-npx-openzeppelin-init-doesnt-work/2209

I am closing this issue as we can discuss in the forum.
