### ISSUE TITLE
Ownable's constructor unexecuted when inheriting

### ISSUE THREAD

**Issue by elishadrion** [OpenZeppelin/openzeppelin-contracts#2084]
**💻 Environment**

**oz** : `2.6.0`
**Solidity compiler** : `0.6.2`
**web3** : `1.2.6`

**📝 Details**

I have a contract inheriting `Ownable`. Once the contract is deployed, the internal constructor of `Ownable` isn't executed, leaving the `owner` attribute "empty".

When the code is tested on Remix, it returns the correct owner address.

When the code is deployed programatically with a JS script using web3, it's correct too.

**🔢 Code to reproduce bug**

The contract :
```javascript
contract Test is Ownable {}
```
The commands : 
`npx oz call`
```
? Pick a network development
? Pick an instance Test at 0x5475e9eE4106d5D1A4B2F0576bb3A7583A65Ff68
? Select which function owner()
✓ Method 'owner()' returned: 0x0000000000000000000000000000000000000000
0x0000000000000000000000000000000000000000

```

Here's the web3 script too : 

```javascript
const Web3 = require('web3');
const { setupLoader } = require('@openzeppelin/contract-loader');

async function main() {
  const web3 = new Web3('http://localhost:7545');
  const loader = setupLoader({ provider: web3 }).web3;
  const accounts = await web3.eth.getAccounts();
  const default_address = accounts[0];

  const Test = loader.fromArtifact('Test');
  const test = await Test.deploy().send({from:default_address, gas: 1500000,});
  const owner = await test.methods.owner().call();
  console.log(owner == default_address);

}

main();
```

**Comment by abcoathup** [comment]
Hi @elishadrion,

This appears to be a question on using OpenZeppelin.  It is best to ask in the Community Forum so that anyone in the community can help you.

Please post your question in the Community Forum with a link to this Issue: https://forum.openzeppelin.com/c/support/17

I am closing this Issue as it is a question.

**Comment by abcoathup** [comment]
Hi @elishadrion,

Assuming that you deployed an upgradeable contract with `oz create`, then you need to `Initialize` the contract with the owner.

The documentation on `Initializers` may help:
https://docs.openzeppelin.com/upgrades/2.6/writing-upgradeable#initializers

Please post your question in the Community Forum and we continue answering your question there.

**Comment by abcoathup** [comment]
Hi @elishadrion,

I posted your question in the Community Forum along with an answer: https://forum.openzeppelin.com/t/ownables-constructor-unexecuted-when-inheriting/2265
