### ISSUE TITLE
Typo in `operatorBurn` description

### ISSUE THREAD

**Issue by cleanunicorn** [OpenZeppelin/openzeppelin-contracts#2090]
**💻 Environment**

OpenZeppelin commit hash `e4d2830f1d60549e638c4108dc4621d3e76cfa65` (most recent at the time)

**📝 Details**

Small typo in method description.

```solidity
* @dev Destoys `amount` tokens from ...
```
Should be changed to
```
* @dev Destroys `amount` tokens from ...
```

**🔢 Code to reproduce bug**

Not a bug, just a typo.

**Comment by abcoathup** [comment]
Hi @cleanunicorn!  Thanks for the typo spot, it is really appreciated.

The project owner should review this during the next week.
