### ISSUE TITLE
Where did token/ERC20/ERC20Mintable.sol go? 

### ISSUE THREAD

**Issue by smalaichami** [OpenZeppelin/openzeppelin-contracts#2092]
It looks like that ERC20Mintable.sol contract is moved or removed. 
Could you please suggest what is the new parth for ERC20Mintable.sol ?

**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by abcoathup** [comment]
Hi @smalaichami!  

Thanks for your question. I have posted it in the Community Forum, where it can get a faster response by the community and the team. I will close this issue so we can continue the discussion there!

https://forum.openzeppelin.com/t/where-is-erc20mintable-sol-in-openzeppelin-contracts-3-0/2283
