### ISSUE TITLE
Options are incorrectly parsed using the command line cli.

### ISSUE THREAD

**Issue by hickscorp** [OpenZeppelin/openzeppelin-contracts#2102]
When issuing the command:

```
yarn oz session --timeout 30 --expires 7200 --from 0x356Cf535FC1f1C4dD1a4C4f4c261684bcbadf00d --network development
```

We get the output:

```
WARNING: Address --network is not checksummed. Consider checksumming it to avoid future warnings or errors.
Given address "--network" is not a valid Ethereum address.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems that OZ is ignoring the address parameter for the `--from` option and is seeing its value set to `--network` literally...

Everything was working recently, until our developers updated stuff outside the project (oh-my-zsh and installed global yarn packages).

**Comment by abcoathup** [comment]
Hi @hickscorp!  

We have been able to reproduce this issue by following these steps:
yarn oz --version `2.7.1`
node `10.19.0`
npm `6.13.4`
OS: Windows 10 with WSL
1. Run `ganache-cli` in a separate terminal
2. In a project with OpenZeppelin CLI installed locally, ensure there are no open sessions
```
$ yarn oz session --close
yarn run v1.21.1
$ /c/Users/andre/Documents/projects/forum/hicks/node_modules/.bin/oz session --close
Closed openzeppelin session
Done in 6.06s.
```
3. Create a new session
```
$ yarn oz session --timeout 30 --expires 7200 --from 0x356Cf535FC1f1C4dD1a4C4f4c261684bcbadf00d --network development
yarn run v1.21.1
$ /c/Users/andre/Documents/projects/forum/hicks/node_modules/.bin/oz session --timeout 30 --expires 7200 --from 0x356Cf535FC1f1C4dD1a4C4f4c261684bcbadf00d --network development
? Enter a timeout in blocks to use for websocket-based web3 transactions 50
Using network development, sender address 0x356Cf535FC1f1C4dD1a4C4f4c261684bcbadf00d, timeout 30 seconds, blockTimeout 50 blocks by default.
Done in 7.17s.
```
4. With the session open, create a session with the same command
```
$ yarn oz session --timeout 30 --expires 7200 --from 0x356Cf535FC1f1C4dD1a4C4f4c261684bcbadf00d --network development
yarn run v1.21.1
$ /c/Users/andre/Documents/projects/forum/hicks/node_modules/.bin/oz session --timeout 30 --expires 7200 --from 0x356Cf535FC1f1C4dD1a4C4f4c261684bcbadf00d --network development
Could not connect to the development Ethereum network on http://localhost:8545. Please check your networks.js configuration file. Error: Given address "0x356Cf535FC1f1C4dD1a4C4f4c261684bcbadf00d" is not a valid Ethereum address or it has not been checksummed correctly..
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Thanks so much for reporting it! The project owner will review and triage this issue during the next week.  In the meantime, you can try the following workaround:

1. Close the current session with `yarn oz session --close` before trying to create a new session
OR
2. Close the current session with `yarn oz session --close` before trying to create a new session, then use checksum addresses.  The session command can then be run multiple times.
The easiest way to get a checksum address is to paste into Etherscan and Etherscan will show a checksum address that you can copy.

**Comment by frangio** [comment]
I believe this is an issue in @openzeppelin/cli, right?

**Comment by hickscorp** [comment]
Reporting back - after restarting our shell the problem went away... Very sorry for the noise, as I think this bug is very likely to be an edge case of PATH or something like this that didn't get updated during a ZSH update or yarn global packages...
