### ISSUE TITLE
ECDSA recover for EIP-155 transaction signatures

### ISSUE THREAD

**Issue by forshtat** [OpenZeppelin/openzeppelin-contracts#2108]
**🧐 Motivation**
We have been using the ECDSA.sol in the RelayHub to do an ecrecover of transaction signatures, not message signatures (in the 'penalize()' method).
This does work for pre-eip155 transaction signatures, but for post-155 signature, the 'v' parameter has to be calculated separately before passing the signature to 'recover'.
Also, I think in some similar cases, it may be necessary for 'ecrecover' to also check if the signature is valid for the current chainID. What do you think?

**📝 Details**

**Comment by nventuro** [comment]
I believe I had considered EIP155 signatures for RelayHub, and there was a way to craft a `penalize` call even if those were used, though I'm fuzzy on the details. The chainID would require using the [specialized opcode](https://eips.ethereum.org/EIPS/eip-1344) (is this available in Solidity?), but it should be doable. 

What sort of interface did you have in mind for this?

**Comment by forshtat** [comment]
@nventuro I gave it some more thought and realized it is not as simple or useful as I thought, so I closed the issue. 

I now realize that as it is only applicable to entire transactions, which sounds like an edge-case, and the required interface for this would be something like this:
```function recover(bytes  memory unsignedRlpEncodedTx, bytes memory signature) internal pure returns (address) {...}```
So that if V == 38, the code can read the ChainID from the transaction, compare it to the current ChainID,  and either fail if these don't match or compute ```actualV = v - (chainId * 2 + 8 )``` and proceed with the recover. 

RelayHub can live without it, we don't need to care whether the transaction was targeting this particular chain in 'penalize' flow.

P.S. Solidity allows chainID opcode in assembly.

**Comment by nventuro** [comment]
Indeed, I'd say computing the signer for an Ethereum transaction is quite a strange scenario for a smart contract, I'd be interested to learn about applications that need to do this.

Given that RelayHub is not one of these, we can keep this closed. Thanks!
