### ISSUE TITLE
Consider removing findUpperBound from Arrays

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#2131]
As mentioned [here](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2122#discussion_r393223754), its semantics are very specific to `ERC20Snapshot` and may not be generally useful.

If we move forward with making this function a `private` function of `ERC20Snapshot`, we'd have to figure out how to port the tests for it.

**Comment by nventuro** [comment]
I'm not so sure it's worth removing this from the library: it isn't much more than a binary search, the associated effort with getting rid of it is not small (due to the need to port the tests).

**Comment by frangio** [comment]
Agreed. Let's keep it.
