### ISSUE TITLE
Contracts Import Paths in Windows

### ISSUE THREAD

**Issue by sacredwx** [OpenZeppelin/openzeppelin-contracts#2140]
Importing contracts that refer other contracts fail.

**💻 Environment**

"@openzeppelin/contracts": "^2.5.0",
no truffle,
vs code project
node 12.14.0

**📝 Details**

Hi guys,
I've encountered a problem, which many others face.
In windows trying to include a contract, that refers another contract an error jumps.

```
✖ Compiling contracts with solc 0.5.17 (commit.d19bba13)
Compilation errors: 
@openzeppelin/contracts/ownership/Ownable.sol:3:1: ParserError: Source "@openzeppelin/contracts/GSN/Context.sol" not found: File import callback not supported 
^--------------------------^
```

I found a solution that does not require from users to switch os to linux or to install a WSL.
You can change the imports within all the contracts from relative to absolute, i.e.:
this:
import "../GSN/Context.sol";
can be changed to this:
import "@openzeppelin/contracts/GSN/Context.sol";

and everything starts work just fine!
thanks.

**🔢 Code to reproduce bug**

```solidity
// contracts/Box.sol
pragma solidity ^0.5.0;

import "@openzeppelin/contracts/ownership/Ownable.sol";

contract Box is Ownable {
    uint256 private value;

    // Emitted when the stored value changes
    event ValueChanged(uint256 newValue);

    // Stores a new value in the contract
    function store(uint256 newValue) public onlyOwner {
        value = newValue;
        emit ValueChanged(newValue);
    }

    // Reads the last stored value
    function retrieve() public view returns (uint256) {
        return value;
    }
}
```

**Comment by abcoathup** [comment]
Hi @sacredwx!  

I don't have access to a native Windows development environment so wasn't able to reproduce this issue (I use WSL).  The suggested change doesn't work for developing/building OpenZeppelin Contracts.

Thanks so much for reporting it! The project owner will review and triage this issue during the next week.  In the meantime, you can try the following workaround:
Microsoft recommends using Windows Subsystem for Linux:
https://forum.openzeppelin.com/t/solidity-smart-contract-development-on-windows/2110

**Comment by abcoathup** [comment]
Hi @sacredwx,

Can you advise what you were compiling the code with and what version this was?  You mentioned "no truffle" so not sure what you were using.

**Comment by sacredwx** [comment]
Hi @abcoathup ,
latest openzeppelin/cli for the date.

**Comment by frangio** [comment]
This sounds like it would be a bug in the tooling (Truffle, Hardhat), so I'll close this issue.
