### ISSUE TITLE
ERC721Mintable is missing after the update to 0.6.x

### ISSUE THREAD

**Issue by Flash-Git** [OpenZeppelin/openzeppelin-contracts#2142]
`ERC721Mintable` is missing from [/ERC721/](../tree/master/contracts/token/ERC721) despite being in the README alongside `ERC721Burnable` and `ERC721Pausable`.

I checked a few open issues and I can't find any direct reference to this.

**Comment by abcoathup** [comment]
Hi @Flash-Git !

Thanks for your question. I have posted it in the Community Forum, where it can get a faster response by the community and the team. I will close this issue so we can continue the discussion there!

https://forum.openzeppelin.com/t/where-is-erc721mintable-sol-in-openzeppelin-contracts-3-0/2508
