### ISSUE TITLE
Go through ERC20Snapshot review

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#2147]
@elopio posted [a review of `ERC20Snapshot`](https://forum.openzeppelin.com/t/draft-review-erc20snapshot/302) in the forum a year ago. Some of the comments are about the API and this is the moment to review it, before we release 3.0. Sorry I keep adding things! Here goes each individual comment from the review that concerns the API:

- [ ] the name `ERC20Snapshot` is not good. To be fully explicit, a better name would be `ERC20WithOnDemandSnapshots`.
- [ ] snapshot is not a nice verb. I suggest to rename the `snapshot` function to `makeSnapshot`, the `Snapshot` event to `SnapshotMade`, and never ever say snapshotted.
- [ ] Snapshot ids start at 1. This is weird, and we are more used to 0-indexing so it could lead to off-by-1 errors.
- [ ] Anybody can call `snapshot`. There should be a role for this. (NB: This function was public but has now been made internal.)
- [ ] I dislike `balanceOf`, but `balanceOfAt` is terrible. I suggest `getBalanceFromSnapshot`. I suggest `totalSupplyAt` -> `getTotalSupplyFromSnapshot`. `_valueAt` -> `_valueFromSnapshot`.

**Comment by frangio** [comment]
About naming: I personally prefer all the shorter names. I actually think users appreciate succinctness, and in this case I don't think the names are terrible.

About the function names: I agree that `getBalanceFromSnapshot` is better, but I chose `balanceOfAt` initially in order to create simple predictable names from the existing functions (`*` -> `*At`) but I don't know how valuable this really is.

**Comment by nventuro** [comment]
I also like the current names. In particular I think `balanceOfAt` does a good job at showing it's the same thing as `balanceOf`, _at_ a particular snapshot. Getting something _from_ a snapshot looks strange, snapshots don't actually store anything themselves.

Regarding the 0-indexing, ids are just identifiers: they should not be expected to be sequential.

**Comment by frangio** [comment]
Okay then. Closing this as resolved: we decided to keep the current names, and `snapshot` is no longer public.
