### ISSUE TITLE
Restore EnumerableSet.enumerate

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#2166]
This function was removed in #2160 due to issues with casting arrays of different types.

This can be achieved using assembly:

```solidity
bytes32[] x = ...;
uint[] ret;
assembly { ret := x }
```

However, creating an assembly block brings all assembly keywords into scope, which causes shadowing warnings to be emitted by the compiler due to the existence of functions with names such as `add` in the same scope.

We should devise a way to bring `enumerate` back without these warnings being triggered.

**Comment by thegostep** [comment]
The better approach would be to store all base data as uint and delegate implementation of types to the user

**Comment by thegostep** [comment]
In any case, my solution here does not trigger a warning: https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2295

**Comment by frangio** [comment]
>delegate implementation of types to the user

We're avoiding this because it can easily result in unsafe casting that we'd rather keep internal to the library.

**Comment by ernestognw** [comment]
Should've been closed by #2768
