### ISSUE TITLE
Cannot use OpenZeppelin Contracts 3.0 beta

### ISSUE THREAD

**Issue by shunp** [OpenZeppelin/openzeppelin-contracts#2175]
### Problem

I was going to try using OpenZeppelin Contracts 3.0 beta but it cannot be installed.

```sh
> npm install --save-dev @openzeppelin/contracts@beta
```

### Error Message

No matching version found for @openzeppelin/contracts@beta.
In most cases you or one of your dependencies are requesting
a package version that doesn't exist.

**💻 Environment**

npm 6.12.1
node v12.13.1
macOS

**Comment by nventuro** [comment]
Hm, it seems like the beta tag was removed when the release candidate came out. Take a look at [the announcement](https://forum.openzeppelin.com/t/openzeppelin-contracts-v3-0-final-release-candidate/2583) to learn about what's included there!

To install it, run

```
npm install --save-dev @openzeppelin/contracts@next
```
