### ISSUE TITLE
Upgrade solidity-coverage to ^0.7.2 to support Solidity v0.6

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#2189]

**Comment by nventuro** [comment]
Ideally this will be handled by a new version of [OpenZeppelin Test Environment](docs.openzeppelin.com/test-environment/), which has added this feature to its [Q2 2020 roadmap](https://github.com/OpenZeppelin/openzeppelin-test-environment/issues/73).
