### ISSUE TITLE
Document workarounds for ECDSA.recover with Ganache

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#2190]
In 2.2.0 we introduced protections against malleability of ECDSA signatures. More details can be found in https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1622.

One unfortunate side effect of this has been that `ECDSA.recover` stopped working with Ganache-generated signatures, because they use the signatures parameters that the library rejects. This seems to be a problem with Ganache only. There seems to be plans to fix it in the next major version of Ganache, with an unknown ETA. The relevant issues are https://github.com/trufflesuite/ganache-core/issues/451, https://github.com/trufflesuite/ganache-core/issues/556.

We evaluated rolling back the changes to ECDSA in Contracts 3.0. Given that we think malleability protection makes sense in general, that the issue only affects the current version of Ganache, and that there are workarounds, we decided to keep the current behavior and instead improve the documentation by including the workarounds that are required to make it work in Ganache, and more details about the issue to understand it.

The workaround can be found in [`test/helpers/sign.js: fixSignature`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/b6513f6ad7f8a31c2bbfd9a8e0a85e78ea5b0df5/test/helpers/sign.js#L9-L19). We should move it to test-helpers to make it available as a complement to the documentation.

**Comment by nventuro** [comment]
I want to add a short clarification, given a bit of context is needed to understand this. 

The current ECDSA code is correct, safe, and will work as intended in all testnets and the main Ethereum network. This is a side-effect of an issue with how a Ganache node behaves on `eth_sign` RPC requests, which on the worst case will lead to head-scratching while developing locally against a ganache node.

**Comment by sarveshwar-singh** [comment]
This side effect took my 16 hrs of debugging.
@frangio Thanks for listing the issue.

**Comment by nventuro** [comment]
> which on the worst case will lead to head-scratching while developing locally against a ganache node.

:sweat_smile: sorry this caused you so much trouble @sarveshwar-singh!

**Comment by giuseppeg** [comment]
Hello there. I just stumbled upon this issue and would appreciate any help:

I signed a message with `web3.eth.sign(message, myAddress)` using MM `10.20.0` and web3 `1.8.0` and still need to fix the signature otherwise `ECDSA.recover` fails with 

```
ECDSA: invalid signature 'v' value
```

Looking [at this commit](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2619/files) though it seems that the workaround shouldn't be needed anymore.
