### ISSUE TITLE
Add "fromAddress" to utils/Strings.sol

### ISSUE THREAD

**Issue by WyseNynja** [OpenZeppelin/openzeppelin-contracts#2197]
**🧐 Motivation**

I am trying to get more useful revert messages in my contracts and being able to format uint256 as a string has been really helpful. It would be nice if the other types had this, too. For now, I only need `fromAddress`.

**📝 Details**

There are a couple (slightly outdated) implementations here: https://ethereum.stackexchange.com/questions/8346/convert-address-to-string

**Comment by WyseNynja** [comment]
I tried all the methods on that stackexchange link and only one worked for me:

```
    function fromAddress(address x) internal pure returns (string memory) {
        bytes32 value = bytes32(uint256(x));
        bytes memory alphabet = "0123456789abcdef";

        bytes memory str = new bytes(42);
        str[0] = '0';
        str[1] = 'x';
        for (uint i = 0; i < 20; i++) {
            str[2+i*2] = alphabet[uint(uint8(value[i + 12] >> 4))];
            str[3+i*2] = alphabet[uint(uint8(value[i + 12] & 0x0f))];
        }
        return string(str);
    }
```

I don't know how efficient this is gas-wise, but that doesn't matter for my current purposes.

**Comment by abcoathup** [comment]
Hi @WyseNynja!  Thanks for the suggestion, it is really appreciated.

The project owner should review your suggestion during the next week. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by nventuro** [comment]
Could you share a short snippet of how you're using this to create nicer error messages?

I'd rather see tooling move in a direction where we can retrieve values directly without having to convert them to strings inside the EVM (!), though I guess there's not much harm in having such a helper. I wonder how easy it'd be to create these messages though.

**Comment by WyseNynja** [comment]
This is what I'm doing for now. I just wanted useful reverts in dev so I'm not caring about gas efficiency at all.

```
if (ending_vault_balance < starting_vault_balance) {
  uint256 decreased_amount = starting_vault_balance - ending_vault_balance;
  string memory err = string(abi.encodePacked("Vault balance of ", address(borrow_token).fromAddress(), " did not increase. Decreased by ", decreased_amount.fromUint256()));
  revert(err);
}
```

This one mostly works, but theres some bytes at the front of call_returned that I don't know how to deal with. That's a separate issue though.

```
(bool success, bytes memory call_returned) = action_address.call{value: action_value}(actions[i].data);

if (!success) {
    string memory err = string(abi.encodePacked("on call #", i.fromUint256()," to ", action_address.fromAddress(), " with ", action_value.fromUint256(), " ETH failed: '", string(call_returned), "'"));
    revert(err);
}
```

**Comment by nventuro** [comment]
Hello @WyseNynja, sorry to have left you hanging. 

Even if usefulness of this feature is unclear, we think it might make sense to include it in the OpenZeppelin Contracts library to provide users with the flexibility to perform these sort of tasks. We arrived at a similar conclusion in https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1795 (which is rather relevant here).

Unfortunately, we don't have enough bandwidth to properly include features that will likely go unsed, with the associated tests, documentation and maintenance tasks, and think our effors will have a larger impact in areas where there's larger evidence of community demand. Head to our [roadmap](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2207) to learn about what we're currently working on.

I'll keep this issue open as a space for people to discuss this and related features - if we find interesting use cases where such as thing is needed, then we can carry on work and think how to best support them from the Contracts library.

Thank you very much for your work and suggestions @WyseNynja!

**Comment by WyseNynja** [comment]
That makes sense. For now, I have a `Strings2.sol` that I'm using for this.

**Comment by WyseNynja** [comment]
Oops. I mis-clicked.

**Comment by ItsNickBarry** [comment]
I have a situation where `n` contracts may be deployed and linked to a corresponding `ERC20` contract.  Users may hold tokens from any number of these `ERC20` contracts.

The token metadata is generated using the string representation of the address of the linked contract.  Something like `string(abi.encodePacked('Linked: ', address(_linkedContract).toString()))`.

This isn't the ideal UI feature, but compare it to Uniswap's tokens, for example, each of which is nondescriptly named "Uniswap V1 (UNI-V1)".

**Comment by nventuro** [comment]
Thanks for sharing your use case @ItsNickBarry! That's very interesting.

A slight issue with this is that the addresses wouldn't be [checksummed](https://eips.ethereum.org/EIPS/eip-55). It doesn't seem like it'd be terribly hard to implement the checksum, though we'd have to hash the address and access its bits, requiring some masking.

**Comment by Amxx** [comment]
This is resolved by [this function](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Strings.sol#L56).

```string fromAddress = toHexString(uint256(uint160(myAddress), 20)```

**Comment by frangio** [comment]
@Amxx What do you think about oadding an override for `toHexString` so a user could simply write `toHexString(myAddress)`?
