### ISSUE TITLE
Batch operations for AccessControl

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#2203]
It's currently only possible to modify one role-account pair at a time. For building management UIs with good usability it's basically a requirement to be able to do batch operations. Being able to grant _and_ revoke multiple roles from multiple accounts in one transaction.

The first option I thought of was a `toggleRoles` function that receives a list of role and account list pairs (`(bytes32, address[])[]`). For each pair: the sender is checked to be an admin for the role, and each account is either granted or revoked the role depending on their current status. However, there is a huge problem with any sort of toggling in that it is not safe for concurrent writes, and I think that would be particularly bad for access control.

To solve the concurrency problem we need to explicitly say whether we want to grant or revoke an account's role. The list argument should thus contain triples: a role and two account lists, one for granting and the other for revoking.

**Comment by nventuro** [comment]
Indeed, toggling doesn't seem like a great idea - these controls should have the same effect regardless of the current state of the system (is there a term for this? idempotency is not the right word).

Would you add this to the base `AccessControl` contract, or build on top of it? I think I'd rather not force features that are not strictly needed to all users.

**Comment by frangio** [comment]
I would add this to the base contract.

**Comment by julianmrodri** [comment]
@nventuro @frangio  would be happy to give this a shot. I can post here a proposal and we can discuss the overall design. It would have to be after Consensus though, which is next week. If you are OK let me know! thanks!

**Comment by nventuro** [comment]
>The list argument should thus contain triples: a role and two account lists, one for granting and the other for revoking.

If we're batching operations, should we not also allow for multiple roles? The caller would have to be the admin of all of them though, which may not be common.

@frangio why not provide this as an extension? Not everyone will need batching, and it might be a good idea to make it optional to keep bytecode size low.

**Comment by frangio** [comment]
Yes the idea would be the argument to this function is a list of triples: `(role, address list, address list)[]`, which allows managing multiple roles at once. I actually think it would be pretty common to have a single admin role for all other roles.

If we don't think this will be generally useful, or that it will be too expensive to deploy, I think I prefer to not provide it as an extension either. I don't like having so many variants of everything.

**Comment by frangio** [comment]
Closing this in favor of the more general `Multicall` contract!

See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2558
