### ISSUE TITLE
Add event for AccessControl._setRoleAdmin

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#2210]
Whenever a role's admin is set by [_setRoleAdmin](https://docs.openzeppelin.com/contracts/3.x/api/access#AccessControl-_setRoleAdmin-bytes32-bytes32-), we should emit an event indicating this happened.

Not only is this useful to react to admin changes, it will also help in dynamic role schemes, where a role hierarchy may be set up without any account having the roles.

**Comment by Skyge** [comment]
That is good, how about the name of this new event is `NewRoleAdmin` or something else?

**Comment by nventuro** [comment]
We name events as verbs in the past tense, so it'd have to be something like `RoleAdminChanged`. I now wonder if `_setRoleAdmin` shouldn't be `_changeRoleAdmin`: 'set' might give the impression of it being a one-off thing.

**Comment by julianmrodri** [comment]
@nventuro I would like to tackle this if you are OK. Not sure whats the expected timeline but can take a look during the weekend if required. Can do just the event or also the renaming if we agree. Let me know, just looking on how to contribute :)

**Comment by nventuro** [comment]
Go for it! The event alone should be fine, it'll be a straightforward PR :)

**Comment by julianmrodri** [comment]
@nventuro Just submitted PR. Ran the tests and lintern and seems to be fine. I dont think we have to modify the CHANGELOG. Please let me know how it looks. Thanks!

**Comment by Skyge** [comment]
> I now wonder if _setRoleAdmin shouldn't be _changeRoleAdmin: 'set' might give the impression of it being a one-off thing.

As far as I am concerned, the function name is OK, the 'set' also means it can 'change', of course,  in order to make it more clear, we can add some comments.
