### ISSUE TITLE
IERC721Receiver should be an 'interface'

### ISSUE THREAD

**Issue by KaiRo-at** [OpenZeppelin/openzeppelin-contracts#2217]
Since I saw that IERC721 was converted from an 'abstract contract' to an 'interface', I tried to include IERC721Receiver in an 'interface' of mine (with OpenZeppelin 3.0.0) and was surprised that it has not been converted as well. This should probably be done.

**Comment by abcoathup** [comment]
Hi @KaiRo-at!  Thanks for the suggestion, it is really appreciated.

The project owner should review your suggestion during the next week. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by frangio** [comment]
Thanks for reporting! Seems like it was an oversight. It shouldn't be a breaking change so we can go ahead and make this change.

**Comment by julianmrodri** [comment]
@frangio Just submitted a PR to fix this issue based on your command to move ahead. Let me know if I need to make any other changes. Thanks!
