### ISSUE TITLE
Use new interfaceId syntax for ERC165

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#2227]
[Solidity v0.6.7](https://github.com/ethereum/solidity/releases/tag/v0.6.7) now supports building ERC-165 identifiers via the `type(InterfaceName).interfaceId` syntax.

We should add examples to our [ERC165 implementation](https://docs.openzeppelin.com/contracts/3.x/api/introspection#ERC165)'s documentation, showing usage of this new syntax.

**Comment by Amxx** [comment]
This was implemented in https://github.com/OpenZeppelin/openzeppelin-contracts/commit/e733b24dfe530bb5f669c749d8b7bcff49c8ae88
