### ISSUE TITLE
Ownable contracts cannot be created by factories

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#2236]
If a contract is `Ownable`, the owner is automatically set to the deployer account. Because `transferOwnership` can only be called by the owner, these contracts cannot be deployed by generic factory contracts because they will retain ownership and have no way of transferring it to another account.

There's two ways to work around this in 3.0, neither of them very comfortable:
1. Override `Context._msgSender` such that `Ownable` assumes the deployer account is a different one, potentially specified as a constructor argument.
2. Perform a delegatecall to the `transferOwnership` function as part of the constructor. This is really only possible in proxies because there is a contract that can be delegatecalled. In non-proxied contracts, the bytecode in `this` hasn't been set yet, and it cannot be delegatecalled.

It seems that we should simply bring back the internal `_transferOwnership` that was removed in 3.0. In restrospect, I don't think it was removed for any good reasons, and this is a very clear situation where it would've been useful. We did bring back the internal `_setupRole`, which is the analogous function in `AccessControl`.

**Comment by nventuro** [comment]
I'm not sure I see the issue with factories. Are you saying the following code will not work?

```
contract Factory {
  function deployContract(address owner) public returns (Ownable) {
     Ownable deployed = Ownable.new();
     deployed.transferOwnership(owner);
     return deployed;
  }
}
```

**Comment by frangio** [comment]
The issue is with _generic_ factories. So, factories that can be used to deploy any contract and that don't contain any logic specific to that contract.

**Comment by julianmrodri** [comment]
So bringing back the `_transferOwnership` would do the trick?  Seems we need to revert this [change](https://github.com/OpenZeppelin/openzeppelin-contracts/commit/5b5d91c9d46e436818ca3ef8fbfa9394fc6a33c6#diff-92fed4d3c8004a2463ff9203cb98e8d3).

 I can take care if you want. Should we do any additions to the Tests to contemplate this scenario?

**Comment by frangio** [comment]
I think we'd want to follow the same convention we use in `AccessControl` and name it `_setupOwnership`. @nventuro ?

**Comment by nventuro** [comment]
I'm not sure about `_setup`, since it does more than that: there is only one owner, and `_setup` would also remove the original one.

What is the use case for a generic factory, just the deterministic address? This seems like an advanced use case for a very simple contract, I'm not sure we should make it more complex to cater to this scenario.

**Comment by frangio** [comment]
There can be a lot of use cases for generic factories. It doesn't make sense to enumerate them. As an example, someone could have a factory that pays for the gas.

I don't think it adds complexity to add this internal function. We removed it because we wanted to close down the API, but then we added back `_setupRole`, giving up that closedness for the `AccessControl` contract. So why shouldn't we add this one here?

**Comment by orenyodfat** [comment]
hey @frangio @nventuro . any update re the one ?

**Comment by frangio** [comment]
@orenyodfat We haven't reached a decision yet. Do you have any preference for the alternatives laid out here?

**Comment by orenyodfat** [comment]
Both alternatives are not nice.
Do you have an eta for decision re that ?

**Comment by orenyodfat** [comment]
@nventuro @frangio ?

**Comment by frangio** [comment]
We've decided to implement the internal transfer ownership function. You can expect a patch release later this week.

**Comment by orenyodfat** [comment]
thanks . well, seems like transferOwnership will inside the initialize function will do the work as it use msgSender() .
see https://github.com/daostack/infra/blob/7cb1a3c38bca58f335c1e7bf9293351ffe1f0108/contracts/Reputation.sol#L76

**Comment by frangio** [comment]
@orenyodfat I was about to implement this issue and realized that the internal function is not necessary if the use case is to run it in the constructor (or in an initializer function ran in the context of a constructor): the existing `transferOwnership` can already be used in this situation.  I looked at your link and this is exactly what you're doing. So I'm a bit lost now: what is your issue exactly? Does the contract that you just shared not work?

I'm sorry I didn't mention this earlier. I was sure I had considered it and that it didn't work for some reasson.

**Comment by orenyodfat** [comment]
> @orenyodfat I was about to implement this issue and realized that the internal function is not necessary if the use case is to run it in the constructor (or in an initializer function ran in the context of a constructor): the existing `transferOwnership` can already be used in this situation. I looked at your link and this is exactly what you're doing. So I'm a bit lost now: what is your issue exactly? Does the contract that you just shared not work?
> 
> I'm sorry I didn't mention this earlier. I was sure I had considered it and that it didn't work for some reasson.

it now works. (I did not noticed that that the transferOwnership use msgSender()) .. .
though still I think there is a room  for optimisation , as with the "workaround" there are 2 storage writes. (for the _owner).

**Comment by frangio** [comment]
Unfortunately we can't change the constructor of `Ownable` (thus its initializer) without introducing a breaking change, and even if we introduce an internal function, you would have to forgo calling `Ownable`'s initializer function to avoid the double storage write, and this would be a dangerous misuse of the library.

**Comment by frangio** [comment]
Additionally, the second storage write has much lower cost than the first, so the optimization is not as worth it. It will cost the same as an `SLOAD` according to [EIP 2200](https://eips.ethereum.org/EIPS/eip-2200).

**Comment by frangio** [comment]
Closing as resolved according to https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2236#issuecomment-637098266.
