### ISSUE TITLE
ERC721 Full Contract still in documentation after being removed 

### ISSUE THREAD

**Issue by josh-kean** [OpenZeppelin/openzeppelin-contracts#2239]
I noticed that the documentation still shows the solidity version being 0.5.0, and it shows the ERC721Full.sol file as being a usable file. Since the newest npm package of openzeppelin uses 0.6.0 and the ERC721Full.sol file has been removed, I feel like the examples should reflect these changes.

**Comment by nventuro** [comment]
Great catch, thanks! Looks like I forgot to update the readme in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2168. I fixed this in https://github.com/OpenZeppelin/openzeppelin-contracts/commit/e2b97d67128e3593083bdf39ee2135871da1b711.

**Comment by josh-kean** [comment]
that was a quick fix! thanks!
