### ISSUE TITLE
Add SafeCast variants for signed integers

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#2240]
[`SafeCast`](https://docs.openzeppelin.com/contracts/3.x/api/utils#SafeCast) currently has support for downcasting uints and casting them to int256, but there's no safe way to downcast signed integers.

This is slightly trickier because the two's complement integer representation has different ranges for positive and negative numbers, but should be easy to do anyway.

**Comment by frangio** [comment]
You're talking about a function functions like `toInt128(int256 x)` right?

**Comment by nventuro** [comment]
Precisely, yes. `toInt8(int256 x)` for example needs to check that `-128 <= x <= 127`.

**Comment by julianmrodri** [comment]
@nventuro  @frangio   I can tackle this if you are OK. Just let me know.

**Comment by julianmrodri** [comment]
@nventuro @frangio  I gave it a shot for the example you mention before moving to the rest. Let me know if this is the correct direction in order to generalize to the other functions.  Thanks a lot for your support.

```
/**
  * @dev Returns the downcasted int8 from int256, reverting on
  * overflow (when the input is less than smallest int8 and greater 
  * than largest int8).
  *
  * Counterpart to Solidity's `int8` operator.
  *
  * Requirements:
  *
  * - input must fit into 8 bits.
  */ 
function toInt8(int256 value) internal pure returns (int8) {
    require(value >= (2**7 * -1) && value < 2**7 , "SafeCast: value doesn\'t fit in 8 bits");
    return int8(value);         
 }
```

**Comment by julianmrodri** [comment]
@nventuro @frangio I gave it a shot for the example you mention before moving to the rest. Let me know if this is the correct direction in order to generalize to the other functions. Thanks a lot for your support.

```
/**
 * @dev Returns the downcasted int8 from int256, reverting on
 * overflow (when the input is less than smallest int8 and greater 
 * than largest int8).
 *
 * Counterpart to Solidity's `int8` operator.
 *
 * Requirements:
 *
 * - input must fit into 8 bits.
 */ 
function toInt8(int256 value) internal pure returns (int8) {
    require(value >= (2**7 * -1) && value < 2**7 , "SafeCast: value doesn\'t fit in 8 bits");
    return int8(value);         
 }
```
