### ISSUE TITLE
I can't run the docs locally 

### ISSUE THREAD

**Issue by NTTMai** [OpenZeppelin/openzeppelin-contracts#2252]
I tried to run `npm run docs start` but it give me this error:
![Screenshot from 2020-05-31 19-31-06](https://user-images.githubusercontent.com/31298991/83352440-8cfb4500-a375-11ea-91e8-1a03e23c8ba7.png)

**💻 Environment**

I cloned the repos today 31.05.2020 
Ubuntu 18.04
Node 10
**📝 Details**

**🔢 Code to reproduce bug**

**Comment by NTTMai** [comment]
Could this relate to this https://github.com/ethereum/web3.js/issues/2863

**Comment by frangio** [comment]
Hi @NTTMai. Can you confirm that you ran `npm install` before the command on the screenshot?

**Comment by frangio** [comment]
Nevermind my last comment. You should be running `npm run docs:watch`. Did you see the `start` command somewhere? It used to be like that so there may be outdated instructions somewhere.

**Comment by NTTMai** [comment]
i followed the instruction from here https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/DOCUMENTATION.md

**Comment by NTTMai** [comment]
i tried with `npm run docs:watch` and everything look good now

**Comment by NTTMai** [comment]
i update it in the [PR](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2255)
