### ISSUE TITLE
parameter name in ERC777 token contract hook misleading

### ISSUE THREAD

**Issue by magooster** [OpenZeppelin/openzeppelin-contracts#2256]
**🧐 Motivation**
Avoid confusing users of ERC777

**📝 Details**

The ERC777 token contract implementation includes the _beforeTokenTransfer hook 

function _beforeTokenTransfer(address operator, address from, address to, uint256 tokenId) internal virtual { }

The last parameter is not a tokenId but an amount, still uint256 but misleading none the less, looks like a remnant from the ERC721 Token...

Also the calling conditions comments reference tokenId, and need to be updated

**Comment by nventuro** [comment]
Thanks a lot for reporting this @magooster!
