### ISSUE TITLE
SafeMath: Addition with custom revert message missing

### ISSUE THREAD

**Issue by gorgos** [OpenZeppelin/openzeppelin-contracts#2281]
All SafeMath operations have a revert with custom message option except the addition. Any good reasons why that one is missing?

**Comment by frangio** [comment]
The reason is that subtraction can overflow due to "business logic" reasons such as "balance too low", while addition can overflow only for technical reasons because a value is out of range. Did you run into a scenario where you wanted to use a custom revert reason?

**Comment by gorgos** [comment]
I see that makes sense. Well the only thing would be to help with figuring out where the `.add` revert came from if you have a complex contract. Feel free to close the issue though.

**Comment by frangio** [comment]
Yes that could be a problem, but it might be a better solution to use something like [Tenderly](https://tenderly.dev/) to inspect a transaction and pinpoint exactly where it failed.

Thanks for your question!
