### ISSUE TITLE
Include mock contracts in NPM bundle

### ISSUE THREAD

**Issue by hitchcott** [OpenZeppelin/openzeppelin-contracts#2288]
Right now this is explicitly excluded from the NPM package:

```
  "files": [
    "!/contracts/mocks",
```

Would it not be useful to include those mock contracts for testing?

**Comment by nventuro** [comment]
The mocks are only used for the tests we run in this project for the library itself, I'm not sure why a user of the library would want to have them. Can you expand on what you're trying to achieve?

**Comment by hitchcott** [comment]
Let's say I've authored a contract that interacts with ERC20 tokens.

In my test suite, I'll usually deploy a Mock ERC20 token, with helper methods such as `approveInternal`.

I could implement this logic myself in a Mock contract within my project, but it is more convenient to use the one provided: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/mocks/ERC20Mock.sol

**Comment by nventuro** [comment]
Ah, so what you want is a mock ERC20 you can use to simplify your testing setup? Unfortunately that's not really what our mocks are ('mock' is really not the right term for them): all they do is expose their internals so we can more easily test the OpenZeppelin Contracts themselves. 

They are not really suitable to be used by other projects as they are part of our internal testing infrastructure. We often alter them extensively as we update our tests, so it would probably be very annoying to depend on them due to constant changes.

**Comment by hitchcott** [comment]
> Ah, so what you want is a mock ERC20 you can use to simplify your testing setup?

Yep, exactly.

Right now I am just duplicating the code from `ERC20Mock.sol` into my own project under `contracts/test` and redeploying that. It would be more convenient to just import it directly.

Sample usage:

```
async function setup() {
  const MyContract = await ethers.getContractFactory("MyContract");
  const ERC20 = await ethers.getContractFactory("ERC20Mock");
  const contract = await MyContract.deploy();
  const token = await ERC20.deploy("Mock Token", "TKN", account, tokenBalance);
  await contract.deployed();
  await token.deployed();
  await token.approveInternal(account, contract.address, 100);
  return { token, contract };
}
```

**Comment by nventuro** [comment]
>`await token.approveInternal(account, contract.address, 100);`

I'd advise you to avoid relying on mocks for this sort of operations. This test is hiding the fact that your contract should call `approve` on the token, which is a non-trivial matter.

It's important to understand the difference between the role the mocks play in testing the OpenZeppelin Contracts themselves, and how the library should be used and this usage tested by end users. We assume users trust the code in Contracts to be correct and don't need to test it themselves.

It this for this reason (plus what I mentioned before about there being no guarantees on the stability of the mocks) that they are not included in the package.

**Comment by frangio** [comment]
For quick testing you could also consider using one of the [preset contracts](https://docs.openzeppelin.com/contracts/3.x/api/presets).
