### ISSUE TITLE
when i extend ownable.sol in my contract,there has some error..

### ISSUE THREAD

**Issue by wangyuyuer** [OpenZeppelin/openzeppelin-contracts#2299]
I want to write blacklist.sol,here is my code:

pragma solidity ^0.6.0;

import "@openzeppelin/contracts/access/Ownable.sol";
contract BlackList is Ownable {
    mapping (address => bool) public isBlackListed;
    
　　　　event AddedBlackList(address _user);
　　　　event RemovedBlackList(address _user);

　　　　function getBlackListStatus(address _maker) external constant returns (bool) {
    　　　　return isBlackListed[_maker];
　　　　}
　　　　
　　　　function addBlackList (address _evilUser) public onlyOwner {
   　　　　 isBlackListed[_evilUser] = true;
    emit AddedBlackList(_evilUser); 
　　　　}

　　　　function removeBlackList (address _clearedUser) public onlyOwner {
    　　　　isBlackListed[_clearedUser] = false;
    emit RemovedBlackList(_clearedUser);
　　　　}

but i got error,can anyone tell me how to fix it?  thank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1

![图片](https://user-images.githubusercontent.com/48520185/86018235-a0bec780-ba57-11ea-8844-4cfbd04708ff.png)

**Comment by frangio** [comment]
Hi @wangyuyuer. Your whitespace is composed of strange characters. You should delete it and replace it with normal spaces or tabs.

If you have any further questions about this please post in [our forum](https://forum.openzeppelin.com/).
