### ISSUE TITLE
Contract to wrap an ERC721 in an ERC20

### ISSUE THREAD

**Issue by abliss** [OpenZeppelin/openzeppelin-contracts#2302]
**🧐 Motivation**
Some ERC721 Non-Fungible-Tokens are held by people who wish they were fungible, so that they could more easily be listed on an exchange (for higher liquidity and better price discovery). Presumably the NFT was designed to be non-fungible by its creator (or they would've used ERC20 from the start), but sometimes, to some of its holders, for some subset of the tokens, fungibility is a better fit.

A "wrapper" contract is straightforward in principle. By transferring an ERC721 token into the wrapper, you mint 1.0 of the ERC20 token, which can then be traded. Later, a holder of at least 1.0 of the ERC20 tokens can burn it and receive one of the ERC721 tokens owned by the wrapper. 

One such "fungifying" contract that I found is Wrapped CryptoKitties (WCK) https://blocklytics.org/blog/wrapped-cryptokitties/ . In this case, only the "unwanted" NFTs are cast into the wrapper. These securitized rejects are then traded somewhat acitvely on uniswap. I have not been able to find other examples, but I and other holders would currently love to have one for the Azimuth Point (AZP) NFT (on mainnet at `ecliptic.eth`).

Anyone could deploy such a contract; however, if OpenZepplin would publish a canonical example contract for doing this in a safe way, then token-holders could have more confidence when they mint.

**📝 Details**

I'm basing my design on WCK, but I'm open to other implementations (in particular, it seems there could be ways to make it significantly more gas-efficient.) Here are the main differences I would want from WCK:

1. The contract's constructor should take the address of contract implementing the target ERC721 NFT to wrap. The ERC20 token can then report its ERC20 name / ticker  by prefixing  "Wrapped" / "W" to the target. This allows byte-for-byte identical contracts to be stamped out for any new ERC721.
2. The contract should have a self-destruct mechanism, invokable by its owner, which *only* operates when all balances are zero. This provides a way to recover the gas costs if the contract (eventually) proves unpopular.
3. There should be some simple, foolproof way to filter the incoming NFTs by a boolean condition. For example, checking that its index is within a specified range, or calling a boolean method on the target contract to filter for NFTs with a certain token-specific property.
4. If the target contract is upgradable, the wrapper should be able to survive the upgrade. 
  

I appreciate that this use case is somewhat niche, and I wouldn't expect OpenZeppelin to spend resources developing it. But if the development can be funded by a third party, would OZ consider reviewing, merging, and distributing the contract?

**Comment by abcoathup** [comment]
Hi @abliss!  Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by abliss** [comment]
Thanks for your willingness to consider the issue! Do you have any estimate of when you might be able to get to it?

**Comment by abcoathup** [comment]
Hi @abliss,

I don't have an estimate for when the project owner can review.  It will be as soon as they can.

**Comment by frangio** [comment]
Hi @abliss. Thank you for this suggestion.

While I think it's an interesting idea for the ecosystem, it's too specific to be included in OpenZeppelin Contracts. The most we can do is ensure that it can be implemented using OpenZeppelin's building blocks, and in this case it seems like it would be possible to do that.

**Comment by frangio** [comment]
Also I would like to add regarding your last point:

>I appreciate that this use case is somewhat niche, and I wouldn't expect OpenZeppelin to spend resources developing it. But if the development can be funded by a third party, would OZ consider reviewing, merging, and distributing the contract?

Merging something into the library implies an additional maintenance burden for us from that point on, and this is why we tend to be conservative in what we decide to merge.

Thanks for understanding!

**Comment by abitofdots** [comment]
any guy know the wide-used contract to convert erc721 to erc20?
