### ISSUE TITLE
Multiple approved addresses for ERC721 token

### ISSUE THREAD

**Issue by DeRain** [OpenZeppelin/openzeppelin-contracts#2306]
**🧐 Motivation**
Hi, in ERC721 token currently there is could be the only approved address for a unique token at the same time. There are some cases when it needed to approve more than one address. For example: `.crypto domain is ERC721 token and I want to allow manage this domain records to multiple users.

**📝 Details**
**Current implementation looks like this:**
```
    function _approve(address to, uint256 tokenId) private {
        _tokenApprovals[tokenId] = to;
        emit Approval(ownerOf(tokenId), to, tokenId);
    }
```

**It might look like:**
```
    function _approve(address to, uint256 tokenId) private {
        _tokenApprovals[tokenId][to] = true;
        emit Approval(ownerOf(tokenId), to, tokenId);
    }
```

**Comment by frangio** [comment]
Thanks for the suggestion @DeRain! Unfortunately this is specified by [ERC721](https://eips.ethereum.org/EIPS/eip-721) and is not something that we can change. There is a single approved address for each token id.

I don't know what was the rationale behind this design.
