### ISSUE TITLE
Mistake in code style

### ISSUE THREAD

**Issue by Met7** [OpenZeppelin/openzeppelin-contracts#2323]
The events example still has underscores at parameters.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CODE_STYLE.md

**Comment by julianmrodri** [comment]
I checked the contracts and it is true that we are not using underscore for Event parameters. I submitted a PR to change this example. @abcoathup @nventuro @frangio  Feel free to review. Thanks!
