### ISSUE TITLE
Fix test on TokenVesting draft

### ISSUE THREAD

**Issue by hems** [OpenZeppelin/openzeppelin-contracts#2350]
I just went through the tests on TokenVesting and figured out that this test isn't finished:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/cdf655f770cf8412fbd4d6aef3c55194a1233ef1/test/drafts/TokenVesting.test.js#L146-L156

What actually needs to be done in order for this test to be valuable is:

1. Add the "vested()" method on TokenVesting.sol

````js
    /**
     * @return the vested amount of the token vesting.
     */
    function vested(IERC20 token) public view returns (uint256) {
        return _vestedAmount(token);
    }
````

2. Call the vested() method on the test instead of using the `vestedAmount` function from the test file

````js
    expect(await this.vesting.vested()).to.equal(vestedPre);
````

Other than all the tests seems to be perfect, thanks a lot for all your work

**Comment by abcoathup** [comment]
Hi @hems,

Thanks for the feedback.  The drafts directory was removed from OpenZeppelin Contracts 3.0.
See the documentation for details: https://docs.openzeppelin.com/contracts/3.x/drafts

If you look at OpenZeppelin/openzeppelin-contracts#1214 TokenVesting may not be aligned with traditional vesting.

Depending on your use case, you could use [TokenTimelock](https://docs.openzeppelin.com/contracts/3.x/api/token/erc20#TokenTimelock)

When creating token time locks or vesting you should consider prevention strategies for: [Bypassing Smart Contract Timelocks](https://blog.openzeppelin.com/bypassing-smart-contract-timelocks/)

I will close this issue as TokenVesting has been removed but really appreciate the feedback on the test.

**Comment by hems** [comment]
> TokenTimelock



> Hi @hems,
> 
> Thanks for the feedback. The drafts directory was removed from OpenZeppelin Contracts 3.0.
> See the documentation for details: https://docs.openzeppelin.com/contracts/3.x/drafts

Yes i noticed

> If you look at #1214 TokenVesting may not be aligned with traditional vesting.

Actually the linear vesting is the perfect implementation for me and to be frank I believe to a lot more people.

> Depending on your use case, you could use [TokenTimelock](https://docs.openzeppelin.com/contracts/3.x/api/token/erc20#TokenTimelock)

Thanks for the link, i'll use the TokenVesting contract tough as it works just as we would like it to work.

> When creating token time locks or vesting you should consider prevention strategies for: [Bypassing Smart Contract Timelocks](https://blog.openzeppelin.com/bypassing-smart-contract-timelocks/)

very interesting concept, thank you for pointing me out!
