### ISSUE TITLE
ERC 721 compile issue

### ISSUE THREAD

**Issue by kimClassics** [OpenZeppelin/openzeppelin-contracts#2351]
Am trying to compile a contract using but I end up getting this error. 
@openzeppelin/contracts/token/ERC721/ERC721.sol:106:46: ParserError: Expected '{' but got reserved keyword 'override'
    function balanceOf(address owner) public override view returns (uint256) {

Am using Truffle v5.1.43 (core: 5.1.43),
Node v14.8.0, vs code 1.48.2

**Comment by abcoathup** [comment]
Hi @kimClassics! I’m sorry that you had this issue.  

Unfortunately, I wasn’t able to reproduce this issue. I tried the following:
1. Changed to node v14 and installed current version of Truffle
```console
$ npx truffle version
Truffle v5.1.43 (core: 5.1.43)
Solidity - ^0.6.0 (solc-js)
Node v14.9.0
Web3.js v1.2.1
```
2. Installed current version of OpenZeppelin Contracts (v3.1.0)
```console
npm i @openzeppelin/contracts
```
3. Compiled the following example contract
From: https://docs.openzeppelin.com/contracts/3.x/erc721#constructing_an_erc721_token_contract
```solidity
// contracts/GameItem.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract GameItem is ERC721 {
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIds;

    constructor() public ERC721("GameItem", "ITM") {}

    function awardItem(address player, string memory tokenURI)
        public
        returns (uint256)
    {
        _tokenIds.increment();

        uint256 newItemId = _tokenIds.current();
        _mint(player, newItemId);
        _setTokenURI(newItemId, tokenURI);

        return newItemId;
    }
}
```
```console
$ npx truffle compile

Compiling your contracts...
===========================
✔ Fetching solc version list from solc-bin. Attempt #1
> Compiling ./contracts/GameItems.sol
> Compiling ./contracts/Migrations.sol
> Compiling @openzeppelin/contracts/GSN/Context.sol
> Compiling @openzeppelin/contracts/introspection/ERC165.sol
> Compiling @openzeppelin/contracts/introspection/IERC165.sol
> Compiling @openzeppelin/contracts/math/SafeMath.sol
> Compiling @openzeppelin/contracts/token/ERC721/ERC721.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721Enumerable.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721Metadata.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721Receiver.sol
> Compiling @openzeppelin/contracts/utils/Address.sol
> Compiling @openzeppelin/contracts/utils/Counters.sol
> Compiling @openzeppelin/contracts/utils/EnumerableMap.sol
> Compiling @openzeppelin/contracts/utils/EnumerableSet.sol
> Compiling @openzeppelin/contracts/utils/Strings.sol
✔ Fetching solc version list from solc-bin. Attempt #1
> Artifacts written to /home/abcoathup/projects/forum/kimclassics/build/contracts
> Compiled successfully using:
   - solc: 0.6.12+commit.27d51765.Emscripten.clang
```

What operating system are you using? (I used Ubuntu 18.04 WSL2 on Windows 10)
What version of OpenZeppelin Contracts are you using?
Are you able to share the contract you are trying to compile?

**Comment by kimClassics** [comment]
Thank You! It worked!

**Comment by maaeyeng** [comment]
ParserError: Source "node_modules/@openzeppelin/contracts/utils/Counters.sol" not found: File outside of allowed directories.
 --> contracts/NFTCollectible.sol:3:1:
  |
3 | import "../node_modules/@openzeppelin/contracts/utils/Counters.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


ParserError: Source "node_modules/@openzeppelin/contracts/access/Ownable.sol" not found: File outside of allowed directories.
 --> contracts/NFTCollectible.sol:4:1:
  |
4 | import "../node_modules/@openzeppelin/contracts/access/Ownable.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


ParserError: Source "node_modules/@openzeppelin/contracts/utils/math/SafeMath.sol" not found: File outside of allowed directories.
 --> contracts/NFTCollectible.sol:5:1:
  |
5 | import "../node_modules/@openzeppelin/contracts/utils/math/SafeMath.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


ParserError: Source "node_modules/@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol" not found: File outside of allowed directories.
 --> contracts/NFTCollectible.sol:6:1:
  |
6 | import "../node_modules/@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error HH600: Compilation failed

For more info go to https://hardhat.org/HH600 or run Hardhat with --show-stack-traces

**Comment by frangio** [comment]
Please request help in the [OpenZeppelin Forum](https://forum.openzeppelin.com/).
