### ISSUE TITLE
ERC20 should not default decimals to 18

### ISSUE THREAD

**Issue by dmdque** [OpenZeppelin/openzeppelin-contracts#2353]
**🧐 Motivation**
The ERC20 spec allows for any number of decimals. Thus, ERC20 should not enforce any opinion about it.

**📝 Details**
Constraining decimals makes it tougher to develop with OZ's ERC20. One way in which having a default is painful is setting up mock contracts for tokens you'll interact with. If you have to work with a token with non-18 decimals, you can't use ERC20.

**Comment by Skyge** [comment]
If you want to change the decimals, you can rewrite the function `_setupDecimals(uint8 decimals_)` to make a change.

**Comment by frangio** [comment]
We've prioritized the usability of the common case (18 decimals), but the ability to change it to something else remains by using `_setupDecimals` as mentioned by @Skyge.
