### ISSUE TITLE
Add documentation on using Upgrade Safe fork

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-contracts#2366]
**🧐 Motivation**
Add documentation on using Upgrade Safe fork

**📝 Details**
Create guide on when and how to use Upgrade Safe fork.

Include:
* When to use chained and unchained initializers
* What `_gap` is used for.

We could use something based on the following:
Upgrade Safe contracts have two initializers: "chained" and "unchained". 

"chain" refers to the linearized chain of parent contracts, the main init contains a chain/sequence of calls to the unchained initializers of the parent contracts.  If we called the chained versions we would be making multiple calls to the "grandparent" initializer.

`__gap` is an empty storage gap put in each Upgrade Safe contract. This allows in future versions new storage variables to be added to a contract.
It isn't safe to simply add a storage variable because it "shifts down" all of the storage variables down the inheritance chain. This makes the storage layouts incompatible, (see: https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#modifying-your-contracts).  The number is calculated so that the size of the storage used by a contract always adds up to the same number (e.g. 100).

**Comment by frangio** [comment]
Fixed by #2403.
