### ISSUE TITLE
Please mark virtual override in ERC721 ownerOf (and potentially others)

### ISSUE THREAD

**Issue by 3esmit** [OpenZeppelin/openzeppelin-contracts#2373]
I am unable to update to solidity 0.6.2 for using ENS in my project.

This is where it breaks
https://github.com/ensdomains/ethregistrar/blob/75b4515b33ff06f4e5e980c36a9a5214e7d1bd4c/contracts/BaseRegistrarImplementation.sol#L46-L49

As workaround I copied ERC721.sol to my project folder and I am using it instead of openzeppelin version.

**Comment by frangio** [comment]
Thanks for reporting @3esmit. See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2154. I'll be collecting over there all the functions that have been requested to be made virtual.
