### ISSUE TITLE
Use EnumerableSet.AddressSet for defaultOperators in ERC777.sol

### ISSUE THREAD

**Issue by hellwolf** [OpenZeppelin/openzeppelin-contracts#2374]
**🧐 Motivation**

Currently the stock implementation of ERC777 do not adjust the `defaultOperators()` return values over time, when there is revokings of the default operators.

I find the usage of `EnumerableSet.AddressSet` could improve the implementation here.

**📝 Details**

Use `EnumerableSet.AddressSet private _defaultOperators` to replace all default operators related code.

**Comment by frangio** [comment]
@hellwolf Thanks for the suggestion. The behavior of our implementation seems compliant with the EIP. Operators can't be revoked globally, only for a single holder, thus `defaultOperators` shouldn't change. Please take a look at [EIP777](https://eips.ethereum.org/EIPS/eip-777).
