### ISSUE TITLE
Signature parsing optimization

### ISSUE THREAD

**Issue by pertsev** [OpenZeppelin/openzeppelin-contracts#2375]
This line 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/8108f2f9b917616a8cd0661c31a211ad9f988110/contracts/cryptography/ECDSA.sol#L43

could be replaced with `v := mload(add(signature, 0x41))`, which is more readable and efficient.

**Comment by abcoathup** [comment]
Hi @pertsev!  Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by frangio** [comment]
Hi @pertsev. Thanks for this suggestion.

It's necessary to mask out everything other than the byte that we want, and the snippet that you propose doesn't do that.

**Comment by rstormsf** [comment]
@frangio since it casted to uint8, I think it's already masked out

**Comment by frangio** [comment]
I'm not sure. I think Solidity masks when storing the value in a byte8 variable. If you store the value using assembly, you're skipping the masking.

I ran a quick test.

```solidity
        uint8 v;
        assembly {
            v := 0x11111111111111111111111111111111
        }
        return v + 1;
```

The addition was performed with an unmasked `v`.

Solidity may mask at some later point, but it doesn't seem reliable at all.
