### ISSUE TITLE
Add ERC20 and ERC777 presets with fixed supply

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-contracts#2377]
**🧐 Motivation**
Create simple ERC20 and ERC777 presets with fixed supply.
The benefits are:
* Easy to deploy (including from Remix).
* No access control (for minting/pausing), and hence no governance required.
* Can be verified easily on public networks and then are verified for all.

**📝 Details**

Community members are creating their own simple ERC20 tokens, so it would be good if they could use a Preset from Contracts which wouldn't require any code changes.

To verify contracts as multi-file it is best to use Buidler Etherscan plugin (Truffle plugin is getting updated).  This can be a challenge for community members deploying from Remix.  A preset contract once verified on a network would be verified for all subsequent deployments.

The Simple ERC777 token example in the forum has 4K+ views so there is potential interest in an ERC777 preset too.
https://forum.openzeppelin.com/t/simple-erc777-token-example/746

Potential presets could look like the following:

## Draft ERC20PresetFixedSupply 
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.2;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20Burnable.sol";

contract ERC20PresetFixedSupply is ERC20, ERC20Burnable {
    constructor(
        string memory name,
        string memory symbol,
        uint256 initialSupply
    ) public ERC20(name, symbol) {
        _mint(msg.sender, initialSupply);
    }
}
```

## Draft ERC777PresetFixedSupply 
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.2;

import "@openzeppelin/contracts/token/ERC777/ERC777.sol";

contract ERC777PresetFixedSupply is ERC777 {
    constructor(
        string memory name,
        string memory symbol,
        uint256 initialSupply,
        address[] memory defaultOperators
    ) public ERC777(name, symbol, defaultOperators) {
        _mint(msg.sender, initialSupply, "", "");
    }
}
```

**Comment by ashwinYardi** [comment]
Hi @frangio @abcoathup ! Have submitted the [PR](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2399) .

Can you please take a look whenever possible and let me know if anything needs to be changed / added? Thanks!

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2399
