### ISSUE TITLE
Virtual balanceOf in ERC20

### ISSUE THREAD

**Issue by ebulku** [OpenZeppelin/openzeppelin-contracts#2400]
**🧐 Motivation**
I want to use my own logic behind the `balanceOf() ` function for ERC20.

**📝 Details**
Is there any known issue if I change the `balaceOf()` in `virtual` in `ERC20.sol`

**Comment by frangio** [comment]
It depends on what you want to override it with. There are potential issues integrating with other contracts when `balanceOf` returns a dynamic value. I'm not sure if this has been explained anywhere. I couldn't find a link to provide, sorry!

**Comment by frangio** [comment]
For the general issue of having virtual view functions see https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2154.

Closing this issue but let's continue the discussion if you want.

**Comment by ebulku** [comment]
@frangio  There are cases when the balance is changing over time, and to save costs for transactions you can implement the changed balance dynamically. This usually occurs in DeFi when users are getting interests, or there may be cases when the token holders are awarded extra tokens.

I have seen this implementation in aave: https://github.com/aave/aave-protocol/blob/f7ef52000af2964046857da7e5fe01894a51f2ab/contracts/tokenization/AToken.sol#L338

But they are using an older version of OpenZeppelin  to override the `balanceOf`

**Comment by ebulku** [comment]
@frangio  what do you think about this?

**Comment by frangio** [comment]
@ebulku We're going to add virtual view functions (see https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2154#issuecomment-729962763) in the next release. Whether `balanceOf` will be one of these virtual view functions I'm still not sure. I will try to make it so but there are some caveats (see https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2154#issuecomment-605745547). I've included your request for ERC20.balanceOf in the list of requested virtual functions.
