### ISSUE TITLE
Feature request for ERC20

### ISSUE THREAD

**Issue by ducquangkstn** [OpenZeppelin/openzeppelin-contracts#2409]
1. 

**🧐 Motivation**

- when user approve infinity to another address, transferFrom should not reset (this will save us about 5000 gas)

**📝 Details**

https://github.com/Uniswap/uniswap-v2-core/blob/master/contracts/UniswapV2ERC20.sol#L74

2. Another feature request is can we implement an internal **_rename**  function for ERC20

**🧐 Motivation**
Because _name and _symbol of ERC20 are private. So I can not change name outside constructor. For token with permission (Ownable), owner can not change name of token so adding an internal **_rename** function will enable it
For example, when ppl rename from DAI to SAI

**📝 Details**
```solitidity
function _rename(string memory name_, string memory symbol_) internal {
        _name = name_;
        _symbol = symbol_;
}
```

**Comment by Skyge** [comment]
When you deploy an ERC20 token, it is not expected to change `name` and `symbol`, and as for Maker changed `SAI` to `DAI`, it does not simply change the token name, they are different token, so they need a new ERC20 token.

**Comment by ducquangkstn** [comment]
No, they rename old DAI to SAI and create a new token named DAI

**Comment by Skyge** [comment]
Okay, but I still do not think it is a good idea to change token name and symbol.

**Comment by ducquangkstn** [comment]
Another use case would be this

https://github.com/compound-finance/compound-protocol/blob/master/contracts/CToken.sol#L51

The token name will be defined in an init function

**Comment by Skyge** [comment]
Emmm, it is a init function to set a name rather than reset the name, and it can only be called once.

**Comment by abcoathup** [comment]
Hi @ducquangkstn,

Thanks for the suggestions, it is really appreciated.

I recommend adding your use case to the following issues:

1. Add ERC20 permit() function: https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2206
2. Virtual view functions: https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2154#issuecomment-729440206

I believe this issue duplicates the above (especially once you add your use case), so I am closing this issue.
