### ISSUE TITLE
Make ERC777 non-view methods virtual

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/openzeppelin-contracts#2414]
Make ERC777's [`send()`](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC777/ERC777Upgradeable.sol#L149), [`transfer()`](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC777/ERC777Upgradeable.sol#L161), [`burn()`](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC777/ERC777Upgradeable.sol#L180), etc `virtual`.

**📝 Details**

As [announced in the forum](https://forum.openzeppelin.com/t/how-we-plan-to-adopt-solidity-0-6-virtual-functions/2063/7), all non-view functions should be made virtual so they can be overriden. I haven't checked if there's any other contracts missing this feature.

**Comment by Amxx** [comment]
By designed, you are invited to use the `_beforeTokenTransfer()` hooks to include some custom logic. This hook triggered for calls to `transfer`, `transferFrom`, `send`, `operatorSend`, `burn` and `mint`.

Additionnaly, the `_mint` and `_burn` functions are virtual. Still, that might not be enough ...

Could you tell us more about your usecase?

**Comment by martriay** [comment]
Thanks for the reply Hadrien! I don't have a use case, I was playing around with 777 when I stumbled upon the restriction which, after consulting with @frangio, it appeared to go against the design decision of the post I linked.
