### ISSUE TITLE
Provide implementation of UUPS proxy pattern

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#2421]
[EIP 1822](https://eips.ethereum.org/EIPS/eip-1822) describes the UUPS proxy pattern. This pattern is simpler and should be cheaper as well, so we're interested in providing it as an alternative to the transparent proxy pattern.

**Comment by Amxx** [comment]
FYI: https://github.com/Amxx/openzeppelin-contracts/tree/feature/UUPS/contracts/proxy/uups (includes tests)

**Comment by frangio** [comment]
The EIP as published on the `eips` site is using the "PROXIABLE" storage slot but there is an open PR that changes it to the same slot we use in our upgradeable proxies.

**Comment by Amxx** [comment]
With that change, it feels like the `UpgradeableProxy` we currently have is an UUPS proxy. The only missing brick would be an abstract class `Proxiable` (with a public proxiableUUID(), and an internal `_updateCodeAddress` that verifies this UUID). What do you think ?

**Comment by frangio** [comment]
Yeah that sounds good. I don't understand wht the UUID is though. I couldn't find an explanation in the EIP.

It seems like it's a mechanism to avoid bricking the upgradeability mechanism. We had some other ideas for such mechanisms and I'm not sure the EIP should be opinionated on which one to implement. I think this is something we should discuss.

**Comment by Amxx** [comment]
The `proxiableUUID()` is just a function that returns the slot. It is used to verify that an implementation is "Proxiable". If not, you should not be able to update to it. This is a small security feature.
