### ISSUE TITLE
erc20 to ierc20 

### ISSUE THREAD

**Issue by Tigersame** [OpenZeppelin/openzeppelin-contracts#2423]
**🧐 Motivation**

How to implement erc20 sol. To ierc20 
& where to find bytes32 code

**Comment by abcoathup** [comment]
Hi @Tigersame,

For information on the OpenZeppelin Contracts ERC20 implementation please see the [documentation](https://docs.openzeppelin.com/contracts/3.x/erc20).

You can also look at the following guides and tutorials:
* [Deploy a simple ERC20 token in Remix](https://forum.openzeppelin.com/t/deploy-a-simple-erc20-token-in-remix/1203)
* [Create an ERC20 using Remix, without writing Solidity](https://forum.openzeppelin.com/t/create-an-erc20-using-remix-without-writing-solidity/2908)
* [Create an ERC20 using Truffle, without writing Solidity](https://forum.openzeppelin.com/t/create-an-erc20-using-truffle-without-writing-solidity/2713)

If you need help, you can ask the community in the [forum](https://forum.openzeppelin.com/).

I am closing this issue and we can pickup the discussion in the forum if you need.
