### ISSUE TITLE
Revert messages are not bubbled in proxy constructors

### ISSUE THREAD

**Issue by ppoliani** [OpenZeppelin/openzeppelin-contracts#2425]
I'm trying to write some tests to check if some of the user inputs are correct. More specifically I've got the following code in my smart contract function. The code is part of the initialize function.

```
contract ContractA is Initializable {
  function initialize(IERC20 token) public initializer {
      require(
      address(token) != address(0), 
      "Invalid erc20 address provided"
    );
  }
} 

```

I have written a test that checks if the correct message is thrown when a 0x address is passed. I used the helper

```

const deployContract = async  () => {
  const token = await ERC20.new('TokenA', 'TokenA')
  const opts = {
    unsafeAllowLinkedLibraries: true
   }

return await deployProxy(
    ContractA, 
    [token],
    opts
  )
}

const {constants, expectRevert} = require('@openzeppelin/test-helpers');

it('should revert', async () => {
    await expectRevert(
      deployContract(constants.ZERO_ADDRESS, validatorRegistry.address),
      'Invalid erc20 address provided',
    );
}) 

```

Now when I run this it revert, however the error I get doesn't include the message defined in the require() section. Instead I get the default message `-revert`

```
     Wrong kind of exception received
      + expected - actual

      -revert
      +Invalid erc20 address provided
```

Now if I deploy the contract user `.new` function and manually invoking the initialize function then I get the correct message.

```
const deployContract = async  () => {
  const token = await ERC20.new('TokenA', 'TokenA')
  const contract =  await ContractA.new()
  await contract.initialize(token)
}
```

I'm using:

- @openzeppelin/truffle-upgrades: 1.3.0
- @openzeppelin/test-helpers": "^0.5.9"
- "ganache-cli": "^6.12.1"
- "truffle": "^5.1.55"

**Comment by frangio** [comment]
Fixed by #2454.
