### ISSUE TITLE
Unable to import “@openzeppelin/contracts/token/ERC20/SafeERC20.sol”: File not found

### ISSUE THREAD

**Issue by franklee00** [OpenZeppelin/openzeppelin-contracts#2426]
**💻 Environment**. Remix

**📝 Details**

when import the IERC20.sol, sth wrong happened.
import “https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/SafeERC20.sol”;
import “https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/IERC20.sol”;

**🔢 Code to reproduce bug**
Unable to import “@openzeppelin/contracts/token/ERC20/SafeERC20.sol”: File not found

pls, how to deal with it.thx.

**Comment by abcoathup** [comment]
Hi @franklee00,

I am sorry that you had this problem.  I am closing this issue as you have created a forum post.  We can pick up the discussion there.

https://forum.openzeppelin.com/t/unable-to-import-openzeppelin-contracts-token-erc20-safeerc20-sol-on-remix/4915
