### ISSUE TITLE
关于合约AccessControl的建议

### ISSUE THREAD

**Issue by xiaozhu001** [OpenZeppelin/openzeppelin-contracts#2433]
**🧐 Motivation**
关于AccessControl合约中的权限控制，当用户只想有一个人可以进行添加和删除权限时，发现当前只有_grantRole的包装函数_setupRole函数允许子合约进行调用，并没有_revokeRole的包装函数允许子合约进行调用。希望可以将它进行支持。

我认真的阅读了合约的内部函数，这里可能真的需要改进，假如合约的使用主体是一个团队时，有人故意作恶，利用它本身拥有这个权限，将所有人的权限都移除了，这样会出比较大的乱子。并且这个人有了这个权限后，也不应该可以随便给其他人加权限。

建议改进方案是：将添加权限和移除权限功能使用internal级别

**Comment by frangio** [comment]
Hi @xiaozhu001, I translated your message [on Google Translate](https://translate.google.com/translate?sl=auto&tl=en&u=https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2433). If you could write in English it would be appreciated.

`_setupRole` is meant to be used in the constructor only. We can't stop people from using it elsewhere. However, all roles can be audited via the events emitted by the contract. Auditing of the code + monitoring of account roles can be put in place to prevent the kind of problem that you describe. Admin roles (that can revoke other roles) should be highly secured accounts in cold storage.

**Comment by frangio** [comment]
Let us know if there is anything else we should discuss!
