### ISSUE TITLE
Minimal proxy factory

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#2437]
EIP-1167 specifies a [Minimal Proxy Contract](https://eips.ethereum.org/EIPS/eip-1167). It's just a bytecode blob and it would be convenient to wrap it in a factory contract or library. A few people have asked for this.

Consider also including functionality to use create2 for deterministic addresses. See the [`ProxyFactory`](https://github.com/OpenZeppelin/openzeppelin-sdk/blob/7d96de7248ae2e7e81a743513ccc617a2e6bba21/packages/lib/contracts/upgradeability/ProxyFactory.sol) contract in OpenZeppelin SDK for reference.

**Comment by abcoathup** [comment]
There have been a few requests in the forum for a Minimal proxy factory.  Having as part of OpenZeppelin Contracts could see more use of minimal proxies.

I created the following example (from: https://forum.openzeppelin.com/t/how-to-compute-the-create2-address-for-a-minimal-proxy/3595/2?u=abcoathup).  Though it would need work and tests to be up to Contracts standard.

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

import "@openzeppelin/contracts/utils/Create2.sol";

contract MinimalProxyFactory {
    event MinimalProxyCreated(address minimalProxy);

    function computeAddress(uint256 salt, address implementation)
        public
        view
        returns (address)
    {
        return
            Create2.computeAddress(
                keccak256(abi.encodePacked(salt)),
                keccak256(getContractCreationCode(implementation)),
                address(this)
            );
    }

    function deploy(
        uint256 salt,
        address implementation
    ) public {
        address minimalProxy = Create2.deploy(
            0,
            keccak256(abi.encodePacked(salt)),
            getContractCreationCode(implementation)
        );
        emit MinimalProxyCreated(minimalProxy);
    }

    function getContractCreationCode(address logic)
        internal
        pure
        returns (bytes memory)
    {
        bytes10 creation = 0x3d602d80600a3d3981f3;
        bytes10 prefix = 0x363d3d373d3d3d363d73;
        bytes20 targetBytes = bytes20(logic);
        bytes15 suffix = 0x5af43d82803e903d91602b57fd5bf3;
        return abi.encodePacked(creation, prefix, targetBytes, suffix);
    }
}
```
