### ISSUE TITLE
Support for Solidity 0.8.x

### ISSUE THREAD

**Issue by andrekorol** [OpenZeppelin/openzeppelin-contracts#2441]
**🧐 Motivation**
Solidity 0.8.0 has been [released](https://blog.soliditylang.org/2020/12/16/solidity-v0.8.0-release-announcement/), and I think it would be a good idea to have openzeppelin-contracts supporting it.

**📝 Details**
Updating the current contracts to support being compiled with solc-0.8 should be pretty straightforward since most breaking changes can be easily addressed.

**Comment by abcoathup** [comment]
Hi @andrekorol !  Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by andrekorol** [comment]
> Hi @andrekorol ! Thanks for the suggestion, it is really appreciated.
> 
> The project owner will review your suggestion as soon as they can.
> 
> Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand. We don’t want you to waste your time!

Thanks for the quick reply! I already had made the changes on the PR above (#2442), and only now saw your comment, my bad 😅.  

But I'll wait before making any further changes 😃.

**Comment by frangio** [comment]
Support for Solidit 0.8 has been merged to master and will be released later in February.

**Comment by jflatow** [comment]
Is 0.8 support still going to be released?

**Comment by Amxx** [comment]
@jflatow Support for 0.8 is part of the 4.0.0 release.

You can follow the corresponding timeline [here](https://forum.openzeppelin.com/t/contracts-4-0-timeline/5774/6).
