### ISSUE TITLE
Request for UpgradableOwnable contract

### ISSUE THREAD

**Issue by bh2smith** [OpenZeppelin/openzeppelin-contracts#2474]
**🧐 Motivation**
Would like to implement an upgradable contract that is ownable instead of copying the ownable logic into an initializer manually.

**📝 Details**

Ideally there would be some kind of `UpgradableOwnable` or `InitializedOwnable` which is identical to `Ownable` but having its constructor replaced with an `initialize` method. Thus, upgradable contracts which are meant to be ownable could inherit `UpgradableOwnable` which no-longer has a constructor. 

I would have implemented this myself and made a PR, but it is unclear at this time where such a contract should live within the project or if such a contract should be implemented by replicating the contract code of Ownable while replacing the constructor with initializer logic.

**Comment by frangio** [comment]
Hi @bh2smith, have you seen [our Upgradeable Contracts package](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable)? I believe it's exactly what you're looking for.

**Comment by bh2smith** [comment]
OH WOW! I had no idea. Thanks very much for pointing me in the exact right direction!
