### ISSUE TITLE
GSN documentation links to deprecated repo

### ISSUE THREAD

**Issue by m1cm1c** [OpenZeppelin/openzeppelin-contracts#2478]
E.g. https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/GSN/IRelayHub.sol contains:

```
 * See the https://github.com/OpenZeppelin/openzeppelin-gsn-helpers[OpenZeppelin GSN helpers] for more information on
 * how to deploy an instance of `RelayHub` on your local test network.
 ```

but https://github.com/OpenZeppelin/openzeppelin-gsn-helpers says:
> This project is deprecated. All development on the GSN has been moved to the OpenGSN organization. Please refer to the OpenGSN localgsn implementation. We won't be developing new features nor addressing issues. Read here for more info.

**Comment by abcoathup** [comment]
Hi @m1cm1c,

Thanks so much for reporting this! The project owner will review and triage this issue as soon as they can.

All development on the GSN has been moved to the OpenGSN organization (https://opengsn.org). They are developing GSNv2.

**Comment by frangio** [comment]
Version 4.0 no longer contains these links.
