### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by TrinhTrungDung** [OpenZeppelin/openzeppelin-contracts#2515]
The error message should be "Counter: decrement underflow" instead of overflow.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f2112be4d8e2b8798f789b948f2a7625b2350fe7/contracts/utils/Counters.sol#L33

**Comment by frangio** [comment]
Thank you for the suggestion @TrinhTrungDung. "Underflow" is actually used for numbers whose _absolute_ value is too small, such as floating point numbers when they're too small. Negative numbers in integer arithmetic are considered overflow. See [Arithmetic underflow](https://en.wikipedia.org/wiki/Arithmetic_underflow) and [Integer overflow](https://en.wikipedia.org/wiki/Integer_overflow) on Wikipedia.
