### ISSUE TITLE
Deprecate GSN v1 support

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#2520]
**🧐 Motivation**
GSN is moving from v1 to v2. Current GSN support in contracts is based around v1, which is being deprecated of the more modular approach that is GSN v2.

**📝 Details**
Support for ERC2771 is the topic of another issue & PR. In order to cleanup the repo, and avoid possible confusion between the old and new GSN tolling, the `contracts/GSN` repository should be removed.

Any comments is welcome.

**Comment by crazyrabbitLTC** [comment]
Hey folks, does this mean Context's convenience features like _msgSender and _msgData will no longer work? (Also, 6 days is pretty short to deprecate something!)

**Comment by frangio** [comment]
@crazyrabbitLTC No, `Context` and its functions are still definitely available in all contracts! What was removed was the Context variant specific to GSNv1.

We tried to notify about these changes in advance by releasing a Beta version a month ago. Apologies if you missed those announcements! Let us know if the change causes any issues for you and we will look into it.
