### ISSUE TITLE
Apparent Bug in ERC721 Transfer Event

### ISSUE THREAD

**Issue by JF0001** [OpenZeppelin/openzeppelin-contracts#2526]
I had initially reported an issue at the following link:
https://forum.openzeppelin.com/t/how-to-pass-values-in-transfer-event/5809

After doing more testing, I am experiencing something that looks like a bug, although it is quite possible that I am doing something wrong.

As explained in the issue referenced above, when I declare the ERC721 Transfer event using only the tokenId parameter (i.e. event Transfer(uint256 tokenId);), a value for the 3 parameters of the emit (returnValues with the "from", "to" and "tokenId" fields) are sent to my front-end.

Meanwhile, when I declare the Transfer event using the 3 parameters (event Transfer(address indexed from, address indexed to, uint256 tokenId);), I am obtaining the following error in the front-end: TypeError: Cannot read property 'returnValues' of undefined

No other modifications are made to either the smart contract or my front-end.

Thank you. J

**Comment by zemse** [comment]
I'd like to help. When you change `Transfer(uint256 tokenId)` to `Transfer(address indexed from, address indexed to, uint256 tokenId)`, that changes the signature of the event (so that changes your ABI). As you said "No other modifications to my front-end", if you are using the old ABI, try updating it in your front end.

**Comment by Amxx** [comment]
Hello @JF0001.
Your problem looks to be frontend related, and not specific to OpenZeppelin's contracts. I'm not right sure this is the right place to raise an issue.
I would personnally say that having multiple event signature use the same name is not a good idea, as it can lead to confusion between inconsistent mapping between name and signature in you frontend. Additionnaly, I'm curious why you need an extra `Transfer(uint256)` event (which is not standard) in addition to the existing one, that already contains the tokenId information you want.

**Comment by JF0001** [comment]
Thank you @zemse I have obviously re-deployed the contract on my test chain and included the updated ABI in my front-end. (My apologies for not including this detail.) If that were not the case, I wouldn't have been able to compare the two outputs.

**Comment by JF0001** [comment]
Hi @Amxx 
I am not using the two different signatures at once within my contract. I have discovered the discrepancy of the output from each signature by chance. I had initially mistakenly used the  Transfer(uint256 tokenId) signature by mistake, not including the other two parameters (from and to) in my declaration. This signature was actually working properly, returning all the parameters in the event (even if they were actually not found in my declaration). Having realised my mistake, I have then modified the signature so that it does actually contain all three parameters. Having change only this signature in my smart contract and nothing else in my front-end, my code stopped working, thus realising after outputting the result that the returnValues were no longer returned as previously.
Thank you again.
J

**Comment by JF0001** [comment]
Hi @Amxx I am uploading the respective outputs of the events when using only the TokenId param and when using the 3 parameters in the signature.
![TokenIdParam](https://user-images.githubusercontent.com/11094435/108223919-58e4d180-7108-11eb-95f9-53e0b2568b78.png)
![3Parameters](https://user-images.githubusercontent.com/11094435/108223935-5bdfc200-7108-11eb-9ceb-312014778fe9.png)

**Comment by Amxx** [comment]
@JF0001 Again, I'm not sure how dis relates the OpenZeppelin contracts. Are you using our implementation of ERC721, and is there any issue with it ? If not, I'd like to close this issue and encourage you to continue the discussion somewhere else (in the forum) since this space is specifically about the @OpenZeppelin/contracts package.

**Comment by JF0001** [comment]
Hi @Amxx Yes indeed, I am using the OpenZeppelin implementation of ERC721. I am importing the ERC721.sol code (without modifying it) within my contract. As explained above, in my contract, if I include in my declaration of the Transfer Event, only the tokenId parameter, I am obtaining the output above, in which one can see that all 3 parameters are emitted by my smart contract (and received in my front-end), while if I actually declare the 3 parameters in my declaration of the Transfer Event, these values are no longer emitted, as displayed in the second output above.
Thank you. J

**Comment by JF0001** [comment]
Hi @Amxx I was able to make it work properly using the following:

event Transfer(address indexed _from, address indexed _to, uint256 indexed _tokenId);

Instead of:
event Transfer(address indexed from, address indexed to, uint256 tokenId);

As previously.

Regards, J
