### ISSUE TITLE
@openzeppelin/contracts support of solidity 8

### ISSUE THREAD

**Issue by ochikov** [OpenZeppelin/openzeppelin-contracts#2529]
I've installed "@openzeppelin/contracts": "^3.4.0" and trying to use ERC20 contracts with solc 0.8.0, however in the ERC20 contract, the version specified is:     `pragma solidity >=0.6.0 <0.8.0;`

**Comment by Amxx** [comment]
Hello @ochikov, and thank you for your issue,
This has already been requested many times, and activelly being worked on. You may notice that the master branch is 0.8.0.compatible.

For more details about the timeline: https://forum.openzeppelin.com/t/contracts-4-0-timeline/5774/7

**Comment by ochikov** [comment]
> Hello @ochikov, and thank you for your issue,
> This has already been requested many times, and activelly being worked on. You may notice that the master branch is 0.8.0.compatible.
> 
> For more details about the timeline: https://forum.openzeppelin.com/t/contracts-4-0-timeline/5774/7

Hello @Amxx , tried to install directly from the branch using: `npm install https://github.com/OpenZeppelin/openzeppelin-contracts.git` but the command does not resolve. Any suggestions ?

**Comment by Amxx** [comment]
I don't think you can install a git branch directly from npm, can you ?
You can either do git clone, of way for the preview to be available (again, see the timeline)

**Comment by ochikov** [comment]
> I don't think you can install a git branch directly from npm, can you ?
> You can either do git clone, of way for the preview to be available (again, see the timeline)

Yes you can. I do it all the time, for examle this is in my package.json: `"circom": "LimeChain/circom",
    "cli-analytics-sdk": "LimeChain/cli-analytics-sdk",` However this approach with openzeppelin does not work.

**Comment by Amxx** [comment]
I've ssen that, and update my message (see above)

**Comment by ochikov** [comment]
> I've ssen that, and update my message (see above)

Cool, so how can I use the latest version from the master branch, however it is not released yet? :(

**Comment by frangio** [comment]
@ochikov It will be released in the next few days. Thank you for your patience. :pray:

**Comment by frangio** [comment]
OpenZeppelin Contracts 4.0 with Solidity 0.8 has been out for a while now.
