### ISSUE TITLE
Remove dead code - override function that does nothing other than call the super?

### ISSUE THREAD

**Issue by marsrobertson** [OpenZeppelin/openzeppelin-contracts#2530]
See below:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/24660c3e48a71041ee3a4424d6e448b047926294/contracts/presets/ERC20PresetMinterPauser.sol#L84-L86

Appears to me like code that does nothing.

Is there any meaning or safe to remove?

**Comment by frangio** [comment]
Hi @marsrobertson. Unfortunately this function is necessary for Solidity. :disappointed:

If we remove it, the compiler will complain that there's two different definitions of `_beforeTokenTransfer` in the inheritance and they need to be disambiguated, thus the part where it says `override(ERC20, ERC20Pausable)`.
