### ISSUE TITLE
pragma experimental SMTChecker;

### ISSUE THREAD

**Issue by vporton** [OpenZeppelin/openzeppelin-contracts#2534]
**🧐 Motivation**
```solidity
//SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;
pragma experimental SMTChecker;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

contract GameToken is Ownable {}
```
compiles with warnings:
```
Compiling 6 files with 0.8.1
Warning: CHC: Overflow (resulting value larger than 2**256 - 1) might happen here.
   --> @openzeppelin/contracts/token/ERC20/ERC20.sol:219:9:
    |
219 |         _balances[recipient] += amount;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Warning: CHC: Overflow (resulting value larger than 2**256 - 1) might happen here.
   --> @openzeppelin/contracts/token/ERC20/ERC20.sol:219:9:
    |
219 |         _balances[recipient] += amount;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Warning: CHC: Overflow (resulting value larger than 2**256 - 1) might happen here.
   --> @openzeppelin/contracts/token/ERC20/ERC20.sol:170:41:
    |
170 |         _approve(_msgSender(), spender, _allowances[_msgSender()][spender] + addedValue);
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**📝 Details**
Add 
```solidity
pragma experimental SMTChecker;
```
to each `.sol` file in this repo.

**Comment by abcoathup** [comment]
Hi @vporton!  

Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by Amxx** [comment]
Hello @vporton, and think you for the proposition.
The additional security information given by SMTChecker could definitelly be usefull to openzeppelin/contracts, and we will investigate enabling it in all files at some point...

... however, int this case SMTChecker doesn't seem to realize that we are using solidity ^0.8.0, which comes with safemath built in by default. In the cases were these operation overflow, panic code are emitted. This protects against math errors that would correspond to forbidden transfers, or that would result in inconsistencies.

This kind of false positive makes me think we should not use SMTChecker for now.

**Comment by frangio** [comment]
I agree with @Amxx's comment.

The SMTChecker is apparently aware that we are using Solidity ^0.8, and it seems it was a decision to keep the warning anyway? There doesn't seem to be consensus on this within the Solidity team itself. See https://github.com/ethereum/solidity/issues/10717.

**Comment by leonardoalt** [comment]
I think the main point against adding it by default is that some queries may take a really long time to finish, and false positives are rather common and might be confusing for someone who doesn't know what it's talking about and where it's coming from.
As @Amxx mentioned, the security hints could be useful for the writers of the OZ contracts, but I feel like the libraries should *not* be shipped with default smtchecker.

**Comment by leonardoalt** [comment]
In this specific case, as @frangio pointed out, the SMTChecker is aware of default revert on overflow, but the warning is kept for now (it is under discussion). Not also that when it says `might happen` it means that it actually *couldn't* solve the query, so it's more like a "dunno" than an actual false positive.

**Comment by frangio** [comment]
Got it, thanks for the input @leonardoalt. Closing this issue since we will not add the pragma.
