### ISSUE TITLE
Tools for ERC1271 signature verification

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#2535]
**🧐 Motivation**
Smart wallet are becoming more and more common. Recovery of signature is supported by contracts through the ECDSA library, but this only works for EOA. Smart Wallet rely on ERC1271 to perform signature verification, but this is not currently support by openzeppelin/contracts 

**📝 Details**
Add a `SignatureChecker` library, that given an expected signer (address), a hash (bytes32) and a signature (bytes), will transparently support traditional EOA signature, or resolve to ERC1271 if the expected signer is a smart contract.

**Comment by heyJonBray** [comment]
Pretty straightforward, and good to stay ahead of the curve with smart wallets. I was in the process of working on a similar feature for a lightweight auth/signature library
Will update if this is something I will do.
Cheers!

**Comment by frangio** [comment]
@heyJonBray Please note that there is an open PR already implementing this feature.
