### ISSUE TITLE
Add EIP3156 FlashLoan support (ERC20 extension)

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#2540]
**🧐 Motivation**
[ERC3156 is now final](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3156.md)

**📝 Details**
Provide an extension for ERC20 that implements this ERC.

**Comment by frangio** [comment]
This sounds nice. Have the EIP or an implemenation been audited? Are there production deployments?

**Comment by Amxx** [comment]
I'm not 100% sure, @albertocuestacanada might be able to tell use more. Maybe yield uses it.

**Comment by Amxx** [comment]
there is this ERC3156 compatible uniswap wrapper: https://ftmscan.com/address/0xa89a83890cc5d43d710846cefcb4a41007a37347#code

**Comment by albertocuestacanada** [comment]
Hi there! 

As all EIPs that make it to Final, ERC3156 has been thoroughly audited pro-bono by an all-star team, including your own Austin Williams.

There are [two ERC3156 compliant wrappers in mainnet and fantom](https://github.com/albertocuestacanada/ERC3156-Wrappers), [MakerDAO's MIP-25](https://forum.makerdao.com/t/mip25-flash-mint-module/4400) is compliant, audited, and scheduled to go live soon, and [Cover Protocol](https://www.coverprotocol.com/) is also a compliant borrower. [WETH10](https://github.com/WETH10/WETH10) is scheduled to go live soon and is also a compliant lender.

Yield doesn't use it in v1, but v2 will implement it for sure.

**Comment by albertocuestacanada** [comment]
Please note that the reference implementation is here: https://github.com/albertocuestacanada/ERC3156

Not to be confused with the ERC3156-Wrappers, which are a personal project:
https://github.com/albertocuestacanada/ERC3156-Wrappers

**Comment by Amxx** [comment]
Implementation proposal: https://github.com/Amxx/openzeppelin-contracts/blob/feature/ERC3156/contracts/token/ERC20/extensions/draft-ERC3156.sol

I just wonder why the return value for `IERC3156FlashBorrower.onFlashLoan` is `bytes32(keccak256("ERC3156FlashBorrower.onFlashLoan"))` and not `bytes4(IERC3156FlashBorrower(0).onFlashLoan.selector)` as most other ERC do ...

**Comment by albertocuestacanada** [comment]
The return value is a sentinel to make sure the lender didn't accidentally call the fallback function. `bytes32(keccak256("ERC3156FlashBorrower.onFlashLoan"))` sounded like a reasonable choice, and no one was seemingly aware that `bytes4(IERC3156FlashBorrower(0).onFlashLoan.selector)` was a best practice.

Maybe you should give a hand to @MicahZoltu in reviewing ERCs. That's quite a detail to know about.

**Comment by Amxx** [comment]
Its true that returning a bytes4 is "weaker". This is the de-facto standard for many eip however (721, 777, 1155, 1271, ...)

**Comment by MicahZoltu** [comment]
I don't see why the seed for a particular sentinel needs to be standardized?  It is just "a well known value" and its actual contents don't matter at all.

**Comment by lepidotteri** [comment]
any updates on this?

**Comment by Amxx** [comment]
PR #2543 is basically good to go. Should be in 4.1 release.
