### ISSUE TITLE
ERC721#_approve is private when it should be internal

### ISSUE THREAD

**Issue by moodysalem** [OpenZeppelin/openzeppelin-contracts#2550]
There is no other way to approve a ERC721 token from subclass because the mapping is also private

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/5c8746f56b4bed8cc9e0e044f5f69ab2f9428ce1/contracts/token/ERC721/ERC721.sol#L452

**Comment by Amxx** [comment]
Hello @moodysalem,
This function is internal in the master branch: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L325-L328

**Comment by moodysalem** [comment]
> Hello @moodysalem,
> This function is internal in the master branch: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L325-L328

master branch is on ^0.8.0, the specifically linked commit/tag is ^0.7.0

**Comment by frangio** [comment]
@moodysalem If Solidity 0.8 is not an option for you, we can release 3.4.1 with this function made internal.

**Comment by moodysalem** [comment]
> @moodysalem If Solidity 0.8 is not an option for you, we can release 3.4.1 with this function made internal.

It isn't, and that would be appreciated!

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/commit/bb068ed5d95cc63176d7b5bb6d2d2864cac24909 and released as 3.4.1 in all its variants.

**Comment by moodysalem** [comment]
> Fixed in [bb068ed](https://github.com/OpenZeppelin/openzeppelin-contracts/commit/bb068ed5d95cc63176d7b5bb6d2d2864cac24909) and released as 3.4.1 in all its variants.

think it was missed in `3.4.1-solc-0.7`

https://unpkg.com/@openzeppelin/contracts@3.4.1-solc-0.7/token/ERC721/ERC721.sol

**Comment by frangio** [comment]
Sorry about that. It is fixed now (in version `3.4.1-solc-0.7-2` at `solc-0.7` npm tag).

**Comment by moodysalem** [comment]
@frangio Could you please create a tag with the commit you built from? Thanks!

**Comment by frangio** [comment]
[`v3.4.1-solc-0.7-2`](https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v3.4.1-solc-0.7-2)
