### ISSUE TITLE
Add getter for decimals to IERC20.sol

### ISSUE THREAD

**Issue by CrackerHax** [OpenZeppelin/openzeppelin-contracts#2559]
**🧐 Motivation**
Could use a getter for decimals()
**📝 Details**
IERC20 = IERC20(address);
uint decimals = token.decimals();

**Comment by abcoathup** [comment]
Hi @CrackerHax,

Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time! 

Can you describe your use case for an interface including optional ERC20 metadata such as decimals?

IERC20 is the interface of the ERC20 standard as defined in the EIP.
From: https://docs.openzeppelin.com/contracts/3.x/api/token/erc20#IERC20

Decimals is optional in the EIP: https://eips.ethereum.org/EIPS/eip-20

**Comment by Amxx** [comment]
Hello @CrackerHax and thank you for raising this issue,

Despite their wide availability, `name`, `symbol` and `decimals` are not actually part of the ERC20 standard. Many ERC20 token do not implement them, and this is why we did include these functions in the ERC20 interface.

An option could be to provide an extension interface `ERC20Metadata` That would extend IERC20 and provide these describe functions. Would that be a good enought solution for you ?
 
 @frangio would you be ok with that ?

**Comment by frangio** [comment]
These functions are standard (they are part of ERC20) but they're optional, this is why they're not in the `IERC20` interface.
