### ISSUE TITLE
openzeppelin 0.8.2 version doesn't work.

### ISSUE THREAD

**Issue by novaknole** [OpenZeppelin/openzeppelin-contracts#2570]
I am trying to use packages of openzeppelin for 0.8.2. I will explain my issue here and if you guys haven't released contracts for 0.8.2, imagine that this still applies to 0.8.0.

I run `yarn add @openzeppelin/contracts` and this installs the following:

> "@openzeppelin/contracts@^3.4.0":
>   version "3.4.1"
>   resolved "https://registry.yarnpkg.com/@openzeppelin/contracts/-/contracts-3.4.1.tgz#03c891fec7f93be0ae44ed74e57a122a38732ce7"
>   integrity sha512-cUriqMauq1ylzP2TxePNdPqkwI7Le3Annh4K9rrpvKfSBB/bdW+Iu1ihBaTIABTAAJ85LmKL5SSPPL9ry8d1gQ==

One of my files look like this:

```js
pragma solidity 0.8.2;

import '@openzeppelin/contracts/token/ERC20/ERC20.sol';

contract TestERC20 is ERC20 {

}
```

The compiler results in an error: 

> The Solidity version pragma statement in these files don't match any of the configured compilers in your config. Change the pragma or configure additional compiler versions in your hardhat config.
>  * @openzeppelin/contracts/token/ERC20/ERC20.sol (>=0.6.0 <0.8.0)

Then, I go to `node_modules` and it seems like `ERC20` really has the pragma like this `>=0.6.0 <0.8.0`.

Is this issue somehow already familiar with you ?

**Comment by julianmrodri** [comment]
Support for Solidity `0.8` has not been officially released. You are installing the latest release which is not prepared for `0.8`. 

You can try to install `v4.0.0-beta.0` for now which is still in Beta.

Link: https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v4.0.0-beta.0

**Comment by frangio** [comment]
@julianmrodri's response is correct. I'll add that you can install the `next` tag on npm to get the latest beta (currently `beta.1`): `npm install @openzeppelin/contract@next`.
