### ISSUE TITLE
SafeTransfer does not validate return data length

### ISSUE THREAD

**Issue by pertsev** [OpenZeppelin/openzeppelin-contracts#2577]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1ee939e7c4b2c1fe84e6f5b6a7c1ce5e7d91667f/contracts/token/ERC20/utils/SafeERC20.sol#L72-L75

SafeTransfer does not validate return data length. The token can be a contract that has the transfer method but returns 2 or more arguments, so it's more reliable to check it like this
```js
if (returndata.length > 0) { // Return data is optional
    require(data.length == 32, "data length should be either 0 or 32 bytes");
    // solhint-disable-next-line max-line-length
    require(abi.decode(returndata, (bool)), "SafeERC20: ERC20 operation did not succeed");
}
```
Also, the token can return just one value with a different type (uint256 e.g) and it's going to be `true` after `abi.decode(returndata, (bool)`. So further validation can be applied

**Comment by abcoathup** [comment]
Hi @pertsev!  Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by frangio** [comment]
Hi @pertsev. Note that Solidity works the same way. If you call a function that you think returns a single `uint`, but it instead returns a pair of `uint`s, it will silently decode the first `uint` only.

We do not intend to add stricter semantics here, just support non-compliant ERC20 tokens that do not return the boolean value.
