### ISSUE TITLE
Make own crypto

### ISSUE THREAD

**Issue by WORLDKING2021** [OpenZeppelin/openzeppelin-contracts#2587]
**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by abcoathup** [comment]
Hi @WORLDKING2021!  

Thanks for your question. I recommend posting it in the Community Forum (https://forum.openzeppelin.com), where it can get a faster response by the community and the team. 

I will close this issue so we can continue the discussion in the forum!
