### ISSUE TITLE
Improve ERC721 design for OpenSea proxy compatibility

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#2594]
**🧐 Motivation**

OpenSea encourages ERC721 developer to include an additional "proxies" approval to smoothen the user experience. This is made available in a [dedicated repo](https://github.com/ProjectOpenSea/opensea-creatures/blob/master/contracts/ERC721Tradable.sol#L64-L79) that is unfortunately still using solidity 0.5.0.

**📝 Details**

The ERC721 tradable mechanism is implemented through a hardcoded `proxyRegistryAddress`

```
contract ProxyRegistry {
    mapping(address => OwnableDelegateProxy) public proxies;
}
```

that is used when checking approval for all:

```
function isApprovedForAll(address owner, address operator)
    public
    view
    returns (bool)
{
    // Whitelist OpenSea proxy contract for easy trading.
    ProxyRegistry proxyRegistry = ProxyRegistry(proxyRegistryAddress);
    if (address(proxyRegistry.proxies(owner)) == operator) {
        return true;
    }
     return super.isApprovedForAll(owner, operator);
}
```

Still, reproducing this in our latest version (3.4.0 and 4.0) is made difficult by the restriction we enforce on virtual overloading:
- in addition to being public, `isApprovedForAll` is used in 2 functions (`approve` and `_isApprovedOrOwner`). However, in both cases, we force the use on the base implementation, meaning that overloading `isApprovedForAll` has no effect on the contract behavior. (this create a "gap" between what the contract advertizes, and what it actually does, which I see as an issue)
- we could also overload `_isApprovedOrOwner`, but this requires extra `ownerOf` calls, meaning unnecessary sload :/
- even with both functions overloaded, `approve` would still not behave correctly, and would also need to be overloaded. Due to its design, this last overloading cannot rely on a super call, and must thus the entirely rewritten.

We can see that, while this update was almost trivial on early versions of contracts, the inheritance restrictions that are currently part of the codebase are a pain to work with, and are more likely to cause issues due to inconsistent behavior between functions than to actually protect end-users. Even advanced users can have a hard time realizing the complexity of it, particularly if they are used to import contracts and not have a deep look at it.
Hopefully, they have good exhaustive tests and see that before deploying.

My proposition would be, at least for the `isApprovedForAll`, to use the overloaded version of the public function for the internal logic. `ownerOf` is complex since it returns an address that is supposed to match the internal book keeping, but `isApprovedForAll` is just a boolean flag that IMO should be easily overloaded.

**Comment by Amxx** [comment]
Note: in ERC1155, isApprovedForAll is directly overidable... so we also have inconsistent coding behavior between our own contracts

**Comment by frangio** [comment]
A reminder for anyone overriding functions: people who wish to override should consult the source code to fully understand the impact it will have, and should consider whether they need to override additional functions to achieve the desired behavior.

**Comment by Marxpark** [comment]
I've been working on a contract and can't find what the proxy address should be set to at deployment. Can someone point me into the right direction please?

**Comment by frangio** [comment]
@Marxpark I think this question is specific to OpenSea. Have you tried asking in [their Discord](https://discordapp.com/invite/ga8EJbv)?

**Comment by michael-stajer** [comment]
> I've been working on a contract and can't find what the proxy address should be set to at deployment. Can someone point me into the right direction please?

Look at the migration scripts in the OS repo -- the address is set at the time the contract is deploy through the constructor.

**Comment by DevonMartens** [comment]
@michael-stajer can you please link that repo

**Comment by michael-stajer** [comment]
@DevonMartens In the repo posted in the OP's original issue, look at the migrations scrip #2, line 28: https://github.com/ProjectOpenSea/opensea-creatures/blob/f7257a043e82fae8251eec2bdde37a44fee474c4/migrations/2_deploy_contracts.js#L28 

That is where the actual opensea address is being injected (at deploy).

**Comment by itinance** [comment]
Specifically for use on Polygon, the official sample code will `revert` because the proxyAddresses do not point to a contract that meets the required interface. Instead

        ProxyRegistry proxyRegistry = ProxyRegistry(proxyRegistryAddress);
        if (address(proxyRegistry.proxies(_owner)) == _operator) {
            return true;
        }

it has to be

        if (_operator == proxyRegistryAddress) {
            return true;
        }

while `proxyRegistryAddress` is the corresponding proxy address, which can be found here: https://docs.opensea.io/docs/polygon-basic-integration
