### ISSUE TITLE
`SignedSafeMath` missing safe unary negation operator.

### ISSUE THREAD

**Issue by nlordell** [OpenZeppelin/openzeppelin-contracts#2595]
**🧐 Motivation**

The signed safe math does not have a helper method for doing unary negation protected from overflow. Specifically, because signed integers are represented in 2's compliment, the most negative value has not positive opposite. For example `-type(int256).min == type(int256).min`.

**📝 Details**

This is fairly easy to implement, as there is only one possible value that can overflow on a unary negation, that is `type(int256).min`. Note that this is **not** needed for Solidity 0.8, as the generated checked math code panics when negating `type(int256.min)`.

**Comment by Amxx** [comment]
Hello @nlordell, and thanks for your proposal.

The contracts library is now targeting solidity 0.8. While support for 0.6 and 0.7 is available in the 3.x branch, and we are going to provide some support if bugs were to be discovered in this branch, we do not plan to publish additional 3.x releases with new features.

We encourage everything to migrate to 4.0, which is still in release candidate but should be official in a few days.

**Comment by nlordell** [comment]
Closing as no new features are being accepted for 3.x
