### ISSUE TITLE
Improve Cryptography test clarity to showcase how signatures are generated

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-contracts#2600]
**🧐 Motivation**
Many people learn how some of the more exotic features of OpenZeppelin contracts work by reading the tests. Having clear tests has always been a hallmark of the OpenZeppelin library. 

In the Cryptography tests (https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/test/utils/cryptography/ECDSA.test.js) the signature used is pre-generated. This opens an uncertainty for the reader who perhaps doesn't understand how to properly generate this signature. 

**📝 Details**

I would like to ask that in the Cryptography tests (and other tests if this idea applies) that we don't use precomputed values, and instead, show the computation of these values as part of the tests so that users understand how to replicate the results on their own, and how to design Javascript code that will properly pass the tests. 

See for [example](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/09e302384a3c77be1b482b18a4e30f88630cfd66/test/utils/cryptography/ECDSA.test.js#L37): 

The pre-computation of this signature leaves the reader unsure how to properly create a signature on their own. 

[Here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/09e302384a3c77be1b482b18a4e30f88630cfd66/test/utils/cryptography/ECDSA.test.js#L102) in the same test file, we have a different form of signature which is unexplained a "high-s" value. 

Precomputing "magic numbers" without an explanation as to how or why this value was obtained makes the tests opaque to those unfamiliar with the subject. 

IMHO the OpenZeppelin tests should not only test the smart contract code, but also show the user HOW to test the smart contract code. 

The accompanying OpenZeppelin [Documentation](https://docs.openzeppelin.com/contracts/3.x/api/cryptography) similarly does not describe how to create signatures so the user is left unsure how the tests created these values.

**Comment by frangio** [comment]
Thanks for bringing this up! I agree that we should not be using precomputed values in most of these cases, and the ones that can't be computed in the test should be better explained (it may be the case with the "high-s" value, I don't remember at the moment).

I'll revert the issue title to keep it more actionable, but we're keeping test clarity as a general guideline.

**Comment by Amxx** [comment]
Note: there is already a test case where the signature is generated using `web3.eth.sign`: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/test/utils/cryptography/ECDSA.test.js#L110-L119

I guess its mostly about adding documentation

**Comment by 78051301012** [comment]
https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2619
