### ISSUE TITLE
Hint at missing role in revert reason for AccessControl rejection

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#2601]
It would be useful to notify clients of what role is necessary to call a function protected by `AccessControl`. We can include this information in the revert reason in a standard and machine-parseable format.

Note that we don't have a built in function or modifier to check if an account has a role. Users are currently encouraged to use `require(hasRole(MINTER_ROLE, msg.sender))`, so we would need to add this new modifier or function in order to standardize the revert reason hint.

**Comment by Amxx** [comment]
+1 for the modifier
