### ISSUE TITLE
Unused IERC721Enumerable import in ERC721 contract

### ISSUE THREAD

**Issue by joZephhh** [OpenZeppelin/openzeppelin-contracts#2602]
Hello!

I had a naive question while I was looking through the ERC721 contract following this comment : 
```
/**
 * @dev Implementation of https://eips.ethereum.org/EIPS/eip-721[ERC721] Non-Fungible Token Standard, including
 * the Metadata extension, but not including the Enumerable extension, which is available separately as
 * {ERC721Enumerable}.
 */
``` 

As the ERC721 contract only inherits of `Context, ERC165, IERC721, IERC721Metadata` and that the `ERC721Enumerable` has its own extension and contract: **it seems that the ERC721 contract has [an unused ERC721Enumerable interface import](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L8)**. Isn't? 

Thanks!

**Comment by maxwellfortney** [comment]
Possibly related, i'm trying to call totalSupply() from remix and getting this error.

![image](https://user-images.githubusercontent.com/29241388/111894750-b90ab400-89e3-11eb-9341-724d4147394d.png)

**Comment by frangio** [comment]
@joZephhh Thanks for reporting! The import has been removed in #2603.

@maxwellfortney This looks like an unrelated issue. Can you post more details in the [OpenZeppelin Forum](https://forum.openzeppelin.com/) so we can debug and help?
