### ISSUE TITLE
File import callback not supported

### ISSUE THREAD

**Issue by carovidela** [OpenZeppelin/openzeppelin-contracts#2611]
/home/carolina/source/proyect_sa/sa_truffle/contracts/IANA.sol:8:1: ParserError: Source "@openZeppelin/contracts/cryptography/ECDSA.sol" not found: File import callback not supported
import "@openZeppelin/contracts/cryptography/ECDSA.sol";
^------------------------------------------------------^
Compilation failed. See above.
Truffle v5.2.2 (core: 5.2.2)
Node v10.19.0

Lo he probado con todas las versiones.
Inicialmente compilaba correctamente y de pronto comenzó a dar el siguiente error.

Compilando los contratos  solc 0.7.5
Probe con la ultima version de OpenZeppelin y igual.
Cuando me funcionaba estaba trabjando con la version  @openZeppelin/contracts@3.4.1 andaba bien y comenzo a lanzar el mismo error

**Comment by abcoathup** [comment]
Hi @carovidela,

I am sorry you had this issue.  Please note we need to use `@openzeppelin` all in lower case in our imports.  Otherwise we get `ParserError: Source "@openZeppelin/contracts/cryptography/ECDSA.sol" not found: File import callback not supported`, with the capital `Z` causing the issue.

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

import "@openzeppelin/contracts/cryptography/ECDSA.sol";

contract MyContract {
}
```

Please see the usage documentation: https://docs.openzeppelin.com/contracts/4.x/#usage

I am closing this issue as fixing the import should allow you to compile.

**Comment by carovidela** [comment]
Buenos dias.
Gracias por tu aporte, sin embargo sigo sin poder solucionar el problema de importacion.
Te envió imagen para que puedas verificarlo
![Captura de pantalla de 2021-03-26 08-13-51](https://user-images.githubusercontent.com/74414981/112623836-9aedeb00-8e0b-11eb-84da-79705bcbe148.png)
En que otro detalle podriamos profundizar???

uso:
 "dependencies": {
    "@openzeppelin/contracts": "^3.4.0-solc-0.7"
  }

**Comment by shashanksinghthakur** [comment]
I am also getting a similar error
![Uploading marketplaceBoilerplate.sol - ethereum-nft-marketplace-boilerplate - Visual Studio Code 15-02-2022 09_55_05.png…]()

**Comment by shashanksinghthakur** [comment]
I am also getting  a similar error
![marketplaceBoilerplate sol - ethereum-nft-marketplace-boilerplate - Visual Studio Code 15-02-2022 09_55_05](https://user-images.githubusercontent.com/85666787/153992509-ce94e134-5b65-41f2-8883-996f21e0a703.png)

**Comment by frangio** [comment]
Please search or ask in the [OpenZeppelin forum](https://forum.openzeppelin.com/c/support/contracts/18).
