### ISSUE TITLE
Update ERC721 example in docs to remove setting of tokenURI

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-contracts#2614]
Current documentation for OpenZeppelin Contracts 4 gives example which includes setting tokenURI which is now an optional extension:
https://docs.openzeppelin.com/contracts/4.x/erc721#constructing_an_erc721_token_contract

Example should be updated.

**💻 Environment**

OpenZeppelin Contracts 4.0

**📝 Details**
Raised by community member in:
https://forum.openzeppelin.com/t/function-settokenuri-in-erc721-is-gone-with-pragma-0-8-0/5978/16?u=abcoathup

**Comment by khanjasir90** [comment]
@Amxx  can i work on this!

**Comment by laurislopata** [comment]
When can we expect this to be fixed, I'm just starting with solidity and it would be nice to have a working example in the documentation to learn from :)

**Comment by abcoathup** [comment]
Hi @laurislopata,

In the meantime you can use the new OpenZeppelin Contracts Wizard: https://docs.openzeppelin.com/contracts/4.x/wizard

Pull Requests to update the documentation are appreciated.

**Comment by frangio** [comment]
Fxied in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2630 and https://github.com/OpenZeppelin/openzeppelin-contracts/commit/07b48484ff259594ec303820a7c3f6d2a477ba52.

Honestly this guide needs to be improved a lot but at least the code works now and the text makes some sense.
