### ISSUE TITLE
Update API docs and comments to change overload to override for ERC20 decimals

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-contracts#2615]
We use `overloaded` when we mean `overridden` for ERC20 `decimals()`
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.0.0/contracts/token/ERC20/ERC20.sol#L78

**💻 Environment**

OpenZeppelin Contracts 4

**Comment by Amxx** [comment]
Fixed, thanks

**Comment by abcoathup** [comment]
Hi @Amxx,

We need to cherry pick to update the 4.x docs: https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#ERC20-decimals--
