### ISSUE TITLE
GetCode

### ISSUE THREAD

**Issue by SilentCicero** [OpenZeppelin/openzeppelin-contracts#2616]
**🧐 Motivation**
I'd like OpenZepplin to add and audit a secure simple library for contracts to get code from a contract and return a bytes. It could easily be a standalone library. There is one suggested by the Solidity developers in the docs. But it hasn't been formally reviewed and tested. 

**📝 Details**

```solidity

library GetCode {
    function at(address _addr) public view returns (bytes memory o_code) {
        assembly {
            // retrieve the size of the code, this needs assembly
            let size := extcodesize(_addr)
            // allocate output byte array - this could also be done without assembly
            // by using o_code = new bytes(size)
            o_code := mload(0x40)
            // new "memory end" including padding
            mstore(0x40, add(o_code, and(add(add(size, 0x20), 0x1f), not(0x1f))))
            // store length in memory
            mstore(o_code, size)
            // actually retrieve the code, this needs assembly
            extcodecopy(_addr, add(o_code, 0x20), 0, size)
        }
    }
}
```

To start, this is a good place. I'd also add a GetCode size as well. This way inline assembly doesn't need to be used which is safer for everyone.

**Comment by abcoathup** [comment]
Hi @SilentCicero!  Thanks for the suggestion, it is really appreciated.

Can you provide more information on the use case for such a library?

Once we have more information, the project owner will then review your suggestion as soon as they can.  

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by frangio** [comment]
@SilentCicero I second the request for more details about what you would do with this feature.

**Comment by SilentCicero** [comment]
There are many cases where you want to study or grab portions of code from
a contract.

Namely around factories that don’t use create2 for example.

So I’d just say, getting code and managing it is a normal function of the
evm and a library to help manage that and turn it into bytes would be
helpful and useful.

**Comment by Amxx** [comment]
Hello @SilentCicero 

This is already [natively supported by solidity](https://docs.soliditylang.org/en/v0.8.3/units-and-global-variables.html). No need for assembly or for a dedicated library.

`address(0x21294610).code`

**Comment by paulrberg** [comment]
> This is already natively supported by solidity. No need for assembly or for a dedicated library.

Perhaps the Solidity docs should be updated then? The [Inline Assembly](https://docs.soliditylang.org/en/v0.8.7/assembly.html) page (which refers to the code shared by @SilentCicero) says this:

> This is not possible with “plain Solidity” and the idea is that reusable assembly libraries can enhance the Solidity language without a compiler change.

**Comment by frangio** [comment]
The [latest docs](https://docs.soliditylang.org/en/latest/assembly.html#example) have been updated and say:
>This is possible with “plain Solidity” too, by using <address>.code.

**Comment by paulrberg** [comment]
Indeed: https://github.com/ethereum/solidity/pull/11897

Anyway, glad we can use high-level Solidity for this now.
