### ISSUE TITLE
isOwner() functionality missing from Ownable.sol

### ISSUE THREAD

**Issue by khanjasir90** [OpenZeppelin/openzeppelin-contracts#2617]
In Ownable.sol file isOwner() function can be added to check whether a particular account is the owner of the contract!

**Comment by khanjasir90** [comment]
@Amxx  can i work on adding this functionality!

**Comment by abcoathup** [comment]
Hi @khanjasir90!  Thanks for the suggestion, it is really appreciated.

Can you provide more information on the need for an `isOwner(address)` function?  There is already an [`owner`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.0.0/contracts/access/Ownable.sol#L35) function and an [`onlyOwner`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.0.0/contracts/access/Ownable.sol#L42) modifier.

Once we have more information, the project owner will then review your suggestion as soon as they can.  

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by khanjasir90** [comment]
So @abcoathup it goes like this : The isOwner() is a boolean functionality which can be used to check whether the the account using the smart contract is its owner or not. at a particular instance of time.This comes handy when there are multiple accounts switching for a transcation during development phase of a smart contract.Below I have given an example to illustrate it in a better way :

Account which deployed smart contract : 0x5B38Da6a701c568545dCfcB03FcB875f56beddC4
isOwner : true
![Capture](https://user-images.githubusercontent.com/53305380/112774704-147a1900-9058-11eb-988e-d19ed8b2925f.JPG)

Second Account : 0x4B20993Bc481177ec7E8f571ceCaE8A9e22C02db
isOwner : false
![image](https://user-images.githubusercontent.com/53305380/112774732-2bb90680-9058-11eb-88fe-64b51badedf8.png)

Hope!!! so you got it.
pls ping for any query regarding this!

**Comment by Amxx** [comment]
Hello @khanjasir90,

This function used to be part of the Ownable contract. However, its interests really limited, and it can be confusing (if read as a view function through an rpc call). Additionally, including this function increases the gas cost of deploying the contract.

For the sake of gas reduction, I really don't think this should be included in the Ownable contract we provide. It would increase the deployment (and run) cost of many contract, without an easy way to opt out. ON the other hand, if you really need this feature, you always opt-in using a very simple wrapper:

```
contract OwnableExtended is Ownable {
    function isOwner() public view virtual returns (bool) {
        return msg.sender == owner();
    }
}
````

**Comment by Amxx** [comment]
Just for the record, I'm trending against function that return a simple boolean, when this boolean is the result of a simple comparison between a public value (like `owner()`) and a parameter of the caller (msg.sender, address(this), ...)
