### ISSUE TITLE
Add IERC721Enumerable to ERC721

### ISSUE THREAD

**Issue by Euxiniar** [OpenZeppelin/openzeppelin-contracts#2621]
I don't know why, but the `IERC721Enumerable` is not implemented by `ERC721` anymore. 
As a result, it is no longer possible to access the functions `totalSupply()`, `tokenOfOwnerByIndex()` and `tokenByIndex()`. 
Have these methods been depreciated? If so, what should I use instead?

**Comment by abcoathup** [comment]
Hi @Euxiniar,

>Our implementation of the ERC721 token (an NFT) was made enumerable by default in version 3.0.0, with no way to opt out of it. This was controversial because it adds to deployment and runtime costs. We’ve now removed enumerability from the base contract and made it an optional extension.

_From: https://blog.openzeppelin.com/openzeppelin-contracts-4-0/_

You can use the optional in extension in OpenZeppelin Contracts 4:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.0.0/contracts/token/ERC721/extensions/ERC721Enumerable.sol
