### ISSUE TITLE
ERC1155 transfers should have internal function that doesn't check approvals

### ISSUE THREAD

**Issue by KaiRo-at** [OpenZeppelin/openzeppelin-contracts#2622]
**🧐 Motivation**
I'm trying to implement a "signed transfer" function for an ERC1155 token (see https://etherscan.io/address/0x478059f577Cb739f0AF0f37A365DD069Ba5BD8Be#code line 2018 ff. for an ERC721 variant) - any user can call this function but needs a fitting signature to actually perform that transfer. In ERC721, this can easily be done by calling the internal `_safeTransfer()` function after checking that all the conditions for the transfer (signature, etc.) are met - but in ERC1155, the same functions that perform the actual transfer also check approval and so with OpenZeppelin 4.0.0, it's hard to implement this (there is a hack I could use but it's ugly). There may be other cases as well where you may want to transfer a token gated by other means than the traditional/standard approval process.
As an overriding contract is unable to access or manipulate the balances directly due to those being private to the OpenZeppelin implementation, it's also not an option to completely copy what the existing functions do into the overriding contract (and I would consider that a hack as well if it were possible).

**📝 Details**
To solve this problem, the ERC1155 transfer functions (`safeTransferFrom`, `safeBatchTransferFrom`) should call additional internal functions that does the actual transfer operation and doesn't check approvals, following the same pattern as the OpenZeppelin ERC721 contract does. Note that this is just a code structuring question, as this would not be available to external callers directly, only to overriding contracts based on the OpenZeppelin implementation.

I actually have a PR for this upcoming.

**Comment by KaiRo-at** [comment]
FWIW, the "hack" I use in the mean time is as follows:
```
contract X  is ERC1155 {
    bool private inSignedTransfer;
    // [...]  

    function isApprovedForAll(address _account, address _operator) public view override(ERC1155)  returns (bool)
    {
        return (inSignedTransfer || super.isApprovedForAll(_account, _operator));
    }

    function _beforeTokenTransfer(address _operator, address _from, address _to, uint256[] memory _ids, uint256[] memory _amounts, bytes memory _data)  internal override
    {
        // If we are in a signed transfer, turn the flag off here, as we did
        // get through approval checks already and there's a theoretical chance
        // that further code could do weird things, including the
        // onERC1155Received() function of the recipient.
        if (inSignedTransfer) {
          inSignedTransfer = false;
        }
        super._beforeTokenTransfer(_operator, _from, _to, _ids, _amounts, _data);
    }

    function signedBatchTransfer(address _from, address _to, uint256[] memory _ids, uint256[] memory _amounts, bytes memory _signature)  public
    {
        // [...]
        inSignedTransfer = true;
        safeBatchTransferFrom(_from, _to, _ids, _amounts, "");
        // This should already be false when we get here, otherwise re-entrancy caused issues.
        if (inSignedTransfer) { revert("Invalid state."); }
    }
}
```

Now, this works, but I guess you will agree that while is should be safe and due to refunds probably not too bad on gas, it's really ugly.

So, I hope my PR for this can be taken as then we can do this pattern in a really decent fashion.

**Comment by abcoathup** [comment]
Hi @KaiRo-at !  Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2636.
