### ISSUE TITLE
Consider changing `isContract` check to use `address.code.size > 0`.

### ISSUE THREAD

**Issue by hrkrshnn** [OpenZeppelin/openzeppelin-contracts#2634]
In https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol#L26

The function `isContract` can be rewritten to

```solidilty
function isContract(address account) internal view returns (bool) {
    return account.code.length > 0;
}
```

Solidity [0.8.1](https://github.com/ethereum/solidity/blob/develop/Changelog.md#081-2021-01-27) implements a shortcut for `account.code.length` that avoids copying code to memory. Therefore the above code should be equivalent. Might also require bumping the pragma to `^0.8.1`.

**Comment by Amxx** [comment]
Hello @hrkrshnn and thank you for this enlightening comments. Solidity is indeed offering more and more feature natively, that used to only be available through assembly.

While this is apparently simple, the 4.0 code is packaged to work with 0.8.0. changing this will require the users to update to at least 0.8.1. It can thus be seen as a breaking change, and we should be careful with such changes.

@frangio any opinion ?

**Comment by hrkrshnn** [comment]
> the 4.0 code is packaged to work with 0.8.0. changing this will require the users to update to at least 0.8.1. It can thus be seen as a breaking change, and we should be careful with such changes.

Why not bump to `4.0.1`?

**Comment by frangio** [comment]
Closing in favor of https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3417.
