### ISSUE TITLE
Total supply issue 

### ISSUE THREAD

**Issue by ValoisProtocol** [OpenZeppelin/openzeppelin-contracts#2641]
So I deployed both the smart contract and the private sale contract. There seems to be a problem with total supply and token tracker of the private sale contract (yes i did enter correctly the token address when deploying private sale ) 

Below is the smart contract 

https://bscscan.com/token/0xf38cd9fa7903871e7602b03acb7dd5b9c210a788

Below is the token contract 
https://bscscan.com/token/0x5d61c35B35b26605ECf7789e3D3F773b4d29961C

 For some reason token tracker comes up an
as 'presale has not started yet. To my understanding the token tracker should have been the name of the project. When I click into token tracker it gives me a very weird total supply where as the total supply for the project is 100M (the private sale contract clearly does not demonstrate that). 

You can see the discrepancies yourself between both links.
Below is the Contract 

https://github.com/BakeryTools/Contracts/blob/main/crowdsale.sol

Will be much appreciated to identify the issues thank you 

Compiler 0.8.2 

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by abcoathup** [comment]
Hi @ValoisProtocol,

This doesn't appear to be an issue with OpenZeppelin Contracts so I am closing this issue.

You can try asking the BSC community and/or in the OpenZeppelin Community Forum https://forum.openzeppelin.com to see if anyone in the community can help.
