### ISSUE TITLE
TimelockController should support an immutable minimum delay baseline upon construction

### ISSUE THREAD

**Issue by alex448844** [OpenZeppelin/openzeppelin-contracts#2642]
**🧐 Motivation**
I'm currently designing a system that will incorporate a `TimelockController` for multiple key contracts. Some operations on these contracts are potentially devastating if called in rapid succession, so a time delay is a perfect solution. A security issue that still remains is that proposers have the power to reduce the `minDelay` to 0, rendering the time lock useless. Even with the one time enforcement of the `minDelay` to reduce it to 0, it still is not great in my opinion that this would be the only time buffer between system participants and a potentially rogue admin.

**📝 Details**
In keeping with the spirit of the contract, an even more trustless experience could be provided to system participants if there was an immutable minimum delay baseline, set on construction and enforced when attempting to lower `minDelay`.

Specifically,

Add `minDelayBaseline`, which is set once during construction. Add a `require` statement in `updateDelay` to check if `newDelay` is not less than `minDelayBaseline`.

**Comment by abcoathup** [comment]
Hi @alex448844 !  Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by Amxx** [comment]
Hello @alex448844.

Thank you for issue, I can see how you would feel safer using a timelock where the delay has a lower bound. Before I discuss that particular point, you should keep in mind that changing the delay is only possible through the timelock itself. It is thus possible to set it to 0, but only after a duration equal to the old delay. While this operation can be considered dangerous, other operations might be even more (like transferring ownership of a contract). It is thus essential to watch/setup alerts on any timelock that you consider critical to your security.

Now about the minimum minDelay. I understand that this is a feature that some people, like you, would want, while others might want to avoid the added complexity and cost. We try to address both use-cases by providing the simplest, and more modular version of the contract, which you can easily expand on. In fact, implementation this additional check is pretty easy to do on top of the existing contract.

```contract TimelockControllerExtended is TimelockController {
  uint256 public immutable hardMinDelay;

  constructor(uint256 minDelay, uint256 _hardMinDelay, address[] memory proposers, address[] memory executors)
  TimelockController(minDelay, proposers, executors)
  {
    hardMinDelay = _hardMinDelay;
  }

  function updateDelay(uint256 newDelay) external virtual override {
    require(newDelay >= hardMinDelay);
    super.updateDelay(newDelay);
  }
}```

In the future, we might extend the TimelockController with additional features, just like the one you requested, by creating modules similar to what we have for ERC20 or ERC721.

I hope this answers your issue.

**Comment by alex448844** [comment]
Thanks so much for the response @Amxx. I can understand how you would prefer to keep the contract minimal to support low costs and needs of all users. Your extended solution is perfect for my needs and I'll be using that :)

**Comment by frangio** [comment]
Glad it's been resolved!
