### ISSUE TITLE
Typo issue in SolDoc on _mint() in ERC20.sol

### ISSUE THREAD

**Issue by iskanderandrews** [OpenZeppelin/openzeppelin-contracts#2649]
Hi, 
I think this is a typo issue in line 232 in the **_mint()** function. Fixed in PR https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2648

Expected: 
     * - `account` cannot be the zero address.
Actual
     * - `to` cannot be the zero address.
 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/3ba2a1354f8f830d5a0e711537efdbdd8bcb109e/contracts/token/ERC20/ERC20.sol#L232

**Comment by abcoathup** [comment]
Hi @iskanderandrews

Thanks so much for reporting it! The project owner will review and triage this issue as soon as they can.
