### ISSUE TITLE
ERC20 : Increase Allowance should cater to max value

### ISSUE THREAD

**Issue by Manik-Jain** [OpenZeppelin/openzeppelin-contracts#2650]
increaseAllowance function in ERC20 expect uint256 value, which has no check on the upper bounds. Although the failure returns a false, there should be an early exit with a descriptive message

**💻 Environment**

**📝 Details**
Version : latest
IDE : Remix

addAllowance  function in ERC20 expect uint256 value, which has no check on the upper bounds. Although the failure returns a false, there should be an early exit with a descriptive message

**🔢 Code to reproduce bug**

increaseAllowance(spender, type(uint).max);

**Comment by frangio** [comment]
Thank you @Manik-Jain. We're currently relying on Solidity overflow checks for addition overflow.

See for example `mint`.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/0d40f705a7d4a42ff622ae3a0e1a90305fc5b93e/contracts/token/ERC20/ERC20.sol#L240

**Comment by frangio** [comment]
Note that Solidity overflow errors return the relevant information in the revert reason, although many clients at this point still do not parse this information and display a nice error message to the user.

**Comment by Amxx** [comment]
Also, note that the standard does NOT require approval to fit within the current balance. A lot of UI rely on this and set the approval to uint256(-1). I don't see any reason to do this kind of change, which might be breaking usecases
