### ISSUE TITLE
The ERC1155 uri format cannot be customized or invoked within contracts that inherit from ERC1155

### ISSUE THREAD

**Issue by ookvic** [OpenZeppelin/openzeppelin-contracts#2652]
The ERC1155 uri format cannot be customized or invoked within contracts that inherit from ERC1155

`function uri(uint256) external view virtual override returns (string memory) {
        return _uri;
  }`
uri methods cannot be called internally ,
It is recommended to use public modifiers, The following code:
`function uri(uint256) public view virtual override returns (string memory) {
        return _uri;
  }`

**Comment by Amxx** [comment]
Hello, 
This issue was addressed in #2576 and is part of the ^4.0 releases.
