### ISSUE TITLE
ERC721PresetMinterPauserAutoId _baseTokenURI do not modify

### ISSUE THREAD

**Issue by ookvic** [OpenZeppelin/openzeppelin-contracts#2668]
ERC721PresetMinterPauserAutoId _baseTokenURI do not modify
I can use the constructor set _baseTokenURI, but when I change the _baseTokenURI it doesn't expose the method call.
I found the code in OpenZeppelin 3.4.1 and asked for it to be made public and available for modification

`/** 
  * @dev Internal function to set the base URI for all token IDs. It is
  * automatically added as a prefix to the value returned in {tokenURI},
  * or to the token ID if {tokenURI} is empty.
  */
function _setBaseURI(string memory baseURI_) internal virtual {
  _baseURI = baseURI_;
}`

**Comment by frangio** [comment]
Hi @ookvic. You can extend `ERC721PresetMinterPauserAutoId` and add this public function as follows:

```solidity
function setBaseURI(string memory baseURI) public {
    _setBaseURI(baseURI);
}
```

**Comment by ookvic** [comment]
> 嗨@ookvic。您可以`ERC721PresetMinterPauserAutoId`使用继承扩展并按如下所示添加此公共函数：
> 
> ```solidity
> 合同XYZ是ERC721PresetMinterPauserAutoId {
>      function setBaseURI（string  memory  baseURI）public {
>          _setBaseURI（baseURI）; 
>     } 
> }
> ```

No _setBaseURI in ERC721PresetMinterPauserAutoId/ERC721 method to call from,
Can you add _setBaseURI (_uri) method to the ERC721PresetMinterPauserAutoId?

**Comment by frangio** [comment]
Oh sorry, `_setBaseURI` doesn't exist on the latest major release of OpenZeppelin Contracts. You should use something like this:

```
contract XYZ is ERC721PresetMinterPauserAutoId {
    string private baseURI;

    function _baseURI() internal pure override returns (string memory) {
        return baseURI;
    }
    
    function setBaseURI(string memory newBaseURI) public {
        baseURI = newBaseURI;
    }
}
```
