### ISSUE TITLE
Wrong eth_estimategas result for ERC721.transferFrom called from approved operator

### ISSUE THREAD

**Issue by olegabr** [OpenZeppelin/openzeppelin-contracts#2688]
I'm calling `ERC721.transferFrom` method through infura.io. It works perfect if sender owns a token. But if it was just approved with an `ERC721.approve` call, then `ERC721.transferFrom` call fails.

**💻 Environment**

Solidity version: v0.8.3+commit.8d00100c

v4.0.0 of OpenZeppelin Contracts were used

**📝 Details**

I'm calling `ERC721.transferFrom` method through infura.io. It works perfect if sender owns a token. But if it was just approved with an `ERC721.approve` call, then `ERC721.transferFrom` call fails.

The reason is wrong return value of the `eth_estimategas` method. It returns lower value [98970](https://ropsten.etherscan.io/tx/0x9853ec70a4d9c50df76c661c976cbeb2d8e6efe532ec263ba76ed2307bccfedd) than MetaMask [149209](https://ropsten.etherscan.io/tx/0xf3718d526e7ebc1f0767e75d30d6a52eae6563d960d72c7453fdb4146044d6ee) for the same transaction. Actual gas used is 54473 for succeeded transaction.

While it is not possible to have a 100% accurate gas estimation, it looks like code changes can improve the estimation results. See this comment please: https://github.com/ethereum/go-ethereum/issues/18519#issuecomment-628609983

**🔢 Code to reproduce bug**
The contract: https://ropsten.etherscan.io/address/0xc8ef2d778e30405ed95e4e3c9cbcd9af9f82289f#writeContract

1. mint token to Alice
2. approve it to Bob
3. calculate data for transferFrom by Bob from Alice to Charlie
4. call eth_estimategas for this data. it would be 98970, while it should be 149209 or similar

**Comment by Amxx** [comment]
Hello @olegabr 

Here are severals things that comes to mind:
- gas estimation for the transferFrom is affected by the approval being processed. You should wait for the approve transaction to be mined, and not just submitted. Maybe that is an issue.
- gas estimation is difficult, and different tooling make different assumption. Also, some tools add some extra, just in case.
- we don't actually gas estimation, metamask/eth nodes do it. If there is an issue with gas estimation, I would argue that I don't see our contract being responsable for the issue. Maybe there is something we can do at the contract level to improve that ... but it mostly feels like something that should be fixed somewhere else.

**Comment by olegabr** [comment]
Hi @Amxx,
Thank you for managing time to answer ;-)
Yes, this issue is not a bug or something that OpenZeppelin should fix, it is a place for useability improvement instead.

**Comment by frangio** [comment]
Does `transferFrom` always fail in this scenario or is it only until the `approve` transaction is mined?

Closing as it doesn't seem there is something we should fix here.
