### ISSUE TITLE
The `Clones` contract could be further optimized to reduce the cost of cloning

### ISSUE THREAD

**Issue by CallMeGwei** [OpenZeppelin/openzeppelin-contracts#2689]
**🧐 Motivation**

While inspecting the OpenZeppelin `Clones` contract, I noticed that the deployment portion of the bytecode seemed like it could be further optimized. Looking to see if this had been discussed elsewhere, I ran across an [OpenZeppelin article](https://blog.openzeppelin.com/deep-dive-into-the-minimal-proxy-contract/) that took note of the same possibility for optimization!

It seems possible to drop 1 byte from this portion of the bytecode.

**📝 Details**
In the `clone` function of the `Clone` contract there is this block of assembly:

```
let ptr := mload(0x40)
mstore(ptr, 0x3d602d80600a3d3981f3363d3d373d3d3d363d73000000000000000000000000)
mstore(add(ptr, 0x14), shl(0x60, master))
mstore(add(ptr, 0x28), 0x5af43d82803e903d91602b57fd5bf30000000000000000000000000000000000)
instance := create(0, ptr, 0x37)
```

The bytes that are responsible for getting our `clone` runtime code onto the blockchain are here:

```
0x3d602d80600a3d3981f3
```

This sequence starts by using a `RETURNDATASIZE` to push a `0` onto the stack (3d), so that we can duplicate it (81) later, just before the return (f3). However, by the end of sequence, we have this left over `0` on the stack. If we removed the initial `RETURNDATASIZE` and, instead, just used it later in place of the DUP2 -- we could save a byte. Users would realize the resultant gas savings with every single clone operation.

Since we're shifting things left by one byte from the start, we need to shift many of the relevant pointers by one byte later in the code.

The optimized, functional assembly block would now look like:

```
let ptr := mload(0x40)
mstore(ptr, 0x602d8060093d393df3363d3d373d3d3d363d7300000000000000000000000000)
mstore(add(ptr, 0x13), shl(0x60, master))
mstore(add(ptr, 0x27), 0x5af43d82803e903d91602b57fd5bf30000000000000000000000000000000000)
instance := create(0, ptr, 0x36)
```

And, of course, analogous changes need to be made to the other functions to keep the entire library on the same page.

Unless there is something I am overlooking that would make us prefer the current implementation - I can submit a PR for this. Is there any reason not to implement this?

**Comment by Amxx** [comment]
Hello @CallMeGwei and thanks for posting this great issue.

We will review your findings are consider further improving the library!

**Comment by frangio** [comment]
If this doesn't affect the bytecode for created clones, please submit the PR!

**Comment by Amxx** [comment]
Closing: see PR
