### ISSUE TITLE
Probably should assign a new value to the free memory pointer

### ISSUE THREAD

**Issue by chiro-hiro** [OpenZeppelin/openzeppelin-contracts#2700]
**🧐 Motivation**
Probably should assign a new value to the free memory pointer at (`0x40`). I have concern that this code could mess up memory and lead to an unexpected result. 

**📝 Details**

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol#L24-L34

```solidity
    function clone(address implementation) internal returns (address instance) {
        // solhint-disable-next-line no-inline-assembly
        assembly {
            let ptr := mload(0x40)
            mstore(ptr, 0x3d602d80600a3d3981f3363d3d373d3d3d363d73000000000000000000000000)
            mstore(add(ptr, 0x14), shl(0x60, implementation))
            mstore(add(ptr, 0x28), 0x5af43d82803e903d91602b57fd5bf30000000000000000000000000000000000)
            instance := create(0, ptr, 0x37)
            mstore(0x40, add(ptr, 0x37))
        }
        require(instance != address(0), "ERC1167: create failed");
    }
```
I added a new line `mstore(0x40, add(ptr, 0x37))`.

**Comment by Amxx** [comment]
Hello @chiro-hiro, and thank you for raising this issue.

We are worried, on the other hand, that increasing the memory ptr would leak memory. It would increase the ptr, and not deallocate it, causing unnecessary gas cost, particularly if this function is called multiple times.

I'll share this with our security team.

**Comment by frangio** [comment]
From the [Solidity documentation](https://docs.soliditylang.org/en/v0.8.4/internals/layout_in_memory.html#layout-in-memory):

> There are some operations in Solidity that need a temporary memory area larger than 64 bytes and therefore will not fit into the scratch space. They will be placed where the free memory points to, but given their short lifetime, the pointer is not updated. The memory may or may not be zeroed out. Because of this, **one should not expect the free memory to point to zeroed out memory**.

**Comment by chiro-hiro** [comment]
@Amxx In the case where we're going to call this method multiple times, it's better implement a batch clone that perform clone without overwrite minimal proxy, it would be better.

@frangio Why do you close this issue? In the code was compiled by Solidity they will seek the fee pointer to new location.

**Comment by frangio** [comment]
The free memory pointer can't be expected to point to zeroed memory. The compiler doesn't guarantee that, as documented in the part I quoted above, so we don't need to maintain the guarantee either.

**Comment by chiro-hiro** [comment]
@frangio Please explain this, https://github.com/ethereum/solidity/blob/develop/libsolidity/codegen/CompilerUtils.cpp#L72-L77

The memory allocation will be performed with fetch the free memory pointer, add it with `data.length` then store the result back to the fee memory pointer.

**Comment by frangio** [comment]
In that case, they have to bump the free memory pointer because the slice of memory will be "returned" in some way to another part of the contract, so it's taking ownership of that slice. In the case pointed out by this issue, we don't need to return the memory slice, we are using it and discarding it.

**Comment by chiro-hiro** [comment]
> In that case, they have to bump the free memory pointer because the slice of memory will be "returned" in some way to another part of the contract, so it's taking ownership of that slice

Please do actual debug you would find out. it's default behavior of the compiled code with `solc`, even the data wasn't "returned" to be used somewhere else.

>  In the case pointed out by this issue, we don't need to return the memory slice, we are using it and discarding it.

Following the answer of @Amxx, this memory wouldn't be discarded.

My point is,

```solidity
function test() external {
   address a;
   a.clone();
   assembly{
       // It's still pointing to minimal proxy
       let b := mload(0x40)
       // even I do this, next 256 bits are still a mess
       mstore(b, 0)
   }
}
```
