### ISSUE TITLE
[ERC20PaymentSplitter]: Missing totalPaymentsReceived event

### ISSUE THREAD

**Issue by jveer634** [OpenZeppelin/openzeppelin-contracts#2703]
In the [ERC20PaymentSplitter](contracts/finance/PaymentSplitter.sol), there is not any event raised when all the shares of an payment are released.

I feel it will be a required feature to ensure all the payments are released.

And I couldn't see a condition that is verifying whether all the shares provided sums up to the totalamount required to pay for the contract.

**Comment by Amxx** [comment]
That is an interesting use case, but that is definitely not what our payment splitter does. 
I'll have this to our request for features, see where it could fit in the roadmap.

**Comment by frangio** [comment]
Indeed the requested feature is not related to the functionality provided by PaymentSplitter.

This sounds very niche and we haven't heard other similar requests so I will close this issue. Feel free to share more use cases if you think we should reconsider.
