### ISSUE TITLE
"File import not supported" is actually a real issue

### ISSUE THREAD

**Issue by heiho1** [OpenZeppelin/openzeppelin-contracts#2708]
I was importing Open Zeppelin contracts via the "@openzeppelin" package but VS Code fails to resolve the import.

**💻 Environment**

> uname -ar

> Darwin Jamess-MBP 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64

**📝 Details**

`  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "chai": "^4.3.4",
    "ethereum-waffle": "^3.3.0",
    "ethers": "^5.3.0",
    "hardhat": "^2.3.0"
  },
  "dependencies": {
    "@openzeppelin/contracts": "^4.1.0",
    "@openzeppelin/contracts-upgradeable": "^4.1.0",
    "@openzeppelin/hardhat-upgrades": "^1.8.2"
  }`

<img width="772" alt="Screen Shot 2021-06-05 at 10 44 24 PM" src="https://user-images.githubusercontent.com/114762/120910824-2d9ed780-c650-11eb-9f35-9059ac5b9375.png">

**🔢 Code to reproduce bug**

`//SPDX-License-Identifier: Unlicense
pragma solidity >=0.7.0 <=0.8.4;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";

contract Scam is ERC721Enumerable {
    constructor() public ERC721Enumerable("Scam", "SCAM") {

    }
}
`

**Comment by heiho1** [comment]
Note this issue was reported earlier at

https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2611

and was simply closed but I've seen it on multiple VS Code projects.  If there is some config that needs to be set to enable "@openzeppelin" then perhaps there should be something in the Open Zeppeling docs but just closing the issue doesn't help Open Zeppelin users.

**Comment by Amxx** [comment]
Hello @heiho1 

Files 
- `@openzeppelin/contracts/token/ERC721/ERC721Full.sol`
- `@openzeppelin/contracts/drafts/Counter.sol`
Do not exist in version 4.1.0

You may be looking for 
- `@openzeppelin/contracts/token/ERC721/ERC721.sol`
- `@openzeppelin/contracts/utils/Counter.sol`

**Comment by Amxx** [comment]
Please reopen an issue if that fix is not working

**Comment by T4533N** [comment]
is there any fix? I am also experiencing the same issue! :)

**Comment by Amxx** [comment]
> is there any fix? I am also experiencing the same issue! :)

https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2708#issuecomment-855661059

**Comment by cryptobabies** [comment]
npm install @openzeppelin/contracts

**Comment by Amxx** [comment]
If you have multiple folders in your workspace, the solidity package will try to resolve dependencies on the first repository...
You can fix the import issue by just reordering the folders.

**Comment by Amxx** [comment]
`@openzeppelin/contracts/drafts/Counters.sol` does not exist.

I don't know where you got that from, but the current version of Contracts is visible [here](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts).
