### ISSUE TITLE
ERC721: transferFrom with ApproveForAll emits event Approval 

### ISSUE THREAD

**Issue by kindex** [OpenZeppelin/openzeppelin-contracts#2709]
When users sets approve for all his tokens, and then some operators call transferFrom for some specific token, than Approval event is emitted.
According to ERC-721 standard Approval event should not be emitted, because approve state was not changed for specific token.
```
    /// @dev This emits when the approved address for an NFT is ***changed*** or
    ///  reaffirmed. The zero address indicates there is no approved address.
    ///  When a Transfer event emits, this also indicates that the approved
    ///  address for that NFT (if any) is reset to none.
    event Approval(address indexed _owner, address indexed _approved, uint256 indexed _tokenId);
```

I offer to change ERC721.sol function
```
    function _approve(address to, uint256 tokenId) private {
        _tokenApprovals[tokenId] = to;
        emit Approval(ERC721.ownerOf(tokenId), to, tokenId); // internal owner
    }
```
to
```
    function _approve(address to, uint256 tokenId) private {
        if (_tokenApprovals[tokenId] != to) {
            _tokenApprovals[tokenId] = to;
            emit Approval(ERC721.ownerOf(tokenId), to, tokenId); // internal owner
        }
    }
```
This will save gas on emitting and storing approve state.

**Comment by adi44** [comment]
@kindex I would like to work on this issue

**Comment by Amxx** [comment]
[From the ERC](https://eips.ethereum.org/EIPS/eip-721)

>    ```
>    /// @dev This emits when ownership of any NFT changes by any mechanism.
>    ///  This event emits when NFTs are created (`from` == 0) and destroyed
>    ///  (`to` == 0). Exception: during contract creation, any number of NFTs
>    ///  may be created and assigned without emitting Transfer. At the time of
>    ///  any transfer, the approved address for that NFT (if any) is reset to none.
>    event Transfer(address indexed _from, address indexed _to, uint256 indexed _tokenId);
>
>    /// @dev This emits when the approved address for an NFT is changed or
>    ///  reaffirmed. The zero address indicates there is no approved address.
>    ///  When a Transfer event emits, this also indicates that the approved
>    ///  address for that NFT (if any) is reset to none.
>    event Approval(address indexed _owner, address indexed _approved, uint256 indexed _tokenId);
```

What I understand here:
- If you "reaffirmed" the approval to its current value, an `Approval` transfer must be emited. 
- If you do a `transfer`, (including `minting`, `burning`, `transferFrom`, `safeTransfer`, ...
) the approval for this token must be reset to `0x0` and an `approval` event must be triggered.

IMO we follow the ERC to the letter, and you propose to deviate from it.

**Comment by Amxx** [comment]
I think the important part is:
- [Transfer event must be emitted] when ownership of any NFT changes **by any mechanism**
- At the time of **any transfer**, the approved address for that NFT (**if any**) is reset to none.
- When the approved address for an NFT is changed **or reaffirmed**.

So we should always trigger the event with only one expectation:
- when the approval is to address(0)
- when the new approval is to address(0)
- when the new approval is triggered by an event.

**Comment by Amxx** [comment]
On the other hand, the "this" keyword in 

> When a Transfer event emits, this also indicates that the approved address for that NFT (if any) is reset to none.

Might refer to the Transfer event. In that case, approvals triggered by transfers should not emit the approval events (but all calls to approve, include "reaffirmed" approval should emit it)

**Comment by Amxx** [comment]
So our code might not quite follow the ERC, but your proposed changes are not going in the right direction.

**Comment by frangio** [comment]
> According to ERC-721 standard Approval event should not be emitted, because approve state was not changed for specific token.

Even if approve state was not changed, it's not against the standard to "reaffirm" the approval. If we want to do it to save gas is a different and also valid question. I wonder how much gas it saves?

**Comment by Amxx** [comment]
Coming back to @kindex 

First of all, thank you for your issue. It really got us thinking and re-reading the ERC multiple time. We come to agree that the ERC is not clear, and that your comment is really pushing our interpretation of it.

Our analysis is:
- If someone calls `approve(...) external` multiple times, we should be emitting the event multiple times
- If `_transfer` is called, regardless of how it was called (safe/unsafe/by operator), we should reset the approval to 0. It is not clear if an `Approval` event should be emitted on top of the `Transfer` event (this is really unclear)

Your proposal would improve gas usage, but it would also break the first bullet point. It might be possible to improve event emission without breaking this, but it would require a non-trivial change of the codebase, for example changing the parameters of the internal `_approve`. This would be a breaking change for people building on top of this contract.

While we do care about gas costs, the complexity and the backward compatibility of the codebase are also very important, and we feel like it might not make sense to change things right now.

**Comment by fulldecent** [comment]
I agree that "this" in the following statement is unclear.

> When a Transfer event emits, this also indicates that the approved address for that NFT (if any) is reset to none.

Sorry, my bad.
