### ISSUE TITLE
Unnecessary inheritance of Context in ERC721Burnable contract

### ISSUE THREAD

**Issue by eatruffle** [OpenZeppelin/openzeppelin-contracts#2728]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ae69ecaf014beac078b4c21da8a83cf005713469/contracts/token/ERC721/ERC721Burnable.sol#L12

Hi,
please check ERC721 Burnable contract because Context is also inherited in ERC721 contract

**Comment by Amxx** [comment]
Hello @eatruffle 

Even when it is not strictly necessary to inherit Context when another parent already includes it, we consider it good practice to have it as the first parent of all contract that use msgSender(). This is done to ensure Context will always be the first contract in the linearized product.

It also doesn't change the produced bytecode, and has not impact on deployment cost / gas usage.
