### ISSUE TITLE
Require at end of function giving unreachable code warning

### ISSUE THREAD

**Issue by BitSigOrg** [OpenZeppelin/openzeppelin-contracts#2731]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4d0f8c1da8654a478f046ea7cf83d2166e1025af/contracts/token/ERC721/ERC721.sol#L212

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4d0f8c1da8654a478f046ea7cf83d2166e1025af/contracts/token/ERC721/ERC721.sol#L264

**Comment by Amxx** [comment]
Hello @BitSigOrg,
Can you give more details about what is issue is ?

**Comment by BitSigOrg** [comment]
Hi @Amxx,
Remix is giving me two "unreachable code" warnings. 
Line 212 in _safeTransfer has the require statement after the call to _transfer instead of before it.
Line 264 in _safeMint has the require statement after the call to _mint instead of before it.

**Comment by Amxx** [comment]
This code is actually NOT unreachable. We have test that do cover it.

[This is a bug in solidity 0.8.5. Please consider using 0.8.6 instead.](https://github.com/ethereum/solidity/releases/tag/v0.8.6)
