### ISSUE TITLE
Inheritance in ERC721 contract

### ISSUE THREAD

**Issue by eatruffle** [OpenZeppelin/openzeppelin-contracts#2735]
Hi,
please consider remove interface IERC721 from ERC721 contract, Because it is inherited in IERC721Metadata interface.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4d0f8c1da8654a478f046ea7cf83d2166e1025af/contracts/token/ERC721/ERC721.sol#L18

**Comment by Amxx** [comment]
Hello @eatruffle and thank you for this issue.

While it is true that inheriting `IERC721` is not strictly necessary, I personally think it improves clarity. Are you facing any issues with having it, that would be fixed if it was removed?
