### ISSUE TITLE
token implementation

### ISSUE THREAD

**Issue by drizieoo7** [OpenZeppelin/openzeppelin-contracts#2740]
i tried creating a token and i got a hint online and created with this scripts.

pragma solidity ^0.8.0;

import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol";

contract BiafranNation is ERC20 {
    constructor(uint256 initialSupply) public ERC20 ("BiafranNation", "Biafra"){
        _mint(msg.sender,initialSupply);

am i doing something wrong and can someone show a solution

**Comment by frangio** [comment]
Use [Contracts Wizard](https://wizard.openzeppelin.com/). If you need support, post in the [OpenZeppelin Forum](https://forum.openzeppelin.com/).
