### ISSUE TITLE
How To Specify Amount To Send With "SplitPayment"

### ISSUE THREAD

**Issue by JimLynchCodes** [OpenZeppelin/openzeppelin-contracts#2743]
Hi, I'm a bit confused by the wording of the "SplitPayment" contract and how it's supposed to be used.

I have some solidity code that makes an instance of OpenZeppelin's "SplitPayment" contract. the idea is that the owner calls the "initiateAirdrop" function and then the other users call the "pullPayment" function.

When I'm creating the SplitPayment instance I pass in an array of addresses that should receive the payments and an array with the same number of elements but all of them being the number 1 (which represents everyone having an equal share).

```
function initiateAirdrop() public {

  uint equalShares = [];

  for (i; i < attendeesCount; i++) {
    equalShares.push(1);
  }

  paymentSplitter = PaymentSplitter(attendees, equalShares);

}

function pullPayment() public {
  paymentSplitter.release(msg.sender);
}
```

the thing that I can't figure out though is how to specify how much ether you want to be given out. I would expect this to be part of the input arguments, or to somehow hook into the "Escrow" contract but I don't see anything like that in the docs

I didn't see any mention or clarification of this in the docs, but I did actually find this interesting test that OpenZep wrote for the SplitPayment contract... at the end they are expecting the end balance for the "this.contract.address" to be zero... so maybe it just splits the entire eth balance for the owner address between all the address passed in?

To me it's very confusing though to have a "payment" with no specified amount... is it assuming the entire amount in the contract address is the payment amount? Also, what happens if the amount in the contract wallet changes after the "initiateAirdrop" function has been called and after the"pullPayment" function has been called by some users but before it has been called by some other users? 🤔

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/94797978bbab60155bdf7517c31c7488f7fbe6dc/test/payment/SplitPayment.test.js#L62_L92

thanks!

**Comment by Amxx** [comment]
Hello @JimLynchCodes 

The payment splitter will split everything it ever received to the share-holders. Lets take your example with three users, Alice, Bob and Charles. All 3 have one share.

At any point in time, they can pull their share of the payment splitter's balance. Initialliy the payment splitter is empty, so they cannot reeem anything.

Imagine you then send 1eth to the payment splitter. They can decide to call the `pullPayment` function to get their share (0.3333... eth).

Now imagine I send an additional 2 eth to the same payment splitter, now everyone should be able to redeem 1 eth (the total balance received by the payment splitter is 3 eth). If they have already redeemed the first 0.333 eth, they can call `pullPayment` to get the remaining 0.666 eth. If they didn't redeemed the initial 0.333 eth, calling `pullPayment` will send them the 1 eth they are entitled to.

A PaymentSplitter contract is never done with ... it remains here in case any balance is sent to him.

**Comment by JimLynchCodes** [comment]
Thanks @Amxx!

This seems like a logical way for it to behave to me, but I still feel like "SplitPayment" is kind of a misnomer... 

it's not just splitting one payment- it's splitting ownership of the contract wallet. there is no "sale" happening for which one party is giving a payment...  🤔
