### ISSUE TITLE
private name and symbol

### ISSUE THREAD

**Issue by climb-yang** [OpenZeppelin/openzeppelin-contracts#2745]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/3ae911b4421a9f2a4f3483e6fb0a660c31f3fc54/contracts/token/ERC721/ERC721.sol#L23

private name and symbol can’t initialize settings in proxy mode, is there any good way?

**Comment by climb-yang** [comment]
Internal enough

**Comment by Amxx** [comment]
Hello @climb-yang 

When building contracts that are meant to be interacted with through a proxy, please use the "upgradeable" version of contracts:

`npm i @openzeppelin/contract-upgradeable`

You'll find an ERC721Upgradeable variant that includes an initializer that replaces the constructor and lets you set the name and symbol.

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC721/ERC721Upgradeable.sol#L41-L53

**Comment by climb-yang** [comment]
cool
