### ISSUE TITLE
Ability to Grant Third Party Spend Permissions (NFT Marketplace)

### ISSUE THREAD

**Issue by aglawson** [OpenZeppelin/openzeppelin-contracts#2746]
**🧐 Motivation**
Building an NFT Marketplace using ERC1155, I realized there is no mechanism that I've found to grant the marketplace permission to transfer the seller's NFT. I've created a workaround myself but worry about the security of it.

**📝 Details**
Resell Flow
 - Seller puts an ERC1155 NFT for sale on the marketplace, granting the marketplace permission to spend their NFT if the desired price is sent in exchange
 - Buyer requests to purchase the NFT, sending the required price
 - The marketplace transfers the NFT to the Buyer and the price to the Seller (not necessarily in that order)

Current Workaround I have
 - Seller puts ERC1155 NFT for sale on the marketplace 
 * There is a flag to check if the seller is trying to transfer an item that is for sale, and they are prevented from doing so. 

 - Buyer requests to purchase the NFT, sending the required price
 - Marketplace gives Buyer temporary approval to transfer the NFT to themselves from the seller, immediately revoking permission (with re-entrancy protections).

Any advice for how to do this better or more securely (if applicable) would be appreciated, along with future work to have a standardized way of handling this type of interaction. Thank you!

**Comment by Amxx** [comment]
Hello @aglawson,
I'm curious, isn't the `setApprovalForAll` mechanism not enough?  Its similar to ERC721's which appears to be sufficient for most usecases.

If ERC1155 doesn't include what you need, I strongly suggest you propose an evolution to this standard, which (if accepted by the community) we would then implement. I don't feel like it is our role at OpenZeppelin to modify/extend standards from our own initiative

**Comment by aglawson** [comment]
> Hello @aglawson,
> I'm curious, isn't the `setApprovalForAll` mechanism not enough? Its similar to ERC721's which appears to be sufficient for most usecases.
> 
> If ERC1155 doesn't include what you need, I strongly suggest you propose an evolution to this standard, which (if accepted by the community) we would then implement. I don't feel like it is our role at OpenZeppelin to modify/extend standards from our own initiative

Thanks for your response! I've tried using setApprovalForAll and maybe I'm just missing how to best use it but it requires the owner of the NFT call that function (for good reason) which means the Seller would have to call that function to approve the Buyer, and then the Buyer would have to call the buy function which contains the transfer function. This seemed to be inconvenient from my perspective and I had one security concern, which is that the Buyer could call the transfer function after being approved without sending the price of the item to the seller. 

Maybe I'm just missing something? 

How do I propose an evolution? 

Thank you again for your time!

**Comment by Amxx** [comment]
You indeed do not want the sender to give approval to the buyer!

What you want to do is designed a trustless smart contract that the sender can give approval to, and that will do the transfer whenever the right conditions apply (for example, when a payment is done).

You can find an example of such a contract [here](https://github.com/amxx/permit). This flavor will do the transfer based on signed messages, but you could easily add a payment mechanism.

**Comment by frangio** [comment]
I'd also mention we have given a workshop on using cryptographic tools for things related to NFTs that you might find interesting. See the recap and video on [our blog](https://blog.openzeppelin.com/workshop-recap-building-an-nft-merkle-drop/).
