### ISSUE TITLE
A fixed supply ERC20 token that use an immutable for `totalSupply`.

### ISSUE THREAD

**Issue by hrkrshnn** [OpenZeppelin/openzeppelin-contracts#2747]
**🧐 Motivation**

Some context: I was experimenting with a solidity feature that can tell users if a state variable can be moved to an immutable (thereby saving gas, if the variable is read.) I noticed that `totalSupply` in examples of ERC20 token implementations could actually be converted into an `immutable`. That is because most tokens only mint during the construction, and does not change it during runtime.

**📝 Proposal**

Have an ERC20 (and other relevant token standards) implementation where `totalSupply` is `immutable` and the value has to be set at most once during construction.

**Comments**

The main argument for converting a state variable into an immutable is the gas savings on reading from storage. However, I don't really believe that fixed supply contracts need to read its total supply on chain, making the argument less effective.

An argument against the change is code duplication in OpenZeppelin's library implementations.

So overall, I don't believe this change is useful. Regardless, I'm opening this issue, to get some feedback on the proposal.

**Comment by frangio** [comment]
I mostly agree with your arguments for and against. I would add that the `_mint` function is very useful and would not be possible to implement with immutable `totalSupply` on current Solidity versions even if it's only called during the constructor.

If someone is interested in having immutable `totalSupply` for their own project I think we would recommend they fork our implementation and make the necessary changes.

I'm wondering what ERC20 examples you used for this analysis? My intuition would be that most projects have some way of minting during runtime.

(Closing the issue as we won't implement it but please continue the conversation.)

**Comment by hrkrshnn** [comment]
> I'm wondering what ERC20 examples you used for this analysis?

They were just two random projects, not particularly interesting.

>  My intuition would be that most projects have some way of minting during runtime.

Interesting, I would have assumed the opposite, at least for simple tokens.

Anyway, I agree that it's better for such tokens to fork your contracts and change the variables to `immutable`, which would also make this compiler info about "variable can be immutable" rather useful.

**Comment by frangio** [comment]
> make this compiler info about "variable can be immutable" rather useful

It could be useful but I would be concerned if this becomes another warning that people will want to get rid of. (If this would be part of the "notices" compiler output, it's still not clear to me in what situation those would be shown to the user.)

**Comment by hrkrshnn** [comment]
We decided to go with the name info instead of notice. Hopefully tooling can offer a way to disable these messages, if it's distracting.

**Comment by frangio** [comment]
Can you link the issue for that? I have a strong feeling that these should be disabled by default and that the compiler should build for that.

**Comment by hrkrshnn** [comment]
See https://github.com/ethereum/solidity/issues/11508
