### ISSUE TITLE
MultiCall Tests:  Is an assertion missing? 

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-contracts#2753]
Maybe I don't understand exactly how this test is working, but are we missing some sort of assertion here? Is it enough to `await` this function call, if it reverts does an error message bubble up to the test? 

I would have expected an explicit test condition like  (psuedoCode) `shouldNotRevert` to be explicit that the test past.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/23869e5b2a7c6b9c3e27dee4289615b8cf50e36b/test/utils/Multicall.test.js#L34

**Comment by Amxx** [comment]
Hello @crazyrabbitLTC 

If any of the call reverts, then the entire batch of calls does revert.

This is tested between lines 37 and 56 of `test/utils/Multicall.test.js`

**Comment by crazyrabbitLTC** [comment]
@Amxx I understand the revert part, what I'm confused about is does the javascript test notice the revert? 

```  
it('returns an array with the result of each call', async function () {
    const MulticallTest = artifacts.require('MulticallTest');
    const multicallTest = await MulticallTest.new({ from: deployer });
    await this.multicallToken.transfer(multicallTest.address, amount, { from: deployer });
    expect(await this.multicallToken.balanceOf(multicallTest.address)).to.be.bignumber.equal(new BN(amount));

    const recipients = [alice, bob];
    const amounts = [amount / 2, amount / 3].map(n => new BN(n));

    await multicallTest.testReturnValues(this.multicallToken.address, recipients, amounts);
  });
```

What I mentally would expect would happen is that the `await` would wait for the tx, which would revery, but my test reporter would tell me that the test passed since I'm not testing to see the tx reverted or failed. Am I understanding what would happen in this test incorrectly? Does just having a reverted transaction cause the javascript test to fail?

**Comment by Amxx** [comment]
`multicallTest.testReturnValues` does a call to `multicallToken.multicall` under the hood. If the `multicall` reverts (solidity), then `testReturnValues` transaction will also fail (solidity), which will then cause the js promise to revert.

When you await a promise that reverts, the revert arguments are thrown.
