### ISSUE TITLE
TypeError: Member "toUint224" not found or not visible in type(library SafeCastUpgradeable)

### ISSUE THREAD

**Issue by noobshow** [OpenZeppelin/openzeppelin-contracts#2756]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/cdb3484988e36232f59ddd2576e11761d65122c9/contracts/token/ERC20/extensions/draft-ERC20Votes.sol#L146

Error using SafeCastUpgradeable with the line above, no complains about  the line below even though they import from the same library
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/cdb3484988e36232f59ddd2576e11761d65122c9/contracts/token/ERC20/extensions/draft-ERC20Votes.sol#L149

Error: TypeError: Member "toUint224" not found or not visible after argument-dependent lookup in type(library SafeCastUpgradeable)

**Comment by Amxx** [comment]
Hello @noobshow 

Could you please give details about the environment that triggers this issue. This piece of code is working in all our automated tests. I strongly advice you have a look at [this](https://stackoverflow.com/help/how-to-ask) when raising an issue.

**Comment by noobshow** [comment]
I'm sorry,
I thought it must have been a general issue that's why I left out details, coz I didn't even change anything in the draft-ERC20Votes file when I did compile... 

I will try replicating it and get back with details or something to check with...

Compiled using 0.8.4

**Comment by noobshow** [comment]
After running some tests this afternoon, i figured the issue happens only when using SafeCastUpgradeable as it does not have `toUint224` method... Is there any workaround available aside copying the `contracts` implementation somewhere in my project and depend on it instead?

**Comment by frangio** [comment]
@noobshow `toUint224` is [included](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.2.0/contracts/utils/math/SafeCastUpgradeable.sol#L31) in the latest release of `@openzeppelin/contracts-upgradeable`. Should work once you update your dependency.
