### ISSUE TITLE
URI Storage should be included in ERC721 default

### ISSUE THREAD

**Issue by vancedy105** [OpenZeppelin/openzeppelin-contracts#2758]
**🧐 Motivation**

I think that tokenURI should be included as default, instead of having to implement extensions. 

What is the point of having such a complicated file structure?

**Comment by fulldecent** [comment]
Because that's how the standard is written. https://eips.ethereum.org/EIPS/eip-721

**Comment by frangio** [comment]
`tokenURI` is in fact included by default, but using a base URI + token URI system, the point of which is to be more gas efficient. ERC721URIStorage allows setting a custom URI for each NFT by keeping them in storage, which costs more.
