### ISSUE TITLE
Will this work for an upgradeable target? 

### ISSUE THREAD

**Issue by noobshow** [OpenZeppelin/openzeppelin-contracts#2760]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/23869e5b2a7c6b9c3e27dee4289615b8cf50e36b/contracts/governance/TimelockController.sol#L277

That line issues direct call to the target, will that work for a proxy target too?

https://github.com/aave/governance-v2/blob/f16655ae3d91d6043c5e345f59c0111d8207771b/contracts/governance/ExecutorWithTimelock.sol#L205-L212 

Just comparing both implementation, seeing this had options for delegatecall too, especially considering that they use upgradeable contracts.

Does it matter someway for me?
Should delegatecall be an option?

**Comment by noobshow** [comment]
https://etherscan.io/tx/0x60a3eb593e1e69865f643e4353ed37af1062a0c6bb453e773e55acccd743c90b#eventlog

Check this transaction Log, the 1st ExecutedAction Event has `withDelegatecall` set to `true` and it was targeting an upgradeable contract(I think)

**Comment by Amxx** [comment]
Hello @noobshow,

Proxies are designed to be transparent, so you can do a call to them, and it should behave just as expected. 
Doing a delegate call to a proxy would however not work.

I encourage you to do some testing, and to learn about delegate calls

**Comment by noobshow** [comment]
> Hello @noobshow,
> 
> Proxies are designed to be transparent, so you can do a call to them, and it should behave just as expected.
> Doing a delegate call to a proxy would however not work.
> 
> I encourage you to do some testing, and to learn about delegate calls

I figured that out too with other governance implementations, I'm not just sure why that transaction have to be delegatecall'd to and i don't think it is necessary seriously for my implementation...

Thanks @Amxx

**Comment by Amxx** [comment]
There are cases where doing a delegatecall from a wallet/timelock/governance contract can enable new usecases ... but it is very dangerous and should be used with extreme caution.
