### ISSUE TITLE
Shouldn't governance TimelockController have maxDelay?

### ISSUE THREAD

**Issue by noobshow** [OpenZeppelin/openzeppelin-contracts#2761]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/6d97f0919547df11be9443b54af2d90631eaa733/contracts/governance/TimelockController.sol#L346

I think since there's a lower limit, there should also be a higher limit of delay allowed in governance seeing that updateDelay isn't public or internally overridable to prevent such delays to be validated.

Almost all governance controllers have a max delay to avoid queuing up execution for eternity, especially when such votes doesn't make any sense anymore...

Can i make such feature-request to avoid linking the file directly from my project folder?

Thanks

**Comment by noobshow** [comment]
A suggestion would be to allow the maxDelay be set in the constructor only and nowhere else so it can't be modified to allow lax delay...

I think the major reason some governance protocol put maxDelay and gracePeriod there is to make sure only proposals that have been implemented or has viable research and implementations come to vote...

**Comment by Amxx** [comment]
Hello @noobshow 

I max delay is an additional feature, which some people might need while other don't. We try to be unopinionated, and not to had features that are not essentials and can easily be added on top of our contract.

If you need such a feature, I believe you should write you own 

```
TimelockControllerWithMaxDelay is TimelockController {
    uint256 private _maxDelay;
    
    constructor(
        uint256 minDelay,
        uint256 maxDelay,
        address[] memory proposers,
        address[] memory executors
    ) TimelockController(minDelay, proposers, executors) {
        _maxDelay = maxDelay;
    }

    function schedule(
        address target,
        uint256 value,
        bytes calldata data,
        bytes32 predecessor,
        bytes32 salt,
        uint256 delay
    ) public virtual override {
        require(delay <= _maxDelay);
        super.schedule(target, value, data, predecessor, salt, delay);
    }
    
    function scheduleBatch(
        address[] calldata targets,
        uint256[] calldata values,
        bytes[] calldata datas,
        bytes32 predecessor,
        bytes32 salt,
        uint256 delay
    ) public virtual override {
        require(delay <= _maxDelay);
        super.scheduleBatch(targets, values, datas, predecessor, salt, delay);
    }
}
```

**Comment by noobshow** [comment]
Hi @Amxx,
I believe you got my intentions wrong, i wasn't referring to the `schedule()` delay, i was referring to the delay set here :
```solidity
	function updateDelay(uint256 newDelay) external virtual {
		require(
			msg.sender == address(this),
			"TimelockController: caller must be timelock"
		);
		require(
			newDelay >= _minDelay,
			"TimelockController::setDelay: delay must exceed minimum delay."
		);
		require(
			newDelay <= _maxDelay,
			"TimelockController::setDelay: delay must not exceed maximum delay."
		);
		emit MinDelayChange(_minDelay, newDelay);
		_minDelay = newDelay;
	}
```
such that the delay won't be set too lax or too short...

**Comment by Amxx** [comment]
Sorry I got the details of your request wrong, but I'll have the same answer. This can easily be added by overriding `updateDelay`

```
function updateDelay(uint256 newDelay) external virtual {
    require(newDelay <= _maxDelay);
    super.updateDelay(newDelay);
}
```

**Comment by noobshow** [comment]
Thanks for the snippet, you tested it?
Was getting `Member "updateDelay" not found or not visible after argument-dependent lookup in type(contract super Timelock)`.

![image](https://user-images.githubusercontent.com/7571856/125209535-445ccd80-e291-11eb-9a6d-1eb0b764af5a.png)

I'm compiling with 0.8.4

**Comment by frangio** [comment]
@noobshow Yes, unfortunately this is due to `updateDelay` being external. We will have to make it public in the next release. Sorry about that.

As a workaround, it's not ideal but you can define your own variable and override both `updateDelay` **and `getMinDelay`** to use your new variable. This will work because you won't need to call the `super` functions and the contract will work correctly.

**Comment by noobshow** [comment]
Nope, it won't work even without super because _minDelay is private, so the only way to use the plugin now is by pulling to my project folder...
updateDelay is external and _minDelay is private, so not accessible from outside...

**Comment by noobshow** [comment]
I'm watching out for the next release too, probably will be okay with my modification 😄

**Comment by frangio** [comment]
No what I said is definitely possible, I suggested to ignore the `_minDelay` variable and override `getMinDelay` to use a different variable that you declare in a child contract.

```solidity
import "@openzeppelin/contracts/governance/TimelockController.sol";

contract TC is TimelockController {
    constructor(
        uint256 minDelay,
        address[] memory proposers,
        address[] memory executors
    ) TimelockController(minDelay, proposers, executors) {
        _minDelay = minDelay;
    }

    uint _minDelay;
    
    function getMinDelay() public view override returns (uint) {
        return _minDelay;
    }
    
    function updateDelay(uint newDelay) external override {
        require(msg.sender == address(this));
        emit MinDelayChange(_minDelay, newDelay);
        _minDelay = newDelay;
    }
}
```

**Comment by noobshow** [comment]
hmm, i should try this... Thanks for the time spent

**Comment by noobshow** [comment]
> No what I said is definitely possible, I suggested to ignore the `_minDelay` variable and override `getMinDelay` to use a different variable that you declare in a child contract.
> 
> ```solidity
> import "@openzeppelin/contracts/governance/TimelockController.sol";
> 
> contract TC is TimelockController {
>     constructor(
>         uint256 minDelay,
>         address[] memory proposers,
>         address[] memory executors
>     ) TimelockController(minDelay, proposers, executors) {
>         _minDelay = minDelay;
>     }
> 
>     uint _minDelay;
>     
>     function getMinDelay() public view override returns (uint) {
>         return _minDelay;
>     }
>     
>     function updateDelay(uint newDelay) external override {
>         require(msg.sender == address(this));
>         emit MinDelayChange(_minDelay, newDelay);
>         _minDelay = newDelay;
>     }
> }
> ```

Thanks, it works... 
Just figured there's no direct use of `_minDelay` internally, `getMinDelay` was used instead.
