### ISSUE TITLE
Two package.json in project lack sufficient distinguishing documentation

### ISSUE THREAD

**Issue by fulldecent** [OpenZeppelin/openzeppelin-contracts#2771]
The project includes /package.json and /contracts/package.json and publishes `@openzeppelin/contracts` and `openzeppelin-solidity` respectively. I'm sure there is some good, well-thought-out reason for this.

The two files contribute the same `description` of `Secure Smart Contract library for Solidity` and look mostly the same inside.

To improve maintainability of these two files, some note should be added inside (e.g. `"note":`) each describing the difference between the two files or where responsibility of one ends and the other starts.

**Comment by Amxx** [comment]
Hello @fulldecent 

Both packages are identical. We keep the two for backward compatibility reasons. `openzeppelin-solidity` is the old name, but we want to continue publishing new version using that name, because some people will look at that. `@openzeppelin/contracts` is the new name, that we now advertise.

**Comment by frangio** [comment]
We want the packages to be identical. The difference is the deprecation notice for [`openzeppelin-solidity`](https://www.npmjs.com/package/openzeppelin-solidity), which gets removed by npm every time we do a new release... I'll make sure this stays up.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/commit/466cf05912d393c06e0930da9ddc1a9ac01e430e.

**Comment by fulldecent** [comment]
The two files are not currently identical

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/package.json
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/package.json

Shall I update one to equal the other? Which one shall keep?

**Comment by frangio** [comment]
I did not mean identical in every way... The files cannot be identical. The contracts on npm are the same in both packages. There are differences that are not of substance.

Please don't make any changes to the package.json files.
