### ISSUE TITLE
Can't verify contract on bsc scan, help me how the verify contract

### ISSUE THREAD

**Issue by Prathapachar** [OpenZeppelin/openzeppelin-contracts#2773]
**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by 5hanth** [comment]
@Prathapachar if you use hardhat, `hh verify --network mainnet proxyaddress` and then `hh verify --network mainnet implementationAddress`

**Comment by Prathapachar** [comment]
> @Prathapachar if you use hardhat, `hh verify --network mainnet proxyaddress` and then `hh verify --network mainnet implementationAddress`

Why,I verify contract in testnet, can't verify test ha?

**Comment by frangio** [comment]
See [Verify ERC20 token on Etherscan that was deployed through Remix: Step by Step Guide](https://forum.openzeppelin.com/t/verify-erc20-token-on-etherscan-that-was-deployed-through-remix-step-by-step-guide/9051)

Please use the forum for support requests.
