### ISSUE TITLE
My solidity contract fail to deploy for ERC20

### ISSUE THREAD

**Issue by joymukherjee82** [OpenZeppelin/openzeppelin-contracts#2783]
Hi All,

We have developed/modified a few solidity contracts.
Those are properly deployed in 
Local Ganache dev
Rinkeby Testnet

Now we have created an environment with ethereum and Kubernetes.
Where geth is running properly inside the pod, we can check
the accounts and make transactions between accounts.

But when try to deploy our solidity contract to this environment
then it is failing with this error.

1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:   Deployment Failed 

"Migrations" hit an invalid opcode while deploying. Try:
   * Verifying that your constructor params satisfy all assert conditions.
   * Verifying your constructor code doesn't access an array out of bounds.
   * Adding reason strings to your assert statements.

Please let me know if any further information required.
It will great help if you can share some guidance.
For ethereum and kubernetes we use this
https://github.com/kairen/kubereum

My codebase link
https://drive.google.com/file/d/1KbyMXchNFlghO0NZ6wFRfUhPMLeyS9aB/view?usp=sharing

**Comment by frangio** [comment]
Use [Hardhat](https://hardhat.org) for testing instead of Geth, you will get vastly better error messages. For any further support requests please use the [OpenZeppelin Forum](https://forum.openzeppelin.com).
