### ISSUE TITLE
ERC721: static call for ownerOf function

### ISSUE THREAD

**Issue by fulldecent** [OpenZeppelin/openzeppelin-contracts#2784]
In the ERC721 contract, the `ownerOf` function is defined as `virtual` which allows implementations to change this function.

But invocations of this function do NOT call with virtual dispatch (i.e. they use `ERC721.ownerOf`).

This creates the possibility somebody will override it and it will stop working.

Proposed solutions:

1. Remove `virtual`—because the ownership is tightly coupled with other implementation details. This is a "breaking change", whatever, file this under "Will say's it's okay".
2. Use virtual dispatch (`s/ERC721\.//g`)—this might be inconsistent and confusing

---

P.S., in the past, other ERC721 functions were called without virtual dispatch and it created a security problem risk. This affects past versions of OZC. I'm not sure if those versions are still supported (see https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2759). I have seen an implementation in the wild that is vulnerable as a result of this.

**Comment by frangio** [comment]
Please see https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2154 for extensive prior discussion, in particular https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2154#issuecomment-767781070:

>For example, overriding `ERC20.balanceOf` does not guarantee that that balance is available for transferring. However, it will generaly be possible to obtain the desired behavior by overriding other functions in the contract, in this case `ERC20._transfer`. Understand that this limitation was necessary to keep the contracts simple and consistent, but it means that the responsibility to ensure correctness when functions are overriden will be on the users and not on the OpenZeppelin maintainers. People who wish to override should consult the source code to fully understand the impact it will have, and should consider whether they need to override additional functions to achieve the desired behavior.



> in the past, other ERC721 functions were called without virtual dispatch and it created a security problem risk. This affects past versions of OZC

Can you please give detail about this?

**Comment by fulldecent** [comment]
I agree that providing this power is useful. And at the same time, of course, we are making a risk of somebody doing something wrong.

Maybe a nice way to handle this is to provide "subclassing" notes everywhere we allow subclassing.

A good example of developer subclassing notes for an objection-oriented language is the documentation for Swift. Please search the web with `"Subclassing Notes" site:https://developer.apple.com/documentation` to see how this looks.

---

I sent detail to you by email. I can create a new issue for that when needed.

**Comment by frangio** [comment]
Closing this issue for reasons explained in my previous comment: "The burden of guaranteeing internal consistency [when ownerOf is overriden] is moved to the developer who wishes to override in these niche cases."

The specific case of `isApprovedForAll` in Contracts 3.x is tracked in https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2792.

**Comment by matthiasgeihs** [comment]
@frangio

I came upon this issue when dealing with the following: I'd like to have an ERC721 contract where initially a fixed number (100+) of tokens are assigned to the contract owner. To do this in a gas-efficient way, the idea is to override `ownerOf` such that it returns the contract owner in case the token is not in `_owners`.

Now this does not work because the OZC `ERC721` implementation uses `ERC721.ownerOf` internally, and not `ownerOf` (the overridden function).

What's the purpose of making `ownerOf` overridable when, at the same time, the core contract is forced to use the original implementation?

**Comment by fulldecent** [comment]
@matthiasgeihs Thank you for checking in. There are some implementations you can study which are doing that approach:

- [Su Squares](https://github.com/su-squares/ethereum-contract/blob/master/contracts/ERC721.sol) implements where the first 10,000 NFT are transferred to the contract owner at time of deployment.
- [ERC721a](https://www.erc721a.org/) includes a batch transfer function you can use at time of contract deployment.

You can use both of those ideas while still employing OpenZeppelin Contracts, it's just nice to see how others have done it.

Specifically regarding OZC and your proposed implementation, please ensure you are testing that `YourContract.ownerOf` (the external call) will throw for tokens that have not been minted. (Unless you are minting exactly 2^256 tokens at deployment.) This is a requirement of ERC-721.

If you would like to review your work together live, you can join my weekly call, please see https://phor.net/#hour, follow, and add yourself into the schedule.

Based on what we learn, if we find anything that affects OZC and specifically the `virtual` part of `ownerOf` subclassing, then we can report back our findings here.

**Comment by frangio** [comment]
@matthiasgeihs For efficient batch minting please see our new [ERC721Consecutive](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.8.0-rc.2/contracts/token/ERC721/extensions/ERC721Consecutive.sol) contract. It is included in 4.8, to be released next week.

**Comment by fulldecent** [comment]
Looks good. Thank you @frangio for restricting it to the constructor not just documenting that caveat!

**Comment by matthiasgeihs** [comment]
Thanks @frangio for pointing out ERC721Consecutive. That was exactly what I needed. (Looks like you have included the necessary modification to ERC721 in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3311.)
