### ISSUE TITLE
"https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol 1" not found: File import callback not supported

### ISSUE THREAD

**Issue by Prathapachar** [OpenZeppelin/openzeppelin-contracts#2785]
![Uploading gh.jpg…]()

**Comment by Prathapachar** [comment]
"https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol 1" not found: File import callback not supported
![gh](https://user-images.githubusercontent.com/83361470/126770734-f58d4865-bbfb-4b14-85f0-0b1d1e6afc9e.jpg)

**Comment by Amxx** [comment]
Hello @Prathapachar 

Please, when raising an issue on a repo, try to be nice to the reader. [I would strongly encourage you to read this](https://stackoverflow.com/help/how-to-ask) ... And I'm pretty sure you wouldn't just send a picture of you screen to a colleague without any additional info.

That being said, you issue is that Etherscan doesn't resolve dependencies like that. You would either have to flatten your source code in a single file or use the multifile option. Remix does come with a verify plugin that you can use to automate that.
