### ISSUE TITLE
Return the current `_value` when incrementing or decrementing a `Counter`

### ISSUE THREAD

**Issue by hexcowboy** [OpenZeppelin/openzeppelin-contracts#2786]
**🧐 Motivation**
Instead of running a call to `counter.increment()` or `counter.decrement()` and then a subsequent call to `counter.current()`, wouldn't it be simpler to just return the count along with the relative call?

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Counters.sol

**📝 Details**

Currently the interface is:

```solidity
current(struct Counters.Counter counter) → uint256 internal
increment(struct Counters.Counter counter) internal
decrement(struct Counters.Counter counter) internal
```

but I'm proposing it's changed to

```solidity
current(struct Counters.Counter counter) → uint256 internal
increment(struct Counters.Counter counter) → uint256 internal
decrement(struct Counters.Counter counter) → uint256 internal
```
This could be implemented like so:

```diff
    function increment(Counter storage counter) internal returns(uint256) {
        unchecked {
            counter._value += 1;
        }
+        return counter._value;
    }
```

**Comment by Amxx** [comment]
Hello @hexcowboy and thank you for raising that issue.

This was already discussed as part of #2599. At the time we didn't feel comfortable with the proposition of the PR with added 2 functions with close names. Your approach seems more conservative and is backward compatible.

**Comment by frangio** [comment]
My issue with #2599 was that it is not obvious in the interface whether the return value is pre or post increment. I would oppose this suggestion for the same reason.

**Comment by tab00** [comment]
Intuitively we'd expect the return value to be the post-incremented one, i.e. the end result of calling the `counter.increment()` function.

**Comment by frangio** [comment]
The problem is that often that's not really the useful value. Imagine that your counter is a nonce, you generally want it to start at 0, so you'd want the pre-increment value.

**Comment by frangio** [comment]
I support something _like this_, but `returnAndIncrement` is a confusing name, as "returning" is always the last thing done in a function. 

We should brainstorm other options. What about `getCurrentAndIncrement` together with `incrementAndGet`? Hoping to hear other options as well though.

**Comment by frangio** [comment]
A way to sidestep this issue would be to return both pre and post values from the function:

```
function increment(Counter storage counter) returns (uint previousValue, uint currentValue);
```

Although this sidesteps the issue of naming, it has an issue that return parameters are not really named so the callee needs to know the order. I'd imagine `previous, current` is the intuitive order though.

**Comment by elawbek** [comment]
Maybe do it as in [\_useNonce](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/draft-ERC20Permit.sol#L90)?

Something like: `useCurrentIncrementValue` & `useNextIncrementValue` and `useCurrentDecrementValue` & `useNextDecrementValue`.

or an abridged version: `useCurrentInc` & `useNextInc` and `useCurrentDec` & `useNextDec`.

Sorry, I'm not very good at naming. I think your "`getCurrentAndIncrement` together with `incrementAndGet`" are better than my suggestion.

About your suggestion about returning both values from the increment and decrement functions I think is a good solution, but I would be confused about what I should get from the functions, i.e.you suggest calling them previousValue and currentValue, but I intuitively think that the current value is the one before the increment/decrement, and what comes after is the next value. I think in this case, universality can be bad for the clarity of what the user of these functions should get.

**Comment by frangio** [comment]
What if we named the return values `(previousValue, nextValue)`?

**Comment by elawbek** [comment]
I think this is a good choice: functions will return data and developers can choose the value they need for their current purposes.

But can you answer why you don't want to create a separate function for each case?

**Comment by frangio** [comment]
I'm ok with creating separate functions, we just need good names for them. I don't think the alternatives proposed so far are good enough. Maybe we should just go with `preIncrement` and `postIncrement`.

**Comment by elawbek** [comment]
`preIncrement` and `postIncrement` looks nice, but does not make it clear by itself what exactly they do.
As I wrote before, I'm not very good at naming functions. I can only suggest something like:
`getAndIncrementValue`, `incrementAndGetValue`, `getAndDecrementValue`, `decrementAndGetValue`.

**Comment by frangio** [comment]
> maybe `getAndIncrement`, `incrementAndGet`, `getAndDecrement`, `decrementAndGet`.

Let's go with this. Feel free to submit a PR.

**Comment by frangio** [comment]
Counters are being removed in 5.0.
