### ISSUE TITLE
ERC20Permit permit implementation ought to be secure without OZ ERC20 implementation

### ISSUE THREAD

**Issue by prestwich** [OpenZeppelin/openzeppelin-contracts#2799]
the current `permit` implementation does not correctly validate signatures. It relies on `_approve` implementation details to cover up the incomplete validation. Anyone copy+pasting the implementation or overriding the `_approve` function will accidentally allow `permit`s with invalid signatures

recommendation:
add a `recoveredSig != address(0)` check to the permit function. Accept that this is redundant

**Comment by Amxx** [comment]
Hello @prestwich,
I'm not sure I understand how permit doesn't validate signatures correctly and where the security issue might be. 

Could you provide example of inputs that would not be verified correctly?

**Comment by frangio** [comment]
`ECDSA.recover` already validates that the recovered address is not 0. Is that the issue you were pointing out? If so, I think this issue can be closed.
