### ISSUE TITLE
ERC721: testing "return empty string by default" is an opinionated behavior

### ISSUE THREAD

**Issue by fulldecent** [OpenZeppelin/openzeppelin-contracts#2804]
The test: 

  - Contract: ERC721
     -  metadata
         - token URI
           - return empty string by default:

is checking for an opinionated behavior.

Contract ERC721 is supposed to be unopinionated as per https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/token/ERC721.

Such a behavior can be tested in a "ERC721Mock" test. But this should not be part of the broad ERC721.behavior.js because someone may very reasonably implement ERC-721 by setting the base URI inside the constructor and that would fail the broad unopinionated test.

**Comment by Amxx** [comment]
Hello @fulldecent 

While I 100% support that contracts should not be opinionated in their design (or as little as possible), I don't think this is true of the tests. The tests are for internal usage, and are not published as part of the package. If someone wants to copy tests to its own repo, he is free to do so, but that is not a usecase we advertize. I'm not sure we want to do the extra mile to ensure such reusability. After all, if some copies the tests, he/she will have to design additional ones for all the additional logic he/she puts into the contracts ... should it shouldn't be an issue to modify the test slightly to reflect its contracts specificities.

**Comment by fulldecent** [comment]
My experience has been that the tests are entirely reusable and I opinionated (except for this thing I found).

I have worked on a ERC-721 implementation that overrides *every* overridable function and the ERC721.behavior test suite still passed. (Minus that one)

And yes you are correct, that additional proprietary behavior should be tested as using new tests.

**Comment by frangio** [comment]
These tests are not at all generic, given they use for example a custom `setBaseURI` function that is not available in the core unopinionated ERC721. Closing since it's not a goal for these tests to be reusable.
