### ISSUE TITLE
ERC20 - transfer equivalence with transferFrom using address(this) as from

### ISSUE THREAD

**Issue by hasandogu** [OpenZeppelin/openzeppelin-contracts#2817]
The call to `IERC20(token).safeTransferFrom(**address(this)**, to, value)`  and `IERC20(token).safeTransferFrom(to, value)` are not equivalent. 

**💻 Environment**

Truffle

**📝 Details**

OpenZeppelin 4.2.0

**🔢 Code to reproduce bug**

Hi there, thank you for the amazing work with these contracts. 

We have figured that if we use `IERC20(token).transferFrom(address(this), to, value)`  instead of  `IERC20(token).transfer(to, value)` the transfer goes through the allowance flow and we receive the error. 

`ERC20: transfer amount exceeds allowance.`

Shouldn't these two calls be equivalent and that they should both succeed (without the need to provide an explicit allowance/approval provided for address(this)?

ERC721 use function `_isApprovedOrOwner` or ERC1155 uses `isApprovedForAll`. Would it not be better to use a similar approach for ERC20 here so that transferFrom (with address(this) as from address) is equivalent to transfer()?

Our current solution is to do the check externally:

```
    if(from == address(this)) {
        IERC20(token).safeTransfer(to, asset.value);
    }
    else {
        IERC20(token).safeTransferFrom(from, to, asset.value);                
    }
```

Many thanks in advance.

**Comment by Amxx** [comment]
Hello @hasandogu

ERC20's `transfer` and `transferFrom` both follow the ERC20 standard. This standard includes:

> The (`transferFrom`) function SHOULD throw unless the _from account has deliberately authorized the sender of the message via some mechanism.

The standard wording is SHOULD, and not MUST, so I guess allowing the owner to use `transferFrom` from itself, even without approval set, would be somehow acceptable. However this is a behavior most token does not implement, and I think we should stick to the most commonly accepted approach.
