### ISSUE TITLE
Cryptography API Demo Function Fails

### ISSUE THREAD

**Issue by nickjuntilla** [OpenZeppelin/openzeppelin-contracts#2818]
The demo function from this page:

https://docs.openzeppelin.com/contracts/4.x/utilities#api:cryptography.adoc#ECDSA

using this code:

```
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
...

using ECDSA for bytes32;

function _verify(bytes32 data, address account, bytes32 signature) pure public returns (bool) {
        return keccak256(data)
            .toEthSignedMessageHash()
            .recover(signature) == account;
    }
```

Fails with this error:

```
TypeError: Member "recover" not found or not visible after argument-dependent lookup in bytes32.
  --> contracts/...:51:16:
   |
51 |         return keccak256(data)
   |                ^ (Relevant source part starts here and spans across multiple lines).
```

I just added the signature to the _verify parameters and public otherwise it wouldn't work. I'm using 
"@openzeppelin/contracts": "^4.0.0",

**Comment by julianmrodri** [comment]
Created a PR to update this example. I feel we should add the `signature` as a parameter as it is a key component in the verification process. Regarding visibility I think it is better to be explicit so I added the `internal` modifier (considering the function is named `_verify` I think its the best option). But feel free to update it or let me know and can change it. Thanks!
