### ISSUE TITLE
ERC-721 implementation allows zero address to freely transfer tokens.

### ISSUE THREAD

**Issue by marcoatpaladin** [OpenZeppelin/openzeppelin-contracts#2828]
The ERC-721 implementation lacks the zero address requirements that are present in ERC-20. This allows the zero address to theoretically transfer any token at will, since it has infinite approval over any token that is not explicitly approved to a different address.

All though this is a hyper-theoretical vector, it is inconsistent with other OpenZeppelin standards.

**💻 Environment**
[ERC721@4e2641a9151fcbb0cd59126a52040fea68ecb807](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1baa009266425400f289449f0a373fa60e23ecae/contracts/token/ERC721/ERC721.sol)

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1baa009266425400f289449f0a373fa60e23ecae/contracts/token/ERC721/ERC721.sol#L152-L161

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1baa009266425400f289449f0a373fa60e23ecae/contracts/token/ERC721/ERC721.sol#L234-L238

**Comment by frangio** [comment]
It is unfortunately very indirect in the code, but `ownerOf` reverts if the owner is zero, so zero can't transfer anything.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/56d4063e928d963a96e376f2dc71831cfecf5214/contracts/token/ERC721/ERC721.sol#L71

**Comment by marcoatpaladin** [comment]
**Request for re-open**
Thank you for your reply, @frangio.

We're requesting a re-open since the issue in question is related to the zero address being approved by default, and not being the owner by default. Since the zero address is not the owner the mentioned ownership check does not apply.

**Comment by Amxx** [comment]
@marcoatpaladin I think one of the assumptions we make is that the address 0 will never send any transaction. What makes you think this assumption is not going to hold.

**Comment by JorgeAtPaladin** [comment]
Nothing much except some really black-swan events. It was more an inconsistency with other components of the OpenZeppelin suite, specifically the ERC-20 implementation where this non-zero check is made consistently.
