### ISSUE TITLE
How to verify on Etherscan

### ISSUE THREAD

**Issue by ATG2021** [OpenZeppelin/openzeppelin-contracts#2829]
Hello, we are newbies, but we managed to create our own token, while using a script that included the import of the openzeppelin ERC20 contract. We just adjusted our details, and it created it worked so far.

But now we are facing on Etherscan the problem, that we can't verify the contract, because of the imported file.
Error message:

**Error! Unable to generate Contract ByteCode and ABI (General Exception, unable to get compiled [bytecode])**

Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: " to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> myc

ParserError: Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol" not found: File import callback not supported
 --> myc:3:1:
  |
3 | import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol"
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I tried to search in the forum and internet myself, but didn't find a solution.

Can you please tell me how to fix it or where I can find an article, which already covered this problem and came up with a working solution?

It took us a week to come to this step, we spend for the contract around 200$ - please help that it was not done for nothing.

Thanks a lot for your time and knowledge in advance.

**Comment by frangio** [comment]
Please use the forum for this kind of support question, as opposed to GitHub issues. Follow the guide [Verify ERC20 token on Etherscan that was deployed through Remix: Step by Step Guide](https://forum.openzeppelin.com/t/verify-erc20-token-on-etherscan-that-was-deployed-through-remix-step-by-step-guide/9051).

However, you made the mistake of using an import from the `master` branch of the repository, and this can make deployments not reproducible. If you still have the imported files cached on Remix you should be able to verify anyway.

**Comment by ATG2021** [comment]
Hello frangio, thanks a lot for your comment, but I deleted the file on Remix by accident.
I am in the process to create a new contract - only one question I have now: does the new file name and the contract name in the code have to match? 
I mean if I chose the token name: altogether - do I have to name the file name in remix at start as well: altogether.sol
Someone sent me a script - I can insert it in Remix, but I still have to chose the file name, before I can use the script.
I don't want to spend another 200$ by making small mistake..

**Comment by frangio** [comment]
File name doesn't have to match. Contract name might need to match.

Deploy to testnet first and practice verifying the contract there so you avoid wasting hundreds of dollars.

See the [new post](https://forum.openzeppelin.com/t/how-to-verify-a-contract-on-etherscan-bscscan-polygonscan/14225) I've put up on the forum. It still doesn't cover everything though. If you have any other questions please use the forum.
