### ISSUE TITLE
Meta Issue: 4.4

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#2836]
**Candidates:**

- #2568
- #2748 
- #2858
- #2834
- #2852
- #2865
- #2841
- **Governor improvements**
  - #2849 
  - https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2892
  - https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2904
  - https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2849
    - [x] Changelog entry
- ~#2686~ → moved to 4.5

**Comment by k06a** [comment]
Do you consider index recovery from #2815 or non-ordered merkle tree proof validation?

**Comment by sabotagebeats** [comment]
@Amxx let me know if i can help with #2701 and #2762

**Comment by Amxx** [comment]
> @Amxx let me know if i can help with #2701 and #2762

You can track the work in progress on this branch: https://github.com/Amxx/openzeppelin-contracts/tree/feature/paymentsplitter/contracts/finance

I understand your desire to see this issue address, but we want to make sure we do it right. In particular, there are a lot of challenges to work around, and difficult choices to make. 

In particular, we would like
- A single contract supporting multiple assets tokens.
- The ability to reallocate payment shares dynamically, with moving of shares only affecting future payments.

Both feature are easilisy implementable alone, but the combination feels insolvable.

**Comment by sabotagebeats** [comment]
> In particular, we would like
> - A single contract supporting multiple assets tokens.
This one seems pretty easy, the code I added in the comment does this. If there is a registration array, multiple tokens could be rescued in one call by looping the array. 

> - The ability to reallocate payment shares dynamically, with moving of shares only affecting future payments.
This can be accomplished if the reallocation calls release on all ether in the contract, and rescue all tokens, before the reallocation occurs.  The addresses of the tokens to be released must be added in a array somewhere I'm the contract. There's not a way for the contract to be able to pull all the tokens balances that it holds that I know of, without calling balances on the original contracts, which it won't know about unless they're added to a registry array. Unless you know a better way?

**Comment by frangio** [comment]
The first release candidate has been released. It will be at least 3 weeks before the final release is published. We will be announcing more details about the timeline later.

**Comment by whitecow** [comment]
Any update on release date?

**Comment by Amxx** [comment]
@whitecow 4.4 release candidate is currently available. Actual release should be out in 1 to 2 weeks

**Comment by whitecow** [comment]
@Amxx Thank you. Is this how I should use the release candidate?

import @openzeppelin/contracts@next/finance/PaymentSplitter.sol

I've run npm install @openzeppelin/contracts@next but don't actually see anything in my openzeppelin directory with contracts@next

**Comment by frangio** [comment]
A new release candidate is available with a few bug fixes.

A release candidate for the upgradeable contracts is available as well.

**Comment by frangio** [comment]
This release is out now! [Short announcement in the forum.](https://forum.openzeppelin.com/t/openzeppelin-contracts-4-4/19706)

This release was a little slow because it was the first time we formalized a longer Open Review Period and were trying to get the [bug bounty](https://immunefi.com/bounty/openzeppelin/) set up on time. Thanks for the patience. Things will be faster next time!
