### ISSUE TITLE
Too restrictive condition?

### ISSUE THREAD

**Issue by olegabr** [OpenZeppelin/openzeppelin-contracts#2844]
In the current implementation the approved operator can not send tokens.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fb36326a58f1bf05896014d540ba7190886e5673/contracts/token/ERC721/ERC721.sol#L334

On this line sender is required to be a token owner, while on the 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fb36326a58f1bf05896014d540ba7190886e5673/contracts/token/ERC721/ERC721.sol#L158

line it allows sender to be just approved also.

**Comment by Amxx** [comment]
Hello @olegabr,

As specified in the ERC, as shown in the tests, and as you saw yourself, an operator CAN definitely send a token. Indeed the `_transfer` function takes a from argument that is the current owner. However, that `from` is not the sender of the transaction. If you check out the [`transferFrom` function ](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fb36326a58f1bf05896014d540ba7190886e5673/contracts/token/ERC721/ERC721.sol#L152-L161), you'll see that the operator can send a token from `from` to `to`.

If `A` ownes a token `X`, and `B` is approved for it, `X` can perform the transfer to `C` by calling `transferFrom(A, C, X)`
