### ISSUE TITLE
Define "describe" in tests

### ISSUE THREAD

**Issue by fulldecent** [OpenZeppelin/openzeppelin-contracts#2848]
Currently, "describe" is used in tests without qualification.

This can confuse VS Code. Because if you start typing a test file and type in "describe", then with default settings it will automatically and silently add this line of code to the top of your file:

```js
const { describe } = require('yargs');
```

That causes compiler errors and confusion.

Recommend to add the correct `require` statement at top of all tests that use `describe`.

**Comment by frangio** [comment]
Mocha (the testing framework) doesn't work like this. It's not possible to require the describe function.
