### ISSUE TITLE
Bug: ERC20 tokens sent to paymentsplitter.sol will be lost. 

### ISSUE THREAD

**Issue by sabotagebeats** [OpenZeppelin/openzeppelin-contracts#2853]
Trying to use payment splitter contract however opensea royalties forces acceptance of WETH tokens which are not supported. If these are sent into paymentsplitter contract they will be lost. 

**💻 Environment**
Ethereum.

**📝 Details**

Trying to use payment splitter contract however opensea royalties forces acceptance of WETH tokens which are not supported. If these are sent into paymentsplitter contract they will be lost. 

**🔢 Code to reproduce bug**

paymentsplitter.sol

**Comment by sabotagebeats** [comment]
similar issue https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2701

**Comment by Amxx** [comment]
Merging issues. Lets continue this discussion here: #2701
