### ISSUE TITLE
Feature: Add an “onlyProxy”-Like Check to the Initializable Contract

### ISSUE THREAD

**Issue by Zer0dot** [OpenZeppelin/openzeppelin-contracts#2861]
**🧐 Motivation**
Currently the ["Initializable" abstract contract](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/utils/Initializable.sol) allows for implementations to be initialized without going through a proxy. This could cause unintended consequences where an implementation's initialization sets a contract that is then called via delegateCall.

**📝 Details**
I think we should implement a mechanism similar to what is implemented in the "UUPSUpgradeable" contract at  commit [#6241995,](https://github.com/OpenZeppelin/openzeppelin-contracts/commit/6241995ad323952e38f8d405103ed994a2dcde8e) in this case we would add a validation for `(address(this) != __self)` to the initializer modifier.

Though I do understand that there are potential edge cases where implementations should be able to call initializers, I believe the "plug and play" nature of OpenZeppelin's (undeniably awesome) contracts library implies that contracts should be optimized for the widest possible and most secure use case. 

Of course I'm not saying we should add this restriction to individual upgradeable initializers (like ERC721Upgradeable for example), since there are probably a lot of projects that, likely for the sake of convenience, stick to inheriting from upgradeable contracts even in cases where the upgradeability isn't needed.

Interested in hearing your thoughts!

**Comment by Zer0dot** [comment]
Note that this would require some changes to tests, since tests validate that an initializer can be ran by calling it via the implementation. Happy to do that in my local branch if this is something we'd like!

**Comment by Amxx** [comment]
Hello @Zer0dot, and thank you for this proposal.

This is something we have discussed, and that we might implement in the future. I do believe there are cases where `Initializable` is used in the context of "standard" contracts. We would kill that use-case, and we would thus be making a breaking change.

While we are not yet certain if we want to implement that or not, feedback like yours is really valuable and appreciated!
