### ISSUE TITLE
Add the possibility to include ERC721 token voting within OZ Governor module 

### ISSUE THREAD

**Issue by ivanminutillo** [OpenZeppelin/openzeppelin-contracts#2873]
**🧐 Motivation**
As stated in the [governance introductory article](https://blog.openzeppelin.com/governor-smart-contract/):
> OpenZeppelin Contracts contain the most common requirements out of the box. Beyond these, OpenZeppelin Governor could potentially be configured with ERC721 voting power so certain NFT owners can participate in governance when specified.

I was wondering if such possibility is already explored somewhere or not yet...
I imagine the customization and usecases could be infinite, but what would imply to have a basic version of the OZ Governor that uses ERC721 tokens to create proposals, delegate and vote?

This issue is a continuation of the https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2868 one.
In [this thread](https://forum.openzeppelin.com/t/using-governor-with-erc721/15824) I explain a little bit more the usecase I'm working on.

**📝 Details**
Following @Amxx suggestions I drafted 3 new contracts:
- [GovernorERC721Votes](https://github.com/ivanminutillo/openzeppelin-contracts/blob/master/contracts/governance/extensions/GovernorERC721Votes.sol): A new governance flavor extension for voting weight extraction from an ERC721Votes token. 
- [ERC721Votes](https://github.com/ivanminutillo/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/ERC721Votes.sol): A clone of ERC20Votes, with the same functions - included `getPastVotes` - but that inherits `NFTPermit` instead of `draft-ERC20Permit`
- [NFTPermit](https://github.com/ivanminutillo/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/NFTPermit.sol): A draft implementation of Permit for the ERC721 token (taken from [here](https://gist.github.com/Amxx/e3c87476093a6b27d9271b2e54b35292))

As I am not really proficient with solidity, I expect there's lot of devil in the details when implementing even the most trivial things, so I was wondering if I'm totally out of track or not?

**Comment by Amxx** [comment]
Hello @ivanminutillo 

Just for the records, the link you shared as a reference for NFTPermit is a prototype for [this](https://github.com/amxx/permit), which is not really the idea I would have of porting ERC2612 to ERC721.

[Uniswap as an implementation of this concept](https://github.com/Uniswap/v3-periphery/blob/main/contracts/base/ERC721Permit.sol) ... but I think it would already be interesting to have a voting ERC721 WITHOUT any of the 712 signature. We can add that later, if there is some consensus around the "ERC721Permit" interface.

**Comment by ivanminutillo** [comment]
Happy to give it a try, btw I am still figuring out where exactly the Permit function is used in the [ERC20Votes.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Votes.sol) - I guess for delegating votes, but cannot find references...
What pratically would imply to not include the permit in the ERC721Votes contract?

**Comment by frangio** [comment]
We want to implement this reusing as much code as possible with `ERC20Votes`. There is a prototype by @Amxx [here](https://github.com/Amxx/amxx-hre/blob/3dbb0ced1e7e411e7e854354787f0f462fc59dd0/contracts/extensions/ERC721Votes.sol).

**Comment by ivanminutillo** [comment]
thanks @frangio, is there any updates about it from your side? I'd likely take the time to test it out

**Comment by frangio** [comment]
@ivanminutillo We haven't made progress on the code as we're still finishing up the the 4.4 release. There's nothing to test yet but if you want to contribute we would welcome a PR.

**Comment by cygnusv** [comment]
> We want to implement this reusing as much code as possible with `ERC20Votes`.

What about the idea I originally mentioned in #2868 about extracting the checkpoint functionality to a separate abstract contract? That way, you would only have to extend from it for `ERC20Votes`, `ERC721Votes`, or whatever other voting power source you need. We already did this extraction in https://github.com/threshold-network/solidity-contracts/pull/19/ and used it not only for an ERC20 token, but also for a staking contract (https://github.com/threshold-network/solidity-contracts/pull/25/). I'd be very happy to contribute this here. BTW, this code has gone already through a security audit, if that's useful

**Comment by frangio** [comment]
@cygnusv Nice. That looks similar to @Amxx's prototype [Voting.sol](https://github.com/Amxx/amxx-hre/blob/3dbb0ced1e7e411e7e854354787f0f462fc59dd0/contracts/Voting.sol).

@JulissaDantes Is currently working on this in #2944, including extracting the checkpoint functionality to a library, so will be using the code as a reference.

**Comment by CrownOfBojji** [comment]
Hi I‘m trying to follow the threads here, is there any updates to the prototype of ERC721Votes? Our team also has a use case and really want to have something in place. 

If we need to wait for 0.4.5, can I simply use this [prototype](https://github.com/Amxx/amxx-hre/blob/3dbb0ced1e7e411e7e854354787f0f462fc59dd0/contracts/extensions/ERC721Votes.sol) this one to replace the [draft-ERC721Votes](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/draft-ERC721Votes.sol)?

**Comment by frangio** [comment]
@CrownOfBojji We're publishing a release candidate this week that includes ERC721Votes.

**Comment by Amxx** [comment]
@omer2307 It's marked as draft because it depends on EIP712, which is not final
