### ISSUE TITLE
Why need uncheck block over _transfer function of ERC20.sol?

### ISSUE THREAD

**Issue by lawweiliang** [OpenZeppelin/openzeppelin-contracts#2875]
Hi everyone,

While  reading through the smart contract of openzeppelin, I found out that their code had include `unchecked`  block?
Why not checking that part?

![image](https://user-images.githubusercontent.com/34936929/134284296-cfde717b-1b5c-4809-b74d-10bf1e14e56b.png)

**Comment by Amxx** [comment]
Hello @lawweiliang 

Lets consider this exact function:
- The balance before transfer is stored on line 30: `senderBalance = _balances[sender];`
- We check that the balance is enough to perform on line 31: `require(senderBalance >= amount);`
- At this point we know for sure that `senderBalance - amount` is greater or equal to 0, and we have thus ruled out any risk of overflow. We thus don't need solidity to perform math checks here.
