### ISSUE TITLE
 I want to implement 4.pow(0.5)

### ISSUE THREAD

**Issue by lailaibtc** [OpenZeppelin/openzeppelin-contracts#2876]
Can you help me, I want to implement 4.pow(0.5)
This calculation
What should I do

**Comment by 3sGgpQ8H** [comment]
`4^0.5` is basically `2`, so  it is nothing to implement here.  Do you mean `x^0.5` or `4^x` or `x^y`?

**Comment by lailaibtc** [comment]
yes sir 

i mean,
i want a function to do pow float like this

pow(x,y)

pow(0.5,0.5)
0.707106781186548

**Comment by Amxx** [comment]
Hello @lailaibtc 

There is currently no implementation of floating points or fixed points in OpenZeppelin contract (or native to solidity). We are thus not going to start implementation operations on type we do not support.

If you are looking for generic solidity advice, not related to OpenZeppelin contracts, this is not the right place. You maybe want to ask on stackoverflow or on the [forum](forum.openzeppelin.com/)
