### ISSUE TITLE
Possible DDOS vulnerability in ERC721.sol ,  setApprovalForAll(address operator, bool approved)

### ISSUE THREAD

**Issue by dattasid** [OpenZeppelin/openzeppelin-contracts#2882]
This code is in main branch right now:
```
    function setApprovalForAll(address operator, bool approved) public virtual override {
        require(operator != _msgSender(), "ERC721: approve to caller");

        _operatorApprovals[_msgSender()][operator] = approved;
        emit ApprovalForAll(_msgSender(), operator, approved);
    }
```
This allows anyone with a Ether address to set a approver for themselves, even if they dont own a NFT here.
It is possible for a attacker to create a million accounts, and set approvers for them in a NFT , making gas costs for operations on this NFT very high.

Yes, the attacker needs to spend a lot of gas doing this, so it is not economical. This depends on the importance of the NFT.

This can be averted by simply checking the msgSender() has at least 1 NFT, 
```
  require(_balances[_msgSender] > 0, "Unknown owner");
```
If this is not a serious threat, maybe we can just put a comment here saying an attack is possible but not economical.

Or perhaps there are other checks and balances I am aware of. I would like to know. Thanks!

**Comment by Amxx** [comment]
Hello @dattasid, and thank you for your concern about security.

We agree that setting up approvals would have a huge cost for the attacker. But you are also saying that by doing so, the attacker would "making gas costs for operations on this NFT very high". This last part I don't quite understand. 

How would this attack be detrimental to anyone but the attacker himself?

Also, please keep in mind that this is an implementation of [a standard](https://eips.ethereum.org/EIPS/eip-721). So maybe this issue reaches beyond our implementation.

**Comment by dattasid** [comment]
I am new to Ethereum, just trying to understand, thanks!

After I filed this, I did more research and seems like existing size of a `mapping` does not add gas to future operations on it. This was non intuitive, so I guess I over reacted. 

If you do not see any impact of an attacker being able to balloon the size of  a `mapping` in a NFT, Please close this issue. I suppose Ethereum was designed to be resistant to this.
