### ISSUE TITLE
should add queue period

### ISSUE THREAD

**Issue by zgfzgf** [OpenZeppelin/openzeppelin-contracts#2885]
Now that a proposal is passed, it can be kept waiting for a long time without entering the queue.
It's not easy to determine the life span of a proposal

refer to https://github.com/compound-finance/compound-protocol/pull/121/
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1b27c13096d6e4389d62e7b0766a1db53fbb3f1b/contracts/governance/extensions/GovernorTimelockCompound.sol#L109-L124

**Comment by Amxx** [comment]
Hello @zgfzgf 

I'm not sure I understand your question/issue.

Our governor reproduced the lifecycle of Compound's proposals:
- Call to propose → proposal is Pending
- After the vote starts → proposal is Active
- After the vote ends → proposal is either Succeeded or Defeated
- Call to queue → propose is Queued
- Call to execute (after delay) → proposal is Executed

Queuing a proposal after the voting ends (resp executing a proposal after the queue delay ends) is not automatic and requires someone sending a transaction.
