### ISSUE TITLE
Bug: Governor state 

### ISSUE THREAD

**Issue by zgfzgf** [OpenZeppelin/openzeppelin-contracts#2886]
for example: when startBlock=100000

A have 200 COMP 
B no COMP
when block.number=10000
OpenZeepelin  state is Active (is error)
Compound state is Pending  (is OK)

A castVote. and transfer to B. B is also castVote.  in block.number=10000

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1b27c13096d6e4389d62e7b0766a1db53fbb3f1b/contracts/governance/Governor.sol#L111-L130

https://github.com/compound-finance/compound-protocol/blob/a6251ecc30adb8dfa904e2231e9a9fdb4eea78be/contracts/Governance/GovernorAlpha.sol#L226-L246

**Comment by zgfzgf** [comment]
https://github.com/compound-finance/compound-protocol/blob/a6251ecc30adb8dfa904e2231e9a9fdb4eea78be/contracts/Governance/Comp.sol#L190
        require(blockNumber < block.number, "Comp::getPriorVotes: not yet determined");

Without this, there will be errors.

**Comment by Amxx** [comment]
Hello @zgfzgf 

In Openzeppelin governor, just like in Compound's governor, when an address casts a vote, the governor asks the (Comp) token what the votes of the address were at a given point in time.

- Compound: [here](https://github.com/compound-finance/compound-protocol/blob/a6251ecc30adb8dfa904e2231e9a9fdb4eea78be/contracts/Governance/GovernorAlpha.sol#L266)
- OZ: [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/Governor.sol#L329) and [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/extensions/GovernorVotesComp.sol#L23-L25)

This avoids transferring tokens and voting twice.

As you saw, this mechanism is part of the token contract, not the governor. Note also that for a user to be able to cast a vote, we must be in the `Active` state. This can only be achieved if :

- the proposal is not executed
- the proposal is not canceled
- `block.number > proposal.startBlock`
- `block.number <= proposal.endBlock`

Consequently, when we query 
```
uint96 votes = comp.getPriorVotes(voter, proposal.startBlock)
```
We are certain that `proposal.startBlock` is in the past, (check was performed in the `state()` function)

**Comment by zgfzgf** [comment]
I see. but We don't guarantee others proposal.startBlock is in the past.

**Comment by zgfzgf** [comment]
see email:security@openzeppelin.org
