### ISSUE TITLE
SafeMath documentation suggesting that it is no longer required - not entirely accurate

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/openzeppelin-contracts#2897]
[The documentation of `library SafeMath`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/math/SafeMath.sol#L12-L13) states:
> NOTE: `SafeMath` is no longer needed starting with Solidity 0.8. The compiler now has built in overflow checking.

This is not entirely accurate IMO.

Consider the following scenario:
- We decide to upgrade to solc 0.8
- We have a function which consists of many native operations, but only a handful of `SafeMath` operations

Instead of splitting that function into several blocks of 'checked' code and 'unchecked' code, it is cleaner to just scope the entire function code within an `unchecked` block, which means that the `SafeMath` library remains useful in such cases.

Thanks

**Comment by Amxx** [comment]
Yes, [this was pointed out when we consider completely removing the library and is one of the reasons we till have it.](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2465#issuecomment-756955545)

**Comment by frangio** [comment]
Changed to "generally not needed" in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2898
