### ISSUE TITLE
Doesn't snapshot + 1 block makes a proposal active?

### ISSUE THREAD

**Issue by noobshow** [OpenZeppelin/openzeppelin-contracts#2902]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/6c1a6340539be1967e63158fb9f997ef62d47f70/test/governance/Governor.test.js#L555-L561

Does this test still pass even after this line below states isPending can only happen after deadline is > block.number...

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/75d422feca902d155d478b56cdf67cf1cf3e3527/contracts/utils/Timers.sol#L66

...And the line below uses Timers.isPending to check if voteEnd has passed...

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1b27c13096d6e4389d62e7b0766a1db53fbb3f1b/contracts/governance/Governor.sol#L120

How did that test passed(proposalState becomes Active) when the time is advanced to snapshot and not snapshot + 1 according to the line below?

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/6c1a6340539be1967e63158fb9f997ef62d47f70/test/governance/Governor.test.js#L558

**Comment by frangio** [comment]
Thanks for the issue.

You're looking at the wrong condition. It's `voteStart.isPending()` that determines whether the Governor moves onto `Active` state. So when the block is advanced to "snapshot" (i.e. `voteStart.deadline`), it is no longer `Pending` and moves onto `Active`.

**Comment by noobshow** [comment]
I think even though i mentioned `voteEnd `instead of `voteStart`, you should understand my case around that test lines i shared, my tests were failing somehow with this one until i either `advanceBlock `once more after advancing to snapshot or just `advanceBlock(this.snapshot.add(1))`

**Comment by noobshow** [comment]
Oh, I see...
Just saw your commit. This is much like I think it was supposed to be.

Great work there.
