### ISSUE TITLE
Brownie / Pytest versions of the Unit Tests for OpenZepplin Contracts

### ISSUE THREAD

**Issue by justinpezzack** [OpenZeppelin/openzeppelin-contracts#2909]
**🧐 Motivation**
I am currently using OpenZepplin contracts in my Brownie based project. Even though the code I have written is fully unit tested, when I run `brownie test -C` I get 0% coverage for all of the OpenZepplin files, thus the overall coverage report reports a very low % for my project. I was going to add tests targetting OpenZepplin myself but figured it might be something that is useful for the community and could be integrated into this repo, opposed to just my personal repo. 

**📝 Details**
- Pytest / Brownie tests for OpenZepplin Contracts
- I can assist with this and/or submit a PR if that is of interest.

Thoughts from an OpenZepplin engineer would be awesome.

Cheers,
Justin

**Comment by Amxx** [comment]
Hello @justinpezzack 

Brownie is not part of our work process when building and testing our contract. We currently use hardhat (with various modules) to test everything. Also, as discussed in previous issues, we do not consider the test scripts to be part of the deliverables. Users are free to reuse them to further test their projects, but we do not take any specific actions to make sure that our test scripts work outside this repo.

I'm not exactly sure what the demand for brownie tests covering our contract is, but I would personally not feel comfortable shipping this considering it is not the goal of this repo to prove such tests AND we are not familiar with brownie. 

If you think this would be valuable, then maybe a community-managed repo would make more sense.

**Comment by justinpezzack** [comment]
Thanks for the responses @Amxx @frangio. Just out of curiosity what was the motivation for utilizing hardhat over something like Brownie. I am more Python native than JS, hence why I started with Brownie. Are there tangible benefits to using JS based frameworks? Seems like most people tend to favour them.

**Comment by frangio** [comment]
There is nothing inherent to JavaScript that makes it more suitable for Ethereum development, except perhaps the fact that the same language can be used to write a dapp for the browser.

Most of the tooling is built on JavaScript and this gives it a huge advantage.

**Comment by vsmelov** [comment]
It would be nice to disable the brownie coverage report for imported libraries, I'm not sure if it's possible
