### ISSUE TITLE
Documentation problem

### ISSUE THREAD

**Issue by grapevinegizmos** [OpenZeppelin/openzeppelin-contracts#2913]
In your documentation for ECDSA, you give the following example of how to use recover:

using ECDSA for bytes32;

```
function _verify(bytes32 data, address account) pure returns (bool) {
    return keccack256(data)
        .toEthSignedMessageHash()
        .recover(signature) == account;
}
```

Note that in this function, the parameter to the `recover` function (`signature`) is undefined.  I am having a heck of a time getting this to work as expected, made somewhat more difficult because I can't quite tell what kind of variable "signature" is expected to be.

**Comment by julianmrodri** [comment]
Check the updated example here: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/docs/modules/ROOT/pages/utilities.adoc

It was fixed but apparently not deployed. This is the example you need:

```
using ECDSA for bytes32;

function _verify(bytes32 data, bytes memory signature, address account) internal pure returns (bool) {
    return keccak256(data)
        .toEthSignedMessageHash()
        .recover(signature) == account;
}
```

**Comment by frangio** [comment]
You're right, sorry about that. Fixed the code sample in https://github.com/OpenZeppelin/openzeppelin-contracts/commit/e6f26b46fc8015f1b9b09bb85297464069302125.
