### ISSUE TITLE
Delegate votes or add checkpoint to minter of ERC20votes token

### ISSUE THREAD

**Issue by PatrickAlphaC** [OpenZeppelin/openzeppelin-contracts#2916]
**🧐 Motivation**
When going through the process of learning the new governance code, I deployed an ERC20Votes token, minted it to myself, but was surprised to see no checkpoint was created. It was only when I looked into the tests did I find out I had to first delegate them to myself. 

Is this intentional? Should we have ERC20Votes token auto delegate to whomever mints them?

For context, the ERC20Votes `_mint` function looks like this:
```javascript
    function _mint(address account, uint256 amount) internal virtual override {
        super._mint(account, amount);
        require(totalSupply() <= _maxSupply(), "ERC20Votes: total supply risks overflowing votes");

        _writeCheckpoint(_totalSupplyCheckpoints, _add, amount);
    }
```
It calls `_writeCheckpoint` with `_totalSupplyCheckpoints`, but for voting, the right one would be `_checkpoints[account]`

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/e6f26b46fc8015f1b9b09bb85297464069302125/contracts/token/ERC20/extensions/ERC20Votes.sol#L172

Would it make sense to also add:

```javascript
_writeCheckpoint(_checkpoints[account], _add, amount);
```

So we could have a checkpoint right when the token is minted to a user?

**Comment by Amxx** [comment]
Hello @PatrickAlphaC 

When you call `_mint`, there is a super call happening. This super call will trigger a `_afterTokenTransfer` call, which will call `_moveVotingPower`

If the receiver as a delegate set (either to itself or to someone else) this will write the corresponding checkpoint

**Comment by frangio** [comment]
Delegation is opt in by design, because delegation adds overhead to token transfers (the checkpoint bookkeeping). If a token holder only wants to trade the token on a DEX, they are much better off without setting up a delegate.

In your code you can add `delegate(...)` right after `_mint` if you want to make it auto-delegate.

**Comment by PatrickAlphaC** [comment]
Right, I get that. Was wondering if it made sense to just do it in mint. I see the rationale. Thank you.
