### ISSUE TITLE
Revert on any error inside MultiCall

### ISSUE THREAD

**Issue by vsmelov** [OpenZeppelin/openzeppelin-contracts#2930]
Why in
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Multicall.sol
you don't copy the revert message as e.g. UniSwap do
https://github.com/Uniswap/v3-periphery/blob/main/contracts/base/Multicall.sol

            if (!success) {
                // Next 5 lines from https://ethereum.stackexchange.com/a/83577
                if (result.length < 68) revert();
                assembly {
                    result := add(result, 0x04)
                }
                revert(abi.decode(result, (string)));
            }

I think this is useful and expected behaviour

**Comment by frangio** [comment]
Yes, the answer is the logic you quoted is already happening inside our `functionDelegateCall` helper.
