### ISSUE TITLE
add `override(X)` to any override singletons

### ISSUE THREAD

**Issue by hacker-DOM** [OpenZeppelin/openzeppelin-contracts#2937]
The `override` keyword occurs many times without an identifier:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/governance/extensions/GovernorTimelockControl.sol#L111

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/access/AccessControlEnumerable.sol#L37

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/token/ERC20/ERC20.sol#L101

Adding the name of the contract where the function that is being overriden is defined may not be required by the compiler, but it will improve code readability.

**Comment by frangio** [comment]
Thank you @hacker-DOM. I personally strongly prefer the simpler syntax here. Solidity is already very verbose and I don't think adding more annotations does good things for code readability. Additionally, see my final sentence in https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2936#issuecomment-961483458.
