### ISSUE TITLE
Remove DEFAULT_ADMIN_ROLE

### ISSUE THREAD

**Issue by hacker-DOM** [OpenZeppelin/openzeppelin-contracts#2940]
### Background
`AccessControl.roleData` has a field called `adminRole`.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/access/AccessControl.sol#L50-L53

By default, this will be set to `0x00`. This means that anyone with that role will be an admin (be able to add and remove members) for all roles that don't have a set admin.

Furthermore, assume a role has set an admin. If this admin role (call it `AR`) has not set its own admin role, the DEFAULT_ADMIN_ROLE would be able to make themselves a member of this role, and hence a member of the administered role.

It follows that that the DEFAULT_ADMIN_ROLE can become an admin for every single role, so it is not just default.

This recursion works on itself as well - even if the admin **of** the DEFAULT_ADMIN_ROLE is changed, any member of the DEFAULT_ADMIN_ROLE may recusively become an admin of the DEFAULT_ADMIN_ROLE, and hence add or remove other people.

### Recommendation
Remove this intricate construct by adding checks that `adminRole != ""`. This will ensure no default admin exists, greatly simplifying the contract's logic

**Comment by Amxx** [comment]
Hello @hacker-DOM 
What you are seeing as a bug is in fact a well-thought-out feature.

By default, any role that is doesn't have an admin set is administered by the `DEFAULT_ADMIN_ROLE`. That is what its all about, the `DEFAULT_ADMIN_ROLE` is plain and simply the default admin role.

Now, for some reason you want roles A, B and C to manage one another, and not be administered by the default, you can do

```
_setRoleAdmin(A, A);
_setRoleAdmin(B, A);
_setRoleAdmin(C, B);
```

**Comment by frangio** [comment]
The default admin role is indeed a very critical role, but it also doesn't have any default members. If that wasn't the case I would be concerned about the potential consequences of forgetting to set a role admin.

Closing as the risks are not greater than intended or implied.
