### ISSUE TITLE
`ERC20PresetFixedSupply` does not have fixed supply

### ISSUE THREAD

**Issue by hacker-DOM** [OpenZeppelin/openzeppelin-contracts#2941]
### Description
`ERC20PresetFixedSupply` inherits from `ERC20Burnable`:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/token/ERC20/presets/ERC20PresetFixedSupply.sol#L19

As such, the token supply may be decreased.

### Recommendation
Rename this contract to `ERC20PresetInitialSupply`.

**Comment by frangio** [comment]
This is a good point, I would agree that "initial supply" is more accurate. However, we need to keep the name for backwards compatibility. Presets will be removed in the next breaking release as we are now favoring [Contracts Wizard](https://wizard.openzeppelin.com/) as a more powerful alternative.
