### ISSUE TITLE
Unable to complete "npm install @openzeppelin/cli"

### ISSUE THREAD

**Issue by xrpdevs** [OpenZeppelin/openzeppelin-contracts#2945]
Issue: see title

Env: Ubunu 20.04, NPM 8.1.0, Node v16.13.0

Trying to use latest openzeppelin/cli from npm install with Truffle v5.4.17
openzeppelin/contracts installed without issue - v4.3.2

Detail: 
```

sudo npm install -g @openzeppelin/cli
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/web3-js/scrypt-shim.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.


```

**Comment by xrpdevs** [comment]
Ahh... probably because I dont have github's pubkey installed on this machine.

Would probably be better if http schema was used. Will close this if problem resolves when installing the pubkey.

**Comment by xrpdevs** [comment]
Added keys but got:
```
npm ERR! command git --no-replace-objects clone ssh://git@github.com/web3-js/scrypt-shim.git /root/.npm/_cacache/tmp/git-cloneZgaFlC --recurse-submodules --depth=1
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-cloneZgaFlC': Permission denied

```
Solution was:
```
npm cache clean --force
npm install - - global @openzeppelin/cli
```
It installed, but with lots of warnings about deprecation.

I'm trying to compile a bunch of contracts with truffle which reference openzeppelin with 
`import "@openzeppelin..."`
I read that I need to do
`openzeppelin init`
in the project directory before using truffle build.

Presume there is a better way of doing this?

**Comment by xrpdevs** [comment]
Scratch all of the above. The better way of doing this is to just use hardhat to build instead of truffle.

**Comment by frangio** [comment]
OpenZeppelin CLI is no longer mainteined. See [announcement](https://forum.openzeppelin.com/t/building-for-interoperability-why-we-re-focusing-on-upgrades-plugins/4088).

**Comment by xrpdevs** [comment]
Thanks, I had worked that out by the time I failed for the second time to get it to install/run =)Sent from Samsung Mobile on O2
