### ISSUE TITLE
Should the MerkleProof library verify empty proofs? 

### ISSUE THREAD

**Issue by nicholashc** [OpenZeppelin/openzeppelin-contracts#2949]
The MerkleProof.sol library returns `true` when verifying a proof with arguments that meet these conditions:

1. `proof` is an empty array
2. `root` == `leaf`

Should the library validate an empty Merkle proof?

**📝 Details**

[MerkleProof.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/MerkleProof.sol) checks for the inclusion of a leaf in a given Merkle tree. The function `verify(proof[], root, leaf)` checks if the root is equal to the computed hash of the proof. The function `processProof(proof[], leaf)` computes the result of the proof. 

The local variable `computedHash` is initialized as `leaf`. Normally, it is hashed with each item in the `proof` array in a loop. If `proof` is an empty array with a length of 0, however, the loop block is never reached. The function simply returns `leaf`. The library now verifies if `root == leaf` and returns `true` if the original two arguments were the same.

Technically, an empty array is a valid proof of a tree with only one node.  Does sensible input validation fall within the scope of this library's responsibilities? 

**🔢 Code to reproduce bug**

Consider a simple example contract using the MerkleProof.sol library:

```solidity
// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts v4.3.2 (utils/cryptography/MerkleProof.sol)

pragma solidity ^0.8.0;

import "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";

contract MerkleProofProof {
    
    function verify(
        bytes32[] memory proof, 
        bytes32 root, 
        bytes32 leaf
    ) 
        external
        pure
        returns (bool isValidProof) 
    {    
        return MerkleProof.verify(proof, root, leaf);
    }
}
```

Calling `verify(proof[], root, leaf)` invokes the MerkleProof.sol library method by the same name. If `proof` is an empty array and `root` == `leaf`, it returns `true`. 

Example calldata:

`0x5a9a49c70000000000000000000000000000000000000000000000000000000000000060ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000000000000000000000000000000000000000000000000000`

**Comment by Amxx** [comment]
Hello @nicholashc 

A Merkle-tree that contains a single a single entry will be reduced to only one node, which is both the only leaf AND the root of the tree. In that case, an empty proof is the expected proof.

Requiring the proof to be non-empty would forbid merkle-trees containing a single entry. I don't see any reason to forbid such trees and lose the generality for no security benefit.

**Comment by bmarcot** [comment]
Thanks for the clarification, @Amxx . I encountered this special case today—a Merkle tree with only one entry—and couldn't understand why I was able to successfully verify an empty proof.
