### ISSUE TITLE
I don't think the second argument is necessary in renounceRole function

### ISSUE THREAD

**Issue by LisenH** [OpenZeppelin/openzeppelin-contracts#2950]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.4/contracts/access/AccessControl.sol#L161
```
function renounceRole(bytes32 role, address account) public virtual override {
    require(account == _msgSender(), "AccessControl: can only renounce roles for self");
    _revokeRole(role, account);
}
```
the second argument is unnecessary, you can do it just like this:
```
function renounceRole(bytes32 role) public virtual override {
    _revokeRole(role, _msgSender());
}
```

**Comment by Amxx** [comment]
Hello @LisenH 

This was already discussed somewhere but I cannot find the link (Possibly in the forum).
The logic behind this (overly?) expressive ABI is the following one:

- It prevents someone from renouncing the wrong role (potentially breaking things) if the transaction is sent with the wrong EOA or by the wrong smart contract.
- Backward compatibility prevents us from changing that now, as it could break existing codebases.

**Comment by LisenH** [comment]
> Hello @LisenH
> 
> This was already discussed somewhere but I cannot find the link (Possibly in the forum).
> 
> The logic behind this (overly?) expressive ABI is the following one:
> 
> * It prevents someone from renouncing the wrong role (potentially breaking things) if the transaction is sent with the wrong EOA or by the wrong smart contract.
> * Backward compatibility prevents us from changing that now, as it could break existing codebases.

got you, thanks.
