### ISSUE TITLE
require to late

### ISSUE THREAD

**Issue by Vadiml1024** [OpenZeppelin/openzeppelin-contracts#2953]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/5cdf2a8fdf50448d3d51c0a0e615d27b430765d9/contracts/token/ERC20/ERC20.sol#L158

Shouldn't this this _require call be done
BEFORE the _transfer call?

**Comment by Amxx** [comment]
Hello @Vadiml1024 

This was already discussed in #2683. The discussion there explains why we do the transfer before the allowance check.
