### ISSUE TITLE
TokenTimelock.release() uses block.timestamp, which can be set arbitrarily far in the future

### ISSUE THREAD

**Issue by lukehutch** [OpenZeppelin/openzeppelin-contracts#2954]
`TokenTimelock.release()` uses `block.timestamp`, which can be set arbitrarily far in the future by miners (the only requirement for this field is that it must be greater than the parent block's timestamp).

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/utils/TokenTimelock.sol#L63

https://ethereum.stackexchange.com/a/428/82179

https://ethereum.stackexchange.com/a/432/82179

This seems to negate the usefulness of TokenTimelock, and may even introduce a security vulnerability for certain contracts.

**Comment by Amxx** [comment]
Hello @lukehutch 

The malleability, by miners, of block.timestamp is well known and documented. IMO the only alternative is using block number, which also comes with many drawbacks:
- (average) time between blocks changes between EVM compatible chain.
- (average) time between blocks is subject to change in case of network upgrades (such as the merge)
- for most people, (future) timestamps are easier to understand than (future) block numbers.

Assuming we could break backward compatibility (we can't) ... what would you rather have ?

**Comment by lukehutch** [comment]
Well what I'm saying is that as a security framework that purports to provide bulletproof reference implementations of things, you shouldn't provide anything that cannot be used without big caveats (which are not even documented here), or that has a massive security gotcha that anyone could drive a truck through! So I suggest removing this altogether, or put a large all-caps disclaimer on it.

The block timestamp can only be used to deny access to something before a certain time, it cannot be used to grant access to something after a certain time. But since these two conditions are two sides of the same coin, this field is basically useless for any sort of access control.

**Comment by Amxx** [comment]
So you would remove anything that involves time? 
- TokenTimelock
- TimelockController
- Governor
- VestingWallet

If we remove that, it won't stop people from needing these building blocks for their apps, so rather than using the standard, recognized, contracts we propose, everybody will have to re-invent the wheel, and possibly make mistakes. This doesn't sound like a move that would improve security in the web3 space...

You may not like it, but users do build contracts that have time-related features. Sure you have to be careful when dealing with time (or PRNG) and evaluate the risks of miners tricking it ... but many apps just have to deal with timings to work, and we think it's our role to address their needs by providing the best contracts possible (while also notifying them of the potential issues).

**Comment by lukehutch** [comment]
Well take or leave my advice, but it's important to understand that you cannot use the block timestamp if arbitrarily increasing its value can benefit a potentially malicious party (including and up to the worst case scenario that the benefit to the malicious party monotonically increases the further out that the timestamp is forged).

I am aware of a contract that uses the timestamp correctly -- it is set up in such a way that the more a would-be hacker increases the timestamp value past the true Unix time, the more it disadvantages them. So there is no incentive to mess with the timestamp. If contracts cannot be set up this way, then timestamp should not be used.

If you strongly believe OoenSolidity should allow people to shoot themselves in the foot, then you at least must include a large bold disclaimer on any contract that uses the block timestamp... And you should probably write into OoenZeppelin's development policies that any future contracts that are written to include the block timestamp must have the same disclaimer added.

Again though, take it or leave it :-)

**Comment by Amxx** [comment]
> I am aware of a contract that uses the timestamp correctly -- it is set up in such a way that the more a would-be hacker increases the timestamp value past the true Unix time, the more it disadvantages them. So there is no incentive to mess with the timestamp. If contracts cannot be set up this way, then timestamp should not be used.

In that case an attacker could decide to under-estimate the timestamp to penalize the user by delaying its actions (DOS). So its not perfect either.

Also, I do believe that ethereum clients are designed to reject blocks that are to far in the future, preventing an attacking miner to fast forward too much.

**Comment by lukehutch** [comment]
No, you can't arbitrarily lower the block timestamp. In the Ethereum yellowpaper, it states that a block timestamp must be greater than the parent block timestamp. That is the only constraint that is specified.

There is discussion in the two StackExchange links I shared that describe how (1) from a game theoretic standpoint, block timestamps will not usually have large error, however (2) there is nothing stopping a particularly determined attacker, especially one with a great deal of network influence, from arbitrarily increasing the block timestamp and having it accepted. The larger the potential payoff for doing so, the more likely this scenario becomes.

You could use block interval to determine if the timestamp has been forged far in the future, but of course block interval is not guaranteed to be within any specific time range either, so this can only be used for long timescales. (and even then you would have to look closely at the accuracy distribution of parent block timestamps given the behavior of clients in accepting or rejecting blocks).

**Comment by Amxx** [comment]
You can't lower it, but you can not increase it as much as expected.

**Comment by lukehutch** [comment]
Looks like you're right, some Ethereum clients are much stricter than the specification.

https://ethereum.stackexchange.com/questions/5927/how-would-a-miner-cope-with-a-huge-block-time

I'll close this. Thanks for the discussion.
