### ISSUE TITLE
ERC721Revealable - an interface for NFT projects revealing contents after the sale.

### ISSUE THREAD

**Issue by whtjdals016** [OpenZeppelin/openzeppelin-contracts#2959]
**🧐 Motivation**
NFT projects often do a launching first, and later reveal the contents by changing baseUri. However, having a funciton that could change the baseUri could be dangerous, given the content could change after buying or minting the tokens without notice to the owners.
ERC721Revealable is inspired by Initializable, that it allows once to "reveal" the contents after a successful public sale, while once revealed, the baseUri cannot be changed anymore, protecting the owners from any potential harm caused by changing the baseUri.

**📝 Details**
I have prepared this initial draft of what it would look like.
https://github.com/whtjdals016/openzeppelin-contracts/commit/a2626b823f3f80ee268f637312b2be107462d2ab

Would super appreciate if you could share your thoughts here.

**Comment by Amxx** [comment]
Hello @whtjdals016 

There are many ways to achieve this. You could have the admin publish the base URI after the fact, but you could also have anyone be able to do, provided it matches a cryptographic commitment set at construction. You could also use a merkle tree of individuals URIs that users will be able to put onchain themselves ...

All options come with advantages and drawbacks.

I don't think its our role, at OpenZeppelin, to decide which one should be commonly used. We do however provide everything needed for devs to easily implement the solution of their choice. IMO this is enough.

If an ERC standard for revealability was created and adopted by the community, we would implement it. Until then, I think the best approach would not be to create a PR here, but rather to write a tutorial on the OpenZeppelin Forum, explaining how to do it and how it works in practice.

**Comment by whtjdals016** [comment]
Thanks for your reply - definitely makes sense!
