### ISSUE TITLE
Add CANCEL_ROLE to TimelockController

### ISSUE THREAD

**Issue by cygnusv** [OpenZeppelin/openzeppelin-contracts#2980]
**🧐 Motivation**
In the forthcoming Threshold Network DAO, there's a council with veto power over proposals. The only way to allow this with current implementation of `TimelockController` would be to grant the council the `PROPOSER_ROLE`, but this council shouldn't be able to make proposals, according to our governance design. We need something like a `CANCEL_ROLE` that's different from `PROPOSER_ROLE` and `EXECUTION_ROLE`. This feature could also be a solution for the ["Proposer fight" problem](https://docs.openzeppelin.com/contracts/4.x/api/governance#timelock-proposer) that's discussed in the documentation.

**Discussion**
I wanted to do this by creating a contract that inherits from `TimelockController`, but since its variables and functions are marked as private it's being difficult. In particular, we need to further restrict the cancel operation to a different role than proposers, but the modifier in `cancel()` forces us to override it and re-implement it, and we encounter the problem of `_timestamps` being private.

Anyway, if you find this interesting, I'd love to help, since I'm working on that anyway.

**Comment by Amxx** [comment]
Hello @cygnusv 

This is definitely an interesting discussion, but changes like that will take time to make. In the meantime, I believe you could fix that by having an Ownable or AccessControl contract, that would be a proposer for the timelock, and which only function (on top of the Ownable or AccessControl) would be a cancel forwarder.

That way your council could cancel through this relayer, but not propose.

**Comment by frangio** [comment]
We can add a `_cancel` function without access control check so you can define the function with a new role.

In the meantime, there is a somewhat hacky workaround you can implement:

```solidity
function cancel(bytes32 id) public virtual onlyRole(CANCEL_ROLE) {
    _grantRole(msg.sender, PROPOSER_ROLE);
    super.cancel(id);
    _revokeRole(msg.sender, PROPOSER_ROLE);
}
```

(Note: This requires the latest version of OZ Contracts for the internal grant and revoke functions.)

**Comment by cygnusv** [comment]
Thanks @frangio and @Amxx ! 

After playing around with the idea of a cancel proxy I realized that we actually want the cancel functionality to happen at the Governor level, and since it's already a proposer in the timelock, it can cancel. We then just add an access control check in `Governor.cancel()`

**Comment by frangio** [comment]
@cygnusv We've been thinking about adding a cancel role, how did you solve this in your governor? Who has the ability to cancel?

**Comment by cygnusv** [comment]
@frangio We decided to add a cancel role in the Governor contract and implement `cancel()` there. Since all proposers for the Timelock can cancel, and in our setting only the Governor contract is a proposer, anyone with the cancel role can cancel in the timelock via the Governor contract. 
See https://github.com/threshold-network/solidity-contracts/commit/9002bdb33060c74c55d9648dbf5a8b2bcb732d34#diff-9762b5e3ad775b50a9ae4df345a244e7a6d73f45103be32b229cc8ae2b032686

**Comment by frangio** [comment]
I see. And in practice who has veto power?

**Comment by cygnusv** [comment]
In the Threshold DAO, it was decided that a council multisig has veto power in case there's a dangerous proposal (see https://forum.threshold.network/t/threshold-network-dao-proposal-v2/57)
