### ISSUE TITLE
safeTransferFrom being called by Anyone once setApprovalForAll has been called

### ISSUE THREAD

**Issue by JF0001** [OpenZeppelin/openzeppelin-contracts#2985]
I have created a Dapp Marketplace (Web Portal) based on a Smart Contract (using OpenZepelin library), where users can purchase and sell NFTs. Owners can grant my Contract authorisation to sell their NFTs on their behalf by calling the setApprovalForAll function from the portal. I have noticed however, that once this approval has been granted, that any user, including a purchaser, can call the safeTransferFrom function directly on the Smart Contract.

**💻 Environment**
Linux Ubuntu 20.04

@openzeppelin/contracts-upgradeable: ^4.3.2

**📝 Details**

Please see scenario described below:

**🔢 Code to reproduce bug**

I have the following function in my ERC721 Smart Contract:

` function tokTransfer(address payable from, address to, uint256 tokenId, uint256 price) external payable {
   require(msg.value >= price);
   this.safeTransferFrom(from, to, tokenId);
   AddressUpgradeable.sendValue(from, price);
 }`

I am calling this function from my front-end Dapp using the following:

` this.contInst.methods.tokTransfer(tokOwner, this.account, TokenId, PriceBN).send({
   from: this.account,
   value: this.web3.utils.toWei(PriceStr, 'ether')
 })`

Token owners have called the setApprovalForAll on my Smart Contract, granting it authorisation to sell their tokens on their behalf. However, I am able to call this function directly in Truffle with the following statement (using the Purchaser account (i.e. accounts[2]) as the from (i.e. _msgSender)):

`instance.tokTransfer(accounts[1], accounts[2], 1001, '2500000000', {from: accounts[2], value: '2500000000'})`

How can I actually call my function, which itself calls the safeTransferFrom OpenZeppelin function, while the Sender (_msgSender i.e. Purchaser) of the Transaction does not satisfy the require statement in the function below?

` function safeTransferFrom(
    address from,
    address to,
    uint256 tokenId,
    bytes memory _data
 ) public virtual override {
    require(_isApprovedOrOwner(_msgSender(), tokenId), "ERC721: transfer caller is not owner nor approved");
    _safeTransfer(from, to, tokenId, _data);
 }`

Thank you for your time. J

**Comment by Skyge** [comment]
It seems like you have asked this question in the forum, and `frangio` has replied you.

**Comment by Amxx** [comment]
Hello @JF0001 

`setApprovalForAll` and `transferFrom` behavior behavior is described in ERC721. We only implement this community recognized standard. This standard works for many people, and I'm pretty sure it can work for you ... but if you have concerns with it, you should voice your concern in a new ERC, or on the EthMagician forum.

**Comment by JF0001** [comment]
Thank you @Amxx I can certainly follow your suggestion. Meanwhile, do you agree that the `setApprovalForAll` function does not behave  as one would expect it (in the sense that it shouldn't grant every one the ability to call the `safetransferFrom` function once approved), or am I misunderstanding something? I wouldn't want to waste anyone's time. Thanks again.

**Comment by Amxx** [comment]
IMO, `setApprovalForAll(address operator, bool approved)` **does** behave as one would expect.

- It **does not** grant everyone the ability to call `safeTransferFrom`
- it **does** grant one particular address (the operator) the ability to call `safeTransferFrom` for **all** the token owned by the caller.

For example, if OpenSea has a smart contracting managing all exchanges in the platform, and that this contract is at address X, then what calling `setApprovalForAll(X, true)` does is giving authorisation for this contract to transfer all my tokens (following the rules implemented in the contract X).

**Comment by JF0001** [comment]
Thanks again @Amxx  This is exactly how I would expect it to work. But it actually does grant anyone the ability to call the `safeTransferFrom` function once executed. As explained above, I am able to call it directly in Truffle with the following statement (using the Purchaser account (i.e. accounts[2]) as the from (i.e. _msgSender)). The tokTransfer function is implemented in my smart contract, and basically calls the `safeTransferFrom` function. Thus, I am using accounts[2], which is not authorised (only my smart contract address was), to call the function, and it works! Considering that this could be a major vulnerability for some existing smart contracts, and considering that this flaw is so basic, I thought for a moment that I was not understanding it properly, but you are confirming that I actually do. I would advise you or your team to try it out yourself.

`instance.tokTransfer(accounts[1], accounts[2], 1001, '2500000000', {from: accounts[2], value: '2500000000'})`

Thank you. J

**Comment by Amxx** [comment]
It is dangerous for a user to give approve to an arbitrary operator. But if
- the operator is a smart contract, 
- the contract has strict condition to perform a transferFrom
- the contract is open source & audited
then a user can safely give it operator right.

[Here is an example of such a contract](https://github.com/Amxx/Permit/blob/master/contracts/Permit721.sol)

This is actually super powerful, and what allows services like OpenSea to operate.

**Comment by JF0001** [comment]
Thanks again @Amxx  Absolutely, and I was actually trying to imitate the behaviour of OpenSea in my own Marketplace/Smart Contract by giving users the ability to grant the Smart Contract, permission to sell any of their Tokens so that they do not have to pay gas every time that they wished to put an NFT on sale, or change its selling price. But considering that by using the setApprovalForAll function it appears that anyone (I believe that this is not by design) could call the safeTransferFrom function from outside my Web Portal (outside of the Smart Contract's control, and thus could be triggered even for items that users do not actually wish to sell), I will have to either rewrite the function (I was trying to avoid this by using as much code from the OpenZeppelin library as possible), or use another strategy. I was wondering how OpenSea was actually implementing this functionality. From what I have read (I might be mistaking) it appears that they are not using OpenZeppelin but another library called [Wyvern](https://github.com/ProjectWyvern/wyvern-ethereum) in their Smart Contract, which appears to have similar functions as OpenZeppelin.

**Comment by JF0001** [comment]
Just for you information @Amxx I am happy to report that the OpenZeppelin library is working as expected (which is reassuring and actually not surprising considering the extensive use of it). As you had suggested, I have reported my problem on the ethereum-magicians.org forum. There is a gentlemen by the name of rmeissner that has noticed that I was using the `this` keyword in my function call `this.safeTransferFrom(from, to, tokenId)`. He has noted that "when you call a function of a the contract with `this,` it will trigger an internal transaction and therefore msg.sender in the called method will be the contract itself. Therefore it doesn’t matter what sender actually called your tok method." After indeed removing the `this` keyword, only authorised addresses are able to call the safeTransferFrom function, as expected. You can find my post with his answer at the following [link](https://ethereum-magicians.org/t/safetransferfrom-can-be-called-by-anyone-once-setapprovalforall-has-been-granted-on-one-address/7554) for your reference. I would like to thank you for your time and for suggesting me to post my reported problem at the Forum in question. Have a great day!

**Comment by Amxx** [comment]
Having a new look at your code, the issue really is in how you designed the `tokTransfer` function:

```
function tokTransfer(address payable from, address to, uint256 tokenId, uint256 price) external payable {
   require(msg.value >= price);
   this.safeTransferFrom(from, to, tokenId);
   AddressUpgradeable.sendValue(from, price);
 }
```

If Alice has a few tokens, and sets approval so that this contract is an operator, then anyone (Bob) can come, call
`tokTransfer(Alice, Bob, tokenID, 0)` and get the token for free. there absolutely no verification whatsoever of anything.

Also, if this is a function that is added inside the ERC721 contract, you should be using `_transfer`, not `this.safeTransferFrom` (which is really a recipe for bugs)

You could do something like:
```
mapping(address => mapping(uint256 => uint256)) internal price;

function setPrice(uint256 tokenId) external {
    price[msg.sender][tokenId] = price;
}
function tokTransfer(uint256 tokenId) external payable {
    address owner = ownerOf(tokenId);
    require(msg.value >= price[owner][tokenId]);
    _transfer(owner, msg.sender, tokenId);
    AddressUpgradeable.sendValue(from, msg.value);
 }
 ```
 
 This would be "safe"

**Comment by JF0001** [comment]
Thank you again @Amxx for your continued support and for your code. Everything is now working properly and I am relieved that the OpenZeppelin library is working exactly as expected!

**Comment by JF0001** [comment]
Hi @Amxx I had the following questions regarding your code:

1) From your code, a user would need to "register" the selling price on the blockchain, which costs gas. Would you know how does marketplace such as OpenSea actually implement the ability for a user to specify the selling price on the front-end Dapp portal without having to go to the blockchain? Do they limit the ability to send a transaction to the blockchain to their Dapp somehow?

2) You are using the `_transfer` function, which from my understanding requires the owner to send the transaction. However, in a marketplace, the owner wouldn't be "present" during a transaction, in which the said transaction would be initiated by the purchaser. Shouldn't the `transferFrom` function be used in this case instead?

Thank you again for your valuable help. J
