### ISSUE TITLE
[storage optimization] contracts/finance/VestingWallet.sol - pack time variables into same memory slot with address

### ISSUE THREAD

**Issue by SvenMeyer** [OpenZeppelin/openzeppelin-contracts#2987]
I would suggest to change `_duration` to `uint32` which would still allow a vesting duration of max ~ 136 years.

This will allow the compiler to put all these values into one (instead of 2) 256 bit storage slots.

```
    address private immutable _beneficiary; // 160 Bit
    uint64 private immutable _start;        //  64 Bit
    uint32 private immutable _duration;     //  32 Bit 
```

Alternative : change `_start` and `_duration` both to `uint48`

**Comment by Amxx** [comment]
Hello @SvenMeyer 

two things to say here:
- Changing storage layout is not something we would do lightly, as it would break backward compatibility of the upgradeable version of the contracts.
- These variables are marked as immutable, as a consequence they are never put into storage anyway, so changing the type here would have absolutely no effect (these havues are never sload-ed).
