### ISSUE TITLE
Optimize memory allocation in MerkleProof

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#2989]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7d17acfb2f12be0a2ad4c08ad4a3d823704b68d6/contracts/utils/cryptography/MerkleProof.sol#L42-L48

`abi.encodePacked` allocates a new memory location on every iteration. This is incredibly wasteful. For this code in particular we don't even need to allocate new memory, since we're hashing exactly two words, we can use the scratch space in memory.

**Comment by Amxx** [comment]
Since both values are bytes32, I expect the resulting hash would be the same, right ? (otherwise it would be a breaking change)

I that is the case, and if the resulting code is more memory efficient, then we should merge that.

**Comment by Amxx** [comment]
I tried using both `abi.encode` and `abi.encodePacked`. With optimizations, running and deploying codes are identical (I believe the produced bytecode is the same).

Would you like to use assembly?

**Comment by frangio** [comment]
Yeah I don't think we have an alternative than using assembly, but we should localize it to a helper function that hashes 2 bytes32 words using the scratch space in memory.

**Comment by hack3r-0m** [comment]
@frangio would something like this work? i can open PR with comparision of performace

```solidity
function efficientHash(bytes32 a, bytes32 b) internal pure returns (bytes32) {

    assembly {
        mstore(0x00, keccak256(a, b))
        return(0, 0x20)
    }
}
 ```

**Comment by hack3r-0m** [comment]
thanks @frangio for helping
```solidity
function efficientHash(bytes32 a, bytes32 b) public pure returns (bytes32 value) {

    assembly {
        mstore(0x00, a)
        mstore(0x20, b)

        value := keccak256(0x00, 0x40)
    }
}
```
I tried the above functions with a few random inputs and it seems to work. what would be the best way to return value from a function without aborting execution? I checked yul docs but there does not seem to be way other than pushing on top of stack

**Comment by Amxx** [comment]
@hack3r-0m your proposal is very dangerous! Slots 0x00 and 0x20 of the memory are not to be used like that. In particular, I believe that slot 0x00 is reserved and should be left to zero, otherwise you would potentially be breaking things.

You need to use the free memory pointer, but not move it (I think this is the wastefully part @frangio is talink about)

A better implementation would be

```
function efficientHash(bytes32 a, bytes32 b) public pure returns (bytes32 value) {
    assembly {
        let ptr := mload(0x40)
        mstore(add(ptr, 0x00), a)
        mstore(add(ptr, 0x20), b)
        value := keccak256(ptr, 0x40)
    }
}
```

**Comment by frangio** [comment]
@hack3r-0m's proposal is correct. The 64 bytes starting at position 0 are ["scratch space for hashing methods"](https://docs.soliditylang.org/en/latest/internals/layout_in_memory.html). The zero slot is at 0x60.

Please open a PR!
