### ISSUE TITLE
Please make fields of common contract types internal, not private

### ISSUE THREAD

**Issue by lukehutch** [OpenZeppelin/openzeppelin-contracts#2990]
Contracts such as the ERC20 contract have `private` variables, which means that even if you inherit from the contract, you cannot extend the contract's behavior in meaningful ways. For example, in the ERC20 contract, you can read an account's balance through the public interface, but you can't set the balance (so derivative contracts cannot implement their own balance-changing logic).

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol

It would be great if fields marked `private` in commonly-inherited-from contracts like this could be marked `internal`, to allow derivative contracts to implement richer behavior.

**Comment by Amxx** [comment]
Hello @lukehutch 

As it as already been discussed in the issues, we make the storage variable private on purpose, exactly to prevent someone modifying them in ways that are not consistent with the ERC policy.

For balances, you already have `_mint`, `_burn` and `_transfer` that are available as internal functions. They should cover everything your need. If you start writing to the balance mapping directly, you might forget to emit the required event ... you might bypass some checks enforced in modules such as ERC20Capped, or you might altogether break modules like ERC20Votes.

IMO, most custom balances mechanisms can be implemented using _mint and _transfer. If that is not the case, then maybe you should not be using our ERC20 implementation in the first place.
