### ISSUE TITLE
OpenZeppelin Wizard with `Votes` fails to deploy on Ganache

### ISSUE THREAD

**Issue by gnomadic** [OpenZeppelin/openzeppelin-contracts#2999]
Trying to deploy an ERC20 with voting on ganache - copy pasted out of the openzeppelin wizard, but using solidity 0.8.10.  Deployment works fine if script doesn't extend `ERC20Permit` and `ERC20Votes`.  

 * This error also occurs when using solidity "0.8.2, which is what's supplied in the wizard
 * This error also occurs with a shorter token name
 * This error also occurs with an empty constructor (disabled premint)

```
Error:  *** Deployment Failed ***

"MoonDust" hit an invalid opcode while deploying. Try:
   * Verifying that your constructor params satisfy all assert conditions.
   * Verifying your constructor code doesn't access an array out of bounds.
   * Adding reason strings to your assert statements.
```

**💻 Environment**

Windows 10, linux sub system.
    "@openzeppelin/contracts": "^4.4.0",
    "truffle": "5.4.23",
    "solc":0.8.10

**📝 Details**

I have to assume the issue is with the constructor of /contracts/utils/cryptography/draft-EIP712.sol - that is the only place I can see where this error is possible?

**🔢 Code to reproduce bug**

```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.10;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/draft-ERC20Permit.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Votes.sol";

contract MoonDust is ERC20, Ownable, ERC20Permit, ERC20Votes {
    constructor() ERC20("MoonDust", "DUST") ERC20Permit("MoonDust") {
        _mint(msg.sender, 200000000 * 10 ** decimals());
    }

    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
    }

    // The following functions are overrides required by Solidity.

    function _afterTokenTransfer(address from, address to, uint256 amount)
        internal
        override(ERC20, ERC20Votes)
    {
        super._afterTokenTransfer(from, to, amount);
    }

    function _mint(address to, uint256 amount)
        internal
        override(ERC20, ERC20Votes)
    {
        super._mint(to, amount);
    }

    function _burn(address account, uint256 amount)
        internal
        override(ERC20, ERC20Votes)
    {
        super._burn(account, amount);
    }
}
```

**Comment by Amxx** [comment]
Hello @gnomadic 

I'm able to deploy the code you provide, without any modification whatsoever, on remix. 

What version of ganache are you using? 
```Ganache CLI v6.12.2 (ganache-core: 2.13.2)```

Is it configured to use an older version of the EVM?

**Comment by Amxx** [comment]
Not that `ERC20Votes` depends on `ERC20Permit` which depends on `EIP712` which computes the domain separator during construction.

This domain separator depends on the chainId oppcode which was introduced by EIP1344. This EIP was part of the Istanbul hard fork that hit mainnet in December 2019.

**Comment by gnomadic** [comment]
Wow, thank you.  I'm using the Ganache UI, and it was set to the Petersburg hard fork.  I changed that to Istanbul, and now it works.  💯 I appreciate your time, sorry for the rookie mistake!
