### ISSUE TITLE
[ Feature request ] Dark theme

### ISSUE THREAD

**Issue by ghost** [OpenZeppelin/openzeppelin-contracts#3004]
**🧐 Motivation**

**📝 Details**

Adding a dark theme would be good.

**Comment by Amxx** [comment]
I may have closed that too promply. Are you talking about the wizard ? The documentation ?

**Comment by frangio** [comment]
The account that posted this seems to have been deleted?

I'd say anyone interested in a dark theme please open an issue in the relevant repository. [Wizard](https://github.com/OpenZeppelin/contracts-wizard) or [docs](https://github.com/OpenZeppelin/docs.openzeppelin.com).
