### ISSUE TITLE
NFT minted using ERC721URIStorage shows totalSupply 0 on Etherscan

### ISSUE THREAD

**Issue by takwaiw** [OpenZeppelin/openzeppelin-contracts#3013]
I followed the https://docs.openzeppelin.com/contracts/4.x/erc721 to create a simple NFT contract. When I mint the token, Etherscan shows totalSupply is 0.

**💻 Environment**

OpenSzeepelin: 4.4.0
Brownie

**📝 Details**

Since ERC721URIStorage does not implement totalSupply, it always show 0. totalSupply shoule be 1 because I just minted the token. I see that totalSupply is declared on the IERC721Enumerable interface. I will submit a PR with a new wrapper contract that returns the correct totalSupply.

**🔢 Code to reproduce bug**

// Use the example https://docs.openzeppelin.com/contracts/4.x/erc721
// Or the following contract:

// SPDX-License-Identifier: MIT
pragma solidity >=0.6.6 <0.9.0;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract SimpleCollectible is ERC721URIStorage {
    using Counters for Counters.Counter;
    Counters.Counter private tokenIds;

    constructor() ERC721("Doggie", "DOG") {}

    function createCollectible(string memory tokenURI)
        public
        returns (uint256)
    {
        uint256 newTokenId = tokenIds.current();
        _mint(msg.sender, newTokenId);
        _setTokenURI(newTokenId, tokenURI);
        tokenIds.increment();
        return newTokenId;
    }
}

=========================================
# brownie deploy.py:

from brownie import SimpleCollectible
from scripts.helpful_scripts import get_account, OPENSEA_URL

SAMPLE_TOKEN_URL = "https://ipfs.io/ipfs/Qmd9MCGtdVz2miNumBHDbvj8bigSgTwnr4SbyH6DNnpWdt?filename=0-PUG.json"

def deploy_simple_collectible():
    print("Deploying SimpleCollectible DOG...")
    account = get_account()
    simple_collectible = SimpleCollectible.deploy({"from": account})
    tx = simple_collectible.createCollectible(SAMPLE_TOKEN_URL, {"from": account})
    tx.wait(1)
    tokenId = simple_collectible.getLastTokenId()
    print(
        f"You can view your NFT at {OPENSEA_URL.format(simple_collectible.address, tokenId)}"
    )
    print("May need to wait up to 20 mintes, and hit the refresh button.")

def main():
    deploy_simple_collectible()

==================================

# helpful_scripts.py

from brownie import accounts, config, network

FORKED_LOCAL_ENVIRONMENTS = ["mainnet-fork", "mainnet-fork-dev"]
LOCAL_BLOCKCHAIN_ENVIRONENTS = [
    "development",
    "geth-dev",
    "hardhat",
    "hardhat-fork",
    "ganache-local",
]
OPENSEA_URL = "https://testnets.opensea.io/assets/{}/{}"

def get_account(index=None, id=None):
    if index:
        return accounts[index]
    if id:
        return accounts.load(id)
    if (
        network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONENTS
        or network.show_active() in FORKED_LOCAL_ENVIRONMENTS
    ):
        return accounts[0]
    return accounts.add(config["wallets"]["from_key"])

**Comment by Amxx** [comment]
Hello @takwaiw 

AFAIK, the total supply visible on etherscan is computed base on the number of existing tokens (if any) or by the `totalSupply()` function is available.

This is why [this token](https://etherscan.io/token/0x6d0de90cdc47047982238fcf69944555d27ecb25) (that is ERC721Enumerable) shows a total supply of 445 (at the time of writing this message) while [this other token](https://etherscan.io/token/0xe9f3037c7e035ab4ad286ccb6ce0be60836446cf), that implements its own fixed `totalSupply()` function, shows 10000.

This all has nothing to do with `ERC721URIStorage` but with the presence or absence of the `totalSupply()` function, and what you decided to have it return.

**Comment by takwaiw** [comment]
Thanks for the explanation. Sorry, I'm new to this space. Very eager and excited to contribute, so I jumped in without fully understanding the semantics of totalSupply. When I minted my own NFT using the OpenZeppellin ERC721URIStorage version 4.4.0, it wasn't shown on OpenSea. While trying to figure out what's wrong, I noticed that the totalSupply in Etherscan always show 0, even days later. I then dropped back to ERC721URIToken version 3.x - OpenSea picked it up. When Iooked at Etherscan, the totalSupply is 1. That made me think that totalSupply is a required function that is missing in ERC721URIStorage.

Here is an example of totalSupply 0 when minted with version ERC721URIStorage 4.x:
https://rinkeby.etherscan.io/token/0xce0091d9d5cc59bf5d604488b7f1855f6d9132a8

Minted with my version that implements totalSupply: https://rinkeby.etherscan.io/token/0xd271ed7c0e52ab9cb0beeac72c03875737d2cb4a

If I inherit from ERC721URIStorage version 4.x, and I don't implement totalSupply, it looks like it is always 0. Is that an expected behavior?

**Comment by takwaiw** [comment]
I see. Got it. I will check out the wizard. Thanks!

**Comment by alijafri001** [comment]
> `ERC721URIStorage` is absolutely not related to all of this.
> 
> In version 3.x, `ERC721` included the full interface, including the enumerability part. In version 4.x, `ERC721` doesn't include enumerability by default, and the `totalSupply()` function is thus not present. In 4.x, if you want the supply tracked, you need to enable the `ERC721Enumerability` module in addition to any other module that you may have.
> 
> [I strongly encourage you try out the wizard for that](https://wizard.openzeppelin.com/#erc721)

Ohh man, really does the job without manually checking what to override , thanks mate
