### ISSUE TITLE
Comment in contracts

### ISSUE THREAD

**Issue by vittominacori** [OpenZeppelin/openzeppelin-contracts#3026]
Release version in each contract cause a very bad compare view https://github.com/OpenZeppelin/openzeppelin-contracts/compare/v4.4.0...v4.4.1.

It seems that 141 files changed but only that comment changed.

I think that it could be better to not to have this in each contract. It adds explicit version in each file but lot of redundancy.

**Comment by Amxx** [comment]
it is on our roadmap to detect which file has been modified since the last release, and only bump these one.

**Comment by frangio** [comment]
Polluting the compare view is a good point we didn't consider. We're looking into this now.

I'm curious @vittominacori, in what situations do you use the compare view?

**Comment by vittominacori** [comment]
I use after each new release to see what is changing in order to update my contracts if they use something you updated. 

Anyway I have some projects where I use flattened code so also changing nothing it results as lot of code changes when just updating open-zeppelin.
