### ISSUE TITLE
Update pragma for `Address.sol` util to ^0.8.1 upwards

### ISSUE THREAD

**Issue by koolamusic** [OpenZeppelin/openzeppelin-contracts#3031]
Referencing this PR https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3025 as @axic  had mentioned In `0.8.0` version of solidity the `account.code.length` syntax is supported, but the compiler does not have the shortcut implemented. This means it will first `extcodecopy` the entire target contract and measure size afterwards.

Following the guidelines with pragma version in OZ, my recommendation would be to create a new PR to update the pragma to  `^0.8.1`
cc @Amxx

**Comment by frangio** [comment]
From https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3025#issuecomment-996007519:

> My vote in this particular case is to bump this pragma to 0.8.1.
> 
> - It's always good to remove assembly.
> - 0.8.1 is already almost a year old, I expect most users on 0.8 are using newer versions.
> - 0.8.0 to 0.8.1 is unlikely to be very disruptive.
> 
> It should be noted as a breaking change in the changelog.
