### ISSUE TITLE
not found: File import callback not supported once again

### ISSUE THREAD

**Issue by stoplion** [OpenZeppelin/openzeppelin-contracts#3048]
Identical to this [closed issue](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2708).

**💻 Environment**

OZ 4.4.1
Macintosh

**📝 Details**
**Importing these contracts results in this bug:**
```
//Contract based on [https://docs.openzeppelin.com/contracts/3.x/erc721](https://docs.openzeppelin.com/contracts/3.x/erc721)
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/utils/Counters.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
```
```
"@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol" not found: File import callback not supported
```

**🔢 Code to reproduce bug**

**Comment by frangio** [comment]
This is not an issue of the library, but a standard compiler error that indicates a problem in your code or environment. If you're trying to verify on Etherscan look at our [guide in the forum](https://forum.openzeppelin.com/t/how-to-verify-a-contract-on-etherscan-bscscan-polygonscan/14225), if you're compiling locally on your computer make sure that you installed using npm and that you installed the right version.
