### ISSUE TITLE
[Ownable] Allow non msg-sender ownable to initialize contract as Owner

### ISSUE THREAD

**Issue by iainnash** [OpenZeppelin/openzeppelin-contracts#3049]
**🧐 Motivation**
Recently, I've been using Ownable and OwnableUpgradeable to set ownership of contracts other than the deployer.

The pattern used is something like:
```
constructor(address newOwner) {
  transferOwnership(newOwner);
}
```

Which emits to `transferOwnership` events.

Especially for upgradable contracts this is useful.

**📝 Details**

Add in a new constructor argument to the upgradeable contracts that allows a different initial owner to be set.

**Comment by Amxx** [comment]
Hello @iainnash 

This has already been discussed in 
#2402
#2639
#2647

**Comment by iainnash** [comment]
Whoops @Amxx my bad, i was thinking of posting on `contracts-upgradeable` since the function overloading issue doesn't exist with that fork and this is a more common issue. However, i'm not sure if that works with the idea that the fork needs to be 100% compat with this core version.
