### ISSUE TITLE
Order of code in transferFrom function

### ISSUE THREAD

**Issue by MatHatter** [OpenZeppelin/openzeppelin-contracts#3055]
Shouldn't the require statement in the `transferFrom` function come before `_transfer`?https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol

**Comment by MatHatter** [comment]
Also, what is the difference between: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v3.4.0/contracts/token/ERC20/ERC20.sol and https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol, which one should I be using?

**Comment by ivanmlerner** [comment]
I think it does not matter which order you choose since "require" will revert all state changes.

**Comment by MatHatter** [comment]
Ok, thanks
