### ISSUE TITLE
Declare constructors as `payable` to save gas

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/openzeppelin-contracts#3059]
**🧐 Motivation**
You can cut out 10 opcodes in the creation-time EVM bytecode if you declare a constructor `payable`. The following opcodes are cut out:

- `CALLVALUE`
- `DUP1`
- `ISZERO`
- `PUSH2`
- `JUMPI`
- `PUSH1`
- `DUP1`
- `REVERT`
- `JUMPDEST`
- `POP`

In Solidity, this chunk of assembly would mean the following:
```
if(msg.value != 0) revert();
```

I also added it here: https://forum.openzeppelin.com/t/a-collection-of-gas-optimisation-tricks/19966/5?u=pcaversaccio

**Comment by frangio** [comment]
Thanks for the suggestion @pcaversaccio!

I don't think we're going to implement this, as making constructors payable enables a kind of error that can result in loss of funds.

Note that a developer intent on taking on this risk for the gas optimization is able to make the constructor `payable` via inheritance to get the same benefit. (The constructor being payable or not is a "global" property of a contract.)
