### ISSUE TITLE
Cannot override internal virtual AccessControl functions referencing private field _roles

### ISSUE THREAD

**Issue by ackvf** [OpenZeppelin/openzeppelin-contracts#3064]
Hi, I am new here, so forgive me if I am missing something obvious.

I am trying to override an `internal virtual` function that is, by definition of the keyword `virtual` intended to be overridden, however, the variable `_roles` they are all referencing is private and therefore can't be referenced in the overriding function, effectively preventing me from overriding the functions themselves.

In my limited view, the state variable `_roles` should be `internal` as well.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ef0273fde16fa4e6ea2096782dceb66ef589a811/contracts/access/AccessControl.sol#L55

**Comment by Amxx** [comment]
Hello @ackvf 

The choice of `private` visibility as already been discussed many times. #2990

Can you give more details about what override you would like to do, that you cannot ? We expect overrides to be able to perform the required storage operation using super, as demonstrated in [AccessControlEnumerable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControlEnumerable.sol)
