### ISSUE TITLE
Context.sol updated with msg.value

### ISSUE THREAD

**Issue by MaxflowO2** [OpenZeppelin/openzeppelin-contracts#3066]
**🧐 Motivation**

yes just one... in Context.sol we have internal getters for msg.sender and msg.data, but none for msg.value

**📝 Details**

add these lines of code to Context.sol

```
    function _msgValue() internal view virtual returns (uint) {
        return msg.value;
    }
```

**Comment by Amxx** [comment]
Hello @MaxflowO2 

The reason for `_msgSender` and `_msgData` is that there are cases, such as with ERC2771 meta-transaction relaying, where the "base" values (`msg.sender` and `msg.data`) should not be used as is. AFAIK, there is no equivalent issue with `msg.value`.

Also, there are cases, such as when doing a multicall (by delegating to self in a loop), where the use of `msg.value` is dangerous, and I fear having a `_msgValue` would be interpreted as fixing that when it doesn't.

Do you have a particular usecase in mind, maybe on some L2, or do you propose that only for completeness?

**Comment by frangio** [comment]
Assuming it was proposed for completeness. But for now we don't have a use case that would require this.

The only thing that comes to mind is mocking values for testing, like we might need to do with block.timestamp and so on. But until we need this I don't think we should add it.
