### ISSUE TITLE
Fix ERC721 usage example in docs

### ISSUE THREAD

**Issue by v0xat** [OpenZeppelin/openzeppelin-contracts#3068]
An example of how to use ERC721 contract on page https://docs.openzeppelin.com/contracts/4.x/erc721#constructing_an_erc721_token_contract seems not working.

It gives me the following errors:
`Derived contract must override function "_burn". Two or more base classes define function with same name and parameter types.`
`Derived contract must override function "tokenURI". Two or more base classes define function with same name and parameter types.`

Looks like it's because `GameItem` contract derives from both ERC721 and ERC721URIStorage, but the ERC721URIStorage also derives from the ERC721, so maybe this example should be edited.

**Comment by Amxx** [comment]
Hello @v0xat 

Thank you for pointing that! We'll update the documentation to fix that. In the meantime, if you need more help creating an ERC721 token, I encourage you check out [the wizard](https://wizard.openzeppelin.com/).
