### ISSUE TITLE
ERC20BurnableTransfer

### ISSUE THREAD

**Issue by Metarei-network** [OpenZeppelin/openzeppelin-contracts#3069]
**🧐 Motivation**
Hi, 
I recently used openzepplin-contracts/ERC20Burnable for my start-up Metarei.net, I found the code and documentation to be excellent thank you. Additionally I wanted to create demand for my token and provide a supplementary income by burning some tokens from each transfer. 

Does this feature interest you? if so what are you expectations for the submission? I suppose: 

- contract
- truffle tests
- documentation

**📝 Details**
The contract overrides ERC20 transfer method with a call to burn a specified fraction. It allows the owner to set the fraction that is burned and exposes a field which is a count of the total burned for the life of the contract.

Please see [ERC20BurnableTransfer](https://github.com/Metarei-network/openzeppelin-contracts/blob/ERC20BurnableTransfer/contracts/token/ERC20/extensions/ERC20BurnableTransfer.sol)

Thank you

Tom

**Comment by Amxx** [comment]
Hello @Metarei-network 

IMO your implementation is erroneous. By overriding transfer, you are designing your contract such that anyone could use `transferFrom` to bypass the burning mechanism.

If anyone was interested in doing burns on transfers, he should do that in the `_transfer` internal function. I'm pretty sure this has been discussed multiple time in the forum, with code example.

One of the reason we are not providing this, is we believe this is a dangerous thing to do, that might break interoperability with a lot of contracts that handle tokens. If you known what you are doing, understand the consequences, and do in depth compatibility testing ... then feel free to do it ... but we want to avoid less experienced devs from doing things that might have consequences they do not understand.

**Comment by Metarei-network** [comment]
Hi Amxx,

This is great feedback thank you I will look at the implementation again before proceeding. 

Have a great 2022
