### ISSUE TITLE
ERC20HalvingReleaseSchedule

### ISSUE THREAD

**Issue by Metarei-network** [OpenZeppelin/openzeppelin-contracts#3070]
**🧐 Motivation**
Hi, 
I recently used openzepplin-contracts/ERC20Capped for my start-up Metarei.net, I found the code and documentation to be excellent thank you.

Additionally I wanted to have a simple unlock mechanism that would gradually release the token supply to make it more difficult for speculators to control price and allow us to get a better average sale price as we mature and develop the products.

If this feature interests you please let me know and I will raise a PR. 

**📝 Details**
The contract take an additional 'unlocks' parameter which is an array of unix timestamps. The mint function uses a similar algo as BTC in that there is a halving of the released supply at each unlock. 

Once the unlocks have passed the owner can call mint at any time and will issued whatever tokens are available from burning for example. 

Please see [ERC20HalvingReleaseSchedule](https://github.com/Metarei-network/openzeppelin-contracts/blob/ERC20HalvingReleaseSchedule/contracts/token/ERC20/extensions/ERC20HalvingReleaseSchedule.sol)

Thank you

Tom

**Comment by Amxx** [comment]
Hello @Metarei-network 

As far as token release goes, we already include vesting contracts. My go to solution would thus be to mint whatever you want (during the constructor ?) and have these tokens owner by a vesting wallet that will control the release. To implement your particular schedule you might need to override the [`_vestingSchedule`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/finance/VestingWallet.sol#L126-L134) function. But it should be relatively easy.

You proposal might work for your particular case, but IMO it loses a lot of the generality that we want to have with our contracts. In particular, you are tightly coupling ERC20 with Ownable ... also you are considering a very specific halvening flow with unlock timestamp ... which might be good for you, but is not generic at all.

In the end, I would argue that your implementation is very specific to a particular release schedule, but would have to be significantly re-writtend is anyone wanted to modify it. Our approach is to provide "mostly ready to use" contract. and anything that needs to be significantly re-written to be specialized isn't where we want to go.

**Comment by Metarei-network** [comment]
Hi Amxx, 

Thanks for the reply, that's fair enough.

Cheers
