### ISSUE TITLE
DisposableAccessCode

### ISSUE THREAD

**Issue by Metarei-network** [OpenZeppelin/openzeppelin-contracts#3071]
**🧐 Motivation**
Hi, 
I recently used Openzepplin-contracts for my token sale contract, I found the code and documentation to be excellent thank you. 

Additionally I wanted to be able to operate a private sale before going public so I created a contract that uses a simple disposable passphrase mechanism

Does this feature interest you? If so I'm happy to raise a PR. 

**📝 Details**
Please see [DisposableAccessCode](https://github.com/Metarei-network/openzeppelin-contracts/blob/DisposableAccessCode/contracts/security/DisposableAccessCode.sol)

Thank you

Tom

**Comment by Amxx** [comment]
Hello @Metarei-network 

I'm currious about the usecase for this feature. Is something similar used in any live protocol?
Also, I'm worried that this is not really safe, as any transaction that passes the "phrase" is susceptible to being front-run.

IMO the interested is limited, the security assumption are not simple, and it would be extremely simple for someone that needs that (and understand the consequences) to implement it itself. Thus I'm not really sure it should be part of our contracts.

Side note: for gas optimisation, you could remove the `isPrivate` variable and replace it with `code != bytes32(0)`

**Comment by Metarei-network** [comment]
HI Amxx, 

Thanks for the reply, I'm embarrassed to say I had not thought of this. "phrase is susceptible to being front-run"

No the project isn't live yet glad to say I wanted to give something back first and here we are. 

Very much appreciate your feedback its a valuable lesson, cheers.
