### ISSUE TITLE
ERC721: Release missing '_afterTokenTransfer' function

### ISSUE THREAD

**Issue by zeeshanhanif** [OpenZeppelin/openzeppelin-contracts#3074]
**💻 Environment**

Using Version 4.4.1 with Hardhat

**📝 Details**

Implementation of ERC721 includes `_afterTokenTransfer` function which is available on main repo but the release of 4.4.1(which is the latest one) does not include this function. And because of this we can not override `_afterTokenTransfer`

**Comment by Amxx** [comment]
Hello @zeeshanhanif 

`_afterTokenTransfer` was introduced as part of #2944. This is going to be released in the next version (in the next few weeks)

**Comment by zeeshanhanif** [comment]
Thanks, understood
