### ISSUE TITLE
ERC721: document no access control in _burn function 

### ISSUE THREAD

**Issue by 7harshit20** [OpenZeppelin/openzeppelin-contracts#3088]
**📝 Details**

The _burn function in ERC721.sol does not have require statement to check if the sender is either owner or approved. If the function is used directly then the user can burn any token. 

current implementation of _burn function: 

    function _burn(uint256 tokenId) internal virtual {
        address owner = ERC721.ownerOf(tokenId);

        _beforeTokenTransfer(owner, address(0), tokenId);

        // Clear approvals
        _approve(address(0), tokenId);

        _balances[owner] -= 1;
        delete _owners[tokenId];

        emit Transfer(owner, address(0), tokenId);

        _afterTokenTransfer(owner, address(0), tokenId);
    }

**Comment by frangio** [comment]
This is standard for our internal functions, they don't have access control requirements so they can be used in flexible ways (e.g. an NFT contract can establish its own rules for when a contract can be burned).

I can see there is possibility for error though so we should have a clear mention of this in the documentation.

**Comment by Niceural** [comment]
Hi! Does this issue need a pr?
