### ISSUE TITLE
Error when inherit from ERC721Enumerable and ERC721Burnable at the same time

### ISSUE THREAD

**Issue by yieniggu** [OpenZeppelin/openzeppelin-contracts#3107]
Getting this error when inherit from ERC721Enumerable and ERC721Burnable at the same time:
`
Derived contract must override function "_beforeTokenTransfer". Two or more base classes define function with same name and parameter types.`

`Derived contract must override function "supportsInterface". Two or more base classes define function with same name and parameter types.
`

Code: 

```
contract UndergroundGen0PreMint is
    ERC721Enumerable,
    ERC721Burnable,
    Ownable
{}
```
OZ version: master, fresh npm install of @openzeppelin/contracts on jan 12 at 20:45 utc-3
solc version: ^0.8.0

**Comment by Amxx** [comment]
Hello @yieniggu 

`ERC721Enumerable` and `ERC721Burnable` both override the `_beforeTokenTransfer` and `supportsInterface` functions. Solidity requires you to "fix" that overriding conflict. If we were able to address that in our contract we would, but its a solidity requirement that the child contract explicitly resolves this.

If you are not sure how to do, check the [Wizard](wizard.openzeppelin.com/).
