### ISSUE TITLE
Add multiProofVerify to MerkleProof.sol

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#3108]
Code is already available [here](https://github.com/miguelmota/merkletreejs-multiproof-solidity).

Would open new airdrop mechanisms.

**Comment by balajipachai** [comment]
@Amxx 
This is mostly adding multiProofVerify to MerkleProof.sol and ensuring that the previous tests plus the tests for multiProofVerify don't break, right?

**Comment by frangio** [comment]
@balajipachai Yes!

**Comment by khanjasir90** [comment]
@frangio can i take this one!

**Comment by colinjhicks** [comment]
@khanjasir90 I started working on this and made a PR for review to see if I'm on the right track. I'm new to blockchain and making contributions so maybe we could collaborate on this if you'd like.

**Comment by khanjasir90** [comment]
Yes sure!
