### ISSUE TITLE
Unable to import "@openzeppelin/contracts/access/Ownable.sol"; into my smart contract

### ISSUE THREAD

**Issue by varunponda** [OpenZeppelin/openzeppelin-contracts#3116]
I have successfully installed openzeppelin/contracts, but I am unable to import it. It shows me an error which is 
`Source "@openzeppelin/contracts/access/Ownable.sol" not found: File import callback not supported`
Does anyone have any idea? Thanks

**Comment by usmanatechy** [comment]
use this -->import "../node_modules/zeppelin-solidity/contracts/ownership/Ownable.sol";

**Comment by Amxx** [comment]
Hello @varunponda 

I think your question would be better fitted to the [OpenZeppelin forum](https://forum.openzeppelin.com/). Please make sure you give details about your environment and tooling, as this will affect the answer.
