### ISSUE TITLE
ERC721 optimised for sequential id and no burn

### ISSUE THREAD

**Issue by aalmada** [OpenZeppelin/openzeppelin-contracts#3118]
**🧐 Motivation**

The high values for gas fees when minting has been a big issue. [There have been some suggestions on how to lower these](https://shiny.mirror.xyz/OUampBbIz9ebEicfGnQf5At_ReMHlZy0tB4glb9xQ0E) when using the `ERC721` contract but then these are limited to the implementation of this same contract.

The `ERC721` contract is rightfully a general implementation but there's one case where it should be possible to considerably reduce the gas usage.  I believe this is a very common case.

**📝 Details**

For the case when using sequential ids and there's no support for burning tokens the following optimizations for `ERC721` are possible:

1. `_owners` can be an array instead of a mapping.

https://github.com/aalmada/openzeppelin-contracts/blob/44d55cfe3298d563a63df7b5d67711312810112b/contracts/token/ERC721/ERC721Lite.sol#L32

2. `exists()` can just check if the `tokenId`is smaller than `_owners.length`

https://github.com/aalmada/openzeppelin-contracts/blob/44d55cfe3298d563a63df7b5d67711312810112b/contracts/token/ERC721/ERC721Lite.sol#L233-L235

3. `mint()` can generate the `tokenId` from the value of `_owners.length` and `_owners` can be updated by using `_owners.push(to)`

https://github.com/aalmada/openzeppelin-contracts/blob/44d55cfe3298d563a63df7b5d67711312810112b/contracts/token/ERC721/ERC721Lite.sol#L289-L302

`ERC721Enumerable` can also be optimized:

1. `_allTokens` and `_allTokensIndex` can be removed.

2. `totalSupply()` can return the `_owners.length` from `ERC721` exposed as an internal `_totalSupply()` method.

https://github.com/aalmada/openzeppelin-contracts/blob/44d55cfe3298d563a63df7b5d67711312810112b/contracts/token/ERC721/extensions/ERC721LiteEnumerable.sol#L40-L42

3. `tokenByIndex()` can simply return the `index` value

https://github.com/aalmada/openzeppelin-contracts/blob/44d55cfe3298d563a63df7b5d67711312810112b/contracts/token/ERC721/extensions/ERC721LiteEnumerable.sol#L47-L50

**Conclusions**

My tests show that gas usage for minting reduces from around 161k to around 101k. I believe this can be considered a significant improvement for a very common scenario.

I'd like to know your opinions and if I should consider submitting a PR.

**Comment by Amxx** [comment]
Hello @aalmada 

There is a lot of discussion around the gas usage of ERC721 lately, and we appreciate the clarity of your approach. We understand that in very specific cases, our implementation is not the most gas effective. Sequential tokens minting with no burn is definitely one of these specific cases.

We care a lot about the versatility and backward compatibility of our codebase. For this reason, we don't think it would be reasonable to deprecate our current proposal. AFAIK, nobody is asking for that anyway.
 
If we were to provide an implementation optimized for this specific case, we would be splitting our codebase, with unclear compatibility with ERC721 modules (voting being the last one). I don't think this is optimal.

An opinion that we have shared, and that we will continue to share, is that ERC721Enumerable should not be used unless absolutely necessary. I have personally never seen any situation where it was actually needed. If you don't include Enumerability, our (generic) implementation is as cheap as any other (that is focused on "batch-minting") within the margin or error.

My answer to your issue would then be:
- We strongly encourage the community to build and distribute contracts that are optimized specific requirements (at our generic contracts are not optimized for)
- Please please please, don't use enumerability unless you really need to. And if you don't need it, then benchmark other implementations against our "core" erc721 contract.

**Comment by Amxx** [comment]
Linking [this post with gas reports](https://forum.openzeppelin.com/t/erc721enumerable-gas-optimization/22795/3) as a reference.

**Comment by frangio** [comment]
> ERC721Enumerable should not be used unless absolutely necessary. I have personally never seen any situation where it was actually needed.

If somebody knows something about this that we're missing, please let us know...

The only place I know that requires enumerability (last time I checked) was the "total supply" field in Etherscan, that shows up as 0 unless the token is enumerable. This is relatively a big deal but I would argue that Etherscan is doing the wrong thing here... `totalSupply` is only available in the enumerable extension, and the enumerable extension is necessarily more expensive, as there is a lot more bookkeeping that becomes necessary.

One thing we could consider and I think I've mentioned before is we could have an `ERC721TotalSupply` with _only_ total supply, if this makes Etherscan happy. But they could infer total supply from the `Transfer` events as well.

**Comment by frangio** [comment]
What you're saying implies that using events to infer total supply may lead to an inaccurate number. But if `totalSupply` is not available that's the best thing you can do.

Our potential `ERC721Supply` contract would not support that, totalSupply would track the minted supply, but this is fine, if someone wants something else they can write their own totalSupply function.

**Comment by aalmada** [comment]
Hi! Thanks for the feedback. 

My proposal includes optimizations for both `ERC721` and `ERC721Enumerable`. I agree that `Enumerable` should be avoided when possible but, for those that can't, I included it in the proposal.

I understand the rationale of avoiding too many versions and keeping backward compatibility. Still, I wanted to share the ideas.

As a side note, just because you raised the `Enumerable` scenarios, I'm actually using it to list the owned tokens on a custom website. I thought about taking that information off-chain but then struggled to find a robust solution. A possible solution is to [use the OpenSea API](https://docs.opensea.io/reference/getting-assets). IMHO, this has two problems. It depends on a centralized service and the metadata updates are not instantaneous. They take a long time to update it after a "reveal". Using the proposed optimizations, I decided to keep it on-chain.

**Comment by frangio** [comment]
@aalmada Did you consider using TheGraph?

**Comment by Amxx** [comment]
[shameless advertisement for my generic subgraph](https://thegraph.com/explorer/subgraph?id=0x7859821024e633c5dc8a4fcf86fc52e7720ce525-0&view=Playground)

It indexes all ERC721 contracts on mainnet, and you can easily build equivalent instances for other chains using our @openzeppelin/subgraphs toolkit.

**Comment by aalmada** [comment]
I haven't tried TheGraph yet. Thanks for the suggestion.
