### ISSUE TITLE
Improve clarity of error messages in functions checking token ownership

### ISSUE THREAD

**Issue by MarcelCutts** [OpenZeppelin/openzeppelin-contracts#3120]
**🧐 Motivation**
Good morning folks. I feel this somewhat walks the line between feature and bug.

While extending some `.*transfer()` functionality in the OpenZeppelin contracts (thank you for providing them!) I found some of my tests failing due to an error reading:

```
ERC721: transfer caller is not owner nor approved
```

As a newcomer, most of the terminology of ownership in documentation and in the "higher level" contracts refers to the contract owner - with frequently used modifiers like `onlyOwner` and the `Ownable` contract reinforcing this. I spent quite some verifying that the test was indeed making calls with the owner's signature, and that signature matches the `.owner()` in the instance of the contract under test. 

After delving in a little more I found that the term "owner", in this context, refers to the _token_ owner. 

(A more dramatic reading of this experience as at the bottom for those interested in such things)

**📝 Details**
A small amount of clarification may go a long way to saving others the journey I went on myself, for example extending the error message to

```
ERC721: transfer caller is not *token* owner nor approved
```

I have a PR ready with this, and for all similar instances of such messages. Thank you for your consideration.

**Dramatic Reading**
>"But I am the owner", I whinge at the test suite, exhausted. In red, emblazoned in the flickering terminal: "'ERC721: transfer caller is not owner nor approved'" stands its ground - repeatedly unconvinced of my ownership. I checksum, and I verify. The messages are signed with poise, grace, and cryptographic correctness. The deployer is requesting the transfer. The very deployer that is also the current owner of this fine establishment.
So I dig. I fear I'll dig too greedily and too deep, and awaken something in the darkness.
"Ah." I sigh. Owner can mean owner of the contract, but this "owner" refers to a check of owner of the token.
So let this fable guide you all - don't reuse curt terminology for something that is already overloaded. All this could have been avoided with a simple
"ERC721: transfer caller is not *token* owner nor approved".

**Comment by frangio** [comment]
Hi @MarcelCutts! Thanks for the suggestion. Generally I think you have a point that the error messages could be clearer, but the trade off is that longer error messages make deployment more expensive. While I understand your frustration, I think that these errors are clear enough in this case.

**Comment by MarcelCutts** [comment]
No problem, thank you for replying and providing perspective. Perhaps one can minimise gas requirements while maximising detailed error messages through a system of error codes? It will add the unergonomic step of a user having to do the lookup, but honestly I often google the error messages I receive regardless, which amounts to the same thing with less structure.

**Comment by frangio** [comment]
Yeah, error codes are not a bad idea. We really would like to move to Solidity custom errors instead of strings though.

**Comment by frangio** [comment]
Sorry closed accidentally. Keeping open because I agree the current wording can be confusing.

**Comment by kanedaaaa** [comment]
This might sound funny, but here is your alternative without making the message too long, but keeping it more clear than what it was before:

```
ERC721: caller is not token owner nor approved
```

**Comment by frangio** [comment]
@kanedaaaa I like that! Do you want to submit a PR?

**Comment by kanedaaaa** [comment]
Haha, yes I can send one.
