### ISSUE TITLE
Fix exponentiation in the ERC20 Documentation.

### ISSUE THREAD

**Issue by 0xpranay** [OpenZeppelin/openzeppelin-contracts#3129]
The ERC20 Guide page for decimals uses bitwise XOR `^` operator instead of exponentiation operator `**` for decimals demo.

**📝 Details**

The docs use the XOR operator instead of the exponentiation operator which leads to different results when users try to produce their own implementation.

**🔢 Code to reproduce bug**

```
constructor(uint256 maxSupply) {
    _totalSupply = maxSupply * (10 ^ decimals());
    balances[msg.sender] = _totalSupply;
  }
```
Mints 24,00,000 tokens for 18 decimals and 100,000 maxSupply values. Which should instead be 1e23.

**Comment by 0xpranay** [comment]
It is the last code snippet that intends to explain the decimals use. This one exactly,
`transfer(recipient, 5 * 10^18);`

**Comment by 0xpranay** [comment]
Hey, @Amxx I see that you've made a PR that'll fix this. Turns out I was correct lol. I was doubting if I was too dumb to understand something simple or it's really a mistake. Thanks for the fix!

**Comment by frangio** [comment]
Not dumb. Thank you for pointing it out!
