### ISSUE TITLE
Opt in pull pattern instead of push pattern when transfering NFTs

### ISSUE THREAD

**Issue by jalooc** [OpenZeppelin/openzeppelin-contracts#3142]
**🧐 Motivation**
The ability to send anyone an NFT without them wanting to is problematic, because it opens door for spam.

**📝 Details**
What could solve it, is a mapping with pending token withdrawals instead of an ability to directly send them to the recipient. This mode could be opt-in, but once opt-in, it'd have to be the only possible mode of transfer - otherwise it wouldn't make sense in context of spam prevention. However it could be made opt-in not just per-contract, but also per-account, so that users could decide themselves whether to receive the NFTs instantly or to withdraw them.

A naive pseudo-implementation to illustrate the intent:
```solidity
mapping(tokenId => address) private awaitingAcceptance;

function giveAwayToken(address to, uint256 tokenId) public {
  // ownership checks etc.

  delete _owners[tokenId]
  awaitingAcceptance[tokenId] = to
}

function receiveToken(uint256 tokenId) {
  address to = awaitingAcceptance[tokenId]
  require(to == msg.sender, 'You are not the eligible recipient')

  delete awaitingAcceptance[tokenId]
  _owners[tokenId] = to; // https://github.com/OpenZeppelin/openzeppelin-contracts/blob/8f70c8867e31d2d2f212ecea079b1f1afecb0440/contracts/token/ERC721/ERC721.sol#L346
  // events and hooks etc.
}
```

**Drawbacks**
This is not in the 721 standard, so apps like OpenSea wouldn't be able to handle it by default. If, however, the community decides this is a good proposal, maybe it'd be worth to try to push it.

**Comment by Amxx** [comment]
Hello @jalooc 

This ability to mark "pending withdrawal" doesn't need any new code. Its already present in the ERC721 standard, through the approval process.

When you do `approve(address to, uint256 tokenId)` you are saying:
> I'm allowing the to address "to" receive the token "tokenid" from me

Please also note that for any discussion that is related to the evolution of an ERC, or the creation of new ERCs, you should rather submit that to [the Ethereum Magicians forum](ethereum-magicians.org/).

**Comment by jalooc** [comment]
Thanks for the explanation @Amxx 👍. I'm not fully sure that the: _"I'm allowing the to address "to" receive the token "tokenid" from me"_ functionality is what I was looking for. If I understand correctly, the `approve()` function allows **the owner** (which usually means **the sender**) to approve the receiver, right? Sounds like it in this part of [an implementation doc](https://docs.openzeppelin.com/contracts/4.x/api/token/erc721#IERC721-approve-address-uint256-): _**"The caller must own the token** or be an approved operator."_

What I was looking for, was rather a way for the recipients to allow others to have the token sent to them, which would be a way of preventing spam.

**Comment by frangio** [comment]
As a way of preventing spam, the fact that `approve` allows a pull pattern isn't enough, because @jalooc would also like a way to _disable_ push transfers.

Disabling transfers would effectively mean that the contract is not exactly ERC-721 compliant. It would not be guaranteed to work correctly with wallets, and this can cause many issues for users.

An NFT with only pull transfers would need to be a new token standard, but I think this method of spam prevention would be very easy to circumvent so it would not be effective.
