### ISSUE TITLE
Add Math.sqrt

### ISSUE THREAD

**Issue by Dentrax** [OpenZeppelin/openzeppelin-contracts#3149]
**🧐 Motivation**
It would be nice to have. Currently, we have to write our "custom" function that we can find the logic on the internet. But I'm not so sure whether those are "safe" to use.

**📝 Details**
Something like:

https://github.com/Uniswap/v2-core/blob/4dd59067c76dea4a0e8e4bfdda41877a6b16dedc/contracts/libraries/Math.sol#L11

```
math.Sqrt(16)
```

```solidity
function sqrt(uint x) constant returns (uint y) {
    uint z = (x + 1) / 2;
    y = x;
    while (z < y) {
        y = z;
        z = (x / z + z) / 2;
    }
```

In OpenZeppelin way:
```solidity
   function sqrt(uint y) internal pure returns (uint z) {
        if (y > 3) {
            z = y;
            uint x = (y.div(2)).add(1);
            while (x < z) {
                z = x;
                x = ((y.div(x)).add(x)).div(2);
            }
        } else if (y != 0) {
            z = 1;
        }
    }
```

**Comment by frangio** [comment]
Thanks for the request @Dentrax!

The reason we don't have this function currently is that it's not constant time. But I think we should take a closer look to see if there is real risk of running out of gas in the worst case, and what is the "average" cost.

It would be interesting to see smart contracts in production that are using sqrt to see if they took any special precautions and what particular implementations they used.

**Comment by Amxx** [comment]
@frangio UniswapV2 pairs use sqrt.

**Comment by frangio** [comment]
Implementation `pow` in Balancer in constant-time, can be used as `sqrt` with `y = 0.5`:

https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/solidity-utils/contracts/math/LogExpMath.sol#L89
