### ISSUE TITLE
Add a `_setBeneficiary(address)` internal function to the Vesting wallet

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#3152]
In some cases we may want the beneficiary of a vesting wallet to be updatable. This would not affect the vesting schedule, and the limited flow of tokens it produces. In other words, liquidity would remain low.

This is motivated by the fact that a beneficiary's address might be compromised and might need to be changed. Another use case is that of a project team that wants to reassure investors by limiting liquidity while keeping an admin power over who receives the token.

Currently, an implementation would look like this:

```
contract Reserve is VestingWallet, AccessControl, Ownable {
    constructor(uint64 start, uint64 duration)
        VestingWallet(address(0xdead), start, duration)
    {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
    }

    function beneficiary()
        public
        view
        override
        returns (address)
    {
        return owner();
    }

    function setBeneficiary(address newBeneficiary)
        external
        onlyRole(DEFAULT_ADMIN_ROLE)
    {
        _transferOwnership(newBeneficiary);
    }
}
```

This is functional, but because of security checks in  `VestingWallet`, it is not possible to set that slot to 0, and it is not possible to write to it.

Adding a `VestingWallet:_setBeneficiary(address)` internal function would improve the use of this storage slot.

**Comment by Amxx** [comment]
I just realized _beneficiary is immutable, so we cannot add a setter. 

This is ok for a non-upgradeable contract (I guess) ... but for the upgradeable contracts, we end up with a storage slot that the initializer will set to a non 0 value, and that cannot be modified. You can overload the accessor (as shown above) but you'll still have to pay for the initial setting :/

**Comment by frangio** [comment]
I don't think there is a way around this. Are you suggesting a change?

**Comment by Amxx** [comment]
Not really.

Basically would only make sense in the upgradeable version, but would not compile on the "vanilla" version. I'd put that under "limitation of having the upgradeable version result of transpilation" + "immutable storage becomes private".

An effective, but dirty way of doing that ends up overriding all 3 variables (start, duration, beneficiary) with storage slots that can be set ... and not calling the initializer at all.
