### ISSUE TITLE
ERC721A approach for cheaper batch mint

### ISSUE THREAD

**Issue by syffs** [OpenZeppelin/openzeppelin-contracts#3158]
**🧐 Motivation**
Much cheaper batch mint

**📝 Details**

I've dived into this implementation and I'm wondering if OZ could use [this approach](https://github.com/chiru-labs/ERC721A) to improve its ERC721.

**Comment by Amxx** [comment]
Hello @syffs 

This issue has already been discussed many times. I invite you check out [this post on the openzeppelin forum](https://forum.openzeppelin.com/t/erc721enumerable-gas-optimization/22795).
