### ISSUE TITLE
Add SafeCast for all possible uintX types

### ISSUE THREAD

**Issue by k06a** [OpenZeppelin/openzeppelin-contracts#3159]
**🧐 Motivation**
These methods are required when optimizing and tightly packing storage variables. We often use `uint40` or `uint48` for time and `uint216`/`uint208` for the rest slot value, `uint112` or `uint96` (*presented*) for storing token amounts etc

**Comment by Amxx** [comment]
Hello @k06a and thanks for the suggestion

The casting contract contains a lot of code repetition. Ideally, we would have generics (c++ templates) supported by solidity ... but we don't live in that world. So we wait for requests, and we add them one at a time, which we probably both agree is not the right way to do.

IMO, these contracts should be generated procedurally, just like I did in this repo a few years ago (https://github.com/Amxx/SolStruct). @frangio would you be open to that idea?

**Comment by frangio** [comment]
Yes as long as they are all tested. What would that look like? Do we write a script and then commit the result to the repository?

If we add all of the 32 functions we may want to review the documentation approach. Having virtually the same docstring for all 32 functions just adds noise.

**Comment by frangio** [comment]
Just took a look at SolStruct. I wouldn't follow this approach, it's too custom. I think either we use solpp or we just write a simple JavaScript program to generate the code (without using templates).

**Comment by Amxx** [comment]
Yes, I would have gone for a JS generator. SolStruct was just an example of procedural generation.
