### ISSUE TITLE
ERC721 Contract for 1NFT with 1000 copy

### ISSUE THREAD

**Issue by igensis** [OpenZeppelin/openzeppelin-contracts#3163]
Hi Friends 
i'm asking if you can suggest me a contract for 1 NFT image with 1000 copy for the same nft with openzeppelin
i hope you help me thanks

**Comment by Amxx** [comment]
Hello @igensis 

For this kind of enquiry, I suggest you go to the [forum](https://forum.openzeppelin.com/). There is a [smart contract section](https://forum.openzeppelin.com/c/smart-contracts/39) for generic smart contract sections.
