### ISSUE TITLE
 event ERC20PaymentReleased(IERC20) throws Identifier not found or not unique error upon compiling

### ISSUE THREAD

**Issue by TheVexy** [OpenZeppelin/openzeppelin-contracts#3164]
**💻 Environment**
Using Remix IDE with 
Compiler : 0.8.11

**📝 Details**
I'm planning to deploy a contract that initiates the Payment Splitter: 

```
pragma solidity ^0.8.0;
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/finance/PaymentSplitter.sol";

contract MOPS is PaymentSplitter {
    constructor (address[] memory _payees, uint256[] memory _shares) PaymentSplitter(_payees, _shares) payable {}
} 
```
The contract it's successfully imported into Remix but the compiler points to the event ERC20PaymentReleased declaration

```
"DeclarationError: Identifier not found or not unique.
--> .deps/github/OpenZeppelin/openzeppelin-contracts/contracts/finance/PaymentSplitter.sol:13:32:
|
13 | event ERC20PaymentReleased(IERC20 indexed token, address to, uint256 amount);
| ^^^^^^"
```

Am I missing a step in importing & deploy a Payment Splitter contract?

**Comment by Amxx** [comment]
Hello @TheVexy 

I am not able to reproduce this issue. When I copy your code into remix everything compiles fine. Is it possible that you are working with an old, cached, version of `PaymentSplitter.sol` ? In the latest version, the event is defined on line 30 and not on line 13.

**Comment by TheVexy** [comment]
Apologies for late reply, indeed it was Remix fetching a cached version.
