### ISSUE TITLE
in VestingWallet the value was incorrectly calculated

### ISSUE THREAD

**Issue by henry-fi** [OpenZeppelin/openzeppelin-contracts#3185]
in the release() or release(address token) method, The current value is releasable.but in the sourc code of VestingWallet.sol,the display reads "+="，please confirm the accuracy of these two codes.

**Comment by Amxx** [comment]
Hello @henry-fi 

I'm sorry I'm not sure I clearly understand your concern. Here is how the vesting wallet works:

- The `vestedAmount` is computed by applying the `_vestingSchedule` to the historical balance (all assets received to date)
- The historical balance is computed by adding the current balance + the amount of assets already `released`.
- At any point, if someone calls `release` we compare the `vestedAmount` (so the fraction of the historical balance that is already vested) with the amount that was already `released`
  - if there are releasable assets (vested and not yet released), we release them, and we add them to the released counter to make sure the historical balance remains valid.
  
Does that explanation clear your concerns?

**Comment by henry-fi** [comment]
Sorry, I didn't understand the meaning of this code well before, please close this issue
