### ISSUE TITLE
can these files be deleted?

### ISSUE THREAD

**Issue by Silver514** [OpenZeppelin/openzeppelin-contracts#3189]
I found this link via a youtuber 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol

I'm not a tech guy, so my apologies if this is a stupid question: Is it possible for the above URL/code to be deleted/taken down? And if I "import" the above URL into my code, and that happens, would it render my crypto token untradable? Or is the code saved onto my smart contract once it's executed.. if that makes sense?

**Comment by frangio** [comment]
Yes it is possible for this URL to be taken down. However, once you compile your smart contract and then publish it to the blockchain it no longer depends on this URL. If you verify the source code on a service like Etherscan, the code will even be "backed up".

There are other issues with this URL though. It's a link to the `master` branch of the repository which can change at any time and this can make it really difficult to get reproducibility. You should not use this link. If you will use a link to GitHub, please use a link to a version tag such as https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.5.0/contracts/token/ERC20/ERC20.sol.
