### ISSUE TITLE
Merkle Proof gas cost may be reduced in some cases. 

### ISSUE THREAD

**Issue by Cr0wn-Gh0ul** [OpenZeppelin/openzeppelin-contracts#3198]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/eae238417862b4797e36fbff928d906bb9242261/contracts/utils/cryptography/MerkleProof.sol#L28

In the normal mode of operation a Merkle proof is passed into a contract by a external party. As such there is little benefit to copying the Merkle proof to memory before invoking `_efficientHash`. Therefore gas may be saved if in this case calldata is used instead of memory for the proof variable. Recommend either modifying the contract or offering a variant that utilizes calldata.

**Comment by BCLeFevre** [comment]
Looks like the original contract was written before 0.6.9 which allowed for using `calldata` within internal function calls.  Most likely why `memory` is still being used in it's current iteration.

**Comment by Cr0wn-Gh0ul** [comment]
@frangio Created a PR with this change. https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3200
