### ISSUE TITLE
Composition over inheritance

### ISSUE THREAD

**Issue by dvird** [OpenZeppelin/openzeppelin-contracts#3199]
https://en.wikipedia.org/wiki/Composition_over_inheritance

Hi i would like to know why everything is inheritance? is it something that related to solidity or something?
I mean there are some implementations with 4 5 inheritance deep and some are even have inheritance to same code.

Its impossible to understand whats happening for a giving class

**Comment by frangio** [comment]
Hi @dvird. We're familiar with the principle of composition over inheritance, and would love to be able to follow it. However, in current Solidity, inheritance is the only way to efficiently implement these patterns.

I'm talking for example about the ability to take the ERC20 implementation and extend its behavior in multiple ways by including different modules: ERC20Permit, ERC20Votes, etc.

If you want to explore alternative ways to implement this functionality using composition that would be interesting. We've thought about this in the past but didn't arrive at anything good.

That said, we definitely don't want the code to be "impossible to understand". If you want to point out specific things that you find hard to understand we can look into possible code improvements or comments that can clarify.

**Comment by dvird** [comment]
Ok actually im new to solidity.. can you explain what specifically is different from other languages that prevent from you to do it? i would like to know because im working on something new now, so its good to know before im making mistake haha

And for example 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/presets/ERC1155PresetMinterPauser.sol

The main problem as you may know with inheritance is that you open a class and you think "oh so nice just 80-100 lines"
but then you understand you in 1000 lines case that hide behind, so to understand the all connections and how its connected its very hard because it splits in many places.

**Comment by frangio** [comment]
> can you explain what specifically is different from other languages that prevent from you to do it?

Off the top of my head, two things that are very related:

1. The language is not sufficiently high level. 
2. The cost model is completely different. Every layer of abstraction that can't be optimized away results in higher gas costs for the end user as well as the developers during deployment.

> but then you understand you in 1000 lines case that hide behind

This would be just as true with composition! :slightly_smiling_face: 

> to understand the all connections and how its connected its very hard because it splits in many places.

This is somewhat true. We try to keep it manageable by using inheritance in very simple ways.

**Comment by frangio** [comment]
Sorry closed accidentally. Though there don't seem to be many actionable items in this issue I think it's worth to keep the discussion going, and some actionable items may arise as well.
