### ISSUE TITLE
Should the address that calling method burn be validated

### ISSUE THREAD

**Issue by w33d-w33d** [OpenZeppelin/openzeppelin-contracts#3205]
**🧐 Motivation**
While reading function _burn i was wondering is this could be used maliciously

**📝 Details**

```
function _burn(
        address from,
        uint256 id,
        uint256 amount
    ) internal virtual {
        require(from != address(0), "ERC1155: burn from the zero address");

        address operator = _msgSender();
        uint256[] memory ids = _asSingletonArray(id);
        uint256[] memory amounts = _asSingletonArray(amount);

        _beforeTokenTransfer(operator, from, address(0), ids, amounts, "");

        uint256 fromBalance = _balances[id][from];
        require(fromBalance >= amount, "ERC1155: burn amount exceeds balance");
        unchecked {
            _balances[id][from] = fromBalance - amount;
        }

        emit TransferSingle(operator, from, address(0), id, amount);

        _afterTokenTransfer(operator, from, address(0), ids, amounts, "");
    }
```

It seems to me that when the Burn method is called, there is no verification that the change of this ERC1155 tokens belongs to the caller. That is, theoretically anyone can Burn someone else's ERC1155 tokens, and for some careless developers, few will even think to add some detail to it.
i mean maybe like 

`require(owner == msg.sender || operators.contains(msg.sender))`

So I was wondering if it was possible to validate msg.sender directly within the internal function.

**Comment by Amxx** [comment]
Hello @w33d-w33d 

`_burn` is an internal method. This means that it cannot just be called by anybody. It is designed to be used by external methods that implement the checks according to the design of the contract.

You could have instances that let anyone burn their own tokens, of tokens that they are approved to operate on. This is visible here:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/extensions/ERC1155Burnable.sol#L15-L26

Other logic might automatically burn tokens as part of more complex processes. The are unopinionated about these process, and we thus do not enforce any protection on the internal function so devs can be creative about when/how they use it.
