### ISSUE TITLE
ERC721MetadataMintable missing from v3.0.0

### ISSUE THREAD

**Issue by takahser** [OpenZeppelin/openzeppelin-contracts#3206]
**💻 Environment**
- ✅ OpenZeppelin v2.5.0
- ❌ OpenZeppelin v3.0.0

**📝 Details**

In OpenZeppelin v2 there used to be a [ERC721MetadataMintable extension containing a mintWithTokenURI method](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/5fe8f4e93bd1d4f5cc9a6899d7f24f5ffe4c14aa/contracts/token/ERC721/ERC721MetadataMintable.sol#L19) that allowed you to pass the tokenUri when minting a new token.
In v3 and v4 this ERC721 extension seems to be missing. Unfortunately I was not able to figure out why it was removed. The [v3.0.0 release notes](https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v3.0.0) fail to mention this change as well. I didn't find any answer in the [forum](https://forum.openzeppelin.com/) neither.
Is there any particular reason for its removal?

**Comment by Amxx** [comment]
Hello @takahser 

Instead of providing a limited number of presets, our focus is on helping devs design build the contract that best matches their needs.

If you try out the [wizard](https://wizard.openzeppelin.com/#erc721), and if you enable `mintable` and `uriStorage`, it will give you code that should fit your needs.

**Comment by takahser** [comment]
Hi @Amxx 

> our focus is on helping devs "compose" the contract

Generally, I think that's a very good approach. 👍  I was just wondering why features are getting deprecated without being mentioned in the release notes. It's unfortunate that I was not able to find an answer to that question, is there a place where I would have found this information?

> If you try out the [wizard](https://wizard.openzeppelin.com/#erc721), and if you enable `mintable` and `uriStorage`, it will give you code that should fit your needs.

That's awesome! Well, actually in my case the `ERC721URIStorage` would normally do the job.
Unfortunately, in contrast to its [ERC1155](https://docs.openzeppelin.com/contracts/3.x/api/token/erc1155#ERC1155-_mint-address-uint256-uint256-bytes-) counterpart, the ERC721 contract doesn't allow me to define an `amount`. Since I'd like to use that functionality as well, I think I'll have to use ERC1155 but there is no `ERC1155URIStorage` extension (or similar). Do you know if there's a way to combine these two functionalities (ERC1155 and URIStorage)?

**Comment by Amxx** [comment]
> Do you know if there's a way to combine these two functionalities (ERC1155 and URIStorage)?

It is possible to build URIStorage on top of `ERC1155`, just not using `ERC721URIStorage` (obviously).
This should be pretty straightforward to implement.

**Comment by takahser** [comment]
I wrote an extension for ERC1155 implementing the behavior I was looking for.
Basically, it adds an `ERC721URIStorage`-like behavior: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3210

**Comment by frangio** [comment]
> wondering why features are getting deprecated without being mentioned in the release notes

The removal of ERC721Metadata was mentioned [in the breaking changes for 3.0.0](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CHANGELOG.md#breaking-changes-4):

>ERC721Metadata, ERC721Enumerable: these contracts were removed, and their functionality merged into ERC721.

ERC721MetadataMintable was a preset that used this contract so it was removed as a result.

We will make sure to mention all contracts removed next time.
