### ISSUE TITLE
Governor: Use smaller integers for timing parameters

### ISSUE THREAD

**Issue by cygnusv** [OpenZeppelin/openzeppelin-contracts#3208]
Some voting timing parameters are expressed as `uint256`, like `votingDelay` and `votingPeriod` in`GovernorSettings`, while the newly introduce `GovernorPreventLateQuorum` has a `votingExtension` parameter with type `uint64`. These should be consistent.

**Comment by Amxx** [comment]
Hello @cygnusv, and thank you for raising that issue.

I'll check what we can do, but please note that we want to move the `votingDelay` and `votingPeriod` to uint64

**Comment by cygnusv** [comment]
Right, either way works 👍

**Comment by anantasty** [comment]
fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3224

**Comment by frangio** [comment]
Sorry folks the getters that return `uint256` were inherited from GovernorBravo and we defined them that way for compatibility with that contract. That hasn't changed so I think we should keep them this way.

**Comment by frangio** [comment]
Following up on my previous comment. While the external getters should continue to return `uint256`, we can change the storage variables to use uint64 in order to more efficiently pack storage.

This is a breaking change that would be scheduled for 5.0.
