### ISSUE TITLE
Beacon for UUPS Proxy

### ISSUE THREAD

**Issue by wiasliaw** [OpenZeppelin/openzeppelin-contracts#3233]
**🧐 Motivation**

Currently, beacon is based on transparent proxy. It still can be used to setup with UUPS, but not all compatible.

**📝 Details**

Issue:
1. UUPS's upgrade logic is placed in logic contract. Upgrade call will setup new implementation address in proxy's storage, not beacon.
2. Upgrade in beacon doesn't check if the new implementation had imeplemented `proxiableUUID()`.

Prototype:
I made up a [prototype repo](https://github.com/wiasliaw/uups-beacon) about UUPS beacon. The implementation detail is written in README.

**Comment by Amxx** [comment]
I'm not sure what you mean by "beacon is based on transparent proxy".

The beacon pattern relies on two contracts:
- The [[BeaconProxy](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/beacon/BeaconProxy.sol)
- The [UpgradeableBeacon](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/beacon/UpgradeableBeacon.sol)

The first one relies on the second one to notify it of what logic to use. The second one is ownable, and can be updated, which is how you "upgrade".

It is completely independent of by the TransparentProxy and the UUPSProxy.

What you clarify what you'd like to do ?

**Comment by wiasliaw** [comment]
UUPS can be setup with beacon with these two contract. However,, there will be some issues.

1. Upgradeable logic is in UUPS contract. It is spare to use beacon's upgradeable logic.
2. Using beacon's upgradeable logic cannot check if new implementation implement `proxiableUUID()`.
3. It might cause bug if proxy calls UUPS's upgradeable logic.

**Comment by wiasliaw** [comment]
OK, I got it.
