### ISSUE TITLE
EIP-712 still draft?

### ISSUE THREAD

**Issue by RobertoDonPedro** [OpenZeppelin/openzeppelin-contracts#3237]
Any reasons why [EIP-712](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/draft-EIP712.sol) is still in draft status?
Is it save to use for new projects?

**Comment by Amxx** [comment]
[The corresponding EIP is not yet final](https://eips.ethereum.org/EIPS/eip-712).

We don't anticipate the EIP to change, and it's safe to use ... but technically, it could change.

**Comment by frangio** [comment]
Please read the docs section about [Drafts](https://docs.openzeppelin.com/contracts/4.x/releases-stability#drafts). The contract is safe to use.
