### ISSUE TITLE
Zero againstVotes should be considered a successful proposal

### ISSUE THREAD

**Issue by youngbagua** [OpenZeppelin/openzeppelin-contracts#3239]
**🧐 Motivation**
Aside from just being more intuitive, the common use case to cover here is situations in which a proposal approval is needed to mint the first ERC20Votes tokens ever created. In such a scenario, a proposal may be `Proposal #1: Distribute first ERC20Votes tokens` while the quorum will be 0, and there will be 0 For, 0 Against, and 0 Abstain votes. 

This situation will be covered by considering the proposal as succeeded when `againstVotes == 0`.

PR for this: #3240

**Comment by Amxx** [comment]
Compound Governor Bravo, which is the reference we got our inspiration from [doesn't agree](https://github.com/compound-finance/compound-protocol/blob/master/contracts/Governance/GovernorBravoDelegate.sol#L214).

Changing that would make use inconsistent with Compound, and would make it more difficult for services like withTally.com to understand what is happening.

Your proposed change (from the PR) would change the behavior if:
- the quorum is 0
- there are 0 for votes
- there are 0 against votes

Under those circumstances, the current code makes the proposal defeated, your code would make it successful.

I understand this could be debated (and devs are free to change that by overriding the `_voteSucceeded` function) ... but I do believe it is correct to mark that as a failure. One of the arguments is that this situation could happen in the case of large DOS that prevent anyone from voting. In that case, I wouldn't want the proposal to go through.

**Comment by frangio** [comment]
I don't think we should make this change. This is only more intuitive in the same way that "0/0 = 0" could be seen as intuitive in math, but it is not a good axiom and 0/0 is undefined.

The initial minting of tokens should be delegated to another account or contract. But if you want to customize `_voteSucceeded` in your own Governor instance to add this behavior that's fine.

**Comment by youngbagua** [comment]
Thanks for the feedback, these are fair points. I will opt to just override this in single project for now.
