### ISSUE TITLE
Optimization in _isApprovedOrOwner - ERC721

### ISSUE THREAD

**Issue by ahbanavi** [OpenZeppelin/openzeppelin-contracts#3247]
**🧐 Motivation**

About ERC721 [_isApprovedOrOwner](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c239e1af8d1a1296577108dd6989a17b57434f8e/contracts/token/ERC721/ERC721.sol#L232-L236) function:
In practice, `setApprovalForAll` is used more than `approve`.  
Therefore, `isApprovedForAll` is likely returns true more than `getApproved`.
Checking `isApprovedForAll` before `getApproved` may save users a redundant SLOAD and gas.

**📝 Details**

Simply, move `isApprovedForAll` before `getApproved` in this line: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c239e1af8d1a1296577108dd6989a17b57434f8e/contracts/token/ERC721/ERC721.sol#L235

Like:
```solidity
return (spender == owner || isApprovedForAll(owner, spender) || getApproved(tokenId) == spender);
```

Inspired by https://github.com/chiru-labs/ERC721A/pull/89 and [these tweets](https://twitter.com/vectorized_dev/status/1499014372668379145).

**Comment by Amxx** [comment]
Hello @ahbanavi 

Thank you for raising this issue and PR. It makes total sense to me to change the ordering.
