### ISSUE TITLE
ERC721TokenReceiver misnamed as ERC721Receiver

### ISSUE THREAD

**Issue by pascaldekloe** [OpenZeppelin/openzeppelin-contracts#3262]
The [standard](https://eips.ethereum.org/EIPS/eip-721) declares an `ERC721TokenReceiver`. Somehow this interface got rebranded to `token/ERC721/IERC721Receiver.sol`.

**Comment by Amxx** [comment]
Hello @pascaldekloe and thank you for pointing that out.

We should not just rename the current files, as this would be breaking for possibly many users.
We could however have the same interface available twice, with different names/paths.

**Comment by frangio** [comment]
Names are not part of EIP specification and we've decided to keep `IERC721Receiver` for simplicity and consistency with the rest of the library.
