### ISSUE TITLE
ERC721Holder.sol -- onERC721Received function incorrectly has "public" visibility

### ISSUE THREAD

**Issue by ams-tech** [OpenZeppelin/openzeppelin-contracts#3266]
Per the [ERC721 Spec](https://eips.ethereum.org/EIPS/eip-721), the `ERC721TokenReceiver` interface should include function `onERC721Received` with `external` visibility, e.g. `function onERC721Received(address _operator, address _from, uint256 _tokenId, bytes _data) external returns(bytes4);`

This function's implementation in the [ERC721Holder.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/utils/ERC721Holder.sol#L25) contract incorrectly uses `public` visibility.

[IERC721Receiver.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/IERC721Receiver.sol#L26) correctly uses the `external` visibility for this function.

**Comment by frangio** [comment]
Whether a function is external or public is not in the scope of an EIP. EIPs specify an external interface. A public function is both external and internal, so it implements the requirement of the external function.
