### ISSUE TITLE
ERC721Voting implementation

### ISSUE THREAD

**Issue by omer2307** [OpenZeppelin/openzeppelin-contracts#3269]
I'm trying to implement ERC721Voting and did as mentioned here overriden _afterTokenTransfer and _getVotingUnits functions.
My questions are: 
1. Do I need to override also ERC721 required functions like isApprovedForAll or others(because ERC721Votes inherits from ERC721)?
2. How I implement EIP712? when I'm compiling it tells me I miss an implementation.
Thanks in advanced.
I wanted to upload this question to openzepplin forum, but for some reason it does not let me.

**Comment by Amxx** [comment]
Hello @omer2307 

If you are unfamiliar with the overriding required by solidity when assembling a contract out of modules, I recommend you try out the [wizard](https://wizard.openzeppelin.com/#erc721) that will help you with that.
