### ISSUE TITLE
ERC721PresetMinterPauserAutoId _setTokenURI

### ISSUE THREAD

**Issue by feiyiban** [OpenZeppelin/openzeppelin-contracts#3290]
I use ERC721PresetMinterPauserAutoId.sol demo；but i don't konw how to use SetTokenURI

**Comment by Hiro-Yuma-Dogy-Club** [comment]
Phase 1:

Hold the collection  #PLAYER CARDS  HIRO YUMA DOGY CLUB# collect the collections to become a set (red and black), all types of cards, until July 2022.

After that, all holders will receive compensation in the form of HIRO YUMA coins to be exchanged for games from HIRO YUMA which will be made attractive and profitable for all HIRO YUMA gamers.
