### ISSUE TITLE
Give names to magic values in TimelockController tests

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-contracts#3297]
This might not be a big thing, but in tests for more abstract concepts like building transactions to be executed, it would be great if possible if the tests could be very thorough on how values are created. In this case, it's not clear why the salt is this value. Would be awesome if all the values to be used in the test were clearly generated at the top of the test file for folks looking to learn how the system works by reading the tests. 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/76eee35971c2541585e05cbf258510dda7b2fbc6/test/governance/TimelockController.test.js#L147

**Comment by mw2000** [comment]
I believe this is a random value. The salt is a value used to obfuscate tx's. However, I think a comment indicating the same, or perhaps even a neatly named variable storing this value is needed.

**Comment by Amxx** [comment]
Hello @crazyrabbitLTC.

This value should be treated as random. IMO, it would be cleaner to use a random generator to fill this argument. When writing this test, it was decided that for reproducibility reasons we should hardcode a value.

**Comment by crazyrabbitLTC** [comment]
That makes a lot of sense. Do you think it would be possible for users to
add at least a comment describing that it's random? And if there is some
format required for it, a note on how it should be generated?

**Comment by frangio** [comment]
Yes, we can just define the value at the top like:

```
const salt =  '0x025e7b0be353a74631ad648c667493c0e1cd31caa4cc2d3520fdc171ea0cc726'; // a random value
```
