### ISSUE TITLE
Missing "require" implementation in ERC2981 ?

### ISSUE THREAD

**Issue by mcIovin** [OpenZeppelin/openzeppelin-contracts#3312]
In most of the contracts whenever the @dev comments mention a 'requirement' - the requirement is then implemented in the following function. However, this seems to be missing in contract ERC2981 at line 91
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/69c3781043b9671012c5b19fdea81784a70a5289/contracts/token/common/ERC2981.sol#L91

Should the _setTokenRoyalty() function have the following line of code?
`require(_exists(tokenId), "ERC2981: URI query for nonexistent token");`

I'm still wrapping my head around solidity inheritance when it comes to storage, so maybe the line above cannot be included (like for example it is included in other places like ERC721SURIStorage) because ERC2981 does not inherit ERC721...therefore maybe _exists won't be accessible to in.
If that is the case, should the 'requirement' in the comment be removed?

Apologies in advance if I'm misunderstanding the 'requirement' in the @dev section. Maybe what those comments mean is that the developer should ensure those requirements are met before calling the function; however, in most other cases I've seen the function implement the requirements, so I thought I would just point out that in this case the 'requirement' of existence is not implemented in the function.

**Comment by mw2000** [comment]
This is a pretty good issue brought up. I'm new to the repo, so please take this with a grain of salt, but I think the requirement is more of a soft requirement than a hard one.

Technically, there is a niche use case to having royalty of a non-minted NFT be set before it is minted. In my opinion, there's no need for this requirement to exist in the first place, especially since it's not enforced.

**Comment by ATI00** [comment]
That makes sense to me tooo.

**Comment by frangio** [comment]
This was a requirement we had at one point in the pull request but we removed the check and forgot to delete the documentation.

Thanks for pointing it out! Fixed in dd01889.
