### ISSUE TITLE
Created a token with 0 amount value

### ISSUE THREAD

**Issue by ahmedtariqkhan** [OpenZeppelin/openzeppelin-contracts#3315]
i am new so when i starts to write a code it didnt ask have supply option in the list of name  and symbol so  just created it. Please help me with the way to add amount to it

**Comment by mazenkhalil** [comment]
You need to explicitly mint the initial supply utilizing `_mint` function.
I suggest you to have a look at the [Wizard](https://docs.openzeppelin.com/contracts/4.x/wizard); **Premint** property.
