### ISSUE TITLE
Inaccurate comment in ERC721URIStorage.sol

### ISSUE THREAD

**Issue by mcIovin** [OpenZeppelin/openzeppelin-contracts#3321]
There is a simple copy+paste error in the comments preceding the _burn function here:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f81b80fb3957ad9c86bb9f9504dd49a8ef409022/contracts/token/ERC721/extensions/ERC721URIStorage.sol#L52

These comments were most likely copy+pasted from the ERC721 contract. However, they don't really make sense in ERC721URIStorage.sol. In this contract, the _burn function does not deal with approvals, it does not check for _exists(), and it does not emit an event (as stated in the comments)
The comments for this function should probably say something more simple, like:
```
    /**
     * @dev Removes token-specific URI information if it exists, when a token is burned.
     */
```

This is the third issue I have submitted recently. Please let me know if instead of submitting these types of things as issues I should simply submit a PR. I'm not sure what the right thing is to do in terms of the 'culture' of this repo, but I'm certainly happy to submit these observations as PRs if that makes more sense..

**Comment by JulissaDantes** [comment]
Thanks for the concern, but actually it does apply for that burn function too, please notice that `ERC721URIStorage` inherits from `ERC721`, and since the the original ERC721 burn commands are executed [on this line](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f81b80fb3957ad9c86bb9f9504dd49a8ef409022/contracts/token/ERC721/extensions/ERC721URIStorage.sol#L61) inside the function it applies.

**Comment by JulissaDantes** [comment]
Hi,
Those are good observations, and hopefully this comments pattern will help the developers have a clearer understanding, thanks for pointing it out. Feel free to create the PR documenting the child function, if not, we´ll address this as soon as we have the bandwidth.

**Comment by ATI00** [comment]
Sounds great! Thanks @JulissaDantes 
I'll create a PR.

**Comment by ATI00** [comment]
Re-opening this issues so I can create a fork and Pull Request that references it.

**Comment by mcIovin** [comment]
@JulissaDantes , thank your for your guidance. I've changed the comment to be similar to the comment ERC721Royalty.sol and I have made a PR for this. Thanks again!

**Comment by mcIovin** [comment]
Closing issue as PR for it has been created / approved / merged.
