### ISSUE TITLE
File import callback not supported  --> myc:4:1: error on polyscan

### ISSUE THREAD

**Issue by akang123** [OpenZeppelin/openzeppelin-contracts#3323]
![image](https://user-images.githubusercontent.com/36091708/162083205-f7984921-5088-4a39-9acf-4ee86485276e.png)

**Comment by frangio** [comment]
Please see our guide on verification to understand how to verify a contract with imports: https://forum.openzeppelin.com/t/how-to-verify-a-contract-on-etherscan-bscscan-polygonscan/14225

**Comment by akang123** [comment]
👍🏾👍🏾👍🏾
