### ISSUE TITLE
Feature: github.com/openzeppelin/contracts

### ISSUE THREAD

**Issue by sambacha** [OpenZeppelin/openzeppelin-contracts#3334]
**🧐 Motivation**

Simplicity. 

Additionally, if unwilling to migrate repo to new fqdn, create a contracts repo that only has tagged releases and accepts no PRs/etc: basically. 

The real motivation is for git-assited installs of `@openzeppelin/contracts`

**📝 Details**
Move the repo to point at just github.com/openzeppelin/contracts as opposed to github.com/OpenZeppelin/openzeppelin-contracts/

Alt: duplicate tagged releases in that repo with only tagged releases being mirrored.

**Comment by frangio** [comment]
The reason this repository is not called `openzeppelin/contracts` is that forks would get names like `sambacha/contracts` and this is too generic and will clash often.

Feel free to provide more info in reply to my questions above.

**Comment by sambacha** [comment]
> The reason this repository is not called `openzeppelin/contracts` is that forks would get names like `sambacha/contracts` and this is too generic and will clash often.
> 
> Feel free to provide more info in reply to my questions above.

Sorry @frangio just saw your message, I should have been more explicit, in stating that creating a new repo to point towards this would be better, either way I understand 💯
