### ISSUE TITLE
Consider removing non-standard requirement in ERC721.approve

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3346]
I can't find something in the spec in EIP721 that says we should disallow this operation. Can someone confirm this? Approving to oneself seems like a no-op we should allow.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/5a75065659a65e65bb04890192e3a4bcb7917fff/contracts/token/ERC721/ERC721.sol#L114

**Comment by hugotkk** [comment]
This restriction isn't mentioned on the [EIP-721 spec](https://eips.ethereum.org/EIPS/eip-721#:~:text=function%20approve(address%20_approved%2C%20uint256%20_tokenId)%20external%20payable%3B).

**Comment by RenanSouza2** [comment]
I believe this issue can be closed @frangio

**Comment by frangio** [comment]
Yes thank you. I think this was fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4377.
