### ISSUE TITLE
Inconsistency between the code of ERC721.safeTransferFrom and the doc of IERC721.safeTransferFrom

### ISSUE THREAD

**Issue by DocCon-team** [OpenZeppelin/openzeppelin-contracts#3362]
Hi,

The code of the `ERC721.safeTransferFrom` function is inconsistent with the doc of the interface `IERC721.safeTransferFrom`. 
The `IERC721.safeTransferFrom` interface function explicitly requires that parameter `from` cannot be the zero address.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/848fef5b6c39333a2f9f1fb352cca7c188c3754b/contracts/token/ERC721/IERC721.sol#L67

However, in the implementation function `ERC721.safeTransferFrom`, this particular requirement is not enforced by either itself or its callee functions, while all other requirements of this interface are enforced with `require` statements.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/848fef5b6c39333a2f9f1fb352cca7c188c3754b/contracts/token/ERC721/ERC721.sol#L161-L170

The `ERC721.transferFrom` and `ERC721._safeTransfer` functions also have the same inconsistency issue.

A potential fix could be adding a `require(from != address(0), "ERC721...")` statement in this part of the `ERC721._transfer` function:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/848fef5b6c39333a2f9f1fb352cca7c188c3754b/contracts/token/ERC721/ERC721.sol#L336-L337

Could you please check it?

Thanks.

**Comment by Amxx** [comment]
Hello @DocCon-team 

The `safeTransferFrom` functions calls the `_safeTransfer`, which then calls the `_transfer` function, which checks:

```
require(ERC721.ownerOf(tokenId) == from, "ERC721: transfer from incorrect owner");
```

For this check to pass with `from == address(0)`, you would need to have the token owned by address(0). In our implementation, the address(0) is an invalid owner. You cannot transfer any token to 0 (unless you are burning the token) and the `ownerOf` function will revert if no owner is registered for this token

```
    function ownerOf(uint256 tokenId) public view virtual override returns (address) {
        address owner = _owners[tokenId];
        require(owner != address(0), "ERC721: owner query for nonexistent token");
        return owner;
    }
```

Thus, despite the check not being explicitly required, it is not possible to transfer a token from address(0)

**Comment by DocCon-team** [comment]
Thanks for the clarification.
