### ISSUE TITLE
Inconsistency between the code and doc of EnumerableSet._at

### ISSUE THREAD

**Issue by DocCon-team** [OpenZeppelin/openzeppelin-contracts#3366]
Hi,

The doc of the `EnumerableSet._at` function is inconsistent with the code. The doc states an explicit requirement that parameter `index` must be strictly less than the length. However, the code does not enforce it with `require` statements. 

A potential fix could be adding an explicit `require` statement in the function code, or performing  `revert` if `index` exceeds the length. 

The same inconsistency issue also exists in `EnumerableSet.at`, `EnumerableMap._at`, and `EnumerableMap.at`. 

Could you please check it?

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/utils/structs/EnumerableSet.sol#L126-L132

Thanks.

**Comment by Amxx** [comment]
Hello @DocCon-team 

`set._values` is a solidity array. The solidity compiler checks that the index is lower than the length.

It's true that we do not check the index ourselves because solidity does it. Feel free to check that.
