### ISSUE TITLE
Inconsistency between the code and the doc of VestingWallet.release

### ISSUE THREAD

**Issue by DocCon-team** [OpenZeppelin/openzeppelin-contracts#3368]
Hi,

The doc of the two `VestingWallet.release` functions reference an event named `TokensReleased`, which is not an actual event in the code. The two functions actually emit events `EtherReleased` and `ERC20Released`, respectively. 

A potential fix could be changing the first doc to "Emits an {EtherReleased} event." and the second doc to "Emits an {ERC20Released} event."

Could you please check it?

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/finance/VestingWallet.sol#L87

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/finance/VestingWallet.sol#L99

Thanks.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3365
