### ISSUE TITLE
Suggesting updates on the doc of Escrow.deposit and Escrow.withdraw

### ISSUE THREAD

**Issue by DocCon-team** [OpenZeppelin/openzeppelin-contracts#3369]
Hi,

The `Escrow.deposit` function emits a `Deposited` event, which is not stated in its doc.
Similarly, the `Escrow.withdraw` function emits a `Withdrawn` event, which is not stated in its doc either.

A potential fix could be adding "Emits a {Deposited} event" to the doc of `Escrow.deposit`, and adding "Emits a {Withdrawn} event" to `Escrow.withdraw`.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/utils/escrow/Escrow.sol#L41

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/utils/escrow/Escrow.sol#L61

These events can also transitively emit in the functions `PullPayment._asyncTransfer` and `PullPayment.withdrawPayments`, because they call `Escrow.deposit` and `Escrow.withdraw` respectively.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/security/PullPayment.sol#L68

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/security/PullPayment.sol#L48

Could you please check it?

Thanks.

**Comment by Amxx** [comment]
Hello @DocCon-team 

I'll add the details in `Escrow.sol`.
About the `PullPayment`, calling `withdrawPayments` or `_asyncTransfer` will indeed trigger an event, but at another address (the escrow and the PullPayment are two different contract) so the wording should reflect that.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3365
