### ISSUE TITLE
Inconsistency between the code and the doc of Governor._castVote

### ISSUE THREAD

**Issue by DocCon-team** [OpenZeppelin/openzeppelin-contracts#3370]
Hi,

The doc of the `Governor._castVote` function is inconsistent with its code. In the code, this function might emit an `IGovernor.VoteCast` event or an `IGovernor.VoteCastWithParams` event depending on the `if` condition. However, only the `IGovernor.VoteCast` event is stated in the doc.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/governance/Governor.sol#L512-L532

Could you please check it?

Thanks.

**Comment by Amxx** [comment]
Hello @DocCon-team 

The "VoteCastWithParams" is a very recent addition to the codebase that we indeed forgot to mention in the docs

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3365
