### ISSUE TITLE
Facing TypeError: Function needs to specify overridden contract "Governor" when compiling governor contract

### ISSUE THREAD

**Issue by pranavkirtani** [OpenZeppelin/openzeppelin-contracts#3371]
Ran hardhat compile for governor contract listed here https://docs.openzeppelin.com/contracts/4.x/api/governance#Governor

ypeError: Function needs to specify overridden contract "Governor".
  --> contracts/Governor.sol:58:5:
   |
58 |     override(IGovernor, GovernorVotes)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: This contract:
  --> @openzeppelin/contracts/governance/Governor.sol:29:1:
   |
29 | abstract contract Governor is Context, ERC165, EIP712, IGovernor, IERC721Receiver, IERC1155Receiver {
   | ^ (Relevant source part starts here and spans across multiple lines).

TypeError: Invalid contract specified in override list: "GovernorVotes".
  --> contracts/Governor.sol:58:5:
   |
58 |     override(IGovernor, GovernorVotes)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: This contract:
  --> @openzeppelin/contracts/governance/extensions/GovernorVotes.sol:14:1:
   |
14 | abstract contract GovernorVotes is Governor {
   | ^ (Relevant source part starts here and spans across multiple lines).

Error HH600: Compilation failed

**Comment by ketan-sol** [comment]
I got the same error for getVotes() function.
you need to remove GovernorVotes and specify Governor and IGovernor in override
---> override(Governor, IGovernor)
This is because getVotes() function is a virtual function present in Governor contract

---> 
    function getVotes(address account, uint256 blockNumber) public view virtual override returns (uint256) {
        return _getVotes(account, blockNumber, _defaultParams());
    }

**Comment by lanmower** [comment]
Got this error from the wizard, why's it closed?

**Comment by Amxx** [comment]
The author of the issue closed it himself.

If you are getting an error with code coming straight out of the wizard that doesn't compile, please share the exact input you gave the wizard so we can investigate.

**Comment by SantiagoIvan** [comment]
Hi! 
I got the same error. This is the input I gave to the wizard:

Name: GovernorContract
Voting delay: 2 blocks
Voting period: 1 week
Proposal threshold: 0
Quorum: 4%
Updatable settings: checked
ERC20Votes: checked
TimeLockController: checked

And this is the error I get when I compile it 

![imagen](https://user-images.githubusercontent.com/48731203/166343944-e7ed1686-758e-4859-9d73-ddfe2f785e1c.png)

**Comment by ketan-sol** [comment]
replace GovernorVotes with Governor that should solve the issue.
--> override(Governor,IGovernor)

**Comment by lanmower** [comment]
Still a bug though right? That's what I got. It's a pain it works when
clicking remix but doesn't work when copy pasting

**Comment by frangio** [comment]
This was fixed in the Wizard 2 days ago.
