### ISSUE TITLE
Suggesting updates on the doc of ERC1155._mintBatch

### ISSUE THREAD

**Issue by DocCon-team** [OpenZeppelin/openzeppelin-contracts#3374]
Hi,

The code of the function `ERC1155._mintBatch` emits a `TransferBatch` event, but this is not stated in the doc. 

A potential fix could be adding "Emits a {TransferBatch} event." in the doc. 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/token/ERC1155/ERC1155.sol#L314

Could you please check it?

Thanks.

**Comment by Amxx** [comment]
Hello @DocCon-team 

While we document the events being emitted by some functions, we do not consistently do that for ALL functions. 
Similarly, some documentation entries skip over some parameters.

Thank you for pointing that out. We definitely need more consistency or at least clearer guidelines on how we approach that matter. Please keep in mind that the documentation is often as old as the code, and that through time possibly different devs have had different documentation practices.

Please, when you find all these points, make sure you compile them in a single issue. You've been raising a lot of issues over the past few days, and creating new issues for each one makes it more difficult to process on our end.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3365

**Comment by frangio** [comment]
@DocCon-team You're welcome to submit pull requests as well next time.
