### ISSUE TITLE
The doc of Governor._countVote is inconsistent with other functions having the parameter `params`

### ISSUE THREAD

**Issue by DocCon-team** [OpenZeppelin/openzeppelin-contracts#3375]
Hi,

The doc of `Governor._countVote` does not mention the parameter `params`.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/governance/Governor.sol#L220

We noticed that this is inconsistent with other functions with this parameter, e.g., `Governor._getVotes`. In these functions, the `params` parameter is mostly described in the doc. 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/governance/Governor.sol#L211

Could you please check it?

Thanks.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3365
