### ISSUE TITLE
The doc of IERC3156FlashBorrower.onFlashLoan references a non-existing function

### ISSUE THREAD

**Issue by DocCon-team** [OpenZeppelin/openzeppelin-contracts#3377]
Hi,

The doc of the function `IERC3156FlashBorrower.onFlashLoan` references a function `ERC3156FlashBorrower.onFlashLoan`, but there is no such a contract `ERC3156FlashBorrower` in the repository. 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/interfaces/IERC3156FlashBorrower.sol#L20

Could you please check it?

Thanks.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3365
