### ISSUE TITLE
Unique URI for each minted token

### ISSUE THREAD

**Issue by erectilereptiles** [OpenZeppelin/openzeppelin-contracts#3383]
Hi. I am using the ERC721 Metadata token for a university project. I need to mint a token with a different image on every time using the same contract. I know other implementations use _setTokenUri, but this token does not have it. Although, I do see a call method of tokenURI that parses the tokenID. Why does this call method exist? Is there a way to use this token to mint tokens with unique images already using ipfs and a unique tokenURI for each minted token? If so how do i go about it? I upload an image to ipfs and get the link right? Then i need to use that link in a json file that matches the schema of the openzeppelin token correct? Where do i find this schema? Any help is appreciated.

**Comment by Amxx** [comment]
Hello @erectilereptiles 

The `tokenURI(uint256)` function is part of the [ERC721Metadata](https://eips.ethereum.org/EIPS/eip-721) standard.

- By default, our `ERC721` implementation uses an internal, overridable, `_baseURI()` function, and appends the number of the token to that.
- We also have an `ERC721URIStorage` extension that allows you to `_setTokenURI` for any token. Note that this is an internal method, so you'll have to design your own custom endpoint, with access restrictions.

I encourage you to check out [the wizard](https://wizard.openzeppelin.com/#erc721), which will assist you in creating a simple ERC721 contract (you can just select mintable+uri storage and see how that affects the code).

Also, please refer to the [documentation](https://docs.openzeppelin.com/contracts/4.x/api/token/erc721) for both the core ERC721 functionalities, but also the available extensions.

**Comment by Amxx** [comment]
Also, the token URI is just ad address, if you want to setup images/traits/other, please refer to the [OpenSea documentation](https://docs.opensea.io/docs/getting-started).
