### ISSUE TITLE
(4.6) Crosschain docs not rendered properly

### ISSUE THREAD

**Issue by the-emerald** [OpenZeppelin/openzeppelin-contracts#3385]
https://docs.openzeppelin.com/contracts/4.x/api/crosschain#

URLs show up as raw markdown and not clickable links (this appears to be an issue across the entire page).
Example:

![image](https://user-images.githubusercontent.com/12746683/166124301-4c6d831a-1fb5-4066-9e84-fe2425ef476d.png)

Edit: This act

**Comment by Amxx** [comment]
Thank you @the-emerald for pointing that out!
We'll work on fixing that syntax issue.
