### ISSUE TITLE
TimelockController: Use default admin role

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3389]
TimelockController currently uses a custom non-zero `TIMELOCK_ADMIN` role that has complicated the introduction of the new `CANCELLER_ROLE`  in 4.6 and necessitated a custom migration to set the role admin that would not have been necessary had `DEFAULT_ADMIN_ROLE` been used.

Moving forward we should always use the default admin role rather than custom roles.

**Comment by Niceural** [comment]
Hi! Does this issue need a pr?

**Comment by frangio** [comment]
It's a breaking change so we're not doing it yet.

**Comment by frangio** [comment]
Fixed by https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3799 for future 5.0 release.
