### ISSUE TITLE
Programmatic Deployments of Upgradeable Contracts

### ISSUE THREAD

**Issue by hickscorp** [OpenZeppelin/openzeppelin-contracts#3391]
We are trying to allow our users to deploy contracts themselves directly from a Smart Contract method.

We thought about the problem and reached several conclusions and possible solutions:
1. We could have a Web3 page which runs the deployments, via several transactions.
1. We could also have a single Solidity method doing that.

In a nutshell, the user would never deploy an "implementation" contract - and instead would deploy their own proxy - thus allowing them to have a dedicated data segment, with all proxies pointing to the same implementation address. Does that make sense? Or should the implementation deployed as many times as we have users too?

Either way, we would like to understand what our options are in terms of maintaining the `.openzeppelin/dev-${NET_ID}.json` file to track state. It seems that we would at least need the concept of a conventional backend?

If picking option 1, would it be possible to run deployments programmatically using Javascript - but then keep tracking the state of deployed things so that they could be upgraded later?

Or for example for option 2, and given that we would be in a serverless environment, would it be possible to do something like:
- Have a  `Stuff.deploySomething` method on one of our contracts.
- Inside this method, there would be sequential steps to deploy a proxy, an implementation, and set up the proxy with the implementation's address.
- The top-level contract (`Stuff`) would save the address of the deployed proxy and implementation in an internal data structure.
- But at this point, how would we be able to still use the `oz` cli to interact with the deployed infrastructure? Could we, for example, get the state-tracking JSON file to reflect the state of the deployments locally, so that our developper could then use `oz upgrade`?
- Is the `upgrades/contracts/application/App.sol` contract doing part of these things? Where can we find documentation on usage?

Did anyone achieve something identical or similar? Is it something that could get documented in the OpenZeppelin docs - or at least a really clear overview of what happens under the hood when running `oz deploy` and / or `oz upgrade` (Eg what contracts are deployed, using what parameters, etc)?

Thanks!

**Comment by Amxx** [comment]
> In a nutshell, the user would never deploy an "implementation" contract - and instead would deploy their own proxy - thus allowing them to have a dedicated data segment, with all proxies pointing to the same implementation address. Does that make sense? Or should the implementation deployed as many times as we have users too?

It makes sense. A lot of projects do that.

I'd personnaly go for option 2. 

Depending on who is allowed to upgrade the proxy, the solution will be different. Its difficult to answer further without understanding you upgrade process. I any case I recommend you use the "@openzeppelin/hardhat-upgrades" plugin for hardhat. See the docs [here](https://docs.openzeppelin.com/upgrades-plugins/1.x/).

As a good example, you could check out [this registry](https://github.com/p00ls/contracts/blob/master/contracts/tokens/P00lsCreatorRegistry.sol) that deploys beacon proxy programmatically. The [migration script](https://github.com/p00ls/contracts/blob/master/migrations/phase1.js#L76-L110) does setup the beacon and build the manifest for that further upgrades can be done using the plugin.

**Comment by frangio** [comment]
This is not a feature request or issue report so I'm closing. Feel free to continue a brief discussion here but the [OpenZeppelin Forum](https://forum.openzeppelin.com/) would be the best place to have this conversation.

Please note that the OpenZeppelin CLI is no longer maintained.
