### ISSUE TITLE
EIP-4626: Tokenized Vault Standard

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/openzeppelin-contracts#3393]
**Motivation**

[EIP-4626](https://eips.ethereum.org/EIPS/eip-4626) introduces a standard API for tokenized Vaults representing shares of a single underlying [ERC-20](https://eips.ethereum.org/EIPS/eip-20) token. This standard is an extension of the ERC-20 token that provides basic functionality for depositing and withdrawing tokens and reading balances.

**Reference Implementations**

- See [Solmate ERC-4626](https://github.com/Rari-Capital/solmate/blob/main/src/mixins/ERC4626.sol): a minimal and opinionated implementation of the standard with hooks for developers to easily insert custom logic into deposits and withdrawals.

- See [Vyper ERC-4626](https://github.com/fubuloubu/ERC4626): a demo implementation of the standard in Vyper, with hooks for share price manipulation and other testing needs.

@Amxx from OpenZeppelin has already opened a draft PR currently [here](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3171). I essentially opened this issue in order to track the development for anyone searching for this new ERC-4626.

**Comment by Amxx** [comment]
Hello @pcaversaccio 

Providing an implementation of ERC4626 is in our roadmap for the next release. We want our implementation to be modular/overridable, so we still have tests to do in that regard.

It's one of our priorities right now. Please be a little patient, it's coming!
