### ISSUE TITLE
Release 4.7

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3395]
## Estimated Timeline

| Date | Milestone |
|-|-|
| June 6th | 4.7 Release Candidate |
| June 27th | 4.7 Final |

## Goals

- **Milestone:** [`4.7`](https://github.com/OpenZeppelin/openzeppelin-contracts/milestone/10)
- **Main Feature:** ERC4626 Tokenized Vault Standard.
- **Research:**
  - Potential solutions for issues with L2 block numbers in Governor.
  - Staking and reward distribution.
- **Infrastructure:**
  - Improve release process tooling and documentation.
  - https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/pull/151
- **Maintenance:** Work on the large number of open PRs to review and merge or close where appropriate.

**Comment by slavakurilyak** [comment]
Thank you for bringing this implementation to the crypto community! 

I'm looking forward to seeing a tokenized vault with an ERC-20 token.

**Comment by frangio** [comment]
The release candidate for 4.7 was just published. [Announcement](https://forum.openzeppelin.com/t/release-candidate-for-contracts-4-7-open-review-period/29443).

**Comment by slavakurilyak** [comment]
When can we expect the final release?

**Comment by frangio** [comment]
4.7 is now released.
