### ISSUE TITLE
Simplifying Contract Deployment using Remix

### ISSUE THREAD

**Issue by Bhaney44** [OpenZeppelin/openzeppelin-contracts#3396]
**🧐 Motivation**

This request is motivated by a need for new developers to get started with new work on Ethereum faster. There are so many videos and tutorials on how to launch an ERC20 contract in 15 minutes or less, but most of the time it takes a lot longer for new developers to launch the contract. That said, certainly experienced developers can launch new contracts in a couple minutes.

But the problem is that experienced developers are able to connect to the blockchain and launch code that executes. For new developers, there is a lot of learning, hacking, and debugging involved in connecting to the Ethereum network through Remix. I've read through the new developer documentation, but the problem is I can't install [hardhat](https://docs.openzeppelin.com/learn/developing-smart-contracts) on my machine because I don't have enough space. For example, using [Remix](https://remix.ethereum.org/) can be very difficult because it isn't intuitive to understand: 1) how to create new files in remix; 2) how to launch code to the Ethereum network; or 3) what files are required for deployment. I was able to get a [contract](https://github.com/Bhaney44/converter/blob/main/Choice20/GR/Choice20.sol) deployed via Remix, but it isn't clear how to adjust the parameters to get the desired result and once I launched it, I left the IDE and now the environment is permanently corrupted.

That said, Remix is a state of the art IDE and a great technology, the purpose of this request to provide a simpler and easier method for beginners to launch an ERC20 contract. I've been reading through the [docs](https://remix-ide.readthedocs.io/en/latest/#), but not finding some critical information I need to effectively start building, such as what the necessary minimum files are for deployment. I've also read through the [Open Zeppelin Contract](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol), which is extremely well documented and informative. But, I still don't have the necessary information to effectively use the code with Remix. 

It's really easy to make new tools and technologies for experienced developers, but the challenge here is to create something easy to use for complete beginners.

**📝 Details**

My request is for an easy to use and follow tutorial on how to launch the [Open Zepplin ERC20 Contract](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol) to both the Ropsten Test Network and the Ethereum Main Network using Remix. The tutorial should provide a step-by-step guide on how to open Remix, create the necessary minimum file structure, launch the code, and verify the asset creation on the blockchain. As I continue working on this problem, I am happy to contribute to the tutorial and sincerely appreciate any thoughts, ideas, feedback or suggestions. Thank you!

**Comment by Bhaney44** [comment]
I'm working through this problem and found a really great [source](https://www.youtube.com/watch?v=PdNxXGGWJRI). This is exactly what I am trying to do, but the problem is there is a missing piece in the tutorial because I am getting an error when compiling the code: `Invalid input source specified.` So, now I am working on debugging and figuring out how to solve the problem.

**Comment by Bhaney44** [comment]
I am now getting another notification from Remix: `You have not set a script to run. Set it with @custom:dev-run-script NatSpec tag.` I think this is one of the most challenging things to learn for new beginners. I'm not sure what this notification is saying or how to proceed. I think it's really important that new tutorials explain this feature, to save developers time in debugging.

**Comment by Bhaney44** [comment]
Here are the Docs on [running scripts](https://remix-ide.readthedocs.io/en/latest/running_js_scripts.html), but they are not clear or helpful in providing information on setting a script to run. After reading, I still don't have the knowledge necessary to solve the problem. For example, the Docs state: `Create a file with .js extension and put your logic inside it.` But there is no instruction on how to create a `.js` extension and put logic inside it in remix. New developers are left asking, is this supposed to be a new file or the same file? Why is there need for a `.js` extension? Where can I find a solution to debug this problem?

**Comment by Bhaney44** [comment]
The two options provide in the docs to solve this problem are:

`1. Make the script the active file in the editor and run remix.exeCurrent() from Remix terminal`
`2. Just right click on the script name in the Files Explorers plugin and click on the Run option. ShortCut: Ctrl+Shift+S when the script is displayed in the editor.`

However, there is no instruction on how to run `remix.exeCurrent() from Remix terminal` and there is no instruction on where or what the `Files Explorers plugin`is. So, it creates another problem to debug.

**Comment by Bhaney44** [comment]
I ran `Ctrl+Shift+S` but it did not solve the problem.

**Comment by Bhaney44** [comment]
It appears the contract has now been deployed. However, the [address](https://ropsten.etherscan.io/address/0xd9145CCE52D386f254917e481eB44e9943F39138) Remix is providing is not associated with the Open Zepplin Smart Contract I ran using [Wizard](https://docs.openzeppelin.com/contracts/4.x/wizard). Instead, it appears to be a randomized address on the TestNet.

**Comment by Bhaney44** [comment]
Alright! I figured it out. I will get to work on the tutorial. [Contract on Etherscan](https://ropsten.etherscan.io/token/0x870eaf6cfae1163b614503eb759072856ec5edce).

**Comment by Bhaney44** [comment]
I found another bug to hack through. So, there needs to be a way that the created tokens are in an address controlled by the creator.

**Comment by Bhaney44** [comment]
There also needs to be a way to verify the contract on Etherscan, which produces the following error:  `Error! Unable to generate Contract ByteCode and ABI (General Exception, unable to get compiled [bytecode])`It generally is not intuitive to understand how or what compiler was used.

**Comment by frangio** [comment]
Our offering for beginners is [Contracts Wizard](https://wizard.openzeppelin.com/). There you can create an ERC20 using a GUI based on a choice of settings and directly open it in remix. From there, it's simple to deploy. It also serves to teach how to use the contracts.

You're welcome to write a more in depth guide and share it here but we currently don't have the bandwidth to maintain documentation with that level of detail.
