### ISSUE TITLE
Document limitation of delete for EnumerableSet and Map

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3400]
Solidity currently allows executing the `delete` operator on structs like `EnumerableSet` and `EnumerableMap` even though they contain a mapping that will not be cleared, and the operation will in fact corrupt the struct's data.

According to https://github.com/ethereum/solidity/pull/11843 this operation will no longer be allowed in Solidity 0.9, but in the meantime we should document that `delete` should not be used with these types.

**Comment by Code-Donewell** [comment]
hi @frangio . I'm new here on git hub(a little overwhelming for me rn 😅) and I recently started learning to make smart contracts via solidity.
pls tell me how can i take on this task . and what exactly I have to do .
 Do you mean we have to comment in  the smart contracts that 'delete' operator should not be used wherever the related structs has been used in the contracts. Pls tell me how to apply for this particular task 😅.

**Comment by lucasAlonso** [comment]
Hi, new contributing to OZ!
something like this would be fine?

`// WARNING!`
  `  //  delete function should not be used. It will corrupt the data structure,`
  `  //  clear function should be used instead.`
   ` //  ref https://github.com/ethereum/solidity/pull/11843`
 
 Also, where i must put it? in the header after introduction or when delete is used?

**Comment by SamuelOsewa** [comment]
I believe that it should be when the delete is used so if someone wants to see the use case they would see the comment as people tend to skip over the introduction.
