### ISSUE TITLE
ERC1155ApprovalById and Amount

### ISSUE THREAD

**Issue by ivanmmurciaua** [OpenZeppelin/openzeppelin-contracts#3401]
**🧐 Motivation**
I saw that the ERC1155 standard does not have the possibility to approve tokens by id or amounts as for example in ERC20. IMHO, this is very **dangerous**.

**📝 Details**
I have designed the following code to avoid be approved for all ids, later I thought to develop the same but with amounts.
Please, take a view, in this repo I explain the whole idea: https://github.com/ivanmmurciaua/ERC1155ApprovalById

What do you think about including this like an official extension? That's would be great.

Thanks in advance,
Iván M.M.

**Comment by Amxx** [comment]
Hello @ivanmmurciaua 

Please keep in mind that our implementation of ERC1155 follows [the standard](https://eips.ethereum.org/EIPS/eip-1155). If you think there is a fundamental issue with the standard, I don't think this is the right place to have this discussion. You should rather go to the [Ethereum magicians forum](https://ethereum-magicians.org/).

You point being about approvals, it would be part of cross-contract interactions (and should probably be natively recognized by wallets as an approval operation). This makes me thing that standardisation of the interface is important (this is why I think it needs to be discussed with the eth magicians before we implement it)

**Comment by Amxx** [comment]
Also note that approval of ERC1155 is not as important as ERC20's, because ERC1155 include a way to transfer+call the receiver that can very effectively replace "approve+transferFrom"
