### ISSUE TITLE
Bug in MainNet ERC20

### ISSUE THREAD

**Issue by Bhaney44** [OpenZeppelin/openzeppelin-contracts#3404]
I ran the following code on the Ropsten TestNetwork and it worked perfectly. The [OpenZepplin Docs](https://docs.openzeppelin.com/contracts/4.x/erc20-supply) were very helpful.

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract ChoiceCoin is ERC20 {
    constructor() ERC20("Choice Coin", "Choice") {
        _mint(msg.sender, 1000000000);
    }
}
```

Here is the Ropsten [ERC20 asset](https://ropsten.etherscan.io/token/0x870eaf6cfae1163b614503eb759072856ec5edce) that was created. The problem is that when I ran the same code on MainNet, I did not get an asset and instead only a useless [contract](https://etherscan.io/address/0x72b423d98d98d509e66e9c565873c3e63ee4c7ab) was created without the ERC20 asset. 

I'm not sure why this would have happened. The code clearly defines the initial supply:

`_mint(msg.sender, 1000000000);`

So, why wouldn't the asset be created the same as on the TestNetwork? Also, why would the TestNetwork yield a different type of contract?

**💻 Environment**

I'm using remix, injected web3 environment.

**📝 Details**

Ropsten [ERC20 asset](https://ropsten.etherscan.io/token/0x870eaf6cfae1163b614503eb759072856ec5edce)
MainNet [contract](https://etherscan.io/address/0x72b423d98d98d509e66e9c565873c3e63ee4c7ab) 

The problem is the same code produced TestNet and MainNet. The only change was that I switched my MetaMask from TestNet to MainNet. I expected the same result and still need to get the asset created on MainNet, but need to figure this bug out first. Any advice, suggestions, or help would be appreciated.

**🔢 Code to reproduce bug**

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract ChoiceCoin is ERC20 {
    constructor() ERC20("Choice Coin", "Choice") {
        _mint(msg.sender, 1000000000);
    }
}
```

**Comment by Bhaney44** [comment]
I ran the code on Ropsten again and got the same bug as on MainNet, [contract](https://ropsten.etherscan.io/tx/0x32ed053f7c2bba0d7140301f45323edf69fb3b977a1e228bd188e903c1c1e6e5). I'm not sure what changed, or whether it was something about remix?

**Comment by Bhaney44** [comment]
Here is a [post](https://forum.openzeppelin.com/t/bugs-importing-tokens-from-new-contracts/28584) I wrote in the OpenZepplin Forum working toward solving this bug.

**Comment by Bhaney44** [comment]
I also added a list of screenshots to the [successful Ropsten deployment](https://github.com/ChoiceCoin/converter/blob/main/Choice20/GR/Debug/success.png), a failed [Rinkbey deployment](https://github.com/ChoiceCoin/converter/blob/main/Choice20/GR/Debug/fail.png) and the [Remix environment](https://github.com/ChoiceCoin/converter/blob/main/Choice20/GR/Debug/enviornment.png).

**Comment by frangio** [comment]
This is not a bug in the code but misuse of Remix. Will reply in the forum.

**Comment by Bhaney44** [comment]
> This is not a bug in the code but misuse of Remix. Will reply in the forum.

Thank you so much. I really appreciate your help!
