### ISSUE TITLE
Error: missing revert data in call exception on tokenOfOwnerByIndex and tokenByIndex from ERC721Enumerable

### ISSUE THREAD

**Issue by joshuaohana** [OpenZeppelin/openzeppelin-contracts#3406]
I'm getting a odd error across several calls out to ERC721Enumerable that

> Error: missing revert data in call exception; Transaction reverted without a reason string

I didn't change anything and am using out of the box openzeppelin and minimal test harness code

_solidity 0.8.1, hardhat 2.9.3, openzeppelin/contracts 4.6.0_

`contract MyToken is ERC721Enumerable`
This works fine and I successfully call several internal functions from my tests like

```
const totalSupply = await myTokenContract.totalSupply();
const ownerBalance = await myTokenContract.balanceOf(owner.address);
```
these both work just fine

However, when calling functions like tokenOfOwnerByIndex or tokenByIndex I get that Error

```
const ownerToken = await myTokenContract.tokenOfOwnerByIndex(
  owner.address, ethers.BigNumber.from(1).toNumber()
);

const ownerToken = await myTokenContract.tokenOfOwnerByIndex(
  owner.address, 1
);

const firstToken = await myTokenContract.tokenByIndex(1);
```
These each produce the same error that

> Error: missing revert data in call exception; Transaction reverted without a reason string

I'm assuming it's some environmental configuration issue but I can't quite seem to figure it out?

**Comment by Amxx** [comment]
Hello @joshuaohana and sorry for the late reply.

This does appear to be related to you development and testing environment. I would encourage to test your code in remix. If you are still experiencing issues, you should ask your question on the [OpenZeppelin Forum](https://forum.openzeppelin.com/) with a minimal reproducible example.
