### ISSUE TITLE
Unable to Import Openzeppelin-solidity 

### ISSUE THREAD

**Issue by jsim77** [OpenZeppelin/openzeppelin-contracts#3425]
Dear Support,

I have a hard time "Import Openzeppelin-solidity/contracts/....sol"; in Remix-IDE and from what I saw Openzeppelin-solidity has changed to "openzeppelin-contracts/" instead. My problem is, that every time I've changed it to "openzeppelin-contracts/" in Remix IDE, it does not seem to "accept" the changes in Remix IDE and still pops up the same "old" error of "Not Found of OpenZeppelin-solidity/contracts/..". (although I've changed it)

I've searched using Stack Exchange for ways to overcome this, such as using "https://github.com/OpenZeppelin", @OpenZeppelin, and using v2.4.0 or v2.5.0 --> still does not solve this problem. 

I'm curious, is there a bug issue in OpenZeppelin that forbid us to change it in Remix IDE?

Sorry, I'm out of ideas for this issue. Any suggestions? I'm using Remix-IDE in Chrome 

Looking forward to your advice on how to resolve this, thanks.

**Comment by Amxx** [comment]
Hello @jsim77 

Versions 2.4 and 2.5 are really old, and you should probably not use them anymore.
If you are not sure how to import contracts into remix, the [wizard](https://wizard.openzeppelin.com/) can help you with that

**Comment by jsim77** [comment]
> Hello @jsim77
> 
> Versions 2.4 and 2.5 are really old, and you should probably not use them anymore. If you are not sure how to import contracts into remix, the [wizard](https://wizard.openzeppelin.com/) can help you with that

Thanks and sorry for the late reply.
