### ISSUE TITLE
Refactor `isContract()` rather than delete.

### ISSUE THREAD

**Issue by 0xsomnus** [OpenZeppelin/openzeppelin-contracts#3426]
As discussed in https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3417#issue-1238923688 and in twitter DMs with @frangio, I'd like to present and later commit a potential refactor of the isContract() function rather than deleting it entirely. This refactor would be completely safe assuming `tx.origin` is never deprecated in future solidity versions. At this point, I feel it is safe to say `tx.origin` will remain.

**Comment by Amxx** [comment]
Hello @0xsomnus 

This has already been discussed many times, and as you saw yourself, there are already many discussions about it. I'm not sure if opening yet another issue is really necessary.

Now, you mention `tx.origin` so I guess what you want to do is something like `msg.sender == tx.origin`.

**IMO, this is a really bad thing to do**

We have documented it, and we have not changed our minds:
- This doesn't actually allow you to check if some address is a live contract or not, which we need for the ERC777 and ERC1155 hooks
- ERC3074 might render that ineffective (no need for tx.origin to be deprecated).
- This breaks contract composability, which is one of the key features that actually make the Ethereum ecosystem great.

We are not in a position to prevent anyone from doing anything with their code, but by providing code we are possibly setting some trends, and encouraging good practices by making them easier to execute. This is not a good practice, and we are not willing to help the community shoot themselves in the foot.
