### ISSUE TITLE
UNCHANGEABLE TOKEN PRICE

### ISSUE THREAD

**Issue by Yuhana-sr** [OpenZeppelin/openzeppelin-contracts#3435]
**🧐 Motivation**
not so crazy idea 

**📝 Details**
 is that possible to make **unchangeable price for erc20 token** . Example **1Xtoken= USD1 always** . Because this token will only use in spesific environment (ex:VerseX). In this verseX we can play games earn token, trade NFT, buy and sell product, etc. all environment only use Xtoken. So i think no need to change the price based on token activity, no inflation, no dropping price, no up price, no need to compare with up and down USD,etc. because this Xtoken have own currency. Fixed price for 1 token always. Maybe can add voting for democracy.

**Comment by Amxx** [comment]
Hello @Yuhana-sr 

If what you mean is that you want a token to be pegged/backed by another token then you are looking for our [ERC20Wrapper contract](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Wrapper.sol). This can be used to wrap `SomeToken` into `XSomeToken`.

If you are talking about having a fixed price against a non-crypto asset, like € or $, then you are into the "stable coin" territory. There are a lot of these, with varying designs. It is a very difficult thing to get right (as recent actuality showed) and if way beyond the scope of this repo.
