### ISSUE TITLE
Add external `cancel` to OZ Governor by default

### ISSUE THREAD

**Issue by julianmrodri** [OpenZeppelin/openzeppelin-contracts#3436]
**🧐 Motivation**
It would be great to allow the OZ Governor to have the `cancel` proposal functionality offered by default. It should be something similar like the `cancel` offered in Governor Bravo.

**📝 Details**
Even though currently an internal `_cancel` is offered in the OZ Governor, this cannot be used as one would probably need to store the `proposer` on chain, which is not part of the Governor implementation.
```
  function _cancel(
        address[] memory targets,
        uint256[] memory values,
        bytes[] memory calldatas,
        bytes32 descriptionHash
    ) internal override(Governor, GovernorTimelockControl) returns (uint256) {
        return super._cancel(targets, values, calldatas, descriptionHash);
    }
```
It would be great if the OZ governor provided already with the `proposer` on-chain and the ability to have an external `cancel()` that we can call:

```
  function cancel(
        address[] memory targets,
        uint256[] memory values,
        bytes[] memory calldatas,
        bytes32 descriptionHash
    ) external;
   
```

Default implementation could be based on the Governor Bravo cancel, by default could be something on these lines:

```
   function cancel( address[] memory targets,
        uint256[] memory values,
        bytes[] memory calldatas,
        bytes32 descriptionHash) public virtual {
        
        // 1. - Get proposalID
        // 2. - Get proposer based on proposalID 
       
        // 3 - add checks for proposer
        require(
            _msgSender() == proposer || getVotes(proposer, block.number - 1) < proposalThreshold(),
            "Governor: proposer above threshold"
        );
       // 4 -  Cancel
        _cancel(
            targets,
            values,
            calldatas,
            descriptionHash
        );
    }
```
Also this function signature would have to be added to `Tally` for compatibility. Currently Tally does not allow to add external `cancel` to the OZ Governor as this is not part of the common interface. (As shown here: https://docs.tally.xyz/user-guides-1/supported-dao-frameworks/openzeppelin-style)

**Comment by frangio** [comment]
Thanks @julianmrodri.

I'm not sure if we want to add this by default or in an opt-in module. Any thoughts?

**Comment by jgeary** [comment]
definitely agree with this. it took a lot of doc reading and integration testing that i assume many people probably aren't careful enough to think through and write for me to even realize that there was no default cancel functionality via a GovernorTimelockControl and TimelockController configured in the standard way. i cant understand why this would be the case. anyone who deploys these contracts using something like OZ's own contract wizard leaves their DAO vulnerable to a governance attack that cannot be canceled by any entity like a team multisig. Governor or GovernorTimelockControl (or another module like GovernorCanceler) should have a `function cancel(...) external` plus AccessControl and a CANCELER_ROLE.

on that note, OZ should standardize how they spell words like canceled/cancelled and canceler/canceller. im biased towards single L but either one.

**Comment by frangio** [comment]
In Bravo's cancel function there are two alternative conditions:
- `msg.sender == proposer`
- `getVotes(proposer, block.number - 1) < proposalThreshold()`

I would agree that giving the proposer the ability to cancel somewhat goes against the nature of decentralized governance, but the second condition doesn't have the same problem. The second condition is simply extending the concept of "proposal threshold" to say that the threshold must hold throughout the entire duration of a proposal, not just at the time of proposing. Arguably, by not implementing this condition we haven't implemented the same concept of "proposal threshold"!

**Comment by Amxx** [comment]
Even the second condition alone still gives a tremendous power to the proposer. 

A proposer could just:
- de-delegate its votes
- cancel
- re-delegate.

**Comment by frangio** [comment]
We've arrived at a shared belief that giving the proposer the ability to cancel an active proposal gives it a power that we don't think it should have.

However, we think that it could make sense for the proposer to have the ability to cancel a proposal during the delay before it becomes active. This requires storing the proposer address in storage, which is not something the contract currently does. It is possible to add this to the `ProposalCore` struct without increasing the number of storage slots that it uses, thus without substantially increasing the cost of `propose` (though it may require some tricks once we move to represent timepoints by smaller integers).

We may want to reserve the space for some other value, but I don't see at the moment what that could be.

If we decided to use the space for the proposer, we could add `cancel` in Governor by default, with the logic that a proposal can be cancelled before it becomes active.

**Comment by Amxx** [comment]
> It is possible to add this to the `ProposalCore` struct without increasing the number of storage slots

That is possible with the current, poorly packed, version of the structure.

In 5.0 we want to use `uint48` (or at most `uint64`) for both timers. This will make the struct fit into 1 slot, compared to 3 today. On the other hand, this one slot will not have enough spare room for an address.

**Comment by frangio** [comment]
The obvious way to store `voteStart` and `voteEnd` is using `uint48` for each. However, instead of `voteEnd` we can store `voteEnd - voteStart` (i.e. `votingPeriod`) which should be comfortably representable with a smaller integer. This is what I meant by "it may require some tricks".

**Comment by Amxx** [comment]
000-159 : address
160-207: uint48 (vote starts)
208-239: uint32 (duration)
240-247: bool (executed)
248-255: bool (canceled)

The 2 bool might even be merged into a single bytes1 to have a uint40 for the duration.

type(uint32).max = +136 years

uint40 would provide support even for blocknumber that happens 10k times per seconds.
