### ISSUE TITLE
maxBatchSize() parameter for Governance and Governance settings

### ISSUE THREAD

**Issue by Codys12** [OpenZeppelin/openzeppelin-contracts#3443]
**🧐 Motivation**
Having a maxBatchSize parameter that is checked by the Governor contract would limit proposals to a specific number of operations.

**📝 Details**
This parameter could be defined in GovernorSettings and settable by the governance system itself. It would need to be checked that it is set to > 1.

**Comment by Amxx** [comment]
Hello @Codys12 

`GovernorSettings` is an extension we propose to have easy support for all the parameters that are mandatory. IMO a `maxBatchSize` should probably not be included by default. 

Any dev is free to enforce such a restriction by overriding the `propose` function, and I would personally leave it that way.

**Comment by Amxx** [comment]
Why do you think a `maxBatchSize` is an important feature to have?

**Comment by frangio** [comment]
I imagine this parameter is proposed as a way to catch, before it is proposed, a proposal that will be too big to execute. However, a proposal might be too big even with just one operation, if that operation is very expensive, so this check would be ineffective in that case. The number of operations is not really relevant and imposing an arbitrary limit may force a proposal to be unnecessarily split in two, imposing greater voting overhead.

The Governor needs to be resilient to a proposal that can't be executed. It should not and does not prevent the rest of the governance protocol from continuing to operate.

If there is another reason to include this parameter please let us know.
