### ISSUE TITLE
Getting error on yarn install

### ISSUE THREAD

**Issue by person-al** [OpenZeppelin/openzeppelin-contracts#3454]
Hi!
I'm trying to install OpenZeppelin contracts via npm into my project and running into an issue when running `yarn install`. I'm hoping someone here can clarify what I'm doing wrong.

**💻 Environment**

I'm working on a base of the [solidity-template](https://github.com/paulrberg/solidity-template) repo with no changes made yet, except a .env file and my attempt to install OpenZeppelin. I believe I'm trying to install the most recent version of openzeppelin, since I just called `npm install @openzeppelin/contracts`

**📝 Details**

I have a copy of the [solidity-template](https://github.com/paulrberg/solidity-template) repo up and running with no issues. Running yarn install on the project, produces no issues. In order to use OpenZeppelin, I've run `npm install @openzeppelin/contracts`. I then go to run `yarn install` and get the following error:

```
➤ YN0001: │ ethereumjs-abi@npm:^0.6.8: Failed listing refs
➤ YN0001: │   Repository URL: ssh://git@github.com/ethereumjs/ethereumjs-abi.git
➤ YN0001: │   Fatal Error: Could not read from remote repository.
➤ YN0001: │   Exit Code: 128
➤ YN0000: └ Completed in 20s 358ms
➤ YN0000: Failed with errors in 20s 366ms
```

**🔢 Code to reproduce bug**

An unchanged copy of the [solidity-template](https://github.com/paulrberg/solidity-template) repo with a .env file with a random 12 word seed as described in .env.example in the repo.

Thanks in advance for your help! I assume it's something basic that I'm doing wrong.

**Comment by frangio** [comment]
This seems unrelated to OpenZeppelin Contracts, the error is about `ethereumjs-abi`. 

Note that you're using npm to install the dependency but the repo uses yarn, so you should be doing `yarn add @openzeppelin/contracts`.
