### ISSUE TITLE
Remove invalid signature check on `v` in `ECDSA`

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/openzeppelin-contracts#3457]
**Motivation**
All client implementations of the precompile `ecrecover` apparently check if the value `v` is 27 or 28. The references for the different client implementations can be found [here](https://github.com/ethereum/yellowpaper/pull/860).

There are two ways to deal with this IMHO:
1. Either we remove the check [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol#L166), or
2. we keep it with a custom error for better error reporting. In this case, we could even optimise it like that (if you are open to assembly):

```solidity
assembly {
   ...
    vIsInvalid := iszero(byte(v, 0x0000000000000000000000000000000000000000000000000000000101000000))
}
```

**Comment by axic** [comment]
The check is useful for two reasons:
1. Better error reporting
2. Saving as in the failure case (i.e. when this signature check is preceding an EIP-1271 verification -- this is the case in the Seaport use case)

(More context [in this tweet](https://twitter.com/alexberegszaszi/status/1534461421454606336)).

**Comment by pcaversaccio** [comment]
@axic the fundamental question I think here is whether the better error reporting should come from a library or the client implementation directly. I see your point re EIP-1271 tho.

**Comment by pcaversaccio** [comment]
Checking a condition twice (contract & pre-compile implementation) is still not right IMHO.

**Comment by pcaversaccio** [comment]
> We want to generalize the use of custom errors. So, I'd keep the check like we have it today, and just replace the revert reason wit a custom error.

If we do this we should add a small natspec section that informs the dev that the client implementations actually make this check as well. It's important to be informative about that IMO.
