### ISSUE TITLE
Request for the add forge testing for the openzeppelin contracts

### ISSUE THREAD

**Issue by Atarpara** [OpenZeppelin/openzeppelin-contracts#3460]
**🧐 Motivation**

In today's Foundry is one of the fast and most powerfull tools for testing smart contracts. 

**📝 Details**

Benefit of the use Foundry 
1. Foundry provides In-Built Fuzz Testing Facility. 
2. No Need to learn the Java Scripts or Chai Library.
3. Simultaneously Running the Multiple Test Cases we can save a lot of time in testing (Long test case file).
4. Gas Reporting Function Wise
5. If something goes wrong we can trace the entire call

So My Question is Openzeppelin-Team Should ready to adopt the foundry? If Yes, So many Devs are happy to contribute to that.

**Comment by frangio** [comment]
This project has a huge existing test suite in JavaScript and migrating it to something else is a huge effort and risk. There are many incremental improvements we can make to the existing tests for whatever issues we see with them. At the moment I see no strong reasons to migrate.

Fuzzing is definitely interesting, but we should start experimenting with it before attempting to migrate the entire project.

**Comment by Amxx** [comment]
Hello @Atarpara 

We know about Foundry and its features. We would definitely love to benefit from them...
... however, the amount of work required to rewrite our tests in solidity is just to much for us to do this transition in the near future.

We also believe that testing in solidity has real drawbacks, that the foundry team might understate. In particular, I don't think "No Need to learn the Java Scripts" is an improvement. Most devs will design contract front-ends using javascript/typescript as their base language. Writing the test in this language allows us to check contracts against the library that will, in the real world, be used to interact with them. Javascript also provides math functions that we can used as a reference for testing math written in solidity.
