### ISSUE TITLE
PaymentSplitter should use ReentrancyGuard's `nonReentrant` modifier on release() functions

### ISSUE THREAD

**Issue by btroia** [OpenZeppelin/openzeppelin-contracts#3474]
To prevent potential reentrant calls on the [PaymentSplitter](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/6766b2de3bd0473bb7107fd8f83ef8c83c5b1fb3/contracts/finance/PaymentSplitter.sol) contract's `release()` functions, shouldn't PaymentSplitter also inherit from the [ReentrancyGuard](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/security/ReentrancyGuard.sol) contract so that {nonReentrant} modifiers can be added to the `release()` functions?

**🔢 Code to reproduce bug**

See the following lines in [PaymentSplitter.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/6766b2de3bd0473bb7107fd8f83ef8c83c5b1fb3/contracts/finance/PaymentSplitter.sol#L144)

```
    /**
     * @dev Triggers a transfer to `account` of the amount of Ether they are owed, according to their percentage of the
     * total shares and their previous withdrawals.
     */
    function release(address payable account) public virtual {
        require(_shares[account] > 0, "PaymentSplitter: account has no shares");

        uint256 payment = releasable(account);

        require(payment != 0, "PaymentSplitter: account is not due payment");

        _released[account] += payment;
        _totalReleased += payment;

        Address.sendValue(account, payment);
        emit PaymentReleased(account, payment);
    }

    /**
     * @dev Triggers a transfer to `account` of the amount of `token` tokens they are owed, according to their
     * percentage of the total shares and their previous withdrawals. `token` must be the address of an IERC20
     * contract.
     */
    function release(IERC20 token, address account) public virtual {
        require(_shares[account] > 0, "PaymentSplitter: account has no shares");

        uint256 payment = releasable(token, account);

        require(payment != 0, "PaymentSplitter: account is not due payment");

        _erc20Released[token][account] += payment;
        _erc20TotalReleased[token] += payment;

        SafeERC20.safeTransfer(token, account, payment);
        emit ERC20PaymentReleased(token, account, payment);
    }
```

**Comment by Amxx** [comment]
As you can see, the payment splitter computes the releasable amount, and updates all the internal stores, BEFORE transferring the assets. If reentrancy was to happen, that would be after all the states are updated, which is safe.

The (good) design of the function means we don't need to prevent reentrancy to ensure security. Adding it would just increase gas cost.
