### ISSUE TITLE
Gas optimized error for AccessControl.sol

### ISSUE THREAD

**Issue by 0fatih** [OpenZeppelin/openzeppelin-contracts#3476]
**🧐 Motivation**
I think the current error message in `_checkRole()` function is relatively expensive.

**📝 Details**
Here is the current `checkRole()` function:

```solidity
function _checkRole(bytes32 role, address account) internal view virtual {
    if (!hasRole(role, account)) {
        revert(
            string(
                abi.encodePacked(
                    "AccessControl: account ",
                    Strings.toHexString(uint160(account), 20),
                    " is missing role ",
                    Strings.toHexString(uint256(role), 32)
                )
            )
        );
    }
}
```

Why are we giving an error like this? Isn't something like this better:

Define an error:
```solidity
error MissingRole();
```

And revert if the `account` has no `role`:
```solidity
function _checkRole(bytes32 role, address account) internal view virtual {
    if (!hasRole(role, account)) revert MissingRole();
}
```

**Comment by Amxx** [comment]
Hello @0fatih 

The current error is indeed a temporary measure before we transition to custom errors. In this case, we will want a custom error with arguments 
```
error MissingRole(address account, bytes32 role);
```

This will come soon, but we want to make sure the tooling for handling errors is ready (it clearly wasn't when the feature was introduced in 0.8.9)

**Comment by Amxx** [comment]
Please continue the discussion in #2839
