### ISSUE TITLE
Introduce asymmetry between leaf and intermediate nodes in `MerkleProof`

### ISSUE THREAD

**Issue by nikeshnazareth** [OpenZeppelin/openzeppelin-contracts#3485]
**🧐 Motivation**
The current release contains [a warning](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.7/contracts/utils/cryptography/MerkleProof.sol#L15-L18) that the library cannot distinguish between leaf hashes and branch hashes,  internal hash pairs could be interpreted as a leaf value. This means that in some scenarios, a user could potentially (falsely) create an inclusion proof for an internal hash pair.

**📝 Details**
I recommend introducing an explicit asymmetry between leaf hashes and internal hashes. One suggestion is to double-hash the leaf contents. For example, the [original `computedHash`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.7/contracts/utils/cryptography/MerkleProof.sol#L57) in `processProof` could be replaced with `keccak256(leaf)` (with corresponding changes to the rest of the contract). This would ensure that the pre-image of leaf-hashes would by 32 bytes, while the pre-image of internal hashes would by 64 bytes, and therefore they cannot be confused with each other.

Alternatively, to avoid excessive gas costs, perhaps a bit-manipulation asymmetry could be introduced instead. For example, the `computedHash` could be set to `leaf ^ ARBITRARY_NON_ZERO_CONSTANT`. This could be interpreted as a leaf-specific hash function, in line with the current recommendation, except developers would not need to implement it explicitly.

**Comment by frangio** [comment]
We can consider adding a separate new function and making it our new recommendation.

**Comment by Amxx** [comment]
This was not done in 5.0. Since its a breaking change, I think that the next window, if we want it, is 6.0
