### ISSUE TITLE
Remove `_setupRole` from code examples

### ISSUE THREAD

**Issue by ernestognw** [OpenZeppelin/openzeppelin-contracts#3488]
**🧐 Motivation**
Access Control's [`_setupRole`](https://docs.openzeppelin.com/contracts/4.x/api/access#AccessControl-_setupRole-bytes32-address-) has been deprecated in favor of `_grantRole`, which performs the same operations. However, it's still show on the `AccessControl` [examples](https://docs.openzeppelin.com/contracts/4.x/access-control#using-access-control).

If we're intending to discourage its usage, we should replace the `_setupRole` usage on the docs, and replace it with `_grantRole`

**📝 Details**

Only the `docs/modules/ROOT/pages/access-control.adoc` file is affected. I'll open a PR

**Comment by garvey96** [comment]
[https://docs.openzeppelin.com/contracts/3.x/api/access#AccessControl-_setupRole-bytes32-address-](This site) doesn't state that it is deprecated.
Is this website managed by this repository?
