### ISSUE TITLE
MerkleProof.processMultiProof should be callable with parameters stored in memory

### ISSUE THREAD

**Issue by hbriese** [OpenZeppelin/openzeppelin-contracts#3492]
**🧐 Motivation**
`MerkleProof.processMultiProof` only accepts parameters stored in `calldata`.
Leaves are often constructed by the calling code (in `memory`), and sometimes even the proof.
Functions need to be created for each use case

**📝 Details**
#### processMultiProof
```solidity
function processMultiProof(
        bytes32[] calldata proof,
        bool[] calldata proofFlags,
        bytes32[] calldata leaves
) ...
```

## Proposed
In line with the approach taken to solve this problem by `MerkleProof.processProof` & `MerkleProof.processProofCalldata` I suggest that there be three variants of the function.

#### processMultiProofCalldata
```solidity
function processMultiProofCalldata(
        bytes32[] calldata proof,
        bool[] calldata proofFlags,
        bytes32[] calldata leaves
) ...
```
Most gas efficient, least flexible
Simply a rename `MerkleProof.processMultiProof` -> `MerkleProof.processMultiProofCalldata`

#### processMultiProofCalldataProof
```solidity
function processMultiProofCalldata(
        bytes32[] calldata proof,
        bool[] calldata proofFlags,
        bytes32[] memory leaves
) ...
```
This function has the correct gas/flexibility tradeoff for many applications
_Note. Probably not the best name_

#### processMultiProof
```solidity
function processMultiProof(
        bytes32[] memory proof,
        bool[] memory proofFlags,
        bytes32[] memory leaves
) ...
```
Most flexible, but least gas efficient

**Comment by regohiro** [comment]
Totally agree on this. 
However, the hashed leaves passed to the `multiProofVerify` function must be sorted (Refer to [this test](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/029706d1676e541d182eebc90d9bb7a7fca7c0f0/test/utils/cryptography/MerkleProof.test.js#L77)). Clients will need to pre-construct the hashed leaves on their end and change the input order of seed leaves based on the hash results.

**Comment by hbriese** [comment]
@regohiro Indeed, it's probably wise to make that more explicit in the multi proof function natspec

**Comment by Amxx** [comment]
@hbriese Indeed, we focused on the proof, which we believe should almost always be calldata, but the leaves are indeed very likely to me in memory!

Should we use memory for every param? Should we only use memory for the leaves, but keep the proof in calldata? Have the two alternatives?

**Comment by Amxx** [comment]
Note that @regohiro remarks possibly justify including a memory array sorting algorithm for leaves.
