### ISSUE TITLE
_requireMinted() is in master but is not in v4.6

### ISSUE THREAD

**Issue by oksusu12** [OpenZeppelin/openzeppelin-contracts#3494]
For contracts/token/ERC721/ERC721.sol, it seems to be that _requireMinted() function was introduced in v.4.7.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.7/contracts/token/ERC721/ERC721.sol
has requireMinted()
but https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.6/contracts/token/ERC721/ERC721.sol
does not have requireMinted().

in master branch:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol
The second line says that it is last updated v.4.6.
// OpenZeppelin Contracts (last updated v4.6.0) (token/ERC721/ERC721.sol)
But it doesn't have requireMinted().

Is this expected?
I assumed that it was a minor bug in master branch. Should be
// OpenZeppelin Contracts (last updated v4.7.0) (token/ERC721/ERC721.sol)

**Comment by astronatey** [comment]
@Amxx one of my ERC721 contracts does not have the ```_requireMinted()``` function yet does that pose a malicious risk to the contract? or this just for clarity? Thanks I'll be anticipating your response.

**Comment by Amxx** [comment]
That is not a security concern. Don't worry
