### ISSUE TITLE
Support taxed tokens transfers in the ERC4626 contract

### ISSUE THREAD

**Issue by OxMarco** [OpenZeppelin/openzeppelin-contracts#3495]
**Scope**
ERC4626

**Motivation**
Make the standard more inclusive and usable across the hugely-diversified DeFi ecosystem by supporting taxed tokens transfers.

**Description**
Implement a token transfer library that takes into account tokens with transfer taxes or non-standard behaviours (example: a user calls `deposit(...amount = 10)` but the actual deposit is 9 _TKN_ because of a 10% transfer tax.

**Example**
```solidity
function transferTokens(
        IERC20 token,
        address from,
        address to,
        uint256 amount
    ) internal returns (uint256 originalBalance, uint256 received) {
        if (token.balanceOf(from) < amount) revert TransferHelper__Insufficient_Token_Balance(from, address(token));

        if (token.allowance(from, address(this)) < amount)
            revert TransferHelper__Insufficient_Token_Allowance(from, address(this), address(token));

        // computes transferred balance for tokens with tax on transfers
        originalBalance = token.balanceOf(to);
        token.safeTransferFrom(from, to, amount);

        received = token.balanceOf(to) - originalBalance;
    }
```
    
Now instead of `SafeERC20.transferFrom(...)` one could use the function above using the `received` value instead of the user-inputted `amount`.

Source: [TransferHelper.sol](https://github.com/Ithil-protocol/v1-core/blob/master/contracts/libraries/TransferHelper.sol)

**Comment by Amxx** [comment]
Hello @OxMarco 

Indeed, the current ERC4626 implementation assumes that calling transferFrom with a given amount will transfer that amount of token to the receiver. Right now we don't claim compatibility support with non-standard ERC20. Maybe that should be clearer.

Support for non-standard ERC20 could possibly be partially improved using this, but that would not be enough:
- how should the preview behave?
- what about the mint function, which needs to predict the value to transfer to receive a given amount?
- transfer also affects redeem and withdraw, ...

All in all, I believe that the changes you propose would only scratch the surface of what non-standard ERC20 support requires ... and that alone, is not enough. meanwhile, it makes operating on a "normal" ERC20 more expensive.

So I would personally not include that by default, but we should add more warnings about the assumption we make, and tell devs that want to interact with these tokens that they probably override many ERC4626 operations

**Comment by Amxx** [comment]
I considered making the `_deposit` and `_withdraw` internal instead of private. Do you think that would be enough ?

**Comment by frangio** [comment]
I'm okay with making `_deposit` and `_withdraw` internal.

**Comment by OxMarco** [comment]
ok perfect, if that is not going to largely impact the gas costs I think it could be useful to implement them for flexibility
