### ISSUE TITLE
Address.isContract returns false for zero size bytecode contracts

### ISSUE THREAD

**Issue by CodeSandwich** [OpenZeppelin/openzeppelin-contracts#3507]
Even though a zero size bytecode contract doesn't behave differently from an EOA, it's technically still a contract, so `isContract` should probably return `true`.

**📝 Details**

I've been trying to make a quick fix and change `account.code.length > 0` to `account.codehash != 0`, but this change breaks 66 different tests, so there will be quite a lot of cleaning up. This is also a hint that this change is a breaking one and should be published no sooner than with a major version of OZ.

**🔢 Code to reproduce bug**

**Comment by Amxx** [comment]
Hello @CodeSandwich 

`isContract` has been discussed many times, and a simple search would have raised tons of similar discussion:

- #3355
- #3417
- #3426
...

The bottom line is always the same. This is an intrinsic limitation of the EVM that just doesn't have a simple solution. And the code is very extensively documented so users understand what this function does and what is doesn't do.

**Comment by CodeSandwich** [comment]
Thanks for looking into it! I've searched for a similar issue, but none was about zero length and switching to `codehash`.

I agree that it's impossible to make `isContract` bulletproof and I understand the direction the project took. That case is not covered by the documentation, so here's a tiny PR extending the docs: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3508
