### ISSUE TITLE
Add IERC721Receiver to supportsInterface for Governor, ERC721Holder

### ISSUE THREAD

**Issue by songhobby** [OpenZeppelin/openzeppelin-contracts#3511]
```
function supportsInterface(bytes4 interfaceId) public view virtual override(IERC165, ERC165) returns (bool) {
        // In addition to the current interfaceId, also support previous version of the interfaceId that did not
        // include the castVoteWithReasonAndParams() function as standard
        return
            interfaceId ==
            (type(IGovernor).interfaceId ^
                this.castVoteWithReasonAndParams.selector ^
                this.castVoteWithReasonAndParamsBySig.selector ^
                this.getVotesWithParams.selector) ||
            interfaceId == type(IGovernor).interfaceId ||
            interfaceId == type(IERC1155Receiver).interfaceId ||
            super.supportsInterface(interfaceId);
    }
```
=>
```
function supportsInterface(bytes4 interfaceId) public view virtual override(IERC165, ERC165) returns (bool) {
        // In addition to the current interfaceId, also support previous version of the interfaceId that did not
        // include the castVoteWithReasonAndParams() function as standard
        return
            interfaceId ==
            (type(IGovernor).interfaceId ^
                this.castVoteWithReasonAndParams.selector ^
                this.castVoteWithReasonAndParamsBySig.selector ^
                this.getVotesWithParams.selector) ||
            interfaceId == type(IGovernor).interfaceId ||
            interfaceId == type(IERC721Receiver).interfaceId ||
            interfaceId == type(IERC1155Receiver).interfaceId ||
            super.supportsInterface(interfaceId);
    }
```

**Comment by Amxx** [comment]
Hello @songhobby 

### [ERC1155](https://eips.ethereum.org/EIPS/eip-1155)

ERC165 is explicitly mentioned, and it is stated that:

> Smart contracts MUST implement the ERC-165 supportsInterface function and signify support for the ERC1155TokenReceiver interface to accept transfers. See “ERC1155TokenReceiver ERC-165 rules” for further detail.

### [ERC721](https://eips.ethereum.org/EIPS/eip-721)

ERC165 is mentioned for the `ERC721` contract itself, but not for the `ERC721TokenReceiver`. That means `type(IERC721Receiver).interfaceId` is not standardized, and that is why we don't include it.

You can see that 
- `token/ERC721/utils/ERC721Holder.sol` doesn't include ERC165
- `token/ERC1155/utils/ERC1155Holder.sol` does include ERC165 (through ERC1155Receiver)

@frangio, so you think we should include `type(IERC721Receiver).interfaceId` in the governor/timelock ?

**Comment by frangio** [comment]
That's interesting, this is the first time we hear about EIP-165 for EIP-721 receivers. The EIP doesn't seem to require it.

If we add this in Governor we should add it in ERC721Holder as well.

For some background, Gnosis Safe includes support for the interface:

https://github.com/safe-global/safe-contracts/blob/c36bcab46578a442862d043e12a83fec41143dec/contracts/handler/DefaultCallbackHandler.sol#L58

I'd be curious to see other contracts that do this.

@songhobby Do you know of any contracts or systems that assume the interface will be present in `supportsInterface`?

**Comment by songhobby** [comment]
@frangio Not what I'm aware of except for the Gnosis Safe as you pointed out! My rationale to submit issue is that if a contract implements `IERC165`, its `supportsInterface` SHOULD work for all the interfaces the contract implements, or at least for those public well-known interfaces like `IERC721Receiver`.

**Comment by frangio** [comment]
I'm leaning to not adding this to `supportsInterface`... If our implementation does that, others might be misled to think that they should check for the interface using `supportsInterface`, when the correct thing to do as far as I can tell is to call the function `onERC721Received` regardless.
