### ISSUE TITLE
Wrong distribution

### ISSUE THREAD

**Issue by Hikmo** [OpenZeppelin/openzeppelin-contracts#3521]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7a8f269457ca252605f03f8c2f8a333da6be1709/contracts/finance/VestingWallet.sol#L132

If a beneficiary tries to release his money for the second time, he will be getting wrong amount of tokens as contract calculates the releasble amount depending on the balance of the contract

**Comment by frangio** [comment]
The contract calculates the releasable amount as a function of the current balance but also the amount that has already been released in the past. See:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7a8f269457ca252605f03f8c2f8a333da6be1709/contracts/finance/VestingWallet.sol#L119
