### ISSUE TITLE
Address.sol using 0.8.1 pragma version compilation issue.

### ISSUE THREAD

**Issue by woosal1337** [OpenZeppelin/openzeppelin-contracts#3536]
**🧐 Motivation**
The Pragma version creates a problem in the compilation processes.

**📝 Details**
As compiling and deploying both require to have the .sol files to have the exact `pragma` editions, OpenZeppelin did a very decent job of keeping all of the files with a version of `^0.8.0`, however, after installing the contracts with ` npm install @openzeppelin/contracts` and trying to compile the project source code, I have noticed that `Address.sol` is using `pragma version ^0.8.1`, which creates an obstacle in the compilation process. I wondered if `Address.sol` had any specific purpose for using `^0.8.1` instead of `^0.8.0`? If not, then bringing it back to the `^0.8.0` would not be a good idea for a faster and smoother dev experience?

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol#L4

**Comment by frangio** [comment]
>As compiling and deploying both require to have the .sol files to have the exact pragma editions

This is not true. Files can have different pragmas. You need to use a compiler version that satisfies all pragmas. The latest 0.8 release will work. If you are only using files with `^0.8.0` and `^0.8.1` then you can use 0.8.1 or any later version.

The file has pragma `^0.8.1` because it needs a feature of the language that is only available in 0.8.1, it will not be possible to compile it with 0.8.0.

**Comment by woosal1337** [comment]
I agree, but if the project is meant to run on '^0.8.0', just because of one contract whole compilations fails if that makes sense.

**Comment by frangio** [comment]
No, `^0.8.0` is a range of versions that means `>=0.8.0 <0.9.0`.

**Comment by woosal1337** [comment]
I mean the compiler version. If the project was set to run and compile with `0.8.0` exactly, the whole project fails. Because of just one contract version out of dozens, you are supposed to use a compiler `^0.8.1`.
