### ISSUE TITLE
Library for safe interaction with untrusted contracts

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/openzeppelin-contracts#3544]
**Background**
> Inspired by [ExcessivelySafeCall](https://github.com/nomad-xyz/ExcessivelySafeCall)

A low-level Solidity call will copy _any amount of bytes_ to local memory. When bytes are copied from `returndata` to `memory`, the [memory expansion cost](https://ethereum.stackexchange.com/questions/92546/what-is-expansion-cost) is paid. This means that when using a standard Solidity call, the callee can **"returnbomb"** the caller, imposing an arbitrary gas cost. Because this gas is paid _by the caller_ and _in the caller's context_, it can cause the caller to run out of gas and halt execution.

**Details**

OpenZeppelin provides a library for safe interactions with untrusted contracts. Specifically, starting with `call` and `staticcall`. This would be in line with the current _safe_ libraries such as `SafeERC20` or `SafeCast`.

**Comment by frangio** [comment]
Discussed before in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3168.

See our thoughts for not including this in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3168#issuecomment-1034989864.

In summary, there are some contexts where this protection is useful, but we believe the vast majority of users are not affected by this attack and we do not want to encourage unnecessary use of the pattern.

Feel free to share if you disagree with this thinking. Will close as it has been discussed very recently.

**Comment by pcaversaccio** [comment]
I understand the arguments about the reach of use for this library. Nonetheless, let me share my use case for this library: I've built a [batch distributor](https://github.com/pcaversaccio/batch-distributor/blob/main/contracts/BatchDistributor.sol) which is essentially a helper smart contract for batch sending both native and ERC-20 tokens. Now, this contract is planned to be used by projects to distribute e.g. airdrops to registered wallets, distribute funding via ETH to registered wallets (for devs), or to pay crypto salaries to employees in one batch, just to name a few (think about it as a modern version of [disperse.app](https://[disperse](https://disperse.app/).app/). The major reason why I use the low-level call `call` instead of `transfer` is that the 2300 gas forward could be not enough for some cases where one of the addresses is more complex e.g. multisig addresses or smart contract wallets. So to summarise, I tried to be as agnostic as possible and do not check for the existing code of an address. 

Now in the context of my batch distributor, it can well be that you have a list of 100-200 addresses to send ETH or ERC20 tokens to. Now assume one or two of the addresses try to _returnbomb_ the distribution and make the sender pay unnecessary money. There are two ways to resolve that:
- Check each address if it's an EOA
- Use such a library for the low-level calls.

If the sender of a batch is not an advanced user, he/she might even trigger a couple of times the same transaction because Etherscan will just show an OOG error and probably he/she will not use e.g. Tenderly to debug the failing transaction in detail.

It might be a niche case, but I still wanted to share that with you. It'r relevant for a use case where you send batches of ETH to a large list of "unknown" addresses.

**Comment by frangio** [comment]
In the case you describe you're not interested in the returndata at all, so it's not necessary to copy it to memory. If you don't copy it, the target contract can't cause any additional gas to be wasted.

This was addressed by the compiler in https://github.com/ethereum/solidity/issues/12647, and the fix was released in 0.8.13 apparently (not in the changelog so I've asked to confirm https://github.com/ethereum/solidity/pull/12684#issuecomment-1185771667).

**Comment by pcaversaccio** [comment]
Ah very interesting, I was not aware that this was addressed by `0.8.13`. Thanks for the reference @frangio. In this case (since I'm using `0.8.15`) everything looks fine for my use case.
