### ISSUE TITLE
Minor issue: 404/Path not found - ReentrancyGuard

### ISSUE THREAD

**Issue by krakxn** [OpenZeppelin/openzeppelin-contracts#3558]
***The error:*** *The 'OpenZeppelin/openzeppelin-contracts' repository doesn't contain the 'contracts/utils/ReentrancyGuard.sol' path in 'master'.*

***Caveats:*** I know *master* is deprecated, I also tried *main* but it apparently is still not traceable. Or if it is not supposed to be there in the repo.

Appreciated if someone could let me know the updated location where it would have been moved, or if it was outright removed - unless, of course, there is a issue with the path and it is supposed to be there.

Cheers and thank you!

**Comment by Amxx** [comment]
Hello @krakxn 

Since 4.0, `ReentrancyGuard.sol` is in `contracts/security` and not in `contracts/utils`

**Comment by krakxn** [comment]
Thank you!!
