### ISSUE TITLE
Feature Request: Enumerable for ERC1155

### ISSUE THREAD

**Issue by xinbenlv** [OpenZeppelin/openzeppelin-contracts#3564]
**🧐 Motivation**
ERC1155 didn't define enumerable interface, but can be useful to create one for dApp to use.

**📝 Details**
```solidity
interface ERC1155 {
    function totalTokenIds() external view returns (uint256);
    function tokenIdByIndex(uint256 _index) external view returns (uint256);
    function tokenIdByIndexOfOwner(address _owner, uint256 _tokenIndex) external view returns (uint256);
}
```

I wonder if there were previous discussion of adding such features

Also mentioned in https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/issues/166

**Comment by frangio** [comment]
Thanks for the suggestion. ERC721 enumerability is specified in the EIP, while ERC1155 enumerability isn't. Given the lack of a standard, and that ERC721 enumerability is a frequent source of discontent due to its gas overhead, I don't think ERC1155 enumerability is something we should include.
