### ISSUE TITLE
Error: "setData is assigned a value but never used"

### ISSUE THREAD

**Issue by mvwmotor** [OpenZeppelin/openzeppelin-contracts#3566]
Hello,
Excuse me for disturbing you,

I meet a problem when I start the react app, the app start without any problems but the number of the NFT already sold don't appears and the price also (you can see on the screen).

This is the warn message:
 Line 22:16:  'setData' is assigned a value but never used  no-unused-vars
  Line 35:15:  'object' is assigned a value but never used   no-unused-vars

**This the App.js code:**

import { useState, useEffect } from 'react';
import { ethers } from 'ethers';
import GeometricFox from './artifacts/contracts/GeometricFox.sol/GeometricFox.json';
import './App.css';
import img1 from './img/1.png';
import img2 from './img/4.png';
import img3 from './img/76.png';
import img4 from './img/93.png';
import img5 from './img/289.png';
import img6 from './img/391.png';
import img7 from './img/409.png';
import img8 from './img/1101.png';
import img9 from './img/1472.png';
import img10 from './img/1487.png';

const GFaddress = "0xCaf8Ab5A19213a8dBbA78fAC75c1eD38DEBe080b"

function App() {

  const [error, setError] = useState('');
  const [data, setData] = useState({})

  useEffect(() => {
    fetchData();
  }, [])

  async function fetchData() {
    if(typeof window.ethereum !== 'undefined') {
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      const contract = new ethers.Contract(GFaddress, GeometricFox.abi, provider);
      try {
        const cost = await contract.cost();
        const totalSupply = await contract.totalSupply();
        const object = {"cost": String(cost), "totalSupply": String(totalSupply)}
      }
      catch(err) {
        setError(err.message);
      }
    }
  }

  async function mint() {
    if(typeof window.ethereum !== 'undefined') {
      let accounts = await window.ethereum.request({method: 'eth_requestAccounts'});
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      const signer = provider.getSigner();
      const contract = new ethers.Contract(GFaddress, GeometricFox.abi, signer);
      try {
        let overrides = {
          from: accounts[0],
          value: data.cost
        }
        const transaction = await contract.mint(accounts[0], 1, overrides);
        await transaction.wait();
        fetchData();
      }
      catch(err) {
        setError(err.message);
      }
    }
  }

  return (
    <div className="App">
      <div className="container">
        <div className="banniere">
          < img src={img1} alt="img" />
          < img src={img2} alt="img" />
          < img src={img3} alt="img" />
          < img src={img4} alt="img" />
          < img src={img5} alt="img" />
          < img src={img6} alt="img" />
          < img src={img7} alt="img" />
          < img src={img8} alt="img" />
          < img src={img9} alt="img" />
          < img src={img10} alt="img" />
        < /div>
        {error && <p>{error}</p>}
        < h1>Mint a Geometric Fox NFT</h1>
        < p className='count'>{data.totalSupply} / 1542</p>
        < p className="cost">Each Geometric Fox NFT costs {data.cost / 10**18} eth (excluding gas fees)</p>
        < button onClick={mint}>BUY one Geometric Fox NFT</button>
      < /div>
    < /div>
  );
}

export default App;

**Contract Code:**

// SPDX-License-Identifier: GPL-3.0

// Created by HashLips
// The Nerdy Coder Clones

pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract GreedyGeese is ERC721Enumerable, Ownable {
  using Strings for uint256;

  string public baseURI;
  string public baseExtension = ".json";
  uint256 public cost = 0.01 ether;
  uint256 public maxSupply = 50;
  uint256 public maxMintAmount = 1542;
  bool public paused = false;
  mapping(address => bool) public whitelisted;

  constructor(
    string memory _name,
    string memory _symbol,
    string memory _initBaseURI
  ) ERC721(_name, _symbol) {
    setBaseURI(_initBaseURI);
    mint(msg.sender, 5);
  }

  // internal
  function _baseURI() internal view virtual override returns (string memory) {
    return baseURI;
  }

  // public
  function mint(address _to, uint256 _mintAmount) public payable {
    uint256 supply = totalSupply();
    require(!paused);
    require(_mintAmount > 0);
    require(_mintAmount <= maxMintAmount);
    require(supply + _mintAmount <= maxSupply);

    if (msg.sender != owner()) {
        if(whitelisted[msg.sender] != true) {
          require(msg.value >= cost * _mintAmount);
        }
    }

    for (uint256 i = 1; i <= _mintAmount; i++) {
      _safeMint(_to, supply + i);
    }
  }

  function walletOfOwner(address _owner)
    public
    view
    returns (uint256[] memory)
  {
    uint256 ownerTokenCount = balanceOf(_owner);
    uint256[] memory tokenIds = new uint256[](ownerTokenCount);
    for (uint256 i; i < ownerTokenCount; i++) {
      tokenIds[i] = tokenOfOwnerByIndex(_owner, i);
    }
    return tokenIds;
  }

  function tokenURI(uint256 tokenId)
    public
    view
    virtual
    override
    returns (string memory)
  {
    require(
      _exists(tokenId),
      "ERC721Metadata: URI query for nonexistent token"
    );

    string memory currentBaseURI = _baseURI();
    return bytes(currentBaseURI).length > 0
        ? string(abi.encodePacked(currentBaseURI, tokenId.toString(), baseExtension))
        : "";
  }

  //only owner
  function setCost(uint256 _newCost) public onlyOwner {
    cost = _newCost;
  }

  function setmaxMintAmount(uint256 _newmaxMintAmount) public onlyOwner {
    maxMintAmount = _newmaxMintAmount;
  }

  function setBaseURI(string memory _newBaseURI) public onlyOwner {
    baseURI = _newBaseURI;
  }

  function setBaseExtension(string memory _newBaseExtension) public onlyOwner {
    baseExtension = _newBaseExtension;
  }

  function pause(bool _state) public onlyOwner {
    paused = _state;
  }
 
 function whitelistUser(address _user) public onlyOwner {
    whitelisted[_user] = true;
  }
 
  function removeWhitelistUser(address _user) public onlyOwner {
    whitelisted[_user] = false;
  }

  function withdraw() public payable onlyOwner {
    require(payable(msg.sender).send(address(this).balance));
  }
}

**Comment by frangio** [comment]
Please only report things that relate to smart contracts. React application issues are 100% out of scope.
