### ISSUE TITLE
Error importing OpenZeppelin contracts 

### ISSUE THREAD

**Issue by mvwmotor** [OpenZeppelin/openzeppelin-contracts#3568]
Hello,
Escuse me for disturbing you,

I was following the OpenZepellin doc on developing smart contracts and after installing truffle (in my current working directory) with command

npx truffle init

I then tried installing the OpenZeppelin contracts library (also in my current working directory) with command

npm install --save-dev @openzeppelin/contracts
it seemed like it worked, but then when I try importing the Ownable contract in my contracts folder in VSCode, with the command

import "@openzeppelin/contracts/access/Ownable.sol";

i get this

Source "@openzeppelin/contracts/access/Ownable.sol" not found: File import callback not supported

Thanks of reading, maybe someone can help me.

**Comment by Niceural** [comment]
I followed the steps you described but it worked for me. Maybe try to uninstall and reinstall the last version of truffle as suggested here. 
https://github.com/trufflesuite/truffle/issues/400#issuecomment-300848323
Hope it helps!

**Comment by mvwmotor** [comment]
it didn't work but thanks for your help 😄

**Comment by divyam-07** [comment]
@mvwmotor you can use absolute path instead of using relative path. 
Hope this might work :)

**Comment by mvwmotor** [comment]
> @mvwmotor you can use absolute path instead of using relative path. 
> 
> Hope this might work :)
Yes but I think I would prefer an easier solution 
Thanks you so much fo your proposition 😁

**Comment by frangio** [comment]
This should work, it's likely some other error. Please post your question on https://forum.openzeppelin.com and describe the steps to reproduce in detail.

**Comment by divyam-07** [comment]
If I get one then I ll surely convey to you 😀
