### ISSUE TITLE
ERC1155 doesn't work with block explorers, wallets, or marketplaces.

### ISSUE THREAD

**Issue by gnomadic** [OpenZeppelin/openzeppelin-contracts#3571]
**🧐 Motivation**
It would be nice if the ERC-1155 contract worked out of the box with block explorers like etherscan (or polygonscan etc), wallets like metamask, and marketplaces like opensea

**📝 Details**

Basically some variant of an ERC-1155 which is interoperable and compatible with all EVM ecosystems out of the box!

**Comment by frangio** [comment]
This is a problem that needs standardization. We can't solve it with an OpenZeppelin feature, and we won't ship something so central without involving the broader ecosystem first. I suggest drafting an EIP and sharing it with relevant parties.

Note that your proposed features are specifically addressed in [EIP-1155](https://eips.ethereum.org/EIPS/eip-1155#metadata-choices):

> Rationale
> Metadata Choices
>
> The symbol function (found in the ERC-20 and ERC-721 standards) was not included as we do not believe this is a globally useful piece of data to identify a generic virtual item / asset and are also prone to collisions. Short-hand symbols are used in tickers and currency trading, but they aren’t as useful outside of that space.
> 
> The name function (for human-readable asset names, on-chain) was removed from the standard to allow the Metadata JSON to be the definitive asset name and reduce duplication of data. This also allows localization for names, which would otherwise be prohibitively expensive if each language string was stored on-chain, not to mention bloating the standard interface. While this decision may add a small burden on implementers to host a JSON file containing metadata, we believe any serious implementation of ERC-1155 will already utilize JSON

**Comment by gnomadic** [comment]
I mean that's why I implemented it as an extension and not as the base - some of the other extensions, like URI storage also don't support the ERC.

Still, even though I disagree because the current OZ 1155 isn't practically usable, I hear yeah- standards and important, especially for openzeppelin.
