### ISSUE TITLE
Grouping the extension access control contracts into one `extensions/` folder

### ISSUE THREAD

**Issue by 0xisk** [OpenZeppelin/openzeppelin-contracts#3583]
**🧐 Motivation**
I think grouping the extension access control contracts would be more readable and organized, as it happens with the token standard contracts. 

**📝 Details**
### Current structure: 
```
contracts   
│
└─── access
    │   AccessControl.sol
    │   AccessControlCrossChain.sol     "Extension contract"
    │   AccessControlEnumerable.sol    "Extension contract"
    │   IAccessControlEnumerable.sol   "Extension contract interface"
    │   ...
    └───
```

### Expected structure: 
```
contracts   
│
└─── access
     │
     └─── extensions
     │    │   AccessControlCrossChain.sol     "Extension contract"
     │    │   AccessControlEnumerable.sol    "Extension contract"
     │    │   IAccessControlEnumerable.sol   "Extension contract interface"
     │    └───
     │   AccessControl.sol
     │   ...
     └───
```

**Comment by Amxx** [comment]
As discussed in the original PR, this would be a breaking change  as far as the import paths are concerned.
Suggest we put that in the 5.0 roadmap

**Comment by iskdrews** [comment]
Thanks, @Amxx I just wanted to log it here as discussed so you can discuss with the team it later milestone.

**Comment by balajipachai** [comment]
@Amxx any updates, can a PR be submitted for it?
