### ISSUE TITLE
Add internal functions to get values of _initialized and _initializing

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3584]
Referring to Initializable.

- `Initializable._getInitializedVersion() returns (uint8)`
- `Initializable._isInitializing() returns (bool)`

**Comment by hrik2001** [comment]
Hello @frangio.
Will it be okay if I do a PR on this? It seems like something I can implement. Do let me know if there's more to it. Thanks!

**Comment by frangio** [comment]
@hrik2001 Yes go ahead! I've added function signature to the issue description.
