### ISSUE TITLE
Documentation has broken links related to Preset contracts

### ISSUE THREAD

**Issue by YoungeonLee** [OpenZeppelin/openzeppelin-contracts#3590]
The [doc](https://docs.openzeppelin.com/contracts/4.x/erc1155#Presets) has a broken link: [ERC1155PresetMinterPauser](https://docs.openzeppelin.com/contracts/4.x/erc1155#api:presets.adoc#ERC1155PresetMinterPauser).

I think the doc should either remove the "Preset ERC1155 contract" section or explain that 
> Contract presets are now deprecated in favor of [Contracts Wizard](https://wizard.openzeppelin.com/) as a more powerful alternative

The same issue applies to ERC20 and ERC721.

**Comment by frangio** [comment]
Thank you. This also applies to the ERC721 and ERC20 pages.

**Comment by ef3n9r98** [comment]
Hi @JulissaDantes, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much?

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by JulissaDantes** [comment]
@ef3n9r98 Thanks for the interest! There isn't a budget for this, since OpenZeppelin does not offer grants to work on certain features, but if you find a security issue you might be eligible to get a bug bounty. More information [here](https://immunefi.com/bounty/openzeppelin/).

**Comment by SensationalShubham** [comment]
Hii @YoungeonLee, All links are working fine by my side. Can you close this issue now, or is there something I didn't notice?
