### ISSUE TITLE
AccessControl report bug: TypeError: Member "toHexString" not found or not visible after argument-dependent lookup in type(library Strings).

### ISSUE THREAD

**Issue by AmazingAng** [OpenZeppelin/openzeppelin-contracts#3615]
When I ran [AccessControl.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControl.sol), there is bug report:

```
TypeError: Member "toHexString" not found or not visible after argument-dependent lookup in type(library Strings).
```
**📝 Details**

There is a bug for `_checkRole()` function
```solidity
    function _checkRole(bytes32 role, address account) internal view virtual {
        if (!hasRole(role, account)) {
            revert(
                string(
                    abi.encodePacked(
                        "AccessControl: account ",
                        Strings.toHexString(account),
                        " is missing role ",
                        Strings.toHexString(uint256(role), 32)
                    )
                )
            );
        }
    }
```

The `toHexString` function in `String.sol` library is `internal`. I suggest removing the `String.sol` library import.

**🔢 Code to reproduce bug**

Run AccessControl.sol

**Comment by Amxx** [comment]
Hello @AmazingAng 

Could you possibly be using an old version of the Strings library? How did you import the code in your project?

**Comment by frangio** [comment]
If you need further support please post in the forum.openzeppelin.com/.

**Comment by yvasilyev92** [comment]
I've started getting this error in Remix as well, I've used OZ AccessControl.sol plenty of times before in the past and never had this issue. Even my deployed contracts source code is now showing the error-highlight in remix. 
Was a solution found for this?

**Comment by josephnaber** [comment]
It is likely just a mismatch of the versions of your dependencies.  Remove your dependencies from the project and allow them to re-load and recompile
