### ISSUE TITLE
similar match source code on ethereum scan page

### ISSUE THREAD

**Issue by VineeDev** [OpenZeppelin/openzeppelin-contracts#3622]
We have deployed an erc20 proxy smart contract but on Ethereum explorer. It is showing a warning
`similar match source code`.
![Screenshot_2022-08-05_at_9 09 49_PM](https://user-images.githubusercontent.com/62244772/184935128-cffb4870-05a5-4cd6-a19c-7a89ab90126c.png)

We want to avoid warning `similar match source code` on the eth scan page.
I have followed the openzepplin upgradable standard formats.

**Comment by frangio** [comment]
Please do not post in our two channels at the same time. Will reply on your [forum thread](https://forum.openzeppelin.com/t/how-to-avoid-warning-similar-match-source-code-on-ethereum-scan-page/31227).
