### ISSUE TITLE
ERIC721 | adding UniqueURI validator to the ERC721URIStorage._setTokenURI() method

### ISSUE THREAD

**Issue by martinmamdouh** [OpenZeppelin/openzeppelin-contracts#3628]
Problem 
"IF in the real-world two paper contracts can point to the same apartment "asset" with two different owners, here we can have two different NFTs (2 different token_id with two different owners) pointing to the same URI."

Actually, I was writing an NFT token contract inspiring it from the code of the published [zeppelin GameItem example](https://docs.openzeppelin.com/contracts/3.x/erc721) and I found a critical issue, which is having duplicate URIs with different token_id stored in` _tokenURIs` mapping by invoking the `ERC721URIStorage._setTokenURI()` method.
and in the implementation of `ERC721URIStorage._setTokenURI()` we are checking only if the token_id exists or not and my suggestion is to add one more validator to validate that the URI is unique and it's not associated with a different token already.

Thanks
Martin

**Comment by Niceural** [comment]
Hi Martin!
The [ERC721 token standard](https://eips.ethereum.org/EIPS/eip-721) does not require the verification of a token URI being unique. In addition, an ERC721 might choose to allow multiple token IDs to have the same token URI.
The example in Openzeppelin's documentation is a simple use case example. If you want to ensure that each token URI is unique, you could implement a check in your mint function, or the token URI could be set by the contract and not by the wallet calling the mint function.

**Comment by martinmamdouh** [comment]
Thanks! Niceural for the clarification.
