### ISSUE TITLE
Utilities documentation has broken links

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/openzeppelin-contracts#3629]
https://docs.openzeppelin.com/contracts/4.x/utilities has broken links in the Cryptography, Introspection, Math, and Payment sections.

For example, ECDSA links to https://docs.openzeppelin.com/contracts/4.x/utilities#api:cryptography.adoc#ECDSA whereas it should be https://docs.openzeppelin.com/contracts/4.x/api/utils#ECDSA

**Comment by frangio** [comment]
Thanks. Fixed in bbb9a178721dd8430262ac49e06b205b0b81213b.
