### ISSUE TITLE
ERC777: Incompatible ERC1820 registry address with hardhat

### ISSUE THREAD

**Issue by satya1807** [OpenZeppelin/openzeppelin-contracts#3631]
When trying to deploy a ERC777 token I have got the following error.

![image](https://user-images.githubusercontent.com/102351469/185360671-d76d1189-496e-48a5-835a-ec7744bc6b0c.png)

After debugging I have found that the ERC777 constructor is making a call to the ERC1820 registry the interface in [this](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/54dec0cad5bd52ec95cc4a042cae133e9388465c/contracts/token/ERC777/ERC777.sol#L74) line.

Then after searching the address on the etherscan.io, it is confirmed that the address mentioned is the ERC1820 registry contract deployed on Ethereum mainnet.

**💻 Environment**

- Hardhat
- Solidity version 0.8.6
- OpenZeppelin version - 4.7.1

**🔢 Code to reproduce bug**

```
contract Token777 is ERC777, Ownable {
    constructor(
        string memory name_,
        string memory symbol_,
        address[] memory initial_operators,
        uint256 _reserved,
        uint256 _amount,
        address _user
    ) ERC777(name_, symbol_, initial_operators) {
        require(
            _start >= block.timestamp && _end > _start,
            "Invalid time stamps"
        );
        require(_tokenPrice > 0, "Invalid token price");
        require(_reserved > 0, "Invalid reserved amount");
        require(_amount > 0, "Invalid amount");
        require(_user != address(0), "Invalid owner");

        

        _mint(address(this), _amount, "", "", false);
        _mint(_user, reserved, "", "", false);
        _transferOwnership(_user);
    }
```

**Comment by Amxx** [comment]
Hello @satya1807 

This is an unfortunate requirement of ERC-777. It depends on ERC-1820 which dictates that the registry contract must be at address `0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24`.

[You can find that, and the transaction that is used to deploy the registry, in the EIP document](https://eips.ethereum.org/EIPS/eip-1820)

For your tests, there is an helper that you can use:

```
const { singletons } = require('@openzeppelin/test-helpers');

// ...
beforeEach(async function () {
    this.erc1820 = await singletons.ERC1820Registry(<address of an account that has funds to pay for the deployment>);
});
```

**Comment by Amxx** [comment]
Relevant documentation: https://docs.openzeppelin.com/test-helpers/0.5/api#singletons
