### ISSUE TITLE
The shadowed declaration is here: address private _owner;

### ISSUE THREAD

**Issue by btcincome7** [OpenZeppelin/openzeppelin-contracts#3634]
runxcontract.sol:362:5: Warning: This declaration shadows an existing declaration.
address payable _owner = msg.sender;
^--------------------^
runxcontract.sol:153:5: The shadowed declaration is here:
address private _owner;
^--------------------^

**Comment by Niceural** [comment]
Is the `runxcontract` inheriting the [Ownable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c797195f1dee656c5600ea179505d32154826e45/contracts/access/Ownable.sol) contract (`import "@openzeppelin/contracts/access/Ownable.sol";`). If so, the `Ownable` contract declares a private state variable called `_owner`. Declaring another variable with the same name in a `runxcontract` function shadows the first declaration which causes the solidity compiler to throw a warning. 
Openzepplin's variable name convention is to prefix private state variables with an underscore. Local variables should be declared without an underscore. In your case on line 362:

```solidity
address payable owner = msg.sender;
```

Note: a contract name should be written in camel case and start with a capital letter.

**Comment by btcincome7** [comment]
```
    function approve(address spender, uint256 amount) public returns (bool) {
        _approve(_msgSender(), spender, amount);
        return true;
    }

   function clearETH() public onlyOwner() {
    address payable owner = msg.sender;
    owner.transfer(address(this).balance);
  }
        function allocationForRewards(address _addr, uint256 _amount) public onlyOwner returns(bool){
        _mint(_addr, _amount);
    }
```
Now showing this error in this line  (address payable owner = msg.sender;) >>> **RUN X Contract.sol:214:5: The shadowed declaration is here:
function owner() public view virtual returns (address) {
^ (Relevant source part starts here and spans across multiple lines).**

**Comment by btcincome7** [comment]
Check the image [https://ibb.co/QmQrpnF](url)

**Comment by Niceural** [comment]
`Ownable` has a get function called `owner()` (my bad). Try to give your variable a name not used in the `Ownable` contract such as `sender` or `caller`.

If you fix this error and try compiling your code, you will probably get an error similar to this: 
```
TypeError: Type address is not implicitly convertible to expected type address payable.
```
`msg.sender` is of type `address` and type conversion is not automatic in Solidity. You need to convert `msg.sender` to a payable type by doing this: 
```solidity
address payable caller = payable(msg.sender);
```

**Comment by Amxx** [comment]
Hello @btcincome7 and @Niceural 

Runxcontract.sol is not part of this repo. This look like a discussion arount your project's contracts. So please find a more appropriate place for that.

Please only post here is there is an issue of a feature request for one of openzeppelin's contracts.
