### ISSUE TITLE
ERC-20 token tax 

### ISSUE THREAD

**Issue by Zeked9** [OpenZeppelin/openzeppelin-contracts#3656]
I propose that all ERC-20 tokens should impose a 10% transfer tax, that goes to the founders.

**Comment by Amxx** [comment]
Hello @Zeked9 

This was already discussed many time in this repo and in the [openzeppelin forum](forum.openzeppelin.com/). 

This is a very opinionated approach, that we definitely don't want to include by default. If you really want to build that (be aware it could break compatibility with many DeFi primitives), then you can do that pretty easily. I believe a quick search on the forum will show you a few example of code doing that.
