### ISSUE TITLE
VestingWallet: allow to change beneficiary address

### ISSUE THREAD

**Issue by TrejGun** [OpenZeppelin/openzeppelin-contracts#3658]
**🧐 Motivation**

The whole US economy is built on debts. Here is an example from the top of my dome - USDT. It is backed by government bonds. So I want to be able to sell my vesting wallet for immediate profit rather than wait for it to be unlocked for one year. Say I have a vesting for 1000 USDT with the interest of 100 USDT in one year. This money is locked and nobody can gain profit from it. But I'm short on money and want to sell it for 900 USDT in the middle of the period. With the current implementation, I will die from starvation while the reason for vesting is not to starve me out but to prevent liquidity drops.

**📝 Details**

While it is perfectly aligned with other properties set in the constructor, I request to change this line 
```
address private immutable _beneficiary;
```
for
```
address private _beneficiary;
```
and add some setter with event
```
  event BeneficiaryChanged(address indexed beneficiary);

  function _setBeneficiary(address beneficiary) internal {
    _beneficiary = beneficiary;
    emit BeneficiaryChanged(beneficiary);
  }
```
It has to be overridden to be used so no API change and no potential vulnerability is introduced

**Comment by Amxx** [comment]
Hello @TrejGun 

Doing this change in the Contracts repo would be a breaking change. It is however very easy to override the beneficiary to use a ownership mechanism.

This was showcased:
- Using NFTs in [this hackathon project](https://github.com/Amxx/NonFungibleFinance/blob/master/solidity/contracts/VestingFactory.sol)
- Using ownable in [this thirdweb template](https://thirdweb.com/hadriencroubois.eth/Vesting)

**Comment by Amxx** [comment]
Also note: making the beneficiary non immutable will increase the gas cost for immutable case. So I really lean toward not changing anything, and relying on user overrides.

**Comment by Amxx** [comment]
Your right, it wouldn't

**Comment by frangio** [comment]
> the reason for vesting is [...] to prevent liquidity drops.

This is not 100% true generally. The other reason for vesting is to align incentives, precisely by preventing early cashouts.

For now I would close this, as it can be implemented via overrides. I will agree that it isn't very intuitive though. Unfortunately we need to make a tradeoff given the limitations of Solidity.
