### ISSUE TITLE
Consider adding buyability for contract ownership

### ISSUE THREAD

**Issue by aglawson** [OpenZeppelin/openzeppelin-contracts#3663]
**🧐 Motivation**
Make DApps purchasable. Useful for freelance devs who want to sell their code on the blockchain securely and without trust. 

**📝 Details**

This would give the owner of the contract the ability to sell ownership of the contract. If the right price is submitted by a buyer, ownership is transferred.

Merge request [here](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3646) was rejected, and tokenizing ownership was suggested. However, this requires inheriting ERC721 libraries into a contract which may not need those dependencies for anything else. This unnecessarily balloons deployment costs. 
Other suggestions may be helpful, such as enabling ERC20 payments.

**Comment by frangio** [comment]
Thank you for the suggestions @aglawson. However, these are experimental projects and OpenZeppelin Contracts is not the place for them. We try to focus on things that have proven value, and that will be generally useful.

**Comment by aglawson** [comment]
I understand, thank you for your response.
