### ISSUE TITLE
Loss of unused Ether in meta-transaction

### ISSUE THREAD

**Issue by aaaooie** [OpenZeppelin/openzeppelin-contracts#3664]
In the `MinimalForwarder.execute(ForwardRequest req, bytes signature)` payable function, the `msg.value`   may contain more Ether than specified in `req.value`. In this case (since only `req.value` is transferred further), the unused amount of Ether will remain on the contract address.

**Comment by frangio** [comment]
Thank you @aaaooie. As mentioned in the comments:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4b8b92c8bf8d2efaee7444a6470d4ec4f86c36bf/contracts/metatx/MinimalForwarder.sol#L12-L15

MinimalForwarder is inded too minimal. So much so I think we might be better off removing it.
