### ISSUE TITLE
error[6275]: ParserError:

### ISSUE THREAD

**Issue by justinzarate** [OpenZeppelin/openzeppelin-contracts#3675]
So I am trying to deploy a contract using foundry-rs. So far everything is looking good, but right when I began to compile I run into an error (full error listed below).

I have made sure to source .env before forging
I have also made sure to double check my paths and echoed to my .env 

---------------------------------------------------------------------------------------------------------------------------------

**Compiler run failed
error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/token/ERC20/extensions/ERC20Votes.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/ERC20VotesHarness.sol:1:1:
  |
1 | import "../munged/token/ERC20/extensions/ERC20Votes.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/governance/Governor.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/WizardControlFirstPriority.sol:4:1:
  |
4 | import "../munged/governance/Governor.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/governance/extensions/GovernorCountingSimple.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/WizardControlFirstPriority.sol:5:1:
  |
5 | import "../munged/governance/extensions/GovernorCountingSimple.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/governance/extensions/GovernorVotes.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/WizardControlFirstPriority.sol:6:1:
  |
6 | import "../munged/governance/extensions/GovernorVotes.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/governance/extensions/GovernorVotesQuorumFraction.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/WizardControlFirstPriority.sol:7:1:
  |
7 | import "../munged/governance/extensions/GovernorVotesQuorumFraction.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/governance/extensions/GovernorTimelockControl.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/WizardControlFirstPriority.sol:8:1:
  |
8 | import "../munged/governance/extensions/GovernorTimelockControl.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/governance/extensions/GovernorProposalThreshold.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/WizardControlFirstPriority.sol:9:1:
  |
9 | import "../munged/governance/extensions/GovernorProposalThreshold.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/governance/Governor.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/WizardFirstTry.sol:4:1:
  |
4 | import "../munged/governance/Governor.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/governance/extensions/GovernorCountingSimple.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/WizardFirstTry.sol:5:1:
  |
5 | import "../munged/governance/extensions/GovernorCountingSimple.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/governance/extensions/GovernorVotes.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/WizardFirstTry.sol:6:1:
  |
6 | import "../munged/governance/extensions/GovernorVotes.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/governance/extensions/GovernorVotesQuorumFraction.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/WizardFirstTry.sol:7:1:
  |
7 | import "../munged/governance/extensions/GovernorVotesQuorumFraction.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[6275]: ParserError: Source "lib/openzeppelin-contracts/certora/munged/governance/extensions/GovernorTimelockCompound.sol" not found: File not found. Searched the following locations: "/Users/justinzarate/hello_foundry", "/Users/justinzarate/hello_foundry/script", "/Users/justinzarate/hello_foundry/test".
 --> lib/openzeppelin-contracts/certora/harnesses/WizardFirstTry.sol:8:1:
  |
8 | import "../munged/governance/extensions/GovernorTimelockCompound.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^**

**Comment by frangio** [comment]
Can you share a link to a repository or describe your setup in more detail? What is in your lib directory, etc.

**Comment by justinzarate** [comment]
> 

https://github.com/justinzarate/hello_foundry/tree/master/lib

**Comment by frangio** [comment]
Can you try setting `src = 'src'` in your config? I believe this may be causing the problem. This is the recommended configuration I get from `forge init`.

https://github.com/justinzarate/hello_foundry/blob/b916ae0ee2b2b4fefc6f4782a650ac4a6a3f0988/foundry.toml#L2

**Comment by justinzarate** [comment]
> Can you try setting `src = 'src'` in your config? I believe this may be causing the problem. This is the recommended configuration I get from `forge init`.
> 
> https://github.com/justinzarate/hello_foundry/blob/b916ae0ee2b2b4fefc6f4782a650ac4a6a3f0988/foundry.toml#L2

Worked! Thanks. You're amazing. Sending you good energy my friend.
