### ISSUE TITLE
Emit compiler warnings as errors

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3686]
We have had compiler warnings that we should pay attention to but we missed them due to a bunch of other warnings that not so relevant. We should configure Hardhat to emit warnings as errors. We should make it ignore code size warnings unless optimizations are enabled (in which case it requires attention).

Additionally we need a way to ignore warnings selectively in some cases. This is a longstanding missing feature in solc but we can make a Hardhat plugin for it.

**Comment by CryptoSafemoon** [comment]
I also had these problems
