### ISSUE TITLE
ERC4626 should initialize ERC20 token in the constructor

### ISSUE THREAD

**Issue by zoey-t** [OpenZeppelin/openzeppelin-contracts#3689]
The ERC4626 contract does initialize the inherited ERC20 contract in the constructor.

**💻 Environment**
MacOS 12.5.1 M1

v4.7.3
**📝 Details**
The ERC4626 contract inherited an ERC20 token. But the ERC4626 contract does not initialize this token with name and symbol.
It would be more intuitive and easy to understand if the token name and symbol are initialized together with the ERC4626 directly.

**Comment by frangio** [comment]
This is a breaking change that we won't do. Most of the contracts work as "modules" and don't have constructor arguments for their parents. You shouldn't see ERC4626 as a replacement for inheriting ERC20, you should see it as an addon to ERC20.

ERC4626 is not in Contracts Wizard yet but you can look at it to see how it deals with other similar extensions: https://wizard.openzeppelin.com/

```solidity
contract MyToken is ERC20, ERC4626 {
    constructor() ERC20("name", "symbol) ERC4626(...) {}
}
```
