### ISSUE TITLE
Replace `abi.encodeWithSelector` by `abi.encodeCall`

### ISSUE THREAD

**Issue by wiasliaw** [OpenZeppelin/openzeppelin-contracts#3693]
**🧐 Motivation**
Since 0.8.11, `abi.encodeCall` provide type-safe encode utility comparing with `abi.encodeWithSelector`.

**📝 Details**
Example below and detail are from [DevTools Summit | Topics in Solidity - Harikrishnan Mulackal](https://www.youtube.com/watch?v=CDkJ8rIfqWg).

`abi.encodeWithSelector` can use with `interface.<function>.selector` to prevent typo error, but it doesn't provide type checking.

```solidity
interface miniERC20 {
  function transfer(address to, uint256 value) external;
}

// works successfully
function transferData(uint256 to, uint256 value)
    public
    pure
    returns (bytes memory)
{
    return abi.encodeWithSelector(miniERC20.transfer.selector, to, value);
}
```

`abi.encodeCall` provide type checking during compile time.

```solidity
function transferData(uint256 to, uint256 value)
    public
    pure
    returns (bytes memory)
{
    return abi.encodeCall(miniERC20.transfer, (to, value));
}
```

result
```
error[5407]: TypeError: Cannot implicitly convert component at position 0 from "uint256" to "address".
```

**Comment by frangio** [comment]
We should definitely do this, but it requires bumping the Solidity pragma and this is a breaking change.

**Comment by 0xad1onchain** [comment]
To implement this change, the pragma upgrade at min must be >= 0.8.13, since the original implementation was bugged
[Ref to blogpost describing bug](https://blog.soliditylang.org/2022/03/16/encodecall-bug/)

**Comment by frangio** [comment]
@balajipachai Do you want to help with this issue?

**Comment by balajipachai** [comment]
@frangio Let me check this and get back to you if I have any questions, however, thanks a lot for pointing me over here
