### ISSUE TITLE
`CHANGELOG` too big for rendering on GitHub

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/openzeppelin-contracts#3696]
When I click on the current [`CHANGELOG`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CHANGELOG.md) (the same happens with the `v4.8.0-rc.0` version fyi), I get the following GitHub issue:

![image](https://user-images.githubusercontent.com/25297591/189652751-3c7e9ebe-7c66-4362-bf4c-7fa1c17914bd.png)

PS: I don't know whether it's a current GH issue, since they had some problems this morning...

**Comment by frangio** [comment]
I can't reproduce this. Does it happen consistently? Can someone else confirm?

We could split the changelog up for the different majors but if we can avoid that it would be better.

**Comment by pcaversaccio** [comment]
Ok now it's working again - so my guess is that GitHub had a problem on that day. I will close that issue for the moment. Splitting up the `CHANGELOG` would not be such a nice solution :-D.
