### ISSUE TITLE
Integrate EIP-5679: Token Minting and Burning

### ISSUE THREAD

**Issue by xinbenlv** [OpenZeppelin/openzeppelin-contracts#3709]
**🧐 Motivation**
Hi I'd love to propose the OZ contract to standardize the Minting and Burning as per [EIP-5679](https://eips.ethereum.org/EIPS/eip-5679). The EIP has been drafted with OZ's ERC-20, ERC-721 and ERC-1155 in mind.
The major change that is needed for current OZ contract to comply with the draft of EIP-5679 are

- EIP-20 Mintable and Burnable to also respond to EIP-165 identifiers
- EIP-721 Mintable and Burnable to also respond to EIP-165 identifiers
- EIP-1155 Mintable and Burnbale to respond to EIP-165 identifiers plus change `mint` to `safeMint`, change `mintBatch` to `safeMintBatch`.

**📝 Details**
See https://eips.ethereum.org/EIPS/eip-5679

**Comment by Amxx** [comment]
Hello @xinbenlv 

As mentionned in the PR comment, this ERC is still a very early draft. OZ Contracts don't include ERC implementation unless they are final, or they are already widely used (ERC712 was included before it was final). Considering the ERC is less than a week old, I strongly believe effort should focus on getting community feedback and adoption, not on getting it into this repo.

**Comment by xinbenlv** [comment]
Hey Hadrian, thanks for a quick respond. Bit this feature request issue discussion is meant for getting community feedback. Please note all features proposed in EIP-5679 are already supported by OZ except for minor difference in the function name.

**Comment by Amxx** [comment]
I personnally don't see OZ as a community of people discussing contract standards. Possibly on the forum, but definitely not here. 

Just this week, there are something like 7 new ERC, not including your, listed on https://weekinethereumnews.com/. Please understand that we need to put filters, and we need these filters to be simple and as unopinionated as possible.

A a general rule, we are not willing to merge, and commit to provide support, for community contracts that are not strongly backed by either a finalised ERC, or wide adoption. It might be easy for you to write it, it might look like nothing, but understand that if we merge it, we would have to provider support for it for a long time ... and that is not something we take lightly

Also, we think "being part of the OZ library" would give weight/credibility to a draft ERC, and influence the ERC process. This is something we don't want.

That doesn't mean we will never merge this ERC, but there is a workflow for that, and we believe its not yet time for ERC5679.

**Comment by xinbenlv** [comment]
@Amxx got it. Makes sense. Thank you for explaning the workflow. I will persue it to be finalised and adopted before come back to advocate OZ adoption.

**Comment by rube-de** [comment]
@xinbenlv it's final since some time. don't want to push it again? ;)
