### ISSUE TITLE
Add explicit admin address to TimelockControl constructor

### ISSUE THREAD

**Issue by DanielVF** [OpenZeppelin/openzeppelin-contracts#3720]
I've found a dozen or active projects on mainnet using multi-sigs or voting that missed the note about revoking the admin permissions from the deployer of TimelockController. 

The timelock is often deployed unmodified, and often a developer's only interaction with the timelock is a line or two in a deploy file. This means that the only thing they see is the constructor and its method names. Seeing these names, it's logical to conclude that the timelock only has two permissions - and to not know that super admin permissions are granted in the constructor to the deployer key.

I think a way of clearing up this confusion is to have the super admin powers, outside the timelock controlling itself, be explicitly granted as a list in the constructor, just like the other permissions.

(Tweets: https://twitter.com/danielvf/status/1572963306725318657)

**Comment by frangio** [comment]
We agree and will be changing this in the upcoming 4.8 release.

**Comment by 0xJacobs** [comment]
Please what the difference between setting Oz ownable (msg.sender)  to the constructor of a contract and just importing it and the only owner modifier from the Oz to a child contract.

**Comment by 0xJacobs** [comment]
So that means there should be no need to set msg.sender in the constructor of the child contract? It automatically does that?
