### ISSUE TITLE
Unable to compile hardhat in nixOS after tag v4.7.3 

### ISSUE THREAD

**Issue by chrispalaskas** [OpenZeppelin/openzeppelin-contracts#3723]
Stopped working between September 12 2022 05:20 UTC and September 13, 2022 23:31UTC (nightly build)

**💻 Environment**
nixOS

**📝 Details**
Error log:

> openzeppelin-solidity@4.7.0 clean
--
  | > hardhat clean && rimraf build contracts/build
  |  
  |  
  | > openzeppelin-solidity@4.7.0 compile
  | > hardhat compile
  |  
  | An unexpected error occurred:
  |  
  | Error: spawn /var/lib/buildkite-agent-mamba/.cache/hardhat-nodejs/compilers/linux-amd64/solc-linux-amd64-v0.8.9+commit.e5eed63a ENOENT
  | at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
  | at onErrorNT (node:internal/child_process:478:16)
  | at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  | errno: -2,
  | code: 'ENOENT',
  | syscall: 'spawn /var/lib/buildkite-agent-mamba/.cache/hardhat-nodejs/compilers/linux-amd64/solc-linux-amd64-v0.8.9+commit.e5eed63a',
  | path: '/var/lib/buildkite-agent-mamba/.cache/hardhat-nodejs/compilers/linux-amd64/solc-linux-amd64-v0.8.9+commit.e5eed63a',
  | spawnargs: [ '--standard-json' ],
  | cmd: '/var/lib/buildkite-agent-mamba/.cache/hardhat-nodejs/compilers/linux-amd64/solc-linux-amd64-v0.8.9+commit.e5eed63a --standard-json'
  | }
  | npm ERR! code 1
  | npm ERR! path /var/lib/buildkite-agent-mamba/builds/e2e-mamba-3/input-output-hk/mamba-automation/third_party_tests/ERC/openzeppelin-contracts
  | npm ERR! command failed
  | npm ERR! command sh -c scripts/prepare.sh
  |  
  | npm ERR! A complete log of this run can be found in:
  | npm ERR!     /var/lib/buildkite-agent-mamba/.npm/_logs/2022-09-21T23_39_39_946Z-debug-0.log
  |  
  | added 22 packages, and audited 1656 packages in 3s

**🔢 Code to reproduce bug**

git clone --depth 1 https://github.com/OpenZeppelin/openzeppelin-contracts.git
cd openzeppelin-contracts
[[ -f /etc/NIXOS ]] || nvm use v14.17.0
npm install @nomiclabs/hardhat-solhint
npm install
npm install mocha mochawesome

npx hardhat --network xxx etc

**Comment by frangio** [comment]
This seems like a Hardhat problem. Please report it to Hardhat.
