### ISSUE TITLE
EIP-4907 support

### ISSUE THREAD

**Issue by TrejGun** [OpenZeppelin/openzeppelin-contracts#3735]
**🧐 Motivation**

There is a number of games with gene sequences mechanism like CryptoKitties, DeRace, and Axie. Imagine I have a Kitty with rare genes and I want to breed it with others for profit. There is no easy way of doing so because all games have different interfaces and thus It is difficult for exchanges to implement lend/borrow mechanics. ERC4907 will standardize the way how it is done without implementing a flash-borrower and magic tricks

**📝 Details**

Here is ready to use implementation
https://thirdweb.com/doubledev.eth/ERC4907

**Comment by frangio** [comment]
I've left [a comment](https://ethereum-magicians.org/t/eip4907-erc-721-user-and-expires-extension/8572/26?u=frangio) at Ethereum Magicians.

At this point I don't think we should include this feature in OpenZeppelin Contracts due to unaddressed concerns and competing standards without a clear community favorite.

**Comment by TrejGun** [comment]
@frangio you are right about that comment. it totally makes sense. Unfortunately, this is what we have now. no better standard for temporary ownership was introduced. 

Let's talk about how this can be done securely and in the proper way.
here is a Kitties code for breeding
https://github.com/dapperlabs/cryptokitties-bounty/blob/master/contracts/KittyBreeding.sol#L200
3rd party platforms can prepare for sign such a set of transactions

- transfer token#1 to from walletA to walletB
- call breed function(token#1, token#?)
- transfer token#1 to from walletB to walletA
- transfer erc20fee to from walletB to walletA

In fact this is what wyvern protocol does
Instead, I offer to add AccessControl to the token class and assign a new role to exchange (but not owner). Now exchange can assign USER role to anyone to breed as much as he can during subscription time. 

Now as I write this it seems like a bad standard for this purpose to me. It does not restrict usage amount and does not take into account breading limit and cooldown. As well as there is no way to add new exchanges or the owner can discard all usages. I have to think about this more.

Anyways this standard can be added now and replaced later with a better one.

**Comment by frangio** [comment]
> Anyways this standard can be added now and replaced later with a better one.

Unfortunately it's not so simple. Adding code to the library has real maintenance costs and security risks associated.

**Comment by 0xanders** [comment]
> I've left [a comment](https://ethereum-magicians.org/t/eip4907-erc-721-user-and-expires-extension/8572/26?u=frangio) at Ethereum Magicians.
> 
> At this point I don't think we should include this feature in OpenZeppelin Contracts due to unaddressed concerns and competing standards without a clear community favorite.

I've left a reply at Ethereum Magicians:  https://ethereum-magicians.org/t/eip4907-erc-721-user-and-expires-extension/8572/29

**Comment by frangio** [comment]
@0xanders This looks a workaround for the EIP's issues with respect to user protection, but the issue itself remains in the EIP... I don't think it's a good candidate for inclusion here.

**Comment by 0xanders** [comment]
> @0xanders This looks like a workaround for the EIP's issues with respect to user protection, but the issue itself remains in the EIP... I don't think it's a good candidate for inclusion here.

For ENS, there is a Controller role(who can change the data of ENS but can not transfer the NFT), and the owner of the ENS NFT can change the Controller at any time. 

For Decentraland LAND and ESTATE NFT, there is an Operator role(who can update material to Decentraland but can not transfer the NFT ), the  owner of the LAND or ESTATE NFT can change the Operator at any time.

**Comment by frangio** [comment]
Those are interesting data points, though I would argue that the Controller and the Operator are not "users" of the NFT, in fact they are more like "service providers" for the NFT owner.
