### ISSUE TITLE
move _beforeConsecutiveTokenTransfer and _afterConsecutiveTokenTransfer to ERC721Consecutive.sol

### ISSUE THREAD

**Issue by TrejGun** [OpenZeppelin/openzeppelin-contracts#3739]
ERC721Consecutive introduces backward incompatibility between 4.7 and 4.8

My contracts are not compiling after the upgrade because I have to override _beforeConsecutiveTokenTransfer _afterConsecutiveTokenTransfer that I'm never ever going to use. These methods belong to extension and are used only by extension so why were they added to the core contract?

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L495-L519

**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by Amxx** [comment]
Hello @TrejGun 

These hooks are in the core ERC721 contract because we need them to operate on the balances, which are private and can only be modified with the core ERC721 contract itself.

Having this new hooks should be backward compatible. Since any code written for 4.7 does not include them, they should not be defined or overridden anywhere. Consequently, just adding them to the core should not require any manual override.

Could you please provide an example of code that compile when matched to 4.7 but that triggers errors when matched with 4.8 ?

**Comment by frangio** [comment]
Are you using ERC721Enumerable or ERC721Pausable?

**Comment by frangio** [comment]
There is no way to make ERC721Pausable compatible with ERC721Consecutive without introducing some form of breaking change around overrides.

**Comment by TrejGun** [comment]
> Are you using ERC721Enumerable or ERC721Pausable? Please do share your code.

yes I do

```pragma solidity ^0.8.9;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Burnable.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract ERC721ABE is AccessControl, ERC721Burnable, ERC721Enumerable {
  using Counters for Counters.Counter;

  bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");

  Counters.Counter internal _tokenIdTracker;

  constructor(
    string memory name,
    string memory symbol
  ) ERC721(name, symbol) {
    _setupRole(DEFAULT_ADMIN_ROLE, _msgSender());
    _setupRole(MINTER_ROLE, _msgSender());
  }

  function mint(address to) public virtual onlyRole(MINTER_ROLE) {
    // We cannot just use balanceOf to create the new tokenId because tokens
    // can be burned (destroyed), so we need a separate counter.
    _mint(to, _tokenIdTracker.current());
    _tokenIdTracker.increment();
  }

  function safeMint(address to) public virtual onlyRole(MINTER_ROLE) {
    // We cannot just use balanceOf to create the new tokenId because tokens
    // can be burned (destroyed), so we need a separate counter.
    _safeMint(to, _tokenIdTracker.current());
    _tokenIdTracker.increment();
  }

  function supportsInterface(bytes4 interfaceId)
    public
    view
    virtual
    override(AccessControl, ERC721, ERC721Enumerable)
    returns (bool)
  {
    return super.supportsInterface(interfaceId);
  }

  function _beforeTokenTransfer(
    address from,
    address to,
    uint256 tokenId
  ) internal virtual override(ERC721, ERC721Enumerable) {
    super._beforeTokenTransfer(from, to, tokenId);
  }

  function _beforeConsecutiveTokenTransfer(
    address from,
    address to,
    uint256, /*first*/
    uint96 size
  ) internal virtual override(ERC721, ERC721Enumerable){
    super._beforeTokenTransfer(from, to, size);
  }
}
```

**Comment by frangio** [comment]
@TrejGun Unfortunately if we want to release ERC721Consecutive we are forced to do some breaking change on ERC721. We are hoping for this breaking change to be as minor and easy to fix as possible.

Currently we're considering removing the `before/afterConsecutiveTransfer` hooks, but instead changing the existing `_beforeTokenTransfer` hook adding one more argument to the function. This means that any overrides will need to be modified to add that new argument.

```diff
 function _beforeTokenTransfer(
     address from,
     address to,
     uint256 tokenId,
+    uint256 batchSize
 ) internal virtual override
```

What are your thoughts on this small breaking change? Is it acceptable in your opinion?

**Comment by TrejGun** [comment]
looks much better, thanks

is this planned for 4.8 or 5.0?

**Comment by frangio** [comment]
We are planning this for 4.8 regardless of the breaking change because we want to deliver the ERC721Consecutive functionality and it is not possible to do it without a breaking change.
