### ISSUE TITLE
Shouldn't permit() use SignatureChecker? Or ECDSA is fine?

### ISSUE THREAD

**Issue by k06a** [OpenZeppelin/openzeppelin-contracts#3749]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7201e6707f6631d9499a569f492870ebdd4133cf/contracts/token/ERC20/extensions/draft-ERC20Permit.sol#L64

**Comment by frangio** [comment]
See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2845#issuecomment-911968702. Closing as duplicate.

EIP-2612 is actually in Last Call for a few more days. It has been really difficult to even get it onto Last Call without changes so I'm not at all hopeful we would be able to change it to support EIP-1271 signatures. See https://github.com/ethereum/EIPs/issues/2613#issuecomment-1207237629 for a proposal to create a new EIP that extends permit with EIP-1271 signatures among other things.
