### ISSUE TITLE
Name change for `__gaps`

### ISSUE THREAD

**Issue by zemse** [OpenZeppelin/openzeppelin-contracts#3754]
**🧐 Motivation**

Presently there are gaps declared privately with the identifier `__gap`:

```ts
uint256[50] private __gap;
```

The storage layout output from the Solidity compiler also includes the name of the identifier. I have a simple [tool](https://github.com/zemse/hardhat-storage-layout-changes) that basically allows seeing if the storage layout broke. It basically compares if storage entries with the same identifiers are at the same `slot` and `offset` and it warns/errors if change is spotted. 

Currently, when a contract inherits a lot of openzeppelin upgradable contracts, there's a bunch of `__gaps` and it's tricky to compare if they were changed. Currently, as a fallback if duplicate identifiers were found, the tool checks if `astId` was changed but `astIds` change easily if there is a considerable solidity code change prior to the variable declaration and then it gets difficult to confirm if the `__gaps` are at the same location.

**📝 Details**

I think an easy solution to this problem could be to have unique names for gaps, e.g. including the contract name in it: `__gap_ERC20Upgradeable`.

Or any suggestions for improving the comparison of storage layout when multiple inherited contracts have private variables with name collision?

**Comment by frangio** [comment]
In our own Upgrades Plugin We have implemented an approach to storage layout comparison that works even for gaps that have the same name, so I don't find this a compelling reason to change the name.

You should be able to easily reuse our own logic through the `@openzeppelin/upgrades-core` package. This is independent of the plugin, it just consumes Hardhat build info files. See [`getStorageUpgradeReport`](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-core#getstorageupgradereport). Would this work for you?

Including the contract name in the gap could be reasonable but I don't think we should prioritize it, given that we're planning to move away from gaps and instead use the "diamond storage" pattern (#2964).

**Comment by zemse** [comment]
Thanks for pointing this out. Closing the issue.
