### ISSUE TITLE
Add string operation for int256 in Strings.sol

### ISSUE THREAD

**Issue by Suvadra-Barua** [OpenZeppelin/openzeppelin-contracts#3758]
**🧐 Motivation**
There is no implementation of the conversion of int256 to String

**📝 Details**
Using [Strings.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Strings.sol) , We can convert uint256 to String,HexString and address to HexString. But int256 to string is required in many cases.

**Comment by ernestognw** [comment]
Partially solved in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3773, although there's no `toHexString` implementation

**Comment by Amxx** [comment]
What would the Hex representation of a negative integer be? If you want the 2-complement representation, just hard-cast the int256 to a uint256 and then do `toHexString(uint256)`

**Comment by ernestognw** [comment]
> What would the Hex representation of a negative integer be?

I'd say there would be multiple Hex representations available, bur that should be an standard so hold on for now.

**Comment by Amxx** [comment]
I'd say there should not be multiple representations available in our libraries. Any user is free to chose one they like, and implement it on top of what we already have.

**Comment by ernestognw** [comment]
I completely agree with not supporting them all, but I don't know about any way of generalizing it. 

> just hard-cast the int256 to a uint256 and then do toHexString(uint256)

This is the most general version I'd think about. Can be converted to 2's complement.

**Comment by Amxx** [comment]
I don't have any sources, because I have never seen anyone do `int→string` in solidity. Rather then go look for it, the potential users should come to us with realistic usecases. 

When users ask for features, we ask them what their motivation/usecase is, and evaluate if that is relevant to the community in general.

**Comment by DigitalSubham** [comment]
I am working on this issue, please assign this to me
