### ISSUE TITLE
CountersUpgradeable.sol is not included in download

### ISSUE THREAD

**Issue by dcsan** [OpenZeppelin/openzeppelin-contracts#3766]
I buit a contract with the wizard
https://docs.openzeppelin.com/contracts/4.x/wizard

checking `Enumerable` and the `UUPS upgradeable`
this generates download .sol files which have a link to 

`import "./@openzeppelin/contracts-upgradeable/utils/CountersUpgradeable.sol";`

but this import is not part of the downloaded bundle

<img width="278" alt="image" src="https://user-images.githubusercontent.com/514002/196412492-9705cd72-cc57-478d-8db9-3f836ebd163a.png">

**💻 Environment**

using openzep with hardhat 

**📝 Details**

```
contracts/
├── @openzeppelin
│   └── contracts-upgradeable
│       ├── README.md
│       ├── access
│       │   ├── AccessControlUpgradeable.sol
│       │   └── IAccessControlUpgradeable.sol
│       ├── interfaces
│       │   └── draft-IERC1822Upgradeable.sol
│       ├── proxy
│       │   ├── ERC1967
│       │   │   └── ERC1967UpgradeUpgradeable.sol
│       │   ├── beacon
│       │   │   └── IBeaconUpgradeable.sol
│       │   └── utils
│       │       ├── Initializable.sol
│       │       └── UUPSUpgradeable.sol
│       ├── security
│       │   └── PausableUpgradeable.sol
│       ├── token
│       │   └── ERC721
│       │       ├── ERC721Upgradeable.sol
│       │       ├── IERC721ReceiverUpgradeable.sol
│       │       ├── IERC721Upgradeable.sol
│       │       └── extensions
│       │           ├── ERC721BurnableUpgradeable.sol
│       │           ├── ERC721EnumerableUpgradeable.sol
│       │           ├── IERC721EnumerableUpgradeable.sol
│       │           └── IERC721MetadataUpgradeable.sol
│       └── utils
│           ├── AddressUpgradeable.sol
│           ├── ContextUpgradeable.sol
│           ├── StorageSlotUpgradeable.sol
│           ├── StringsUpgradeable.sol
│           └── introspection
│               ├── ERC165Upgradeable.sol
│               └── IERC165Upgradeable.sol
└── MyNFT.sol
```

I notice there is `token/ERC721/extensions/ERC721EnumerableUpgradeable.sol`

perhaps this is a bug, including the wrong item?

**🔢 Code to reproduce bug**

**Comment by dcsan** [comment]
specifically bringing in `auto increment IDs` will require the missing file.

![image](https://user-images.githubusercontent.com/514002/196415512-9bf0d490-e531-40fa-a6c5-dce84b1bbf1c.png)

**Comment by dcsan** [comment]
basic utils/Counters exists when NOT using a proxy/upgradeable.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Counters.sol

and this is the source contract:
https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.7.3/contracts/utils/CountersUpgradeable.sol

For now I can just copy that into the build in the right place and hope it's actually the right thing...

**Comment by Amxx** [comment]
Hello @dcsan 

**I am unable to reproduce the issue.**

When I go to the wizard, and check both "mintable with auto increment Ids" and "upgrdeability uups", I get the following code:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "[@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.7.3/contracts/token/ERC721/ERC721Upgradeable.sol)";
import "[@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.7.3/contracts/access/OwnableUpgradeable.sol)";
import "[@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.7.3/contracts/proxy/utils/Initializable.sol)";
import "[@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.7.3/contracts/proxy/utils/UUPSUpgradeable.sol)";
import "[@openzeppelin/contracts-upgradeable/utils/CountersUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.7.3/contracts/utils/CountersUpgradeable.sol)";

contract MyToken is Initializable, ERC721Upgradeable, OwnableUpgradeable, UUPSUpgradeable {
    using CountersUpgradeable for CountersUpgradeable.Counter;

    CountersUpgradeable.Counter private _tokenIdCounter;

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    function initialize() initializer public {
        __ERC721_init("MyToken", "MTK");
        __Ownable_init();
        __UUPSUpgradeable_init();
    }

    function safeMint(address to) public onlyOwner {
        uint256 tokenId = _tokenIdCounter.current();
        _tokenIdCounter.increment();
        _safeMint(to, tokenId);
    }

    function _authorizeUpgrade(address newImplementation)
        internal
        onlyOwner
        override
    {}
}
```

**When exporting that to remix, the contract compiles correctly**

Please note that the import is 
```
import "@openzeppelin/contracts-upgradeable/utils/CountersUpgradeable.sol";
```
and not
```
import "./@openzeppelin/contracts-upgradeable/utils/CountersUpgradeable.sol";
```

[This file is available in the upgradeable package](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.7.3/contracts/utils/CountersUpgradeable.sol)

**Comment by dcsan** [comment]
I'm using the download files option as a vendored zip, which is using all relative paths such as:

import "./@openzeppelin/contracts-upgradeable/utils/CountersUpgradeable.sol";

![image](https://user-images.githubusercontent.com/514002/196425090-a5584f4f-253b-44e4-a6a8-9bac90905be4.png)

so I guess in this bundle not all the required files are included?

**Comment by Amxx** [comment]
Ok, that is definitelly a bug on the wizard then.

Thanks for finding that out! I'll open an issue in the correct repo pointing to here.
