### ISSUE TITLE
Verify UpgradeableBeacon.sol

### ISSUE THREAD

**Issue by karacurt** [OpenZeppelin/openzeppelin-contracts#3776]
I was not able to verify a UpgradeableBeacon.sol after deploy it on polygon-mumbai using upgrades.deployBeacon. After a lot of attempts, i tried to create a contract that extends a UpgradeableBeacon.sol. After that i was able to verifiy, but that doesn’t work for me, i need to use upgrades.deployBeacon() in order to also deploy the implementation contract for me. Any ideas of what could it be?

Obs: I've also tried to create a flatten file of UpgradeableBeacon.sol to verify as a single file on polygonscan, but it didn’t work.

**Comment by karacurt** [comment]
Thank you for answering @Amxx ! Unfortunately, i've not found any specifically posts in the forum regarding UpgradableBeacon.sol, i found only about BeaconProxy.sol verification. 

Also, i've tried to use the same settings as instructed and i was not able to verify. I have no ideas how to reach the deployed byte codes that plugin uses.

**Comment by Amxx** [comment]
Can you please open an issue on the upgrades plugin repository with:
- the version of the plug-in that you use
- the address of the contract you are trying to verify

**Comment by karacurt** [comment]
Ok, thank you @Amxx  i'm going there!
