### ISSUE TITLE
`block.timestamp` compatible Checkpoints

### ISSUE THREAD

**Issue by jaketimothy** [OpenZeppelin/openzeppelin-contracts#3784]
**🧐 Motivation**

Current implementation of Checkpoints is built for `block.number` based checkpointing.  Would love to generalize the utility to support `block.timestamp`.

Would not be surprised if this has been discussed internally wrt timestamp based Governor and Votes features.  I see this as laying some groundwork to enable those features.

**📝 Details**

I see the following limitations to address

- `uint32` creates unix epoch overflow in year 2106.  While not _urgent_, `uint64` would future-proof this.  `uint64` is also compatible with Timers, increasing composability.
- `getAtBlock`, `getAtProbablyRecentBlock`, and `push` use `block.number` internally.

Would this help `next-v5.0`?

With #2962 coming, is this going too far?
```solidity
    struct Checkpoint {
        Timer _timer;
        uint192 _value;
    }
```

**Comment by jaketimothy** [comment]
> Before we can have block.timestamp based governor we need to figure out the way Governor and Tokens are going to work together on using the same reference. My personal opinion is that the governor should not ever lookup the time, and should ask the token for that information. That way the governor would be oblivious, and the clock would be set by the token.

Agreed.  Since the token must be time aware, this design isolates timekeeping.

> This is what I started to formalize in https://github.com/ethereum/EIPs/pull/5805.

Thank you for writing this EIP!

> The uint32 limitation doesn't feel like its an actual issue...

Fair!  There was no such thing as unix epoch 80 years ago...  Our grandchildren can sort it out.

> for the getAtBlock, getAtProbablyRecentBlock, etc, functions. we should use the new Trace224 with a lookup to the public now() function defined by EIP-5805. Anyone will be able to "just" overidde the now() function to use timestamp, block numbers, or anything they want ... and it should be good.

I propose this become the scope of this feature request as a part of "update Votes to implement EIP-5805".

**Comment by jaketimothy** [comment]
What do you favor between passing in a reference to now() vs removing the now() check?  Something like

```solidity
function getAtTime(Trace224 storage self, IERC5805Now timekeeper, uint256 timepoint) internal view returns (uint256) {
    require(timepoint < timekeeper.now(), "Checkpoints: timepoint in past");
    uint32 key = SafeCast.toUint32(timepoint);
```

vs

```solidity
function getAtTime(Trace224 storage self, uint256 timepoint) internal view returns (uint256) {
    uint32 key = SafeCast.toUint32(timepoint);
```

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3934.
