### ISSUE TITLE
Base64.sol #warning

### ISSUE THREAD

**Issue by ssuriyayuvan** [OpenZeppelin/openzeppelin-contracts#3830]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/99589794db43c8b285f5b3464d2e0864caab8199/contracts/utils/Address.sol#L200

Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
   --> @openzeppelin/contracts/utils/Address.sol:200:30:
    |
200 |     ) internal view returns (bytes memory) {
    |                              ^^^^^^^^^^^^

Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
   --> @openzeppelin/contracts/utils/Address.sol:223:30:
    |
223 |     ) internal pure returns (bytes memory) {
    |                              ^^^^^^^^^^^^

**Comment by jitendra-webkul** [comment]
I had the same problem with AddressUpgradeable.sol
