### ISSUE TITLE
Consider defaulting the type of an asset to be address in ERC4626

### ISSUE THREAD

**Issue by s1monAF** [OpenZeppelin/openzeppelin-contracts#3837]
In [ERC4626](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/8f8fd84f1e60426a5e785d6b5b2524938271bb05/contracts/token/ERC20/extensions/ERC4626.sol#L33), the default type of `_asset` is `IERC20`. Although this can reduce casting, this is also limiting what can be done with `_asset`. In an application we are building, the `_asset` is actually `ERC1155` based structured financial products. With `_asset` being an ERC20 token, we are facing some difficulty adopting this standard. It would be great if it can be simplified to be of just an address type and let the implementation decide what to do with the address variable. A possible fix is given below. Luckily, `_asset` is not used in many occurrences.

**Comment by s1monAF** [comment]
```
abstract contract ERC4626 is ERC20, IERC4626 {
    using Math for uint256;

    address private immutable _asset;
    uint8 private immutable _decimals;

    /**
     * @dev Set the underlying asset contract. This must be an ERC20-compatible contract (ERC20 or ERC777).
     */
    constructor(address asset_) {
        (bool success, uint8 assetDecimals) = _tryGetAssetDecimals(asset_);
        _decimals = success ? assetDecimals : super.decimals();
        _asset = asset_;
    }

    /**
     * @dev Attempts to fetch the asset decimals. A return value of false indicates that the attempt failed in some way.
     */
    function _tryGetAssetDecimals(address asset_) private returns (bool, uint8) {
        (bool success, bytes memory encodedDecimals) = asset_.call(
            abi.encodeWithSelector(IERC20Metadata.decimals.selector)
        );
        if (success && encodedDecimals.length >= 32) {
            uint256 returnedDecimals = abi.decode(encodedDecimals, (uint256));
            if (returnedDecimals <= type(uint8).max) {
                return (true, uint8(returnedDecimals));
            }
        }
        return (false, 0);
    }
```

**Comment by TChairman** [comment]
Doesn't this break deposit/withdraw as well? And totalAssets? Feels like it might be easier to add ERC20 compatibility to your asset, but I could be wrong.

**Comment by frangio** [comment]
It's one thing to use `address` instead of `IERC20` in the argument type, but it's a very different thing to add support for ERC1155 tokens.

EIP-4626 clearly states that the asset must be an ERC20 token ([source](https://eips.ethereum.org/EIPS/eip-4626#asset)), so it is not possible to support ERC1155.
