### ISSUE TITLE
Upgrade `TimelockController` to use `AccessControlEnumerable` 

### ISSUE THREAD

**Issue by DeFiFoFum** [OpenZeppelin/openzeppelin-contracts#3842]
**🧐 Motivation**

The current implementation of the [TimelockController](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/24d1bb668a1152528a6e6d71c2e285d227ed19d9/contracts/governance/TimelockController.sol#L6) uses `AccessControl` to manage roles. 

As Timelock contracts are extremely role sensitive, this makes reviewing and verifying the roles of a particular Timelock difficult by needing to go back through the events and verify the role setup.

**📝 Details**

- [ ] Upgrade the `AccessControl` import with [AccessControlEnumerable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControlEnumerable.sol) to make these Timelock contracts more user friendly.

**Comment by frangio** [comment]
> reviewing and verifying the roles of a particular Timelock difficult

We have a prototype of an application to inspect roles at [Access Control Explorer](https://accesscontrol-explorer.netlify.app/). Feel free to use it.

---

We are unlikely to use AccessControlEnumerable in TimelockController by default. But in case you're not aware you can make this change yourself fairly easily:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;

import "@openzeppelin/contracts/governance/TimelockController.sol";
import "@openzeppelin/contracts/access/AccessControlEnumerable.sol";

contract TimelockControllerEnumerable is TimelockController, AccessControlEnumerable {
    constructor(uint256 minDelay, address[] memory proposers, address[] memory executors, address admin)
        TimelockController(minDelay, proposers, executors, admin)
    {}

    function supportsInterface(bytes4 interfaceId) public view virtual override(TimelockController, AccessControlEnumerable) returns (bool) {
        return super.supportsInterface(interfaceId);
    }

    function _revokeRole(bytes32 role, address account) internal virtual override(AccessControl, AccessControlEnumerable) {
        return super._revokeRole(role, account);
    }

    function _grantRole(bytes32 role, address account) internal virtual override(AccessControl, AccessControlEnumerable) {
        return super._grantRole(role, account);
    }
}
```

**Comment by DeFiFoFum** [comment]
> Access Control Explorer

Incredible, thanks @frangio. 

Between the **Access Control Explorer** and being able to extend the `TimelockController` this will certainly work for our needs.

**Comment by DeFiFoFum** [comment]
For reference, this is the code that I adapted from above which complies. 

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;

import "@openzeppelin/contracts/governance/TimelockController.sol";
import "@openzeppelin/contracts/access/AccessControlEnumerable.sol";

contract TimelockControllerEnumerable is TimelockController, AccessControlEnumerable {
    constructor(uint256 minDelay, address[] memory proposers, address[] memory executors, address admin)
        TimelockController(minDelay, proposers, executors)
    {
        // Setup admin role and revoke deployer admin role
        _setupRole(TIMELOCK_ADMIN_ROLE, admin);
        _revokeRole(TIMELOCK_ADMIN_ROLE, _msgSender());
    }

    function supportsInterface(bytes4 interfaceId) public view virtual override(AccessControl, AccessControlEnumerable) returns (bool) {
        return super.supportsInterface(interfaceId);
    }

    function _revokeRole(bytes32 role, address account) internal virtual override(AccessControl, AccessControlEnumerable) {
        return super._revokeRole(role, account);
    }

    function _grantRole(bytes32 role, address account) internal virtual override(AccessControl, AccessControlEnumerable) {
        return super._grantRole(role, account);
    }
}
```
