### ISSUE TITLE
TransparentUpgradeableProxy not transparent

### ISSUE THREAD

**Issue by gerben-stavenga** [OpenZeppelin/openzeppelin-contracts#3871]
TUP is designed to be transparent ie. that the logic contract ABI is the only and exact ABI you see when interacting with the contract other than the proxy admin. This is unfortunately not true.

**💻 Environment**

Any environment

**📝 Details**

The functions used by the proxy admin, namely

```
function changeAdmin(address newAdmin) external virtual ifAdmin {
    _changeAdmin(newAdmin);
}

/**
 * @dev Upgrade the implementation of the proxy.
 *
 * NOTE: Only the admin can call this function. See {ProxyAdmin-upgrade}.
 */
function upgradeTo(address newImplementation) external ifAdmin {
    _upgradeToAndCall(newImplementation, bytes(""), false);
}
```

are not marked payable and thus a logic contract with these functions but payable will fail. Now these functions itself on the logic contract are not likely to be payable, but due to only 4 billion signature hashes it's not inconceivable a hash collision could happen with another signature. Or someone malicious could design a signature that hashes to one of these and make a apparently correct contract that would opaquely break when used as a logic contract with TUP.

**🔢 Code to reproduce bug**

Trivial, solution trivial by making them payable and just require msg.value ==0 manually

**Comment by frangio** [comment]
Great point. Agree we should make the suggested change.
