### ISSUE TITLE
Missing GovernorBravo compatibility

### ISSUE THREAD

**Issue by RitzyDevBox** [OpenZeppelin/openzeppelin-contracts#3877]
The GovernorCompatibilityBravo.sol contract seems to be missing alot of the the public interface members for bravo

such as:

    /// @notice The latest proposal for each proposer
    mapping (address => uint) public latestProposalIds;

**Comment by frangio** [comment]
Thanks for pointing that out. We may have some public getters.

Are you using `GovernorCompatibilityBravo`? Would appreciate if you could chime in on https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3833.

**Comment by frangio** [comment]
If I understand your comment correctly, you used Uniswap's interface connected to an instance of `GovernorCompatibilityBravo`, and it didn't work correctly. You've already said a few things but I'd appreciate if you can provide as much detail as possible.

So for example `latestProposalIds` is missing. What other properties did you need to add? And what enumerator?

Is the UI broken because proposal ids are not sequential?

This is very valuable so we can evaluate getting to 100% compatibility (sorry this wasn't caught earlier).

**Comment by Amxx** [comment]
Our governor inherits part of its interface (in particular the events and the voting ABI) from Compound's governor. Still, both have significant differences. The most significant is in the storage and representation of proposals:

- Governor Bravo stores everything onchain, and numbers the proposal that are submitted sequentially. This is really expensive!
- OZ's Governor does NOT store the proposal details by default. We publish them through event, which is enough for offchain indexing. A consequence of this design is that proposal need to be identified differently. Therefore, our proposal numbering system is not sequential but relies on the hash of the proposal.

The `GovernorCompatibilityBravo` module is here to provide some backward compatibility by storing the proposal details onchain, which can then be queried using the `proposals(uint256)` getter. This helps with some usecases, but the proposal numbering system remains hash-based.

Sequentiality of proposal in Compound's system allows for simpler (event-less) indexing of the proposal. You just query how much proposal there are, and you can then lookup the proposals, from 0 to N-1. I expect this is what uniswap's interface does. 

Changing the governor to use sequential numbering, and thus achieve 100% compatibility, feels like a very difficult thing to do in a extension module. building an extension means that we continue supporting the "core" interface, which itself requires the hash-based proposal numbering.

We may have to reconsider the amount of compatibility we want to achieve. Event, and voting interface, compatibility is really a blessing, but we also inherited some poor design choice, made by compound years ago in a very different context. We hope that this debt, combined with the compatibility layer, would make everyone's work (expect ours) significantly easier... but if it turn out that this is not the case, maybe we should dial back and remove some (costly) extensions that don't achieve the expected goal.

Note: Similarly, compound includes rules about the each proposer's `latestProposalIds` and enforces a maximum of one live proposal per proposer (which we don't do, even in the compatibility module). Is this something we should have ?

**Comment by FriskyHamTitz** [comment]
Hmm, I would just suggest hybrid compatibility.
Adding enumeration capabilities in the following manner.

1. Add proposalCount to the bravo compatibility contract

2. Add a public mapping of (uint256 => uint256) indexToHashMap

3. On propose add the index and hash to the map.

This way the bravo compatibility has no dependency on the graph.

(If you really wanted to take go wild with it you can override all the
methods to internally use that but that would be a little much )

**Comment by Amxx** [comment]
That would not be compatible though, because the `proposalId` given by the events is the hash one.

So when you have a proposalId, depending on if it is an index, of an actual hash based proposal id, you would have to workflows. 

Also, if you get a count, take the last index, and start listening for the corresponding events you would get nothing.

**Comment by Amxx** [comment]
> My sugguestion for full compatibility is that, You override all the functions, e.g propose, execute, queue, to look up the HashId from the CountId passed in, and pass that to the base.

The events are emitted by the core, using proposalId that are hashed by the core. I'm not sure how we would make sure the core doesn't use the proposalId it produces and use sequential ids instead.

It feels like the difference is so big that we would need a different codebase altogether

```mermaid
classDiagram
    class IGovernor{
        +function something() external virtual
    }
    class AbstractGovernor {
        +function something() public virtual override
    }
    class GovernorCore {
        +function something() public virtual override ...
    }
    class GovernorCompatibilityCore {
        +function something() public virtual override ...
    }


    IGovernor --|> AbstractGovernor
    AbstractGovernor --|> GovernorCore
    AbstractGovernor --|> GovernorCompatibilityCore
    AbstractGovernor --|> GovernorModuleXxx

    GovernorCore --> GovernorModuleXxx : possible composition
    GovernorCompatibilityCore --> GovernorModuleXxx : possible composition
```

I'm not sure would be a lot of development and maintenance, and also a lot of confuction for the users. Considering the compatibility mode is way more expensive to use (because of all the sload/sstore) I'm not sure we want to encourage that ... and then have users complain its expensive

**Comment by Amxx** [comment]
> I just finished writing a Multiple choice voting Governor, not sure what the process is but I would love to become a contributor here.

The process is documented here [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CONTRIBUTING.md)

**Comment by ernestognw** [comment]
Hey @RitzyDevBox, we've been reviewing this, and here are the missing functions:

```solidity
function DOMAIN_TYPEHASH() external view returns (bytes32);
function MAX_PROPOSAL_THRESHOLD() external view returns (uint256);
function MAX_VOTING_DELAY() external view returns (uint256);
function MAX_VOTING_PERIOD() external view returns (uint256);
function MIN_PROPOSAL_THRESHOLD() external view returns (uint256);
function MIN_VOTING_DELAY() external view returns (uint256);
function MIN_VOTING_PERIOD() external view returns (uint256);
function _acceptAdmin() external;
function _setPendingAdmin(address newPendingAdmin) external;
function admin() external view returns (address);
function pendingAdmin() external view returns (address);
function _initiate(address governorAlpha) external; 
function _setProposalThreshold(uint256 newProposalThreshold) external;
function _setVotingDelay(uint256 newVotingDelay) external;
function _setVotingPeriod(uint256 newVotingPeriod) external;
function _setWhitelistAccountExpiration(address account, uint256 expiration) external;
function _setWhitelistGuardian(address account) external;
function isWhitelisted(address account) external view returns (bool);
function whitelistAccountExpirations(address) external view returns (uint256);
function whitelistGuardian() external view returns (address);
function comp() external view returns (address);
function initialProposalId() external view returns (uint256);
function latestProposalIds(address) external view returns (uint256);
function proposalCount() external view returns (uint256);
function proposalMaxOperations() external view returns (uint256);

// EIP-1967 and upgrades
function implementation() external view returns (address);
function initialize(
    address timelock_,
    address comp_,
    uint256 votingPeriod_,
    uint256 votingDelay_,
    uint256 proposalThreshold_
) external;
```

So far, we think not all of these functions need to be there, and most of them would be filled with placeholder values, take as a reference `comp` or `whitelistGuardian`, in which the former should return the address of an underlying token (which may not be ERC20, though), and there's no `whitelist` mechanism.

Aside from that, some of them can be implemented easily but are not critical (such as `DOMAIN_TYPEHASH`). 

Regarding your use case, even if we add the missing `proposalCount`, it won't work for enumerability.
We'll document the limitations of the compatibility, including inner differences (like how `proposalId` works) though we'd like to hear your thoughts if you have reasons to support the addition of any of these functions.
