### ISSUE TITLE
Stop using hardcoded resolution of functions

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3883]
In a few places we hardcode the resolution of functions, skipping over any potential overrides. This is done to preserve the internal consistency of the code. In the example below, we need owner to be the actual owner that the contract stores in the ownership mapping in storage.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/3d7a93876a2e5e1d7fe29b5a0e96e222afdc4cfa/contracts/token/ERC721/ERC721.sol#L113

The result is confusing though, so I think we should look for some alternative. Our policy anyway is that if a developer overrides a function with custom logic it is their responsibility to make sure that other things don't break.

**Comment by fulldecent** [comment]
Sounds good.

Here is all of them to review:

- [ ] `SafeERC20.safeTransfer(token, account, payment);`
- [ ] `SafeERC20.safeTransfer(IERC20(token), beneficiary(), amount);`
- [ ] `return ERC1155URIStorage.uri(tokenId);`
- [ ] `return ERC2771Context._msgSender();`
- [ ] `return ERC2771Context._msgData();`
- [ ] `SafeERC20.safePermit(IERC20Permit(address(_token)), owner, spender, value, deadline, v, r, s);`
- [ ] `ERC1967Upgrade._upgradeToAndCall(newImplementation, bytes(""), false);`
- [ ] `ERC1967Upgrade._upgradeToAndCall(newImplementation, data, false);`
- [ ] `return ERC1967Upgrade._getImplementation();`
- [ ] `return ERC1155Supply.totalSupply(id) > 0;`
- [ ] `require(ERC20.totalSupply() + amount <= cap(), "ERC20Capped: cap exceeded");`
- [ ] `return token == address(this) ? type(uint256).max - ERC20.totalSupply() : 0;`
- [ ] `SafeERC20.safeTransferFrom(underlying, _msgSender(), address(this), amount);`
- [ ] `SafeERC20.safeTransfer(underlying, account, amount);`
- [ ] `SafeERC20.safeTransferFrom(_asset, caller, address(this), assets);`
- [ ] `SafeERC20.safeTransfer(_asset, receiver, assets);`
- [ ] `address owner = ERC721.ownerOf(tokenId);`
- [ ] `address owner = ERC721.ownerOf(tokenId);`
- [ ] `address owner = ERC721.ownerOf(tokenId);`
- [ ] `owner = ERC721.ownerOf(tokenId);`
- [ ] `require(ERC721.ownerOf(tokenId) == from, "ERC721: transfer from incorrect owner");`
- [ ] `require(ERC721.ownerOf(tokenId) == from, "ERC721: transfer from incorrect owner");`
- [ ] `emit Approval(ERC721.ownerOf(tokenId), to, tokenId);`
- [ ] `return retval == IERC721Receiver.onERC721Received.selector;`
- [ ] `require(index < ERC721.balanceOf(owner), "ERC721Enumerable: owner index out of bounds");`
- [ ] `require(index < ERC721Enumerable.totalSupply(), "ERC721Enumerable: global index out of bounds");`
- [ ] `uint256 length = ERC721.balanceOf(to);`
- [ ] `uint256 lastTokenIndex = ERC721.balanceOf(from) - 1;`
- [ ] `bytes memory encodedParams = abi.encodeWithSelector(IERC165.supportsInterface.selector, interfaceId);`

---

Here's the tooling to generate that list:

```sh
egrep -h 'contract [A-Z_][a-zA-Z0-9_]+ (is.* )?{' -- **/*sol | sed -e 's/.*contract //;s/ .*/./' | sort -u > naughty
grep -h -F -f naughty **/*.sol | grep -v '.sol'
# Then delete some of these by hand that are false matches
```

**Comment by frangio** [comment]
Thanks @fulldecent! Note that `SafeERC20` shouldn't be in that list as it is a library.

**Comment by Amxx** [comment]
Also, `ERC1967Upgrade` is used as a library (even though its not), so it should not be on that list (and should possibly be turned into a library).

**Comment by frangio** [comment]
>and should possibly be turned into a library

Let's open an issue to discuss this for 5.0!
