### ISSUE TITLE
Role Suspension for a specific time in AccessControl

### ISSUE THREAD

**Issue by njrapidinnovation** [OpenZeppelin/openzeppelin-contracts#3895]
🧐 Motivation
As a role admin i want to suspend users to perform their role activities instead of revoking their roles for a specific time.

📝 Details

- A method which a `ROLE ADMIN` can call with `UNDERLYING ROLE` , `MALICIOUS USER ADDRESS` and a `TIMESTAMP` to set a time upto which that particular account is suspended to perform its activities.
- A method which return a boolean to check whether the account is suspended or not (call this in hasRole function also).
- A method to return the time remaining for ending of a suspension.

**Comment by njrapidinnovation** [comment]
Any feedback admins?

**Comment by frangio** [comment]
In what situations would you use suspend as opposed to revoke?

**Comment by njrapidinnovation** [comment]
In a system where we have roles in bulk and we found any inappropriate action performed by the user then we can suspend his activities as a method of warning .

**Comment by frangio** [comment]
This doesn't sound like something that would be widely used, so we are not likely to implement it.

You should be able to implement it easily by extending `AccessControl` with inheritance. If you find that it isn't possible let us know.
