### ISSUE TITLE
Error: not found utils/introspection/ERC165.sol

### ISSUE THREAD

**Issue by ykute07** [OpenZeppelin/openzeppelin-contracts#3896]
while I compiling below code in RemixI got error of the Error: not found utils/introspection/ERC165.sol
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol
How can I solve it?

**Comment by JulissaDantes** [comment]
You should not try to compile our contracts in remix but rather use the library. Our contracts depend on the repo structure, in your case the existence of `utils/introspection/ERC165.sol` inside the contained folders in your project. If you are going to copy and paste the contract then you must copy and paste the dependencies of said contracts, meaning, include in remix all the contracts your contract is using.

But the intended use of the library, to be able to use it on remix and other environments, is to first install the library as it says on our [README](https://github.com/OpenZeppelin/openzeppelin-contracts#usage), and then use the contracts the following way:
```
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";

contract MyCollectible is ERC721 {
    constructor() ERC721("MyCollectible", "MCO") {
    }
}
```
You seem to want to create a ERC721 with the code snippet above you can achieve that. But notice that the import includes `@openzeppelin/...` this means its using this contract from that library.

**Comment by frangio** [comment]
Please post support questions to the [OpenZeppelin Forum](https://forum.openzeppelin.com/)-.
