### ISSUE TITLE
Incompatibility between ERC20Permit and Votes

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3905]
Reported initially in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3872.

`ERC20Permit` and `Votes` both implement separate `DOMAIN_SEPARATOR` functions that are not virtual, so they can't be combined.

In the 4.x releases this issue shouldn't show up because users would combine `ERC20Permit` with `ERC20Votes` (and not `Votes`), which do not present an incompatibility.

However, in the current 5.0 code, following https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3816, `ERC20Votes` is built on `Votes` and this will be an issue.

https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3872 proposed making `DOMAIN_SEPARATOR` virtual, but this is not a good use of virtual functions because they would not be chained using `super`. I believe we should look for another solution.

**Comment by Amxx** [comment]
Fixed in #4297
