### ISSUE TITLE
Improve extensibility for contracts such as the accessControl.sol

### ISSUE THREAD

**Issue by RitzyDevBox** [OpenZeppelin/openzeppelin-contracts#3906]
I'm mostly wondering why we market a lot of variables as private in the Smart Contracts, instead of making them more extensible.

Let's take AccessControl  for example
```
abstract contract AccessControl is Context, IAccessControl, ERC165 {
    struct RoleData {
        mapping(address => bool) members;
        bytes32 adminRole;
    }

    mapping(bytes32 => RoleData) private _roles;
    //...
}
```

I'd like to build on top of this contract, and provide the ability to create dynamic role. 
however roles is private, there is no way for me to read the current roles or add to them.

I can very easily clone the code, but audits are extremely expensive, it would be a lot nicer if Openzepplin has more extensible contracts, so audits for the masses would be easier and cheaper.

**Comment by frangio** [comment]
> there is no way for me to read the current roles or add to them.

This is not correct, you can and should use [internal functions](https://docs.openzeppelin.com/contracts/4.x/api/access#AccessControl) like `_checkRole`, `_grantRole`, `_revokeRole`, as well as  `hasRole`. 

The variables are private so that you use the this interface to modify them and the appropriate events are correctly emitted.

**Comment by FriskyHamTitz** [comment]
Yeah, but the issue is there is no way to create role.

**Comment by Amxx** [comment]
> Yeah, but the issue is there is no way to create role.

There is no such thing as creating a role. All roles exist by default, and are administered by the `DEFAULT_ADMIN_ROLE` (`bytes32(0)`).

You can grant any role at any time internally (using `_grantRole` and `_revokeRole`). You can also change the role admin using `_setRoleAdmin`.

**Comment by FriskyHamTitz** [comment]
> > Yeah, but the issue is there is no way to create role.
> 
> There is no such thing as creating a role. All roles exist by default, and are administered by the `DEFAULT_ADMIN_ROLE` (`bytes32(0)`).
> 
> You can grant any role at any time internally (using `_grantRole` and `_revokeRole`). You can also change the role admin using `_setRoleAdmin`.

Yeah, i said I'm building on top of that contract, and I wanted it to be written in a more extensible way in the future.

So that inheritance works better
