### ISSUE TITLE
request adding ERC721Loyalty extension

### ISSUE THREAD

**Issue by codeislight1** [OpenZeppelin/openzeppelin-contracts#3907]
**🧐 Motivation**
it's hard to overall quantify the loyalty of an NFT holder in terms of time held and number of NFTs. that's where ERC721Loyalty makes it easy to integrate an easy to use Loyalty accounting system which can help in identifying the most loyal holders and unlocking new possibilities.
**📝 Details**
ERC721Loyalty implementation which is an abstract contract that overrides _beforeTokenTransfer and adjust the loyalty struct  for the 'from' and 'to' addresses according to the transaction taking place: mint, burn or transfer. at anytime a user can call loyaltyOf(address) and get the seconds the tokens has been held by any user which can be used for governance voting and many other use cases which can unlock more use cases and unlock more scarcity to NFTs overall. 

I have already made a foundry project of the implementation, let me know if i should make a PR into ERC721/extensions
https://github.com/codeislight1/ERC721-Holding-Accrual

--Code--

**Comment by frangio** [comment]
Can you share references to projects that have implemented something like this?

**Comment by codeislight1** [comment]
there is no project that have implemented on production, but i would love
to share it, if it's worth the integration.

**Comment by frangio** [comment]
I don't mean this specific implementation, I mean projects that have used "time held" as part of some on-chain mechanism. This would help to validate the feature as something that it makes sense for us to offer. If this is not already a popular feature, we would not add it to the library.

**Comment by codeislight1** [comment]
Ok, thanks for the clarification.
