### ISSUE TITLE
Remove deprecated features

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3918]
There are various deprecated functions that need to be removed in the next major version. These are annotated in the docs such as:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c1d9da4052a75232dca1fafac80c4a2cb82fe518/contracts/access/AccessControl.sol#L203

We should search and remove all of these.

A list, not necessarily exhaustive:

- [ ] Deprecated contracts
  - [ ] GovernorProposalThreshold
  - [ ] ERC777
- [ ] Deprecated `draft-*.sol` files:
  - [ ] draft-IERC2612.sol
  - [ ] draft-ERC20Permit.sol
  - [ ] draft-IERC20Permit.sol
  - [ ] draft-ERC721Votes.sol
  - [ ] draft-EIP712.sol
- [ ] Deprecated functions
  - [ ] `SafeMath.sol`: function that need use memory for the error reason
  - [ ] `EnumerableMap.sol`: function that need use memory for the error reason
  - [ ] `AccessControl.sol`: `_setupRole`
  - [ ] `BeaconProxy.sol`: `_setBeacon`
- [ ] Deprecated state variables
  - [ ] `GovernorCompatibilityBravo.ProposalDetails.proposer` (not deprecated but not needed since we have `Governor.ProposalCore.proposer`)
  - [ ] `GovernorVotesQuorumFraction._quorumNumerator`

**Comment by akshaysrivastav** [comment]
While those functions are marked as `deprecated`, they are still used in other OZ contracts.
Like here: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/presets/ERC20PresetMinterPauser.sol#L39-L42

Wouldn't it be sensible to remove the usage of deprecated functions in a minor release first?

**Comment by Amxx** [comment]
> Wouldn't it be sensible to remove the usage of deprecated functions in a minor release first?

We want to guarantee a smooth upgrade between minor releases. This means we don't want to do any breaking changes (such as removing a function) in a minor.

That is what majors are for: making breaking change and removing things we want to stop supporting.

**Comment by ernestognw** [comment]
Closed by #4258

**Comment by ernestognw** [comment]
Closed by #4258
