### ISSUE TITLE
Use ERC721Holder & ERC1155Holder for Governor, Timelock

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3936]
As discussed before in https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3174, the Governor and TimelockController contracts are able to receive ERC721 and ERC1155 tokens, so they should implement the respective Receiver interfaces. This was fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3230, but due to storage layout compatibility (https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3174#issuecomment-1033731672) we didn't use `ERC721Holder` and `ERC1155Holder`. We should do that now.

**Comment by kimanikelly** [comment]
@frangio Is this issue still relevant to be picked up? If so, I'd be glad to start working on it
