### ISSUE TITLE
Is _beforeTokenTransfer of ERC721.sol in the right place?

### ISSUE THREAD

**Issue by 0xInuarashi** [OpenZeppelin/openzeppelin-contracts#3942]
Hello, I just looked today at ERC721.sol and found this function which I expected to be empty.

```
function _beforeTokenTransfer(
        address from,
        address to,
        uint256 /* firstTokenId */,
        uint256 batchSize
    ) internal virtual {
        if (batchSize > 1) {
            if (from != address(0)) {
                _balances[from] -= batchSize;
            }
            if (to != address(0)) {
                _balances[to] += batchSize;
            }
        }
    }
```

This was strange to me as ERC721.sol did not include any "batch logic" at all.

Alas, I saw that 2 months ago there was a new extension to ERC721.sol called ERC721Consecutive.sol which has also an _afterTokenTransfer 

```
    function _afterTokenTransfer(
        address from,
        address to,
        uint256 firstTokenId,
        uint256 batchSize
    ) internal virtual override {
        if (
            to == address(0) && // if we burn
            firstTokenId < _totalConsecutiveSupply() && // and the tokenId was minted in a batch
            !_sequentialBurn.get(firstTokenId) // and the token was never marked as burnt
        ) {
            require(batchSize == 1, "ERC721Consecutive: batch burn not supported");
            _sequentialBurn.set(firstTokenId);
        }
        super._afterTokenTransfer(from, to, firstTokenId, batchSize);
    }

    function _totalConsecutiveSupply() private view returns (uint96) {
        (bool exists, uint96 latestId, ) = _sequentialOwnership.latestCheckpoint();
        return exists ? latestId + 1 : 0;
    }
```

I feel like the _beforeTokenTransfer was put out of place, should be put in ERC721Consecutive.sol instead of the standard ERC721.sol 

Is this the case? Please check it out. To me, it makes no sense to include such logic in the original ERC721.sol.

**Comment by Amxx** [comment]
Hello @0xInuarashi 

As you found out, this is part of addition of ERC721Consecutive.

When someone uses the `_mintConsecutive` function from the `ERC721Consecutive` module, we must track the balance increase for the receiving wallet. The thing is the `_balances` mapping is in `ERC721` and private, so we cannot touch it directly from `ERC721Consecutive`.

Our solution was to use this hook so that the core `ERC721` code can update the balances when `_mintConsecutive` "notifies" it.

We are trying to rework that part of the code for the upcomming 5.0 version

**Comment by 0xInuarashi** [comment]
Hey @Amxx thanks for the clarification. 

Is there any reason why the _balances mapping in `ERC721` is private instead of internal? 

Just wondering.

Thanks!

**Comment by 0xInuarashi** [comment]
Also, in ERC721Consecutive.sol, you have a function

```
    function _mint(address to, uint256 tokenId) internal virtual override {
        require(Address.isContract(address(this)), "ERC721Consecutive: can't mint during construction");
        super._mint(to, tokenId);
    }
```

Is `tokenId` supposed to be `amount` ? 

As I believe batch minting does not work with non-sequential tokenIds, unless ERC721Consecutive invented a way to make both sequential (batch) minting and non-sequential (specific tokenId) minting work together.

**Comment by Amxx** [comment]
> Is there any reason why the _balances mapping in `ERC721` is private instead of internal?

That is part of our [guidelines](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/GUIDELINES.md#solidity-code).

**Comment by Amxx** [comment]
> Is `tokenId` supposed to be `amount` ?
> 
> As I believe batch minting does not work with non-sequential tokenIds, unless ERC721Consecutive invented a way to make both sequential (batch) minting and non-sequential (specific tokenId) minting work together.

In our implementation, you can use both batch minting and "normal" minting. 

- Batch minting is only allowed during the construction (so we remain compatible with EIP-721). That is done using the `_mintConsecutive` function
- "Normal" minting becomes available after construction (at this point we know batch minting can no longer hapen) using the `_mint` function. 

The code you shared above is the override that disables normal minting during construction if the Consecutive mode is enabled.

**Comment by frangio** [comment]
Thanks for the question @0xInuarashi. Let us know if you have any other suggestions.
