### ISSUE TITLE
ERC721._mint should allow controlling the event Transfer parameters

### ISSUE THREAD

**Issue by TimDaub** [OpenZeppelin/openzeppelin-contracts#3944]
- The contract I'm working on currently: https://github.com/attestate/ERC4973/blob/master/src/ERC4973.sol
- For EIP-4973, we've been partially using OZ's EIP implementations and now that we want to create compatibility with EIP-5192, our EIP-4973 implementation has to become compatible with EIP721
- For that reason, I was planning to remove our custom implementation of accounting in EIP-4973
- However, EIP-4973 mandates that a mint transaction is between the issuer and the receiver (as represented by the Transfer event) opposed to EIP-721's non-canonical mint transaction that is always between the zero address and the `address to`.
- So since we've been implementing our own accounting and our own mint function, we were so far able to issue a Transfer event between the issuer and the receiver when calling our mint function: https://github.com/attestate/ERC4973/blob/30d542bc5d81a51834746b961dfc7ed3e75e1ef2/src/ERC4973.sol#L170
- However, I'd now like to make ERC721URIStorage the parent class of my ERC4973 contract which would mean using OZ's mint function. But it hard codes the address zero: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/d59306bd06a241083841c2e4a39db08e1f3722cc/contracts/token/ERC721/ERC721.sol#L283
- I cannot overwrite the mint function either as access to balances is set to private: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/d59306bd06a241083841c2e4a39db08e1f3722cc/contracts/token/ERC721/ERC721.sol#L33

**Comment by TimDaub** [comment]
Discussed with @frangio the EIP-721 compliant thing to do is mint to address zero first and then transfer.

**Comment by frangio** [comment]
For reference, sharing the relevant part of the EIP-721 spec, where the `Transfer` event is specified:

> This emits when ownership of any NFT changes by any mechanism. This event emits when NFTs are created (`from` == 0) and destroyed (`to` == 0).
