### ISSUE TITLE
Avoid zero to non-zero SSTOREs in Pausable

### ISSUE THREAD

**Issue by MollyHe5** [OpenZeppelin/openzeppelin-contracts#3995]
**🧐 Motivation**

Bools use 8 bit but they only need 1 bit. And it takes 20,000 gas to set a slot from zero to non-zero with SSTORE. So changing a bool field which occupies a whole slot to uint can save a lot of gas.

**📝 Details**

In contracts/security/Pausable.sol:
```
bool private _paused;
```
can be changed to:
```
    uint256 private constant _PAUSED_FALSE = 1;
    uint256 private constant _PAUSED_TRUE = 2;
    uint256 private _paused;
```

**Comment by Amxx** [comment]
Hello @MollyHe5 

Unlike the `ReentrancyGuard` status, which we expect the value to change very often, we don't expect the pause flag to be updated frequently. But you are right, we should possibly change Pausable to use this pattern.

**Comment by frangio** [comment]
Given the number of times the variable is read versus the number of times the variable is written, I think we should keep it as a boolean. It is just significantly simpler and less error prone.

**Comment by Rassska** [comment]
I also agree that we should keep it as it is. Ofc, using uint8 occurs some overhead for casting on stack, but  it's not huge. 
@MollyHe5 , also keep in mind that changing the state var from non-zero to zero provides some gas refund!

**Comment by frangio** [comment]
Closing for the reasons stated above.
