### ISSUE TITLE
Potential gas savings in the Reentrancy contract

### ISSUE THREAD

**Issue by dimka3553** [OpenZeppelin/openzeppelin-contracts#4016]
**🧐 Motivation**
In the Reentrancy guard contract, the state variables:
    uint256 private constant _NOT_ENTERED = 1;
    uint256 private constant _ENTERED = 2;
    uint256 private _status;

are stored as uint256 which is not the most efficient way to store them.

**📝 Details**
It might make sense to store them as uint8 as by doing that the contract will use 2 less 32 byte slots resulting in the saving of gas on their storage.

**Comment by Amxx** [comment]
Hello @dimka3553 

In the `ReentrancyReentrancyGuard` contract there is only a single storage variable. That is `uint256 _status`. This variable uses one (full) slot. both `_ENTERED` and `_NOT_ENTERED` are constant values that are not actually in storage.

Changing that from `uint256` to `uint8` would not make the contract cheaper by itself.
