### ISSUE TITLE
Remove Checkpoint.History

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#4019]

**Comment by RenanSouza2** [comment]
Hey, I made this PR for this issue **https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4170**

**Comment by RenanSouza2** [comment]
I would like to also edit the files that use Checkpoint in order to eliminate the legacy operations but tought in letting you see these changes first

**Comment by RenanSouza2** [comment]
Made this branch in case you wanna merge it 
https://github.com/RenanSouza2/openzeppelin-contracts/tree/next-v5.0-Checkpoint-history-v2

**Comment by RenanSouza2** [comment]
This issue can also be closed since https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3918 was merged
