### ISSUE TITLE
5.0 cleanup

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#4020]
- [ ] `GovernorCompatibilityBravo:ProposalDetails` doesn't need to store the proposer
- [ ] `GovernorVotesQuorumFraction` doesn't need to have a fallback `_quorumNumerator`
- [ ] Remove deprecated contracts
  - [ ] GovernorProposalThreshold
  - [ ] ERC777
- [ ] Remove deprecated `draft-*.sol` files:
  - [ ] draft-IERC2612.sol
  - [ ] draft-ERC20Permit.sol
  - [ ] draft-IERC20Permit.sol
  - [ ] draft-ERC721Votes.sol
  - [ ] draft-EIP712.sol
- [ ] Remove deprecated functions
  - [ ] `SafeMath.sol`: function that need use memory for the error reason
  - [ ] `EnumerableMap.sol`: function that need use memory for the error reason
  - [ ] `AccessControl.sol`: `_setupRole`
  - [ ] `BeaconProxy.sol`: `_setBeacon`

**Comment by frangio** [comment]
Let's try to organize issues around more specific topics.

We already have #3918 for removing deprecated functions. We can rename it to "remove deprecated features" and add this list there.

For the Governor, it might be OK to have a general "governor technical debt" issue.

**Comment by ernestognw** [comment]
Have we yet defined `MinimalForwarder` will be deprecated? Or just the `ForwardRequest` without a deadline.

I think it's worth mentioning

**Comment by frangio** [comment]
`MinimalForwarder` is not yet deprecated. I've removed it from this issue.
