### ISSUE TITLE
Error: Cannot find module '@openzeppelin/contracts'

### ISSUE THREAD

**Issue by itsabinashb** [OpenZeppelin/openzeppelin-contracts#4025]
i installed ```@openzeppelin/contracts``` by ```yarn add --dev```, i set it in ```hardhat.config.js```, i imported it in my solidity file, but when i running ```hh compile``` im getting ```Error: Cannot find module '@openzeppelin/contracts'``` - this error.
help.

**Comment by frangio** [comment]
Please post your question in the [OpenZeppelin Forum](https://forum.openzeppelin.com/).
