### ISSUE TITLE
Visibility of Clones' `predictDeterministicAddress(address, bytes32)` is `view`

### ISSUE THREAD

**Issue by satykumar** [OpenZeppelin/openzeppelin-contracts#4027]
In the second predictDeterministicAddress function, you can remove the unnecessary view keyword, as this function is already marked as internal. you can use pure

**Comment by ernestognw** [comment]
Can yo provide a compiling example?
From what I see, the `predictDeterministicAddress(address, bytres32, address)` function is already `pure`, while its `predictDeterministicAddress(address, bytes32)` is `view` because it accesses the state with `address(this)`

**Comment by Amxx** [comment]
> In the second predictDeterministicAddress function, you can remove the unnecessary view keyword, as this function is already marked as internal. you can use pure

`predictDeterministicAddress(address, bytes32)` includes a call to `address(this)` so it can't be pure, and needs to be view.
