### ISSUE TITLE
IERC20Permit still shows up as draft-IERC20Permit

### ISSUE THREAD

**Issue by alphak3y** [OpenZeppelin/openzeppelin-contracts#4032]
![image](https://user-images.githubusercontent.com/84204260/217300563-71526602-4028-4777-9802-dc9a9037b90d.png)
![image](https://user-images.githubusercontent.com/84204260/217300623-13521cd7-281d-4d57-9457-002a1fcd5c17.png)

This is even for version 4.8.1 which I have tried pulling from both `yarn` and `npm`. Thanks!

**Comment by Amxx** [comment]
Hello @alphak3y 

We keep these for backward compatibility, so if some used to import the "draft-xxx.sol" version, the import will still work.

We will remove these in the next breaking release (5.0)
