### ISSUE TITLE
Use `>=32` instead of `==32` in `SignatureChecker` for return data length check

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/openzeppelin-contracts#4035]
In the `ERC4626` function [`_tryGetAssetDecimals`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC4626.sol) you use the following pattern with respect to the return data length check:

```solidity
if (success && encodedDecimals.length >= 32) {
    uint256 returnedDecimals = abi.decode(encodedDecimals, (uint256));
    if (returnedDecimals <= type(uint8).max) {
        return (true, uint8(returnedDecimals));
    }
}
```

In the function [`isValidSignatureNow`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/SignatureChecker.sol#L34) you use `result.length == 32` instead for the return data length check. I think it would make sense due to consistency to also use `result.length >= 32` in that case. FYI, I already discussed this issue with @frangio over Discord.

**Comment by HarshitSharma007** [comment]
@pcaversaccio  can you please assign this issue to me.

**Comment by HarshitSharma007** [comment]
@pcaversaccio  can you please assign this issue to me.

**Comment by pcaversaccio** [comment]
I'm not part of the OZ team :-D. Cc: @Amxx

**Comment by frangio** [comment]
@HarshitSharma007 Feel free to submit a PR.

**Comment by Amxx** [comment]
I agree we should have consistency, but I wonder why it should be on >=32 and not on ==32

**Comment by frangio** [comment]
My reasoning for >= 32 is that `abi.decode` will accept data that is larger than needed, and we shouldn't make it more restrictive than the "native" Solidity decoding.

**Comment by Gua00va** [comment]
Hey, is this issue still open. I would like to work on it. Can you assign it to me?

**Comment by Eren-Yeaager** [comment]
Can you please assign this issue to me??

**Comment by pcaversaccio** [comment]
@Eren-Yeaager the issue is already resolved (pending merge) via PR: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4038.

**Comment by Eren-Yeaager** [comment]
ok

**Comment by yvonnezhangc** [comment]
@frangio @pcaversaccio could either of you help provide more context on this change? 

ERC1271 specifies that the return value must be the bytes4 magic value `0x1626ba7e`. Why is it a good idea to use `>=` rather than `==` here?

**Comment by pcaversaccio** [comment]
> @frangio @pcaversaccio could either of you help provide more context on this change?
> 
> ERC1271 specifies that the return value must be the bytes4 magic value `0x1626ba7e`. Why is it a good idea to use `>=` rather than `==` here?

See @frangio's argument [here](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4035#issuecomment-1424711785).
