### ISSUE TITLE
npm is out of sync with master

### ISSUE THREAD

**Issue by frontier159** [OpenZeppelin/openzeppelin-contracts#4044]
Contracts which are packaged and uploaded to npm are out of sync with the `master` branch.

**💻 Environment**

v4.8.1, via npm

**📝 Details**

[ERC20Permit.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Permit.sol) was moved from draft ~3 months ago in master.

From this, v4.8.1 was tagged on Jan 14th 2023

v4.8.1 was also pushed into npm -- however does not contain the `ERC20Permit.sol` contract. It's still only available in draft.
See the code for that package [here](https://www.npmjs.com/package/@openzeppelin/contracts?activeTab=explore)

Can the package please be sync'd and uploaded correctly? I'm unsure what else may be out of date in the npm package

**🔢 Code to reproduce bug**

**Comment by Amxx** [comment]
4.8.1 is the latest release.

Any change to the master branch done since then are going to be included in 4.9, which should ship soon.
