### ISSUE TITLE
Possible race condition in `GovernorPreventLateQuorum` tests

### ISSUE THREAD

**Issue by r0qs** [OpenZeppelin/openzeppelin-contracts#4049]
Hi, we recently noticed some random failures in our external tests of the `openzeppelin-contracts`. You can see two sample logs from our CI here:
- https://app.circleci.com/pipelines/github/ethereum/solidity/28478/workflows/995c85c7-e633-421c-b319-156918c77d5b/jobs/1264364
- https://app.circleci.com/pipelines/github/ethereum/solidity/28507/workflows/cef6dc8d-1e7a-48db-be1e-82cb157e399d/jobs/1265534

Debugging it locally and isolating one of the failed tests (the first one). The test finishes successfully, so I suspect that there may be some race conditions in the tests.

**💻 Environment**

```
Solc compiler version: 0.8.18+commit.87f61d96.Linux.g++
Openzeppelin-solidity version: 4.8.0
```

Our tests run with a combination of settings of the solidity compiler, but all those pass when running individual openzeppelin tests (i.e. using `it.only`), but some of them randomly fail when running the full openzeppelin test suit.

For reference, you can see the full log of that test case (i.e. `Delay is extended to prevent last minute take-over`) that fails when running all tests in the CI but passes if ran alone:
```
Configuring Hardhat...
-------------------------------------
Config file: hardhat.config.js
Settings preset: ir-optimize-evm+yul
Settings: {evmVersion: 'paris', viaIR: true,  optimizer: {enabled: true, details: {yul: true}}}
EVM version: paris
Compiler version: 0.8.18
Compiler version (full): 0.8.18+commit.87f61d96.Linux.g++
-------------------------------------
Running compile function...

> openzeppelin-solidity@4.8.0 compile
> hardhat compile

Solidity 0.8.18 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/hardhat-runner/docs/reference/solidity-support

Compiled 249 Solidity files successfully

real	5m40.086s
user	5m38.894s
sys	0m1.291s
Verify that the correct version (0.8.18/0.8.18+commit.87f61d96.Linux.g++) of the compiler was used to compile the contracts...
Running test function...

> openzeppelin-solidity@4.8.0 test
> hardhat test


  Contract: GovernorPreventLateQuorum
    using $ERC20Votes
      ✓ Delay is extended to prevent last minute take-over
    using $ERC20VotesTimestampMock
      ✓ Delay is extended to prevent last minute take-over


  2 passing (5s)

Configuring Hardhat...
-------------------------------------
Config file: hardhat.config.js
Settings preset: legacy-no-optimize
Settings: {evmVersion: 'paris', viaIR: false, optimizer: {enabled: false}}
EVM version: paris
Compiler version: 0.8.18
Compiler version (full): 0.8.18+commit.87f61d96.Linux.g++
-------------------------------------
Running compile function...

> openzeppelin-solidity@4.8.0 compile
> hardhat compile

Solidity 0.8.18 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/hardhat-runner/docs/reference/solidity-support

Compiled 249 Solidity files successfully

real	0m23.623s
user	0m23.293s
sys	0m1.715s
Verify that the correct version (0.8.18/0.8.18+commit.87f61d96.Linux.g++) of the compiler was used to compile the contracts...
Running test function...

> openzeppelin-solidity@4.8.0 test
> hardhat test


  Contract: GovernorPreventLateQuorum
    using $ERC20Votes
      ✓ Delay is extended to prevent last minute take-over
    using $ERC20VotesTimestampMock
      ✓ Delay is extended to prevent last minute take-over


  2 passing (8s)

Configuring Hardhat...
-------------------------------------
Config file: hardhat.config.js
Settings preset: legacy-optimize-evm-only
Settings: {evmVersion: 'paris', viaIR: false, optimizer: {enabled: true, details: {yul: false}}}
EVM version: paris
Compiler version: 0.8.18
Compiler version (full): 0.8.18+commit.87f61d96.Linux.g++
-------------------------------------
Running compile function...

> openzeppelin-solidity@4.8.0 compile
> hardhat compile

Solidity 0.8.18 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/hardhat-runner/docs/reference/solidity-support

Compiled 249 Solidity files successfully

real	0m49.706s
user	0m49.420s
sys	0m1.597s
Verify that the correct version (0.8.18/0.8.18+commit.87f61d96.Linux.g++) of the compiler was used to compile the contracts...
Running test function...

> openzeppelin-solidity@4.8.0 test
> hardhat test


  Contract: GovernorPreventLateQuorum
    using $ERC20Votes
      ✓ Delay is extended to prevent last minute take-over
    using $ERC20VotesTimestampMock
      ✓ Delay is extended to prevent last minute take-over


  2 passing (6s)

Configuring Hardhat...
-------------------------------------
Config file: hardhat.config.js
Settings preset: legacy-optimize-evm+yul
Settings: {evmVersion: 'paris', viaIR: false, optimizer: {enabled: true, details: {yul: true}}}
EVM version: paris
Compiler version: 0.8.18
Compiler version (full): 0.8.18+commit.87f61d96.Linux.g++
-------------------------------------
Running compile function...

> openzeppelin-solidity@4.8.0 compile
> hardhat compile

Solidity 0.8.18 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/hardhat-runner/docs/reference/solidity-support

Compiled 249 Solidity files successfully

real	1m8.565s
user	1m8.364s
sys	0m1.354s
Verify that the correct version (0.8.18/0.8.18+commit.87f61d96.Linux.g++) of the compiler was used to compile the contracts...
Running test function...

> openzeppelin-solidity@4.8.0 test
> hardhat test


  Contract: GovernorPreventLateQuorum
    using $ERC20Votes
      ✓ Delay is extended to prevent last minute take-over
    using $ERC20VotesTimestampMock
      ✓ Delay is extended to prevent last minute take-over


  2 passing (6s)

Done.
```

**📝 Details**

I suspect that the bug was introduced by the new [test/helpers/time.js](https://github.com/OpenZeppelin/openzeppelin-contracts/commit/790cc5b65a66e0515bcbf97c430975bb7fbef8f7#diff-1c6db426fbabb76102d6fb9f1571b086362d35584b559407d63c8409ce31340bR1) added by this PR https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3934.

You can see that the `extendedDeadline` was changed here to use `clockFromReceipt`: https://github.com/OpenZeppelin/openzeppelin-contracts/commit/790cc5b65a66e0515bcbf97c430975bb7fbef8f7#diff-9b993baaba0944c3ab49a694eb5e65a5b2067339f3b62fbfcfdd0be2aaf859c9L110 for one of the test cases that is failing.

It now does:
```js
// compute new extended schedule
const extendedDeadline = web3.utils.toBN(await clockFromReceipt[mode](txVote.receipt)).add(lateQuorumVoteExtension);
```

But before that PR it was:

```js
const extendedDeadline = new BN(txVote.receipt.blockNumber).add(lateQuorumVoteExtension);
```

As `clockFromReceipt` is a global object in which `mode` can be set to `blocknumber` or `timestamp` property, and the `blocknumber` is a future that returns the `blocknumber`, I wonder if it may be the case of a race condition accessing `blocknumber` in multiple tests when using `waitForDeadline` (which in turn calls `time.advanceBlockTo`) and `clockFromReceipt`.

**Comment by Amxx** [comment]
> As `clockFromReceipt` is a global object in which `mode` can be set to `blocknumber` or `timestamp` property, and the `blocknumber` is a future: `blocknumber: receipt => Promise.resolve(receipt.blockNumber)` I wonder if it may be the case of a race condition accessing `blocknumber` in multiple tests when using `waitForDeadline` (which in turn calls `time.advanceBlockTo`) and `clockFromReceipt`.

Hello @r0qs 

We also noticed some issues running test since the transition to `test/helpers/time.js`

Note that in the case of the particular test you are pointing, `clockFromReceipt[mode](txVote.receipt)` is returning `(txVote.)receipt.blockNumber`. I'm not exactly sure what the race condition would be here.

**Comment by Amxx** [comment]
Related: #4046

**Comment by frangio** [comment]
Pretty sure it's not a race condition, just flakiness due to how the test chain's timestamps are manipulated in the test suite.

**Comment by frangio** [comment]
Fixed by https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4046.
