### ISSUE TITLE
check zero weight before execute _castVote

### ISSUE THREAD

**Issue by hyunkicho** [OpenZeppelin/openzeppelin-contracts#4071]
I was making dapp tutorial and I tried to make a dao contract using ERC721 vote and governor
And when I wrote a test code I found out that if address have NFT after snapshot duartion It can castVote with zero weight but nothing happend.

**💻 Environment**

this is the contract that I made (governor + erc721vote)
https://github.com/hyunkicho/blockchain101/tree/main/governance/tutorial_hardhat/contracts

**📝 Details**

the case I tested was

1. don't have NFT before snaphot (before propse)
2. have NFT after snapshot
3. Vote with NFT (success cast Vote)
4. but weitght was count as 0
5. so eventhough vote was succed it didn' effect the vote
6. People might confuse if castVote is suceess and didn't effect the result

**🔢 Code to reproduce bug**
to prevent this we need  in Governor Sol
```
        require(weight == 0, "Governor: weight is zero")

````

```
    function _castVote(
        uint256 proposalId,
        address account,
        uint8 support,
        string memory reason,
        bytes memory params
    ) internal virtual returns (uint256) {
        ProposalCore storage proposal = _proposals[proposalId];
        require(state(proposalId) == ProposalState.Active, "Governor: vote not currently active");

        uint256 weight = _getVotes(account, proposal.voteStart, params);
        require(weight == 0, "Governor: weight is zero")
        _countVote(proposalId, account, support, weight, params);

        if (params.length == 0) {
            emit VoteCast(account, proposalId, support, weight, reason);
        } else {
            emit VoteCastWithParams(account, proposalId, support, weight, reason, params);
        }

        return weight;
    }

```

**Comment by Amxx** [comment]
Hello @hyunkicho 

Similarly to doing token transfers with `amount = 0`, we believe that voting with weight 0 is a valid no-op.

We tend to accept no-ops and not revert to improve contract composition. Reverting could cause issues if this is a subcall. The voting weight is returned so a contract calling this can see the weight was 0 and revert.

**Comment by hyunkicho** [comment]
Oh I got it. Thanks for the reply :)
