### ISSUE TITLE
Improve `ERC4626` test coverage

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/openzeppelin-contracts#4075]
After my extensive `ERC4626` review, I would like to quickly discuss whether to add the following missing unit tests. As a reference, I refer to the existing tests at [`ERC4626.test.js`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/test/token/ERC20/extensions/ERC4626.test.js). The coverage issue is specifically related to the `private` function `_tryGetAssetDecimals`:

```solidity
/**
 * @dev Attempts to fetch the asset decimals. A return value of false indicates that the attempt failed in some way.
 */
function _tryGetAssetDecimals(IERC20 asset_) private view returns (bool, uint8) {
    (bool success, bytes memory encodedDecimals) = address(asset_).staticcall(
        abi.encodeWithSelector(IERC20Metadata.decimals.selector)
    );
    if (success && encodedDecimals.length >= 32) {
        uint256 returnedDecimals = abi.decode(encodedDecimals, (uint256));
        if (returnedDecimals <= type(uint8).max) {
            return (true, uint8(returnedDecimals));
        }
    }
    return (false, 0);
}
```

- Add a unit test that calls a simple EOA as `asset_` at construction time (checks for `encodedDecimals.length >= 32`).
- Add a unit test that calls a contract as `asset_` at construction time that returns a higher `decimals` than `type(uint8).max` (checks the condition `returnedDecimals <= type(uint8).max`). For that you can use a simple mock like that:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract ERC20DecimalsExcessMock {
    function decimals() public pure returns (uint256) {
        return type(uint256).max;
    }
}
```

- Add a unit test that checks the overflow of `_underlyingDecimals + _decimalsOffset()`. This might be a non-issue right now, but if you add such a check and do an `unchecked` refactor at some point it should immediately throw :)

Let me know what you think.

**Comment by pcaversaccio** [comment]
just following up on this issue - @Amxx and @frangio any thoughts?

**Comment by frangio** [comment]
Hey, sorry for the silence here. We're finishing up code for the 4.9 release and will be doing extensive testing over the next couple of weeks and I think this is a good idea! Are you interested in contributing the tests?

**Comment by pcaversaccio** [comment]
Sure, see my PR https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4134. I was not anymore sure about the Changelog since there is no "Unreleased" section, that's why I added one.
