### ISSUE TITLE
✨ Do you intend to implement ERC4337 Interface (IERC4337)?

### ISSUE THREAD

**Issue by wenceslas-sanchez** [OpenZeppelin/openzeppelin-contracts#4086]
**🧐 Motivation**

I was waiting the [ERC4337](https://eips.ethereum.org/EIPS/eip-4337) for a long time now, I think it's a major step for smart contract adoption. I was wondering if you intended to implent its interface, so we could just import it from your repo.

**📝 Details**

Could you implement an `interface IERC4337 {...}` that match ERC4337 requirements as you did for IERC20 and many others.
If you are not available, I could help !

Thanks a lot for your work team 🚀 !

**Comment by Amxx** [comment]
Hello @wenceslas-sanchez 

The ERC is still in draft, meaning that the interface can technically still change. I believe we will include the interface (IERC4337) in the `interfaces/` folder when the ERC is final. We currently don't plan on implementing the interface in an actual contract.

**Comment by wenceslas-sanchez** [comment]
Understood, I thought if was already live. Thanks !
