### ISSUE TITLE
`toStringWithFallback` misbehaves for an empty string

### ISSUE THREAD

**Issue by CodeSandwich** [OpenZeppelin/openzeppelin-contracts#4087]
I'm sorry for the informal format of this issue, but it's a really small one I've randomly found while reading code.

`toStringWithFallback` checks if the short string encoding failed by running `if (length(value) > 0) {`, but this doesn't take into account a genuinely empty string, which encodes in `toShortStringWithFallback` just fine, without a fallback: `if (bytes(value).length < 32) {` ` return toShortString(value);`. The result is that if a genuinely empty ShortString is used with a non-empty fallback storage string, the storage will be read. This wastes gas, but may also return an invalid value if storage isn't properly cleaned.

To solve this IMO we should encode differently a fallen-back ShortString in `toShortStringWithFallback`, e.g. by setting its length to 255.

**Comment by Amxx** [comment]
Hello @CodeSandwich 

I did considered the empty string case. Its true that is possibly wasting gas but that did not concerned me. The fact that the storage slot might not be empty is something I did not consider though. If `toShortStringWithFallback` was to write empty to storage that would be ok ... but its not the case.

**Comment by Amxx** [comment]
@CodeSandwich can you review #4088 ?

**Comment by Amxx** [comment]
@gitpoap-bot @CodeSandwich
