### ISSUE TITLE
ERC721Consecutive with custom startingTokenId

### ISSUE THREAD

**Issue by kfishnchips** [OpenZeppelin/openzeppelin-contracts#4096]
**🧐 Motivation**
Many of our contracts start with token id 1, ERC721Consecutive currently assumes the starting token id to be zero.

**📝 Details**
Add a constructor which allows setting the starting token id.

**Comment by frangio** [comment]
@kfishnchips What was the reason for closing this issue?

**Comment by kfishnchips** [comment]
I opened a PR instead, apologies.

**Comment by kfishnchips** [comment]
@frangio this is the PR https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4097, should I keep this issue open?
