### ISSUE TITLE
Uncontrolled Resource Consumption

### ISSUE THREAD

**Issue by philipjonsen** [OpenZeppelin/openzeppelin-contracts#4115]
minimatch ReDoS vulnerability A vulnerability was found in the minimatch package. This flaw allows a Regular Expression Denial of Service (ReDoS) when calling the braceExpand function with specific arguments, resulting in a Denial of Service.

Introduced through
package-lock.json

Vulnerable dependency: minimatch (npm)

          }
        },
        "minimatch": {
          "version": "3.0.4",
          "resolved": "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz",
              }
            },
            "minimatch": {
              "version": "3.0.4",
              "resolved": "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz",
          }
          
          Upgrade to:
          
        },
        "minimatch": {
          "version": "3.0.5",
          "resolved": "https://registry.npmjs.org/minimatch/-/minimatch-3.0.5.tgz",
              }
            },
            "minimatch": {
              "version": "3.0.5",
              "resolved": "https://registry.npmjs.org/minimatch/-/minimatch-3.0.5.tgz",

**Comment by philipjonsen** [comment]
https://github.com/advisories/GHSA-f8q6-p94x-37v3

**Comment by frangio** [comment]
This package has no user-facing dependencies. This vulnerability has no effect for us.

**Comment by philipjonsen** [comment]
Great! Just wanted to help :)
