### ISSUE TITLE
Not install in vs code

### ISSUE THREAD

**Issue by REBEL75** [OpenZeppelin/openzeppelin-contracts#4122]
please fix this 

![Screenshot 2023-03-17 210804](https://user-images.githubusercontent.com/78189163/225951903-9b881f81-92aa-493d-8440-f418fa887b9e.png)

**Comment by REBEL75** [comment]
fix it fast

**Comment by ernestognw** [comment]
If you need further support please post in the [OpenZeppelin Forum](https://forum.openzeppelin.com/).
