### ISSUE TITLE
Move `to != owner` check from `ERC721.approval` to `ERC721._approval`

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#4136]
In `ERC721.approve` (public) we do
```solidity
require(to != owner, "ERC721: approval to current owner");
```
we don't do it in `ERC721._approve` (internal)

That means its not ok to approve the owner, unless you do it internally ? IMO the check should move from the public to the internal function. (note that there is already a call to `ERC721.ownerOf` inside the internal version, so its not like we are saving an `sload` anyway)

**Comment by boxingcoder00** [comment]
This may be a foolish question(very new to the space) but what exactly would be the benefit? gas or optimization ?

**Comment by ernestognw** [comment]
> This may be a foolish question(very new to the space) but what exactly would be the benefit? gas or optimization ?

It's just a matter of interface consistency, we expect developers to have reasonable guarantees when they use the library. I think it's reasonable to expect this same check in both the public and internal interface.

**Comment by Amxx** [comment]
> hey i want to work on this issue`
> 
> function _approval(address owner, address to, uint256 tokenId) internal virtual { require(to != owner, "ERC721: approval to current owner"); _tokenApprovals[tokenId] = to; emit Approval(owner, to, tokenId); } `

There are already 2 PRs for this issue.

Also, the code you shared above changes the internal interface, which is not something we want.

**Comment by JusticeBitterbit** [comment]
is this issue solved . I am a web3 developer looking to get my hand dirty in the OPEN SOURCE work especially with the things like openZeppelin 's work . If its not close please tell me and are the extra two issues closed . would like to dedicate 3 months to solving the issues I find for Openzeppelin

**Comment by Saksham010** [comment]
> > hey i want to work on this issue`
> > function _approval(address owner, address to, uint256 tokenId) internal virtual { require(to != owner, "ERC721: approval to current owner"); _tokenApprovals[tokenId] = to; emit Approval(owner, to, tokenId); } `
> 
> There are already 2 PRs for this issue.
> 
> Also, the code you shared above changes the internal interface, which is not something we want.

Made a PR, it passes all required test

**Comment by Amxx** [comment]
@kr-meet There is a big refactor of ERC721 that is going on internally right now. IMO we should wait for that refactor to be done before changing other things, otherwize we'll multiply conflicts

**Comment by kr-meet** [comment]
> @kr-meet There is a big refactor of ERC721 that is going on internally right now. IMO we should wait for that refactor to be done before changing other things, otherwize we'll multiply conflicts

no worries, we can wait.
