### ISSUE TITLE
always give ERROR:  transferFrom function in ERC721.

### ISSUE THREAD

**Issue by vishrut66** [OpenZeppelin/openzeppelin-contracts#4137]
I am creating my NFT marketplace smart contract.

in this, there is a function in which I need to transfer the owner's nft to the marketplace contract.

I use this method : 

    function createSell(address _nft , uint256 _tokenId) external  {
        IERC721 nft = IERC721(_nft);
        require(nft.ownerOf(_tokenId) == msg.sender, "not nft owner");
        nft.approve(address(this), _tokenId);
        nft.transferFrom(msg.sender, address(this), _tokenId);
    }

so when I call this function it always gives me this error:

![2023-03-25 (6)](https://user-images.githubusercontent.com/108527286/227724649-c2964aa0-fdf4-4f21-9814-43a71552d936.png)

when I console log every required condition so I got these results:
![image](https://user-images.githubusercontent.com/108527286/227725084-00d0e6c1-a52f-4d4b-94ef-30ebdae31112.png)

here it's code : 

![2023-03-25 (9)](https://user-images.githubusercontent.com/108527286/227725119-9a2650b5-bf73-41f1-a184-f1cacf2c7184.png)

so I want to say that the nft is approved for marketplace contract but when i call the transferFrom  function it gives me ERROR that is message: "execution reverted: ERC721: approve caller is not token owner or approved for all"

you can also see the console log in that red portion's last line, all required condition is satisfied and it gives True. even i can't transfer Owner's nft to the marketplace.

**Comment by lhemerly** [comment]
The msg sender of the approve is the smart contract which does not own the NFT.

**Comment by vishrut66** [comment]
after spending some hours trying to understand that, thank you for the response.
the approve function should be called externally not within the contract.
