### ISSUE TITLE
Add Call Restrict

### ISSUE THREAD

**Issue by RedHeadphone** [OpenZeppelin/openzeppelin-contracts#4148]
**🧐 Motivation**
I recently wanted a way to restrict function calls for each user by some time. That's when I was searching if there was a utils contract in OpenZeppelin contracts, but I didn't find one. So I decided to make one and contribute here.

**📝 Details**
I have created a repo with the contract and documentation on how to use it. You can find the repo [here](https://github.com/RedHeadphone/CallRestrict). I've added tests to verify the logic of smart contract. I would like to know your opinions and suggestions (if any) on this util contract. If everything looks good, I can make PR adding Call Restrict.

**Comment by ernestognw** [comment]
Hey @RedHeadphone, the idea is interesting. We're currently also discussing [an `AccessManager` implementation](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4121) that might be suited for what you want to do.

There are still some open questions, but the particular use case of count/timestamp is not supported in the current design. We'd love to hear why you think that use-case could be important.

If we decide to support it, I'd say any access restriction should fall into our Access Control category, therefore added to the AccessManager.

**Comment by RedHeadphone** [comment]
Yeah, access control seems correct place to add call restrict functionality, as for important use-case of it can be restricting admin to withdraw funds within same year from a fund raising contract. And for count based restriction, it can be helpful to make user only mint some `x` amount of time.

**Comment by RedHeadphone** [comment]
@ernestognw Let me know if you guys decide to support it, so I can create PR on access manager
