### ISSUE TITLE
Reducing Gas Cost in ERC721 safeTransferFrom Function

### ISSUE THREAD

**Issue by Aboudjem** [OpenZeppelin/openzeppelin-contracts#4155]
**🧐 Motivation** I have identified a potential optimization in the ERC721 `safeTransferFrom` function in the OpenZeppelin Contracts library. By making a small change in the function implementation, I saved 32 gas per transaction. I believe this improvement could be beneficial for library users seeking to optimize gas costs in their smart contracts.

**📝 Details** I propose the following change in the `safeTransferFrom` function:

_Current implementation:_

```solidity

`function safeTransferFrom(address from, address to, uint256 tokenId) public virtual override {
    safeTransferFrom(from, to, tokenId, "");
}` 
```
_Proposed change:_

```solidity

`function safeTransferFrom(address from, address to, uint256 tokenId) public virtual override {
    require(_isApprovedOrOwner(_msgSender(), tokenId), "ERC721: caller is not token owner or approved");
    _safeTransfer(from, to, tokenId, "");
}` 
```

By directly calling `require(_isApprovedOrOwner(_msgSender(), tokenId), "ERC721: caller is not token owner or approved")` and `_safeTransfer(from, to, tokenId, "")` instead of the public `safeTransferFrom(from, to, tokenId, "")`, we can save **32 gas** per transaction. This change maintains the original functionality while providing a gas optimization.

Thank you for your time and effort in maintaining this valuable library ❤️

**Comment by Amxx** [comment]
Hello @Aboudjem 

32 gas is really nothing here. A safeTransferFrom cost something like 70k gas, so its about 0.05%. On the otherhand doing the proposed change could break any contract where `safeTransferFrom(address, address, uint256, bytes)` is overriden.

If someone overrides `safeTransferFrom(address, address, uint256, bytes)`, the changes that he/she adds affect both functions. With your change, you would have to override twice, which some people might forget.
