### ISSUE TITLE
4.8.2. broke "ERC721:_beforeTokenTransfer": TypeError: Function has override specified but does not override anything

### ISSUE THREAD

**Issue by honigkuchenbaer** [OpenZeppelin/openzeppelin-contracts#4162]
I updated from <= 4.6 to 4.8.2 and on my ERC721-based contract, `beforeTokenTransfer`  is not compiling anymore.

If I don't overwrite `beforeTokenTransfer`, it complains that I have to override it. And if I overwrite it, it complains that it is _"not override anything"_.

Here is my contract

```
contract XYZAbc as
    ERC721Enumerable,
    ERC721Burnable,
    ERC721Pausable,
    ERC721URIStorage,
    Ownable,
    AccessControlEnumerable
{
}

function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    ) internal virtual override (ERC721, ERC721Enumerable, ERC721Pausable) {
        super._beforeTokenTransfer(from, to, amount);
    }

```

Multiple Errors will ne logged now:

>  Function has override specified but does not override anything.

>  Invalid contracts specified in override list: "ERC721", "ERC721Enumerable" and "ERC721Pausable".

> Derived contract must override function "_beforeTokenTransfer". Two or more base classes define function with same name and parameter types.

Rolling back from OZ 4.8 to 4.6 fixes this. But 4.6 is considered as being vulnerable so we have to upgrade to 4.8...

**💻 Environment**

4.8

**📝 Details**

as written above

**🔢 Code to reproduce bug**

see above

**Comment by Amxx** [comment]
Hello @honigkuchenbaer 

Since 4.8, the signature of the hook changed. It is now
```solidity
function _beforeTokenTransfer(address from, address to, uint256 firstTokenId, uint256 batchSize) internal virtual {}
```

You are missing the `uint256 batchSize` parameter

**Comment by Amxx** [comment]
This is documented [in the README](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CHANGELOG.md#breaking-changes-2)

**Comment by honigkuchenbaer** [comment]
Wow., this is heavy, as the 3 error messages together are totally misleading here (I know, that the mess of error messages has something to do with how Solidity compiler works)

Many Thanks anyway! Next time I read README earlier when error messages make no sense :)

**Comment by DylanBlockchainDev** [comment]
@Amxx is there anything on version 5.0.0?

**Comment by Amxx** [comment]
Yes, please look at the changelog
