### ISSUE TITLE
Turn ERC1967Upgrade into a library

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#4204]
Solidity 0.8.20 should include https://github.com/ethereum/solidity/pull/10996, which would finally allow `ERC1967Upgrade` to be written as a library (instead of an abstract contract).

This raises the question of what to do with `IERC1967`.

**Comment by balajipachai** [comment]
@Amxx If I understood it correctly, since now we can emit Interface events from within library thus, we are trying to change ERC1967 from abstract to library, right?

**Comment by Amxx** [comment]
We were always able to emit events (defined in libraries or in contracts ... not in interfaces) from libraries.

In the past these events were correctly emitted but the corresponding ABI was not included in the contract that uses the library. Since 0.8.20, the event definition is added to the contracts ABI

**Comment by balajipachai** [comment]
Okay, got it, thank you for the answer, this helps.
That being said, let me get started with this and submit a PR with all necessary changes.

**Comment by Amxx** [comment]
Thank you for your proposal, but please don't. We already have code/branch that starts implementing that and we would not want to ave effort duplication.

**Comment by balajipachai** [comment]
Okay, let me check https://github.com/ethereum/solidity/issues/14206

**Comment by Amxx** [comment]
Blocker was resolved by solidity, and should be available in 0.8.21.

**Comment by frangio** [comment]
@balajipachai Yes, all pragmas will be bumped to near-latest Solidity in Contacts 5.0.

**Comment by balajipachai** [comment]
Great, whose working on bumping the pragma version in all other contracts? I would like to work alongside him/her/them
