### ISSUE TITLE
`ReentrancyGuard` with transient opcodes `TSTORE` and `TLOAD`

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/openzeppelin-contracts#4205]
**🧐 Motivation**

Since [EIP-1153](https://eips.ethereum.org/EIPS/eip-1153) is confirmed to be included in the upcoming Cancun-Deneb upgrade, I would like to discuss the possibility of using the future transient opcodes `TSTORE` and `TLOAD` for the `ReentrancyGuard` (abstract) contract.

Furthermore, I would like to highlight the initiatives (partially driven by myself), to disable reentrancy by default at the compiler level:
- **Vyper:** https://github.com/vyperlang/vyper/issues/3380
- **Solidity:** https://github.com/ethereum/solidity/issues/12996

**Comment by Amxx** [comment]
> Reentrancy as a language feature is built for the 5-10% of professionals that understand the underlying implications

My personal view on that (which is not OZ position) is that maybe those 5-10% of professionals should be the only one writting defi apps. I don't think "everyone should write smart contracts" like "everyone should write python scripts to help with taxes" or "everyone should write php to customize their personal wordpress".

**Comment by Amxx** [comment]
> So maybe we can take this discussion as a good opportunity to have a conversation about a future-proof model, where not all chains are fully EVM equivalent.

That is an interesting and necessary discussion that we don't really have so far. We worked on tooling to identify some key point of the VM behavior, in order to check our contract will behave as expected. This will possibly detect missing/modified features, but it won't identify new one (like the moonbeam precompile you mentioned).

Its also unclear what we want to do with this information:
- add warning that contract X will not work on network Y ?
- propose an alternative implementation ?

**Comment by pcaversaccio** [comment]
> If the language decides to help the 90-95% its ok, as long as they don't make the work of the 5-10% more difficult to write and review.

I guess there is no question that this is the ultimate goal.

> That is an interesting and necessary discussion that we don't really have so far. We worked on tooling to identify some key point of the VM behavior, in order to check our contract will behave as expected. This will possibly detect missing/modified features, but it won't identify new one (like the moonbeam precompile you mentioned).

Is that kind of tooling open-source?

> Its also unclear what we want to do with this information:
> 
> - add warning that contract X will not work on network Y ?
> - propose an alternative implementation ?

Based on my experience, warnings are easily ignored. One solution could be to simply state in a disclaimer, that only fully EVM equivalent chains are supported (I drafted an EIP on the definition of this term [here](https://github.com/ethereum/EIPs/pull/6269) because I think it's very important to align here as a community, but unfortunately the closed it; I'm trying to push them to reconsider it again). But that solution might be too high-level and will be ignored by the folks that simply `npm` install OZ contracts. Will need to think about it.

**Comment by pcaversaccio** [comment]
Another comment on EVM equivalence given the current circumstances: We are right now in a situation where there are numerous chains that do not support the latest EVM version `shanghai` with the opcode `PUSH0`. This means that, for example, the use of the latest Solidity version `0.8.20`, which supports `PUSH0`, will likely fail with these chains (if it includes `PUSH0` in the init code and gets executed at creation time, the deployment fails; if the runtime code has `PUSH0` and is not executed as part of the deployment, the runtime code can revert on calls) and thus these chains can no longer be considered fully EVM-equivalent. I don't think this is OZ's responsibility to ensure EVM-compatible bytecode, but what if such differences increase over time and certain critical OZ logic cannot be deployed or executed anymore due to EVM version differences? I don't know the solution to this problem, but I just want to highlight it since I deem this important.

**Comment by frangio** [comment]
> Is that kind of tooling open-source?

It is a test suite rather than tooling, and it isn't really open source quality. One learning I can share is that it's more tough to deal with the "network level" specifics of a testnet than it is to deal with the EVM differences across networks (for now)!

---

Regarding the point about EVM diverging, I share the concerns but I don't see anything that we can do for now rather than observing how PUSH0 adoption evolves.

**Comment by pcaversaccio** [comment]
> It is a test suite rather than tooling, and it isn't really open source quality. One learning I can share is that it's more tough to deal with the "network level" specifics of a testnet than it is to deal with the EVM differences across networks (for now)!

Can you quickly elaborate on what you exactly mean by the "network level specifics"? I.e. maybe challenges with the gossip protocol, state tries, signature verifications etc.? (and sorry for going off-topic here, since this issue is about the `ReentrancyGuard`, but I feel it's still important)

> I also think that this issue about transient ReentrancyGuard is a little premature 🙂 but rest assured I also want to see that implemented.

Yeah, I was just thinking about it and wanted to drop my thoughts into an issue so we have a go-to source for this discussion. I mean I could also open another thread on FEM, but since it's implementation-specific I thought the OZ repo is appropriate 🙂.

**Comment by sambacha** [comment]
> > Reentrancy as a language feature is built for the 5-10% of professionals that understand the underlying implications
> 
> My personal view on that (which is not OZ position) is that maybe those 5-10% of professionals should be the only one writting defi apps. I don't think "everyone should write smart contracts" like "everyone should write python scripts to help with taxes" or "everyone should write php to customize their personal wordpress".
> 
> If the language decides to help the 90-95% its ok, as long as they don't make the work of the 5-10% more difficult to write and review.

My man, yes. Concurrence is hard to grasp to begin with. 

We dont want to cater to everyone. Principled engineering is an attitude a a much as its experience and knowledge. If you are not serious to begin with go do something else.

We want fanatics, no part time believers.
