### ISSUE TITLE
Should ERC20 `_burn` increase the `_balances` of `address(0)`?

### ISSUE THREAD

**Issue by CJ42** [OpenZeppelin/openzeppelin-contracts#4215]
**🧐 Motivation**

I simply wonder if when the internal `_burn` function on `ERC20` is called, if it should increase the balance of the `address(0)` in the `_balances` mapping.

Currently, this is not done by default. I just wondered if this should be the default behaviour in ERC20, or if this should be an implementation detail.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/9e8b74a0e2c8a6e87f7fa88318f15017d4b14524/contracts/token/ERC20/ERC20.sol#L277-L293

**📝 Details**

For instance, I have noticed on Etherscan that:
- for the DAI token contract, the `address(0)` has some balance.

https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f#readContract
<img width="316" alt="image" src="https://user-images.githubusercontent.com/31145285/236240423-498e0a0a-47ed-4340-abec-e99934735f9e.png">

- for the USDC token contract, the `address(0)` has no balance.

https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#readProxyContract
<img width="383" alt="image" src="https://user-images.githubusercontent.com/31145285/236240358-f8841021-f342-4212-bcfc-5c4aaefa441e.png">

> Although I have no idea if this is the normal behaviour or if this is intended in each implementation.

@Amxx @frangio

**Comment by frangio** [comment]
Strong no, in my opinion. Here's a simple issue: it's possible to mint 2**256-1 tokens, burn them all, mint the same amount again, and burn it again. The balance of address(0) would then overflow uint256.

**Comment by CJ42** [comment]
Ok that makes totally make sense.
Thanks for the quick reply on this @frangio 

Fee free to close the issue, unless you find it relevant to keep the conversation open.
