### ISSUE TITLE
`TimelockController` contract's constructor takes input parameters as `memory` instead of `calldata`

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/openzeppelin-contracts#4217]
Improvement Suggestion
===================

Following [this discussion](https://forum.openzeppelin.com/t/error-in-timelock-using-timelockcrontroller/36007/3?u=barakman) on OZ Forum, [here is the prototype of the TimelockController contract's constructor](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/TimelockController.sol#L81):
```
constructor(
    uint256 minDelay,
    address[] memory proposers,
    address[] memory executors,
    address admin
)
```
You can somewhat reduce the gas consumption of this function, by changing each occurrence of `memory` to `calldata`.

Note that this **may** pose an API-breaking change for:
- Anyone inheriting from `TimelockController`
- Anyone creating an instance of this contract onchain (i.e., via `new TimelockController`)

**Comment by ernestognw** [comment]
Thanks for opening the issue @barakman, I'll close in favor of #4216 since it was published first and both come from similar places but I'll port your description over to #4216 since it's including more information. Thanks!
