### ISSUE TITLE
Add internal name and version getters for EIP712

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#4226]
Note that we have these getters in the [upgradeable version of EIP712](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/utils/cryptography/EIP712Upgradeable.sol).

**Comment by RenanSouza2** [comment]
Made the changes using the ShortStrings library,
https://github.com/RenanSouza2/openzeppelin-contracts/tree/EIP712-getters
