### ISSUE TITLE
Consider cleaning the pending admin (and schedule) in AccessControlDefaultAdminRules's `_revoke`

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#4237]
Following the discussion here: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4230#discussion_r1189475825

The following workflow is currently possible:

- The admin initiate a default admin transfer
- Using the internal _revoke, the dev (admin?) renounce its admin position. 
  - This emits the revoke event, and set the current admin to `address(0)`
    - At the point users will think the contract has no admin, and will not get a new one
- The pending admin accepts, and "resurrect" the admin rights
  - This goes against the expectation (by the user) that the admin was removed from the system.
  
If we consider that a security issue, a possible fix is described [here](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4230#discussion_r1189478106)

**Comment by frangio** [comment]
This was addressed by https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4230.
