### ISSUE TITLE
optimize openzepplin multicall

### ISSUE THREAD

**Issue by malik672** [OpenZeppelin/openzeppelin-contracts#4242]
Optimization
code 
`function multicall(bytes[] calldata data) external virtual returns (bytes[] memory results) {
        results = new bytes[](data.length);
        for (uint256 i = 0; i < data.length; i++) {
            results[i] = Address.functionDelegateCall(address(this), data[i]);
        }
        return results;`
1. do not initialize i to zero, by default variables are zero in solidity
2. cache the length of data before using it for the loop
3. pre increment instead of post increment

**Comment by malik672** [comment]
i've not yet test the the code, so i don't know the gas diffrence yet

**Comment by Juyotal** [comment]
hey @malik672 , can I rapidly look into that?

**Comment by frangio** [comment]
These are not significant optimizations. If you believe otherwise, please provide benchmarks.
