### ISSUE TITLE
Removing checks in ERC20._transfer

### ISSUE THREAD

**Issue by m-zaink** [OpenZeppelin/openzeppelin-contracts#4246]
Isn't it a waste of gas and resources if we're trying to send tokens to ourselves?

Shouldn't we avoid those operations altogether?

[LL223C1-L224C74](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/3ec4307c8a79ddfee9bbaf1f26435c908fae0cae/contracts/token/ERC20/ERC20.sol#LL223C1-L224C74)

```solidity
require(from != address(0), "ERC20: transfer from the zero address");
require(to != address(0), "ERC20: transfer to the zero address");
```

**Comment by frangio** [comment]
If you are concerned about the gas cost of these operations please contribute gas measurements so we can evaluate. It is unlikely to be significant. In any case, we are reviewing all of this code for 5.0 and these lines may change.
