### ISSUE TITLE
Add polygon zkevm interfaces under vendor

### ISSUE THREAD

**Issue by bilbeyt** [OpenZeppelin/openzeppelin-contracts#4247]
**🧐 Motivation**
It would be better if we can have interfaces also in openzeppelin as under vendor we already have polygon.

**Comment by istankovic** [comment]
Specifically, these contracts: https://github.com/0xPolygonHermez/zkevm-contracts/tree/main/contracts/interfaces

**Comment by frangio** [comment]
We're considering removing the cross-chain utilities in the next major version and that would imply removing all of the vendored bridge interfaces. If you are using any of these utilities or interfaces please share more about that so we can take it into consideration.

**Comment by frangio** [comment]
I see. It wouldn't be a priority for us to maintain a separate package. It reminds me of [money-legos](https://github.com/studydefi/money-legos) but it is DeFi focused and doesn't seem actively maintained.

I will close as we are moving ahead with removing these.
