### ISSUE TITLE
Bug in CountersUpgradeable.sol document

### ISSUE THREAD

**Issue by dtnwen** [OpenZeppelin/openzeppelin-contracts#4255]
I'm initializing proxy pattern for my contract and found this little bug in [CountersUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/utils/CountersUpgradeable.sol)

**💻 Environment**
I'm using Open Zeppelin Contracts version 9.5.1, using with Hardhat.

**📝 Details**
When replaced code with Upgradeable contracts, I saw this line in [CountersUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/utils/CountersUpgradeable.sol)
``` * Include with `using Counters for Counters.Counter;```

**🔢 Code to reproduce bug**
It should be `using CountersUpgradeable for CountersUpgradeable.Counter;`
Isn't it?

**Comment by frangio** [comment]
The code is automatically transpiled, among other things the library is automatically renamed, but we do not edit the documentation comments so they remain using the "standard" non-upgradeable names. This is slightly confusing but we hope you can understand the docs regardless!
