### ISSUE TITLE
Remove check for address zero in ERC1155.balanceOf

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#4259]
We have a require statement in this function that doesn't seem to be mandated ERC-1155, or at least I can't find it in the spec. It looks like it should be removed.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1642b6639b93e3b97be163d49827e1f56b81ca11/contracts/token/ERC1155/ERC1155.sol#L70-L71

**Comment by Amxx** [comment]
This might have been imported from the ERC-721 standard into the ERC-1155 implementation (for consistency)

> /// @dev NFTs assigned to the zero address are considered invalid, and this
    ///  function throws for queries about the zero address.
    
(IMO, the part of ERC-721 is really bad)

**Comment by balajipachai** [comment]
In that case it's better we remove it, and update the tests wherever required.
