### ISSUE TITLE
Export and add OZ's contracts' ABIs to this repository

### ISSUE THREAD

**Issue by sshmaxime** [OpenZeppelin/openzeppelin-contracts#4291]
I recently found myself in a situation where I needed OpenZeppelin contracts ABI definitions in `Rust`(although it could have been in any other programming language).

To do so, I was left with the only possibility of cloning this repository, compiling the contracts, retrieving their respective ABIs and finally doing the transformation into `Rust usable` code.

I'm basically suggesting to add to this repository an `abis` folder containing all the ABIs of OpenZeppelin contracts. Is it something that you guys could see doing or is it agains't your current way of doing things ?

**Comment by Amxx** [comment]
Hello @sshmaxime 

The JSON artifacts, that contain the ABI, are distributed in the npm packages (which is our preferred distribution vector).

Keeping track of the artifacts in github would greatly increase the maintenance difficulty and would likely result in errors.

**Comment by sshmaxime** [comment]
Hey @Amxx, thanks for the fast reply !

Alright, make total sense ! I didn't know it was in the npm package ! Thank you 🙏
