### ISSUE TITLE
`toString` method on `Address.sol`

### ISSUE THREAD

**Issue by EvanPiro** [OpenZeppelin/openzeppelin-contracts#4295]
**🧐 Motivation**
Encoding an address for offchain processing from a contract method is an inevitable need for applications with token redemption features to synch offchain with onchain. While I use `Address.sol` as a nice utility layer over `address`, I see no `toString` method to achieve this use case and desire one.

**Comment by Amxx** [comment]
Hello @EvanPiro 

[There is a `toHexString(address addr)` function in the "Strings" library.](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Strings.sol#L75)
