### ISSUE TITLE
Strings.toString doesn't compile with integer literals

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#4298]
As seen [in the forum](https://forum.openzeppelin.com/t/strings-tostring-only-works-with-statically-defined-uint256-and-fails-otherwise/36514/2), `Strings.toString(1)` does not compile in 4.9.0 because `1` could be a signed or unsigned integer and `toString` is available for signed integers since https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3773.

We should rename the function to `toStringSigned` so that the basic `toString` function can be used with integer literals.

**Comment by frangio** [comment]
@Amxx @ernestognw Would you agree with renaming this? If so we can mark this as `good first issue`.

**Comment by himansh295** [comment]
Hi @frangio is this issue is still open.I would like to work on it.
