### ISSUE TITLE
Despite what the 4.9 docs say, time-based governance is broken in 4.9

### ISSUE THREAD

**Issue by gte620v** [OpenZeppelin/openzeppelin-contracts#4319]
The docs say that we can override `clock()` and use timestamp-based governance as of 4.9: https://docs.openzeppelin.com/contracts/4.x/governance#token_2

But `block.number` is still all that is supported in Checkpoint.sol in v4.9.0: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.0/contracts/utils/Checkpoints.sol

It is not until after 4.9 that checkpoint has the right support for timestamps:
<img width="1216" alt="image" src="https://github.com/OpenZeppelin/openzeppelin-contracts/assets/2158394/2cc20d81-172c-4357-8725-9dadc6188349">

**Comment by frangio** [comment]
If you wrote code that doesn't compile or doesn't behave as expected, please share it here. If you opened this issue in error, let us know.

**Comment by gte620v** [comment]
The example does compile.  I looked at the v4.9 Checkpoint contract and saw `requires` checks on `block.number` in various view functions, but none of those functions are used by ERC20Votes.  So there isn't a bug.
