### ISSUE TITLE
set ERC20Wrapper default decimals to 0

### ISSUE THREAD

**Issue by RenanSouza2** [OpenZeppelin/openzeppelin-contracts#4323]
**🧐 Motivation**

If a wrapped token does not implements ERC20Metadata ERC20Wrapper contract defaults it's decimals to 18

I suggest changing it to zero

**Comment by Amxx** [comment]
Hello @RenanSouza2 and thanks for the suggestion. 

I'd love to know more about why you believe zero is a better option then 18 in that case !

**Comment by RenanSouza2** [comment]
From my understanding, if an ERC20 does not implement the decimals function it is an unit in itself, a balance of 20 represents 20 tokens,

In this waythe wrapper is implemented, the frontends that consume the  metadata would show  instead of 20 would show 20 e -18.

Afterall is not that big of a deal since the depositFor and withdrawTo are consistent and will not be modified by this but better keepts the 1:1 token to wrapped proportion

**Comment by ernestognw** [comment]
Thanks for flagging @RenanSouza2,

I think 18 decimals is considered an acceptable default and it's widespread enough to think there's a good consensus of using it. I have two points in favor of keeping it in 18:

- Although developers should do their own research, there's a reasonable chance of them assuming every ERC20 has 18 decimals when they suddenly realize an ERC20Wrapper they're using has 0. That'd be a security concern for me.
- I don't see how you'd represent an 18 decimals token in a 0 decimals token without losing information

**Comment by RenanSouza2** [comment]
> * I don't see how you'd represent an 18 decimals token in a 0 decimals token without losing information

I'm suggesting the change only in the case when the underlying token throws on decimal call

```
function decimals() public view virtual override returns (uint8) {
    try IERC20Metadata(address(_underlying)).decimals() returns (uint8 value) {
        return value;
    } catch {
        return super.decimals();
    }
}
```

In the case the underlying has decimals defines it would not change anything

**Comment by frangio** [comment]
>From my understanding, if an ERC20 does not implement the decimals function it is an unit in itself, a balance of 20 represents 20 tokens,

What is this understanding based on? It's always been our impression that everyone considers the default to be 18.

**Comment by Amxx** [comment]
> ```solidity
> function decimals() public view virtual override returns (uint8) {
>     try IERC20Metadata(address(_underlying)).decimals() returns (uint8 value) {
>         return value;
>     } catch {
>         return super.decimals();
>     }
> }
> ```

I believe we used to have this exact code, and we changed it because of concerns with inheritance order having to much effect on the outcome of the function. 

To be clear, someone who know the wrapped token has no decimals, and who want to use 0 for the wrapped token can do:
```solidity
contract MyWrapper is ERC20Wrapper {
    constructor(address underlying) ERC20Wrapper(underlying) {}
    decimals() public view virtual override returns (uint8) { returns 0; }
}
```
So the question is "what is the most generic fallback ? / what do we want by default ? / should the default be come from the parent ?"

**Comment by RenanSouza2** [comment]
> What is this understanding based on? It's always been our impression that everyone considers the default to be 18.

Tbh I actually had the impression it was specified in the ERC20 specification, it actually says nothing about the default interpretation,

My intuition was always that no decimals means 0 decimals, but your pçoint of view also maes sense since 18 is such a usual number for decimals to be

**Comment by RenanSouza2** [comment]
> I believe we used to have this exact code

My comment was a bit confusing in this sense, the code I copy pasted is the one from the OZ contract

**Comment by Amxx** [comment]
That is why I got confused. At some point we did discuss the `catch` part (between doing `return super.decimals();` and `return 18;`)
Linearisation order was a concern, but that is probably out-of-scope for this discussion

**Comment by frangio** [comment]
It seems like we agree to keep the current way the contract behaves.

**Comment by RenanSouza2** [comment]
If I may ask one last thing

I raised up this same question in the ethereum magicians forum:
https://ethereum-magicians.org/t/erc20-default-decimals/14598/5

Could you document your opinion there?

**Comment by netnose** [comment]
Even if 18 is the de facto standard, ERC-20 is not explicit about the default value to be used for decimals.

An explicit reference to 18 decimals can be found in [ERC-1046](https://eips.ethereum.org/EIPS/eip-1046), even if it is an extension ERC, it is talks about ERC-20 behavior.

IMO, 0 is more intuitive but it looks like 18 has been chosen years ago.
