### ISSUE TITLE
why is _update replacing _beforeTokenTransfer and _afterTokenTransfer

### ISSUE THREAD

**Issue by HalfSuperNate** [OpenZeppelin/openzeppelin-contracts#4328]
About: [Remove hooks](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3838)

The issue is now _update is only called once therefore any function that needed to be performed before the token is transferred  it won't happen not trigger.

Here is an example snippet from [The Sanctuary ERC1155 Contract](https://etherscan.io/address/0x715af60ec1c3c65e294c7d8ef340f14e754c66bb#code)

`function _beforeTokenTransfer(address operator, address from, address to, uint256[] memory ids, uint256[] memory amounts, bytes memory data) internal virtual override{
        super._beforeTokenTransfer(operator, from, to, ids, amounts, data); // Call parent hook
        require(restricted[operator] == false && restricted[from] == false && restricted[to] == false, "Operator, From, or To Address is RESTRICTED"); //checks if the any address in use is restricted

        for (uint256 i = 0; i < ids.length; i++) {
            if(flagged[ids[i]]){
                revert("FID"); //reverts if a token has been flagged
            }
        }
    }

function bindOnMint(uint _id) public view returns(bool){
        uint256 _batchID;
        for (uint256 i = 0; i < collectionBatchEndID.length; i++) {
            if(i != 0 && _id <= collectionBatchEndID[i] && _id > collectionBatchEndID[i - 1]){
                _batchID = i;
                break;
            }
            if(i <= 0 && _id <= collectionBatchEndID[i]){
                _batchID = i;
                break;
            }
        }
        return bindOnMintBatch[_batchID];
    }

function _afterTokenTransfer(address operator, address from, address to, uint256[] memory ids, uint256[] memory amounts, bytes memory data) internal virtual override{
        super._afterTokenTransfer(operator, from, to, ids, amounts, data); // Call parent hook

        for (uint256 i = 0; i < ids.length; i++) {
            if(bindOnMint(ids[i])){
                flagged[ids[i]] = true;
            }
        }
    }
`

**Comment by Amxx** [comment]
> any function that needed to be performed before the token is transferred

If you need to perform an action BEFORE the transfer you should just do
```solidity
function _update(address from, address to, uint256 amount) internal virtual override returns (bool) {
   // ... you action here ...
   return super._update(from, to, amount);
}
```

**Comment by nicolasguasca1** [comment]
@Amxx , do you have an estimate on when this will be available for _ERC1155Upgradeable.sol_? This function appears already in v.4.9.3 of _contracts_, but not _contracts-upgradeable_

**Comment by nicolasguasca1** [comment]
@Amxx  I downloaded v.4.9.3 using npm and the ERC1155Upgradeable contract is not up to date. The version available in github (which I understand is V.4.9.3) is indeed using this new features.
