### ISSUE TITLE
Warning from HardHat in Address.sol

### ISSUE THREAD

**Issue by yash251** [OpenZeppelin/openzeppelin-contracts#4332]
After compiling my contract I got this warning

```Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
   --> @openzeppelin/contracts/utils/Address.sol:200:30:
    |
200 |     ) internal view returns (bytes memory) {
    |                              ^^^^^^^^^^^^


Warning: Unnamed return variable can remain unassigned. Add an explicit return with value to all non-reverting code paths or name the variable.
   --> @openzeppelin/contracts/utils/Address.sol:223:30:
    |
223 |     ) internal pure returns (bytes memory) {
    |     
  ```

**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by ernestognw** [comment]
Hey @yash251,

The apparent reason for this warning is that both [`Address.verifyCallResult`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/54b3f14346da01ba0d159114b399197fea8b7cda/contracts/utils/Address.sol#L223) and [`Address.verifyCallResultFromTarget`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/54b3f14346da01ba0d159114b399197fea8b7cda/contracts/utils/Address.sol#L200) have a reverting branch where the return value is not defined, however, the revert path is guaranteed to always revert so there's no need for such assignment.

I'd say this is a problem on the static analysis you're running (maybe during compilation), can you share the details of what compiling method are you using?

**Comment by frangio** [comment]
I believe this is fixed in newer versions of Solidity. Please update the compiler version and let us know.
