### ISSUE TITLE
Foundry Tests taking a long time to run

### ISSUE THREAD

**Issue by mw2000** [OpenZeppelin/openzeppelin-contracts#4337]
Running foundry tests in the repo is taking a long time to run. This is even happening in GitHub actions, you can check PR #3298 for the same.

**💻 Environment**
GitHub actions, Mac OS

**🔢 Code to reproduce bug**
```
forge test
```

**Comment by frangio** [comment]
The 6 hour run in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3298 seems like a random bug. It doesn't seem to be caused by the tests themselves. The last run on `master` took 14 minutes.

**Comment by Amxx** [comment]
> The 6 hour run in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3298 seems like a random bug

Its an issue in the design of the fuzzing test in #3298. 

@mw2000 for PR that are pending, please raises your concerns in the PR discussion and not in another issue please
