### ISSUE TITLE
Ownable's NatSpec incorrectly describes the mechanism for setting the initial owner

### ISSUE THREAD

**Issue by nxt3d** [OpenZeppelin/openzeppelin-contracts#4368]
I noticed in the most recent version (v4.9.0) that it is now necessary to explicitly specify the contract owner as a constructor argument, rather than having the owner automatically set.

I also saw that the statement "By default, the owner account will be the one that deploys the contract" is no longer accurate.

I suggest it should now say, "The owner account is provided as a constructor argument during deployment."

**Comment by nxt3d** [comment]
Also is there an issue with Ownable2Step.sol? if the owner of Ownable.sol is not set by default?

**Comment by RenanSouza2** [comment]
> Also is there an issue with Ownable2Step.sol? if the owner of Ownable.sol is not set by default?

No because the contract is abstract, so whenever a contract inherits it will be reponsible to call Ownable(_owner) in it's constructor,

the comments do need to be ajusted thought

**Comment by nxt3d** [comment]
Okay right, that works, but its appearance is far from ideal. For example I have an abstract contract called Unruggable, which inherits from Ownable2Step. Therefore, when inheriting Unruggable, I also have to import Ownable and invoke Ownable(msg.sender) in the constructor, without a clear justification. In my opinion, it would be preferable if Ownable2Step had a constructor that automatically called the Ownable constructor and passed the account argument through.

**Comment by RenanSouza2** [comment]
Can you share how you are importing the contracts?

**Comment by nxt3d** [comment]
I can actually reduce it down to this: 

```
import {Ownable2Step} from "@openzeppelin/contracts/access/Ownable2Step.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

contract Unruggable is Ownable2Step, IUnruggable, ERC165{
     
    constructor () Ownable(msg.sender){}
```

But I would rather just do this:

```
import {Ownable2Step} from "@openzeppelin/contracts/access/Ownable2Step.sol";

contract Unruggable is Ownable2Step(msg.sender), IUnruggable, ERC165{

```


```

**Comment by RenanSouza2** [comment]
you can do this:

```
import { Ownable, Ownable2Step } from "@openzeppelin/contracts/access/Ownable2Step.sol";

```

**Comment by nxt3d** [comment]
Looks better, but what I am suggesting for Ownable2Step is:

```
    constructor(address initialOwner) Ownable(initialOwner){ }
``

**Comment by Amxx** [comment]
> ` constructor(address initialOwner) Ownable(initialOwner){ }`

We don't do that kind of constructor inheritance, because it messes up multiple inheritance very fast.

Imagine we do
```solidity
abstract contract OwnableSomethingElse is Ownable {
    constructor(address initialOwner) Ownable(initialOwner) {}
    // ...
}

abstract MyContract is Ownable2Step, OwnableSomethingElse {
  // what should the constructor do here ?
}
```

We don't want to do 
``` solidity
constructor(address initialOwner) Ownable2Step(initialOwner), OwnableSomethingElse(initialOwner) {}
```
that would be a big mess, and it would be inneficient.

**Comment by nxt3d** [comment]
Interesting. Also I found another issue with the comments. The version number I believe is wrong, it should be "last updated v4.9.1" The commit "13d5e0466a9855e9305119ed383e54fc913fdc60" to "Make Ownable's initial owner explicit (#4267)" comes after the 4.9.0 tag.

**Comment by ernestognw** [comment]
> > ` constructor(address initialOwner) Ownable(initialOwner){ }`
> 
> We don't do that kind of constructor inheritance, because it messes up multiple inheritance very fast.

I second that we usually avoid it, but we might consider it in some cases. For example, we have it in `MinimalForwarder`, `ERC20Permit`, and `ProxyAdmin` so we might want to reconsider those.

> The version number I believe is wrong, it should be "last updated v4.9.1" The commit "13d5e0466a9855e9305119ed383e54fc913fdc60" to "Make Ownable's initial owner explicit (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4267)" comes after the 4.9.0 tag.

We have a release cycle (see [RELEASING.md](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/8de6eba8a37d2ece73cb6f0fc7154cdba3619fc0/RELEASING.md)) designed to release from the `release-v4.9` branch so that each time the `patch` is bumped, we only include selected changes cherry picking from `master`.

I'm explaining this to also outline that the imprecision in the Ownable comments is not yet released and distributed, it's rather a change we should definitely fix before the next 5.0 major, thanks for reporting @nxt3d.

I'll label it as a good first issue if someone wants to take it, otherwise, we'll eventually revisit it before 5.0 😃

**Comment by ernestognw** [comment]
I completely forgot there was already #4369 published. Just got merged but it was unlinked to this conversation.

I'm closing since that one is already merged

**Comment by c14sh** [comment]
I still see previous code, why is that?

package.json
```
  "dependencies": {
    "@openzeppelin/contracts": "^4.9.2"
  }
```

yarn.lock
```
"@openzeppelin/contracts@^4.9.2":
  version "4.9.2"
  resolved "https://registry.yarnpkg.com/@openzeppelin/contracts/-/contracts-4.9.2.tgz#1cb2d5e4d3360141a17dbc45094a8cad6aac16c1"
  integrity sha512-mO+y6JaqXjWeMh9glYVzVu8HYPGknAAnWyxTRhGeckOruyXQMNnlcW6w/Dx9ftLeIQk6N+ZJFuVmTwF7lEIFrg==
```

Ownable.sol
```
    /**
     * @dev Initializes the contract setting the deployer as the initial owner.
     */
    constructor() {
        _transferOwnership(_msgSender());
    }
```

**Comment by RenanSouza2** [comment]
Because the code you see is the version 4.9,

The changes were made in the 5.0 version that was not realised os of now
