### ISSUE TITLE
Bugs:README.md "guides on our blog" 404 Page not found

### ISSUE THREAD

**Issue by yanboishere** [OpenZeppelin/openzeppelin-contracts#4375]
**💻 Environment**

MacBook

**📝 Details**

<img width="1246" alt="截屏2023-06-20 下午2 22 18" src="https://github.com/OpenZeppelin/openzeppelin-contracts/assets/76860915/38354a0b-8057-4acb-97af-890c951bb081">

**🔢 Code to reproduce bug**

**Comment by frangio** [comment]
Thanks. Looking at what link we should put instead.
