### ISSUE TITLE
new interface for token

### ISSUE THREAD

**Issue by ElPettego** [OpenZeppelin/openzeppelin-contracts#4380]
**🧐 Motivation**

i think IERC20 and ERC20 should be upgraded. it is too old now. i d like to create an interface with the existing methods on ERC20 but adding a few more like owner of the contract, creator of the contract etc.  
**📝 Details**

new Interface for tokens.

**Comment by frangio** [comment]
This is not the right place for this proposal. Create an ERC if you want to propose an alternative to ERC-20.

**Comment by ElPettego** [comment]
after i create it can i do a pull request or i should just create my own repo'

**Comment by frangio** [comment]
A pull request for a newly created ERC will not be accepted.
