### ISSUE TITLE
Feature: Add pragma version to rela

### ISSUE THREAD

**Issue by Valentin-Seehausen** [OpenZeppelin/openzeppelin-contracts#4385]
**🧐 Motivation**

In our current setup with foundry and slither, we use pragma 0.8.18. It is hard to find the correct openzeppelin release, that still uses this version.

**📝 Details**

It would be awesome if you could add a version bump to your release notes. :)

**Comment by Valentin-Seehausen** [comment]
I just realized that v4.9.0 is the last version to use pragma ^0.8.0, and after it bumps to 0.8.19.

Still, I think adding it to the release notes would be nice, to make it easier to find. And to set a standard for future pragma version bumps.

**Comment by frangio** [comment]
**You should not be using the `master` branch.** Please read the disclaimer in the readme.

I've added a second disclaimer in the changelog. https://github.com/OpenZeppelin/openzeppelin-contracts/commit/cb4bf950df5ae43356c4935b3900446f6dc20261

**Comment by frangio** [comment]
The changelog will include a note about the pragma change once we release the code.
