### ISSUE TITLE
ERC-1822 slot difference

### ISSUE THREAD

**Issue by RenanSouza2** [OpenZeppelin/openzeppelin-contracts#4395]
**💻 Environment**

UUPSUpgradeable.sol uses the same implementation slot as ERC1967 which goes agains ERC1822 specification

"However, rather than forcing use of a variable, the address of the Logic Contract is stored at the defined storage position keccak256("PROXIABLE"). This eliminates the possibility of collision between variables in the Proxy and Logic Contracts, thus providing “universal” compatibility with any Logic Contract."

**Comment by frangio** [comment]
We are not following ERC-1822 strictly, but the change we made is compatible in the sense that the return value of `proxiableUUID` is equal to the slot being used. This means that an ERC-1822 contract would not be confused about whether an implementation is compatible with itself, when inspecting the value of `proxiableUUID`. We had the intention to propose this as a change to ERC-1822.

We see value in using the storage slot defined in ERC-1967 for this purpose.

**Comment by RenanSouza2** [comment]
Makes sense, thanks
