### ISSUE TITLE
contracts/utils/math: replace "if (A && B)" to save gas fees

### ISSUE THREAD

**Issue by BurtonQin** [OpenZeppelin/openzeppelin-contracts#4404]
The solidity compiler generates more code for “if (A && B) {}” than for “if (A) {if (B) {} }”.
Our experiment shows that switching from “if (A && B) {}” to “if (A) {if (B) {} }” can save gas fee.

**💻 Environment**

master branch

**📝 Details**

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/874c2d3c02ec1bce6af9a30bc828d3fe2079136b/contracts/utils/math/Math.sol#L217-L223

Replacing the following code snippet
```
        if (rounding == Rounding.Up && mulmod(x, y, denominator) > 0) {
            result += 1;
        }
```
with
```
       if (rounding == Rounding.Up) {
            if (mulmod(x, y, denominator) > 0) {
                result += 1;
            }
       }
```

can save gas fees and does not hurt code readability.

**🔢 Code to reproduce bug**

**Comment by SensationalShubham** [comment]
I want to work on this issue

**Comment by frangio** [comment]
How much gas? What compiler settings show these results? We need more information.

Have you reported this to the Solidity repository?
