### ISSUE TITLE
Remove Interfaces files from docs

### ISSUE THREAD

**Issue by RenanSouza2** [OpenZeppelin/openzeppelin-contracts#4427]
as discussed during this PR https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4358 , it would be nice to remove interfaces from the readme files

The only ones I suggest keeping are the ones in the 'interfaces' folder and IERC<...>Metadatas

**Comment by frangio** [comment]
There is some more discussion about this #4421, and #3505 is potentially related.

**Comment by RenanSouza2** [comment]
Oh, good to know, thanks
