### ISSUE TITLE
ERC20 permit() should not increment nonce!

### ISSUE THREAD

**Issue by jellohouse** [OpenZeppelin/openzeppelin-contracts#4429]
Why does the nonce increment every time a contract uses a permit?

Consider the case where i sign a permit for a contract to use 10000 of my token X within a deadline of 1 year.
(Maybe it's a bid on an NFT for example)

The next day I go on a different dApp sign a permit for the same token X and the dApp uses it immediately.

Now the permit i had signed before (which was valid for a year) is suddenly invalid.

----

I think the _useNonce  function should be turned public and it is up to the user to call it if he wants to cancel all his previously signed permits.

To me this would make a lot more sense.
Or am i misunderstanding something?

**Comment by frangio** [comment]
Nonces exist to make signatures non-replayable. They need to be discarded once they're used.

The problem you describe is real though but it's a limitation of ERC-2612 (the permit spec).

There have been [proposals to fix this](https://github.com/amxx/permit#out-of-order-execution) but they should be standardized before being implemented.
