### ISSUE TITLE
Can we update Remapping details while working with Foundry

### ISSUE THREAD

**Issue by worksofallwin** [OpenZeppelin/openzeppelin-contracts#4439]
**🧐 Motivation**
While working with foundry, if we copy the below code from ReadMe, it will say file not found
```
import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
```

**📝 Details**
Since the file is not found, it may be confusing for some developers.
So, can we give the  remappings example in Readme? 

Note: Only while working with Foundry
```
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
```

Then, 
```
import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
```

If this will help few devs, then I would like to make this changes.

**Comment by frangio** [comment]
It makes sense to include the remapping in the README instructions for Foundry. Feel free to submit a PR.
