### ISSUE TITLE
Change _approve argument name in ERC721

### ISSUE THREAD

**Issue by RenanSouza2** [OpenZeppelin/openzeppelin-contracts#4457]
In the functions approve and _approve in the ERC20 the areguments are (address to, uint tokenId). I suggest to change the name of the arguments to (address spender, uint tokenId) to be more intuitive.

PS: the name used in the EIP is _approved but I find this confusing because approved could be the agent approved to transfer or the token that is being approved

**Comment by naveed949** [comment]
@RenanSouza2 sorry but are you sure you're referring to right arguments ? I see no function in ERC20 has arguments `(address to, uint tokenId)` 

- `approve` -> `(address spender, uint256 value)`
- `_approve` -> `(address owner, address spender, uint256 value)`
- `transfer` -> `(address to, uint256 value)`

**Comment by RenanSouza2** [comment]
I really need to work in the clarity of my texts

The suggestion in case in in the ERC721.sol file that has the following functions

```
    /**
     * @dev Approve `to` to operate on `tokenId`
     *
     * Emits an {Approval} event.
     */
    function _approve(address to, uint256 tokenId) internal virtual
```

```
    /**
     * @dev See {IERC721-approve}.
     */
    function approve(address to, uint256 tokenId) public virtual
```

**Comment by ernestognw** [comment]
I also agree the name in the EIP is not better than what we have, but since it's already not the same as in the EIP, I'd be fine with having `operator` instead of `better` because I think it's more generalized and aligned with the custom errors.

Another alternative would be to use `_approved` in the interface but `_operator` in the implementation so that the interface matches the EIP

**Comment by RenanSouza2** [comment]
'operator' is a good one, I'll just wait the refactor to be mergerd and then I'll open an PR if it is not yet changed

**Comment by RenanSouza2** [comment]
It was decided to keep the previous names, the comment in PR has more details
