### ISSUE TITLE
ERC20Capped : do not make _cap private

### ISSUE THREAD

**Issue by SvenMeyer** [OpenZeppelin/openzeppelin-contracts#4459]
I would like to create a token which has 2% inflation per year, based on `ERC20Capped`
I would still use the `_cap` which is initialzed in `ERC20Capped` but would then override `cap()`
Surprisingly, i can not access `_cap` to do the math.

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

// import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Capped.sol";
import "@openzeppelin/contracts/security/Pausable.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";



contract COIN is ERC20Capped, AccessControl {
    bytes32 public constant MINTER_ROLE   = keccak256("MINTER_ROLE");

    uint256 public constant SECONDS_PER_YEAR = 36525 days / 100;
    uint256 public constant INFLATION = 2000; // 2.000 %
    uint256 public immutable DEPLOYMENT_TIME;

    constructor() ERC20("inflationary COIN", "COIN") ERC20Capped(100000000) {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(MINTER_ROLE, msg.sender);
        DEPLOYMENT_TIME = block.timestamp;
    }

    /**
     * @dev Returns the cap on the token's total supply
     * @dev ERROR : _cap not accessible here ! - TODO
     */
    function cap() public view override returns (uint256) {
        return _cap + _cap * (block.timestamp - DEPLOYMENT_TIME) * INFLATION / SECONDS_PER_YEAR / 100 / 1000;
    }

    function mint(address to, uint256 amount) public onlyRole(MINTER_ROLE) {
        _mint(to, amount);
    }
}
```

**Comment by frangio** [comment]
See "All state variables should be private" in [GUIDELINES.md](https://github.com/frangio/openzeppelin-contracts/blob/update-guidelines-security/GUIDELINES.md#solidity-conventions).

You can use `super.cap()` getter or you can copy-paste the contract since it's very simple.

**Comment by SvenMeyer** [comment]
As I prefer to make the upgrade to v5 as easy as possible, I went with your suggestion to use `super.cap()` .. thanks for that !

```solidity
    import { ERC20, ERC20Capped } from "@openzeppelin/contracts/token/ERC20/extensions/ERC20Capped.sol";
~~~~~~~~~~
    function capAt(uint256 t) public view returns (uint256) {
        uint256 initialCap = super.cap();
        if (t < DEPLOYMENT_TIME) return 0;
        return initialCap + ((initialCap * (t - DEPLOYMENT_TIME) * INFLATION) / SECONDS_PER_YEAR / 100 / 1000);
    }

    /**
     * @dev Returns the cap on the token's total supply
     */
    function cap() public view override returns (uint256) {
        return capAt(block.timestamp);
    }
```

**Comment by barakman** [comment]
You are losing quite a bit of precision here; you may as well do something like:
```
return (initialCap * ((t - DEPLOYMENT_TIME) * INFLATION + FACTOR) / FACTOR;
```
Where the value of `FACTOR` is `SECONDS_PER_YEAR * 100 * 1000`.

**Comment by barakman** [comment]
BTW, it is not really clear why you use both 100 and 1000 in `/ 100 / 1000`.

You should be using only the value which represents the resolution of `INFLATION`, for example:
- If `INFLATION = 25` denotes 25%, then you should use 100
- If `INFLATION = 25` denotes 2.5%, then you should use 1000

**Comment by SvenMeyer** [comment]
@barakman Thanks for the suggestions ... I was actually aware of the precision problem, thus I do all the multiplications first and then divide at the end. I was thinking about doing it as you suggested, but thought (think) it does not make any difference as the compiler would do it, in my case it would not make any difference, and it work be more readable ... :thinking: 

As we are dealing with integer math the `1000` is just to allow fractional percentage with 3 fractional digits , like 1234/1000 = 1.234% , while the `100` does the "percentage thing" 2% = 2/100
I was hoping if I write it that way, that it would be clear(er)

**Comment by SvenMeyer** [comment]
Maybe a good idea anyway ... ;-)

```solidity
return initialCap + ((initialCap * INFLATION * (t - DEPLOYMENT_TIME)) / (SECONDS_PER_YEAR * 100 * 1000));
```

**Comment by barakman** [comment]
> thus I do all the multiplications first and then divide at the end

Not in your original code:
```
return initialCap + ((initialCap * (t - DEPLOYMENT_TIME) * INFLATION) / SECONDS_PER_YEAR / 100 / 1000);
```
First of all, you are dividing 3 times instead of just 1 time.

Second, you are not doing it at the end of the computation (despite the fact that it appears at the end of the line).

In the line above, the last operation to take place is the addition operation, between these two intermediate values:
- `initialCap`
- `((initialCap * (t - DEPLOYMENT_TIME) * INFLATION) / SECONDS_PER_YEAR / 100 / 1000)`

**Comment by barakman** [comment]
> Maybe a good idea anyway ... ;-)
> 
> ```solidity
> uint256 public constant INFLATION = 2000; // 2.000 %
> ~~~~~~~~~~~~~~~~~~~~~~~~~~
> return initialCap + ((initialCap * INFLATION * (t - DEPLOYMENT_TIME)) / (SECONDS_PER_YEAR * 100 * 1000));
> ```

And as I've mentioned [above](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4459#issuecomment-1636710386), it is not clear why you divide by both 100 and 1000.

Per your example, it seems that the resolution of `INFLATION` (the value of 1 unit) is 0.1%, or equivalently - 0.001.

So you should divide only by `1000`, and not by `100 * 1000`.

**Comment by SvenMeyer** [comment]
> Not in your original code:

`(initialCap * (t - DEPLOYMENT_TIME) * INFLATION)`

that was I was referring to ... so multiplications happen here first
then we do the division (udated as you suggested)
then adding the "base" `initialCap`

I think the math is ok (my test confirm that)
If I want to add 2% to x
`x * 1.02`
`x + 0.02 * x`
`x + 2000 / 1000 / 100 * x`

**Comment by barakman** [comment]
Please read the comment above this one again (I've expanded it, to address some more of your previous claims).

To put it short:
1. The last arithmetic operation in `x + 2000 / 1000 / 100 * x` is `+`
2. If your `INFLATION` resolution is 0.1%, then you should divide by 1000, not by 100, and most certainly not by both
