### ISSUE TITLE
ERC1155 emits TransferBatch event for empty ids and values arguments

### ISSUE THREAD

**Issue by atapin** [OpenZeppelin/openzeppelin-contracts#4461]
If we look at the implementation of `_update` function, we see that it allows emission of a non-sense event when the `ids` and `values` are empty: 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/121be5dd09caa2f7ce731f0806b0e14761023bd6/contracts/token/ERC1155/ERC1155.sol#L176-L182

Even though the standard only requires for length equality for `_mintBatch` and `_burnBatch`, it seems the `TransferBatch` is redundant. Moreover, [the for-loop](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/121be5dd09caa2f7ce731f0806b0e14761023bd6/contracts/token/ERC1155/ERC1155.sol#L156C10-L156C10) prevents any changes of state for these empty values.

The example of a real world TX with this behavior: https://goerli.etherscan.io/tx/0xa6ad6588edb4abd8ca45f30d2f026ba20b68a3002a5870dbd30cc3752568483b#eventlog

Should we revert the transaction and apply stricter requirements of non-emptiness of `ids` and `values`? Or should we just skip the event-emitting logic for empty arrays?

**Comment by Amxx** [comment]
> Should we revert the transaction and apply stricter requirements of non-emptiness of ids and values? Or should we just skip the event-emitting logic for empty arrays?

That is a good question. I'd personnaly not revert, because I see that as a no-op rather than an error. Not emitting an event is an interresting proposal though.

**Comment by atapin** [comment]
@Amxx yes, I agree that a no-op is the way to go here. I'll prepare a PR if no other objections

**Comment by ernestognw** [comment]
I'm personally in favor of making this change but this is also breaking for indexers. I still don't think it's actually breaking anything.

The conversation about reverting or allowing NOOPs is another issue imo.

Also asking for input from @frangio

**Comment by atapin** [comment]
@ernestognw @frangio do you folks think any steps should be taken here?

Generally, this behavior doesn't break anything. But from my personal experience, sometimes a developer of an indexer has to handle this edge case, which seems to be a redundant effort. As NOOP things are not expected to emit events.

**Comment by frangio** [comment]
In what sense is this an edge case for indexers? I would expect it to be trivially handled correctly, resulting in zero changes to balances and ownership.

In fact, I would argue that only with the suggested change empty arrays become an edge case, in which `safeBatchTransferFrom` doesn't emit an event, which you would otherwise expect for all invocations of the function.

I suggest to keep this simple and emit the event unconditionally.

> As NOOP things are not expected to emit events.

I don't think this is true because tokens can emit `Transfer` events with value=0.

**Comment by atapin** [comment]
@frangio I see your points. Let's close this ticket then.
