### ISSUE TITLE
Outdated comments on `AccessControl` contract

### ISSUE THREAD

**Issue by nicolasgarcia214** [OpenZeppelin/openzeppelin-contracts#4470]
The [`onlyRole`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f347b410cf6aeeaaf5197e1fece139c793c03b2b/contracts/access/AccessControl.sol#L67) modifier and the [`_checkRole`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f347b410cf6aeeaaf5197e1fece139c793c03b2b/contracts/access/AccessControl.sol#L103) function have comments referring to a standardized way to present the error messages using a regular expression. However, since the library adopted custom errors these comments should be updated.

**Comment by ernestognw** [comment]
I agree both of these require an update to the docs, thanks for reporting @nicolasgarcia214. I think this is very straightforward for anyone wanting to submit a PR

**Comment by Rahul-Prasad-07** [comment]
Hey 👋
I am interested in contributing to this issue and would be more than happy to work on updating the comments in the codebase to reflect the current error handling mechanism using custom error contracts. I believe this is an essential improvement to make the codebase more maintainable and user-friendly.

If you agree that this issue requires attention, I kindly request your approval to start working on it. Please let me know if it's alright for me to proceed, and if there are any specific guidelines or preferences you'd like me to follow during the process.

Thank you for your time, and I look forward to your response.

**Comment by ernestognw** [comment]
Hey @Rahul-Prasad-07, sure thing, you can take it.

If you need a bit more context why this change is needed, take a look at #4261, the regex is for the previous error message we had, which doesn't apply anymore.

**Comment by Rahul-Prasad-07** [comment]
> Hey @Rahul-Prasad-07, sure thing, you can take it.
> 
> If you need a bit more context why this change is needed, take a look at #4261, the regex is for the previous error message we had, which doesn't apply anymore.

Sure, Thanks 👍
