### ISSUE TITLE
Include custom errors in documentation

### ISSUE THREAD

**Issue by ernestognw** [OpenZeppelin/openzeppelin-contracts#4477]
### Description

After OpenZeppelin Contracts 5.0 and with the addition of custom errors, there are some use cases of listing the custom errors in the documentation. We should consider adding them to the docs in a (maybe) similar way to how we show events docs.

**Comment by frangio** [comment]
This needs to be addressed by modifying the template [contract.hbs](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/docs/templates/contract.hbs).

**Comment by allwin199** [comment]
If you are looking for someone to work on it, I will be happy to help!
