### ISSUE TITLE
Add directions to install using foundry in documentation

### ISSUE THREAD

**Issue by allwin199** [OpenZeppelin/openzeppelin-contracts#4491]
**🧐 Motivation**
https://docs.openzeppelin.com/contracts/4.x/#install

**📝 Details**
Installation directions for `npm` is present.
Installation directions to `foundry` can be added.

**Comment by allwin199** [comment]
I am open to contribute.

**Comment by frangio** [comment]
Thanks @allwin199. I've opened a PR.
