### ISSUE TITLE
 Named arguments can be used  in mapping types in ERC20

### ISSUE THREAD

**Issue by allwin199** [OpenZeppelin/openzeppelin-contracts#4493]
**🧐 Motivation**
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/d6b63a48ba440ad8d551383697db6e5b0ef84137/contracts/token/ERC20/ERC20.sol#L39-L41

**📝 Details**
The Above lines can be changed to this.
```
mapping(address owner => uint256 value) private _balances; 
```
```
mapping(address owner => mapping(address spender => uint256 value)) private _allowances; 
```

**Comment by allwin199** [comment]
I am open to contributing.

**Comment by Amxx** [comment]
This is already addressed by #4433

**Comment by Amxx** [comment]
Duplicate of #4343

**Comment by allwin199** [comment]
oh sorry! didn't notice.
