### ISSUE TITLE
Refactor ERC721 documentation

### ISSUE THREAD

**Issue by allwin199** [OpenZeppelin/openzeppelin-contracts#4500]
**📝 Details**
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fa680739e9c29e18670d44ae47dc1bc49de95629/contracts/token/ERC721/ERC721.sol#L238-L245

`tokenId` is required, but doc says `tokenId` must not exists.
It is kinda confusing.
Let me know if am missing something.

**Comment by allwin199** [comment]
If this has to be refactored, I can raise a PR.

**Comment by Amxx** [comment]
The requirement means that "the NFT with tokenId must not currently exist". Here exist means "having an owner that is not 0". Said otherwize, the token must not have been prevously minted, or it must have been burnt and not yet re-minted.

How would you say it?

**Comment by Amxx** [comment]
I'll check with the team if they fell like there can be an ambiguity between the parameter and the token itself.
