### ISSUE TITLE
The _update method in ERC721 contains an explicit delete of the approval

### ISSUE THREAD

**Issue by vladyan18** [OpenZeppelin/openzeppelin-contracts#4547]
I mentioned it in a comment: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4377#issuecomment-1692045182
Now I'm opening an issue so that the discussion is not lost

**📝 Details**

I find this line causing some inconvenience:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/9e3f4d60c581010c4a3979480e07cc7752f124cc/contracts/token/ERC721/ERC721.sol#L254

Taking into account the fact that both the process of [approving ](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/9e3f4d60c581010c4a3979480e07cc7752f124cc/contracts/token/ERC721/ERC721.sol#L399) and [getting an approved address](_getApproved) are placed in separate virtual functions and can be overriden. In this case, if the internal mechanism is somehow replaced, the above line will remain (or you need to redefine the entire `_update `function), creating unnecessary gas waste.

At the same time, there are projects that really redefine the approval logic (and storage), for example:
https://github.com/Uniswap/v3-periphery/blob/6cce88e63e176af1ddb6cc56e029110289622317/contracts/NonfungiblePositionManager.sol#L395-L399

As mentioned in the discussion, this implementation (explicit delete in `_update`) arose because [OZ used to do _approve(address(0), tokenId);](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.7/contracts/token/ERC721/ERC721.sol#L341) but this was changed to avoid emiting the Approval event (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4377#issuecomment-1692053310).

In fact, such an unnecessary storage slot touch can indeed be avoided if the `_update` function is completely overriden in its implementation. This solves the problem, albeit in a somewhat uncomfortable way in my opinion.

On the other hand, ERC20 takes a different approach in similar circumstances (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4377#issuecomment-1692131099) : https://github.com/OpenZeppelin/openzeppelin-contracts/blob/9e3f4d60c581010c4a3979480e07cc7752f124cc/contracts/token/ERC20/ERC20.sol#L338-L349C6

**Comment by vladyan18** [comment]
UPD: it looks like it will be impossible to override `_update` in your own contract without headache - balances and other state variables are private.

**Comment by frangio** [comment]
> it looks like it will be impossible to override `_update` in your own contract without headache - balances and other state variables are private.

Yes this is expected.

Proposing a fix in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4552.
