### ISSUE TITLE
Remove deprecated `ERC20FailedDecreaseAllowance` error

### ISSUE THREAD

**Issue by trevorgjohnson** [OpenZeppelin/openzeppelin-contracts#4598]
With the inclusion of https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4585, `increaseAllowance` and `decreaseAllowance` was removed. 

This just leaves 1 custom error that is related that now removed functionality.

![image](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/27569194/3297043e-269e-4374-b34c-af6018f59db0)

**Comment by frangio** [comment]
Thanks this is correct. Do you want to submit a PR?

**Comment by trevorgjohnson** [comment]
> Thanks this is correct. Do you want to submit a PR?

Yep! This issue should be resolved with #4604
