### ISSUE TITLE
Util function for converting an address to checksummed string

### ISSUE THREAD

**Issue by Y5Yash** [OpenZeppelin/openzeppelin-contracts#4633]
🧐 **Motivation**
Some applications might need to have the checksummed address be converted to string. In my usage for instance, I need to send some tokens to an address whose hash was committed earlier, so I need the checksummed string.

📝 **Details**
Implement EIP-55 to get the checksummed string corresponding to the address. (I have already implementated for my application on finding no short cut online. More people may need this.)

Some old discussion on this:
https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2197#issuecomment-631005323

**Comment by Y5Yash** [comment]
https://github.com/Y5Yash/openzeppelin-contracts/commit/a77889b8c4c63b6f05e9b8bf3bba2b9384cf6c6d

added a function for the above functionality here. Let me know what you guys think; I'll add tests and raise a PR if this is ok.

**Comment by Amxx** [comment]
Marking that as idea/candidate for 5.1

**Comment by Y5Yash** [comment]
Any updates regarding this idea/candidate? I will be happy to contribute if needed.
