### ISSUE TITLE
Document event changes for ERC1155 batch transfers in 5.0

### ISSUE THREAD

**Issue by TrejGun** [OpenZeppelin/openzeppelin-contracts#4656]
ERC1155 does not emit TransferSingle/TransferBatch on mint/mintBatch
this is expected behavior because v4 does it as well as it is mentioned in specification

https://eips.ethereum.org/EIPS/eip-1155#specification

**Comment by TrejGun** [comment]
sorry you are right TransferSingle works fine, it is only TransferBatch not being sent. I will prepare tests by monday

**Comment by frangio** [comment]
The tests also show that TransferBatch is emitted. This is a pretty serious claim, please provide reproduction as soon as possible.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/3e6c86392c97fbc30d3d20a378a6f58beba08eba/test/token/ERC1155/ERC1155.test.js#L86-L99

**Comment by TrejGun** [comment]
Ok, so I was migrating my code and tests from v4 to v5. No logic is changed


```
git clone git@github.com:GemunIon/contracts.git
git checkout oz-v5
npm I
npm run bootstrap
cd contracts/erc1155
npm t
```

uncomment skipped test at
https://github.com/GemunIon/contracts/blob/oz-v5/contracts/erc1155/src/base/mintBatch.ts#L21

This is not a minimal reproduction example because you asked to show the bug asap. if you would like to have MRE, please tell me

**Comment by frangio** [comment]
Ok, I think I know what you're observing.

When you invoke `transferBatch`, if the arrays are contain a single element (in your example `[tokenId], [amount]`), the event that is emitted will be `TransferSingle` and not `TransferBatch`. This is why `expect(tx).to.emit(contractInstance, "TransferBatch")` is not finding an event.

Note that this behavior is fully compliant with [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155), so I will close the issue as resolved.

**Comment by frangio** [comment]
Reopening to document in the changelog.

**Comment by TrejGun** [comment]
thanks for explanation, you did a great job on optimization
