### ISSUE TITLE
Error during using the OpenZeppelin libraries

### ISSUE THREAD

**Issue by ParsaAminpour** [OpenZeppelin/openzeppelin-contracts#4668]
Hi
Recently, when I wanted to use OpenZeppelin smart contracts in my contract, Brownie couldn't compile the OpenZeppelin contracts, and this error occurred:

> 'UsingForDirective' object has no attribute 'typeName'

I had no issues with the other external smart contracts that I utilized.
But whenever Brownie wants to compile OpenZeppelin, this error appears.

Also, when I reinstalled this package, the Brownie showed this error, too,

> Unable to compile `OpenZeppelin/openzeppelin-contracts@4.9.2` due to an `AttributeError `- you may still be able to import sources from the package, `but will be unable to load the package directly`.

I was stuck in this error for almost two days.
Please help me to solve this issue.
Thanks.

**Comment by ernestognw** [comment]
Hey @ParsaAminpour, this seems to be an error in Brownie. It seems to be internally traversing the Solidity AST and looking for the attribute `typeName` in the `UsingForDirective`, which is [optional](https://solidity-ast.netlify.app/interfaces/usingfordirective#typeName).

The reason why you don't see this error might be related to the usage of `using * for *` directives in the library.
I suggest to look for guidance in the [Brownie repository](https://github.com/eth-brownie/brownie/issues) or you may try to look for help in our [support forum](https://forum.openzeppelin.com)
