### ISSUE TITLE
Documentation links to non-existing contract

### ISSUE THREAD

**Issue by gianmarcotoso** [OpenZeppelin/openzeppelin-contracts#4673]
When reading https://docs.openzeppelin.com/contracts/5.x/utilities#payment there is a link to a `PaymentSplitter` contract that no longer exists. Moreover, the rationale for removing this contract or the `PullPayment` contract are not documented anywhere.

**💻 Environment**

**📝 Details**

The rationale for these code removals is not properly documented in the changelog, and I wasn't able to find the motivation for removing this code anywhere else, nor a valid alternative approach.

**🔢 Code to reproduce bug**

**Comment by Amxx** [comment]
Thank you @gianmarcotoso for raising this.

**Comment by gianmarcotoso** [comment]
Thank you for taking the time to fix it. 

May I ask about the rationale for the removal of the contracts? I am particularly interested in the `PullPayment` contract because, as far as I know, the pull pattern for payments should still be preferred to a push implementation as it prevents funds being locked by a misbehaving contract on the other end of the transfer or a malicious contract "forcing" a badly written auction contract to grant it the auction by not allowing higher bids.

One contract I am working on used the `PullPayment` contract from v4 and after updating to v5 I've had to reimplement it myself. Not a big deal, of course, but still an unexpected bump in the road with no motivation to be found.

**Comment by Amxx** [comment]
Here are some elements

- The escrow only supported Eth, not ERC20. This looked like a limitation that could lead to errors, and lost tokens
- This indirectly affect PullPayment, that relies on the escrow
- The usage of this contract is extremelly low, and its only used by advanced users that can import it from 4.9 or reimplement it
- That is code we ahve to maintain, provide security for, ...

In the end, we did not fell like it was a good idea to carry that code to 5.0, and commit to maintain it until at least 6.0. Depending on the need / request, we may reintroduce it in a better way in an upcomming minor version.

If your are missing it, please open an issue documenting your needs so we can discuss the best way to address them, and the right feature-set for a new version of this design.

**Comment by gianmarcotoso** [comment]
Thanks for the explanation. I do miss it, but nothing has stopped me from reimplementing it without using the escrow contract. Your logic is sound, I agree that the maintenance cost is not justified if most users do not use it; I would have maybe added these bullet points in the changelog to avoid confusion, but that' me :)

Thanks again, I think we can close this!

**Comment by dogukanakkaya** [comment]
I had the same confusion with `PullPayment`, I've been using it for some of my projects and I needed it again now, to find out it's no longer in OpenZeppelin v5. Docs has a lot of other contracts like that `Counters` is one of them. I had to go my way through the issues to check out what's the change.

I think it'd be a good idea to provide better documentation about how to keep functionality of those removed contracts.

**Comment by omegabyte** [comment]
Guys, seriously? if you remove a contract at least point it out in the changelog! Lost an hour on this. Do better
