### ISSUE TITLE
Use unchecked block for counter in loop

### ISSUE THREAD

**Issue by AntonGulak** [OpenZeppelin/openzeppelin-contracts#4704]
For example, instead of https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/ERC1155.sol#L85

implement the loop like this

```
 for (uint256 i = 0; i < accounts.length;) {
            batchBalances[i] = balanceOf(accounts.unsafeMemoryAccess(i), ids.unsafeMemoryAccess(i));
            unchecked {
               ++i;
            }
        }
```

Because the array length cannot exceed uint256, we don't need to check for overflow.

Also found a few options for gas optimization

1) https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/finance/VestingWallet.sol#L71

 uint64 _start and uint64 _duration cannot overflow uint256

2) https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Multicall.sol#L18

To optimize gas usage, use prefix increment instead of postfix increment. Also, it can be moved to an unchecked block.

**Comment by Amxx** [comment]
Hello @AntonGulak 

This was already proposed, and we decided to not implement this change for the following reasons:
- We feel that this syntax reduces readability of the code, by moving some of the `for` logic to some place where it does not belong. As a consequence, it makes review and audit more painfull, and contributes negativelly to the security of the system.
- This is a optimisation that the compiler should take care of. We believe in writting clean high level code, that gets compiled to efficient bytecode. That has been my goal when writting C/C++ for HPC 10 years ago, and its still my goal today writting solidity

[Note that this was just merged by the solidity team, and it should be in the next release (0.8.22)](https://github.com/ethereum/solidity/pull/13378)

My personnal opinion is that writting for loops like that is some trend, that people do to look smart (not saying they are not, but definitelly not for that reason) ... trying to save singular units of gas in places where its not meaningfull at all. I wish all the effort spent on rewritting codebases that way, and sharing these "tricks" on social media  would have been put toward improving the compiler.

**Comment by Amxx** [comment]
> I currently expend an additional 6800 gas for 100 cycles in your multicall

My best guess is that the 100 cycles are not in one single transaction. Even if that is the case, what is the cost of each subcall? You are talking about 68 gas per (sub)-call. I also expect each subcall to somehow similar to an ERC20 transfer, so 50k~60k gas each.

You are taking 6800 gas on something that is probably a +5M gas transaction. I'd bet that you are wasting significantly more gas for duplicated calldata for the subcall that for the increment.

Also, about prefix/postfix : `++i` and `i++` should be strinctly equivalent when the returned value is discarded. If its not then its the compiler that should fix that, not us ... and that is for one good reason: We do not plan on constantly changing our codebase to try and match the behavior of the compiler at a given point in time, considering that this behavior changes depending on the settings, and depending on the version our user uses.

If you ask me:
- we should write simple and clean code
- user should use the latest (or at least a recent) version of the compiler
- the compiler should do a good job at optimising things.

I understand that point 2 and 3 may not be where we are today
- Some contract are compiled with old compiler, some contract don't even have optimizations turned on [thinking of things like this](0xdac17f958d2ee523a2206206994597c13d831ec7)
- There is a drastic lack of funding for compiler work ... People spend more energy bashing it then working on it ... go figure
... but that is not going to have us deviate from point 1 ... particularly considering this whole think will be history in a few weeks/months
