### ISSUE TITLE
Use param instead of a fixed value in event

### ISSUE THREAD

**Issue by vittominacori** [OpenZeppelin/openzeppelin-contracts#4706]
It should not be better (logically speaking) to use the wrong `initialOwner` param in event instead of force using `address(0)`?

It always will be `address(0)` in that case but I would use the param instead.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/2ec2ed96950a6f67a83ea72596bb464b5f4ebd88/contracts/access/Ownable.sol#L39-L41

Also applies here https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol#L86

**Comment by JayeshShukla** [comment]
Hi @vittominacori, what should I name the parameter, let me know one of the following :

address emptyAddress = address(0);
address burnAddress = address(0);
address deadAddress = address(0);

**Comment by Amxx** [comment]
Hello @vittominacori 

AFAIK, the reason we do
```solidity
if (initialOwner == address(0)) {
    revert OwnableInvalidOwner(address(0));
}
```
instead of 
```solidity
if (initialOwner == address(0)) {
    revert OwnableInvalidOwner(initialOwner);
}
```
is because the first one is cheaper. At least it used to be, and I'm guessing `PUSH0` it re-enforcing that. Sure it should be the same ... but the truth is how you get the 0 value actually as an impact.

**Comment by ernestognw** [comment]
Seems solved. Closing
