### ISSUE TITLE
Version 5.0.0 ERC721.safeTransferFrom trying to override non-virtual function.

### ISSUE THREAD

**Issue by quiet-node** [OpenZeppelin/openzeppelin-contracts#4709]
So I have updated @Openzeppelin/contracts from v4.x to the latest v.5.0.0, and when I compile the contracts using `forge build`, I got this error

```bash
Error (4334): Trying to override non-virtual function. Did you forget to add "virtual"?
   --> node_modules/@openzeppelin/contracts/token/ERC721/ERC721.sol:152:5:
    |
152 |     function safeTransferFrom(address from, address to, uint256 tokenId) public {
    |     ^ (Relevant source part starts here and spans across multiple lines).
Note: Overriding function is here:
   --> test/foundry/mocks/hts-precompile/HederaNonFungibleToken.sol:141:5:
```

The overriding function at `test/foundry/mocks/hts-precompile/HederaNonFungibleToken.sol:141:5:` is
```solidity
function safeTransferFrom(address from, address to, uint256 tokenId) public override {
    address sender = msg.sender;
    int64 responseCode = HtsPrecompile.preTransfer(sender, from, to, tokenId);
    if (responseCode != HederaResponseCodes.SUCCESS) {
        revert HtsPrecompileError(responseCode);
    }
    return super.safeTransferFrom(from, to, tokenId);
}
```

So as in the error log, here at [this line](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v5.0.0/contracts/token/ERC721/ERC721.sol#L152), it's missing the `virtual`. I was checking around the release note and the PR in which the `virtual` keyword got removed but couldn't find much information. 

Is this a bug or am I using it incorrectly?

**💻 Environment**

@Openzeppline/contracts @ v5.0.0
Foundry

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by ernestognw** [comment]
Hey @quiet-node, you should check out the [other safeTransferFrom function](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/3e6c86392c97fbc30d3d20a378a6f58beba08eba/contracts/token/ERC721/ERC721.sol#L159). We decided to only allow overriding one of them because both rely on the same implementation.

**Comment by quiet-node** [comment]
Hello @ernestognw thanks much for the comment. Just for my own knowledge, how would we use [this function](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v5.0.0/contracts/token/ERC721/ERC721.sol#L152) now without overriding it?

**Comment by ernestognw** [comment]
The function is available if you create a contract that inherits from ERC721.

That function depends on the overload of `safeTransferFrom(from,to,value,data)` so overriding the latter will override both functions

**Comment by quiet-node** [comment]
Wonderful! Thanks @ernestognw!
