### ISSUE TITLE
Error: invalid opcode: opcode 0x5f not defined

### ISSUE THREAD

**Issue by dev-tom-0108** [OpenZeppelin/openzeppelin-contracts#4714]
I have 4 yrs of exp in Solidity and I wrote a smart contract using latest Openzeppelin/contracts and BEP20 libraries basically to make a BEP-20 token.

**💻 Environment**
```
pragma solidity 0.8.19;
```
**📝 Details**

When i try to deploy the smart contract, i get the following error : "invalid opcode: opcode 0x5f not defined" and in my case i know that the OpCode must begin with 0x608.... I found that others had the same issue, but i still can't found the errors in my code.

How can I fix it?

**Comment by ernestognw** [comment]
The `0x5f` is the [PUSH0 opcode](https://www.evm.codes/#5f?fork=shanghai). It was introduced in Shanghai and most likely your compilation settings are targeting a lower EVM version. If you're trying to make a BEP-20 token I'll assume you're targeting BNB Chain and it doesn't support `PUSH0` yet ([this is all I could find](https://forum.bnbchain.org/t/bep-idea-implement-eip-3855-push0-instruction/985)).

> 💻 Environment
> 
> pragma solidity 0.8.19;

Can you double check this? Solidity 0.8.19 doesn't produce the `PUSH0` opcode.

If the issue remains even if targeting an older EVM version, feel free to ask in our [community forum](https://forum.openzeppelin.com/).
