### ISSUE TITLE
ERC721Consecutive scenario of nextid

### ISSUE THREAD

**Issue by mosi-sol** [OpenZeppelin/openzeppelin-contracts#4729]
**🧐 Motivation**
ERC721Consecutive : next id is pain in this scenario. why not use something like snippet in below:
```solidity
function consecutiveTransfer(
        uint256 fromTokenId,
        uint256 toTokenId,
        address fromAddress,
        address toAddress
    ) public {
        require(fromTokenId <= toTokenId, "Invalid token range");

        _consecutiveTransfer(fromTokenId, toTokenId, fromAddress, toAddress);
    }

    function _consecutiveTransfer(
        uint256 currentTokenId,
        uint256 toTokenId,
        address fromAddress,
        address toAddress
    ) private {
        emit ConsecutiveTransfer(currentTokenId, currentTokenId, fromAddress, toAddress);

        if (currentTokenId < toTokenId) {
            _consecutiveTransfer(currentTokenId + 1, toTokenId, fromAddress, toAddress);
        }
    }
```
**openzeppelin v5 make Althing's better to use, but some codes make pain! 
thanks for response from community**

**📝 Details**
[ERC721Consecutive](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7de6fd4a2604764497990bcc0013f95763713190/contracts/token/ERC721/extensions/ERC721Consecutive.sol#L104) - [next id](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7de6fd4a2604764497990bcc0013f95763713190/contracts/token/ERC721/extensions/ERC721Consecutive.sol#L172)

_snippet in above is experimental, i write that just for specific purposes..._

**Comment by ernestognw** [comment]
If I understand correctly, you're asking for supporting consecutive transfers outside of the constructor. However, that makes the ERC721 non-standard, so consecutive mintings can be only performed during construction.

Still, the purpose of the snippet you shared doesn't seem clear. I'm closing, but if this is a feature request, feel free to reopen but provide a clear intention of what you're trying to achieve and why the current setup doesn't allow you to achieve it.

**Comment by mosi-sol** [comment]
the biggest solidity lib closed issue without complete info!

**Comment by ernestognw** [comment]
You're more than welcome to open a new issue with complete info!

**Comment by mosi-sol** [comment]
as soon, with complete codes... c u
