### ISSUE TITLE
Add a findLowerBound function to the Arrays library

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#4744]
Has request by @alanarvelo during DevConnect, we should add a lower lookup function to `Arrays.sol`. This is already available in `Checkpoints` but is missing from `Arrays`.

**Comment by garv-aga** [comment]
Does this issue also require writing test case for the new function?

**Comment by kamuikatsurgi** [comment]
Hey! I can contribute to this, can someone explain me what exactly is needed for the findLowerBound function in Arrays.sol library? @Amxx

**Comment by Amxx** [comment]
@kamuikatsurgi we already have an implementation and are discussing backward compatibility issues.
Thank you for your proposal though

**Comment by kamuik16** [comment]
> @kamuikatsurgi we already have an implementation and are discussing backward compatibility issues. Thank you for your proposal though

Hey @Amxx, any beginner friendly or good first issue I can work on right now?
