### ISSUE TITLE
v4.9.4 multicall twice?

### ISSUE THREAD

**Issue by seinmyung25** [OpenZeppelin/openzeppelin-contracts#4788]
[I think there's a bug!](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/0d5f54e69b2a2058bc98651a2e200f558c84a953/contracts/utils/Multicall.sol#L35)

**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by ernestognw** [comment]
Hey @seinmyung25, this is correct. We detected no downloads in the upgradeable version whatsoever and we just deprecated 4.9.4 with a warning so it won't be available for installation. 4.9.5 was just released replacing it.

Closing

**Comment by malteish** [comment]
Came here to report this, stayed to hail @seinmyung25! Good catch!
