### ISSUE TITLE
ERC20 variables not marked as immutable even though comment suggests

### ISSUE THREAD

**Issue by tbrannt** [OpenZeppelin/openzeppelin-contracts#4806]
Why are the 2 variables `_name` and `_symbol` not declared as immutable as the comment on the constructor function suggests? https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L41-L42

**Comment by DonnieJay11** [comment]
A Ticket has been opened for you.
Talk to a [Openzeppelin Live support agent](https://desks.live/) with ID: D17Y84D64X

Click on the [Live Chat](https://desks.live/) at the bottom corner to initiate chat

**Comment by ashleybelshe** [comment]
You're right that _name and _symbol aren't explicitly declared with the immutable keyword, but I believe the comment states "All two of these values are immutable: they can only be set once during construction," which pretty much explains it. When you only initialize in the constructor & use private accessors, it's basically immutable. I hope that makes sense, feel free to correct me if I'm wrong as well

**Comment by Amxx** [comment]
Hello @tbrannt 

That is because strings are not value types, and only value types can be marked as immutable.
![Capture d’écran du 2023-12-22 21-41-56](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/2432299/62d0eb9a-1569-4d4d-91b5-5153dce64914)
