### ISSUE TITLE
Code don't work at TransparentUpgradeableProxy

### ISSUE THREAD

**Issue by stanta** [OpenZeppelin/openzeppelin-contracts#4809]
Hi, @ernestognw!

At code, you updated:  https://github.com/OpenZeppelin/openzeppelin-contracts/blob/abcf9dd8b78ca81ac0c3571a6ce9831235ff1b4c/contracts/proxy/transparent/TransparentUpgradeableProxy.sol#L79

What did you mean as   ` _admin = address(new ProxyAdmin(initialOwner));` ?
This don't work!
In prev version was:
`  _admin = admin_ (or initialOwner in this version)`

Check, please!

**Comment by ernestognw** [comment]
Hey, we'll appreciate if you provide a reproducible example of how this doesn't work.

From the changelog:

> TransparentUpgradeableProxy: Admin is now stored in an immutable variable (set during construction) to avoid unnecessary storage reads on every proxy call. This removed the ability to ever change the admin. Transfer of the upgrade capability is exclusively handled through the ownership of the ProxyAdmin. (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4354)

**Comment by stanta** [comment]
Sorry, I can't, project under NDA.
 But you can just  switch on  your logic, if have, of course... 
What address will be stored as _admin in your code?

**Comment by ernestognw** [comment]
> But you can just switch on your logic, if have, of course...

Unfortunately, we can't, it's breaking [backwards compatibility](https://docs.openzeppelin.com/contracts/5.x/backwards-compatibility).

> What address will be stored as _admin in your code?

The address of a new ProxyAdmin whose owner is `_initialOwner`. You can find more info in [the docs](https://docs.openzeppelin.com/contracts/5.x/api/proxy#TransparentUpgradeableProxy).

> Sorry, I can't, project under NDA.

Given no example is provided, I'm closing.

**Comment by stanta** [comment]
Now, new address will be address of new ProxyAdmin(initialOwner) )))
you are really programmer? 
please patch code.
