### ISSUE TITLE
ERC721: Do not depend on Strings.sol

### ISSUE THREAD

**Issue by 0xGh** [OpenZeppelin/openzeppelin-contracts#4814]
I noticed that `ERC721.sol` imports `Strings.sol` just to do a single `tokenId.toString()` in the default `tokenURI` implementation.

This results in a lot of unnecessary code being deployed (3 files). Would it be possible to extract the `uint256` to `string` utility to its own file or duplicate it in ERC721.sol?

**Comment by AbhayRai** [comment]
That means we can simply have the toString() Function in ERC721.sol . Instead of the importing the {String} from String.sol . Right ?

**Comment by ernestognw** [comment]
> This results in a lot of unnecessary code being deployed (3 files).

The files are compiled down to bytecode and libraries with internal functions are inlined, so there's no unnecessary code being deployed at all.

> That means we can simply have the toString() Function in ERC721.sol . Instead of the importing the {String} from String.sol . Right ?

Not really, the `.toString()` overload comes from line 20 where the `using Strings for uint256;` is.

I'm closing, but if you still think there's unnecessary code deployed, a good test would be implementing both the current `Strings.sol` and a simplified `Strings.sol` with only the `uint256` method and then comparing the resulted bytecode using the same compilation settings.

**Comment by 0xGh** [comment]
> libraries with internal functions are inlined

@ernestognw got it. Thanks!
