### ISSUE TITLE
Expand used solhint rules

### ISSUE THREAD

**Issue by RenanSouza2** [OpenZeppelin/openzeppelin-contracts#4825]
**🧐 Motivation**

Hey, I was looking into solhint rules and there are ones that may be interesting to use here but I wanted to discuss it before opening an PR

**📝 Details**

'custom-errors',
'explicit-types',
'no-unused-import',

```
contracts/interfaces/IERC1155.sol
  6:9  error  imported name IERC1155 is not used  no-unused-import

contracts/interfaces/IERC1155MetadataURI.sol
  6:9  error  imported name IERC1155MetadataURI is not used  no-unused-import

contracts/interfaces/IERC1155Receiver.sol
  6:9  error  imported name IERC1155Receiver is not used  no-unused-import

contracts/interfaces/IERC165.sol
  6:9  error  imported name IERC165 is not used  no-unused-import

contracts/interfaces/IERC20.sol
  6:9  error  imported name IERC20 is not used  no-unused-import

contracts/interfaces/IERC20Metadata.sol
  6:9  error  imported name IERC20Metadata is not used  no-unused-import

contracts/interfaces/IERC3156.sol
  6:9  error  imported name IERC3156FlashBorrower is not used  no-unused-import
  7:9  error  imported name IERC3156FlashLender is not used    no-unused-import

contracts/interfaces/IERC721.sol
  6:9  error  imported name IERC721 is not used  no-unused-import

contracts/interfaces/IERC721Enumerable.sol
  6:9  error  imported name IERC721Enumerable is not used  no-unused-import

contracts/interfaces/IERC721Metadata.sol
  6:9  error  imported name IERC721Metadata is not used  no-unused-import
```

**Comment by Amxx** [comment]
The "unused" import here are false positive. "fixing" that would be breaking a lot of usages of the repo.

Not sure about the other rules.

**Comment by RenanSouza2** [comment]
solhint accepts a .solhintignore that can be used to ignore all mocks

explicit types enforces things like ´uint256´ instead of ´uint´

**Comment by Amxx** [comment]
> solhint accepts a .solhintignore that can be used to ignore all mocks

That is interresting, but if we do that then no rule is checked on the mocks, right? We would like the other rules to continue running.

An alternative would be to add `// solhint-disable-next-line` were needed, but that feels like a lot.
