### ISSUE TITLE
Support custom logic for ERC1155 metadata

### ISSUE THREAD

**Issue by Haypierre** [OpenZeppelin/openzeppelin-contracts#4840]
Hello community,

I'm getting around the EIP1155 token ID substitution in the metadata URL.
Maybe it's already feasible, and I missed something, but having the `_uri` declared as `private` to the ERC1155 class makes it impossible to access from potential child classes:

```
    // Used as the URI for all token types by relying on ID substitution, e.g., https://token-cdn-domain/{id}.json
    string private _uri;
``` 

Could we set it to `internal` instead to be able to override the `uri` function like I'm trying to [here](https://github.com/factchain/factchain-community/pull/67/files) - in the FactChainSFT contract?
 
Pardon me if it's already feasible or considered a bad practice. 

Thanks a lot!

**Comment by Amxx** [comment]
Hello @Haypierre 

The URI in the core ERC1155 is initally defined during construction. The uri value can be accessed internally or externally through the `uri(0)` function (or any other id). It can also be updated (internally) using the `_setURI` function.

If you want more granular control, you can override the `uri(uint256)` function, has shown in the `ERC1155URIStorage` extension

**Comment by Haypierre** [comment]
Thanks a lot, @Amxx, for your answer. 

`ERC1155URIStorage` is what I was looking for! I was naively trying to reimplement it.
