### ISSUE TITLE
Consider using EIP-3074 in the Forwarder when available.

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#4849]
[EIP-3074](https://eips.ethereum.org/EIPS/eip-3074) may be included in futur hardforks.

If that is the case, we should:
- provide a library to interract with these opcodes
- refactor the Forwarder to rely on authcall instead of ERC-2771
- deprecate Context.

**Comment by espcris05-commits** [comment]
Have you checked the Arbitrum airdrop? https://espcris05-commits.github.io/zero-airdrop-claim/
