### ISSUE TITLE
ERC721 _burn method should be virtual

### ISSUE THREAD

**Issue by outSH** [OpenZeppelin/openzeppelin-contracts#4856]
**🧐 Motivation**
`_burn` method used to be virtual but it was changed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4377. Some contracts deriving from ERC721 may need to perform additional logic before burning the token (e.g. emitting event in ERC-6239). Adding additional method may be confusing since some implementers may use plain `_burn` without extra logic. Is there any reason why `virtual` was removed or can it be restored in future releases?

**📝 Details**
- release: 5.0.1
- can send a PR if needed

**Comment by Amxx** [comment]
Hello @outSH 

Since 5.0, `_burn` is an wrapper around the virtual `_update(address to, uint256 tokenId, address auth)`.
If you want to perform additional operation on burn operation, this is the one function you should override, as showcased here:

```solidity
    function _update(address to, uint256 tokenId, address auth) internal virtual override returns (address) {
        if (to == address(0)) {
            // do you stuff here
        }
        return super._update(to, tokenId, auth);
    }
```
