### ISSUE TITLE
Note on event access in `ERC1967Utils.sol` should be removed

### ISSUE THREAD

**Issue by Sabnock01** [OpenZeppelin/openzeppelin-contracts#4860]
`ERC1967Utils.sol` contains the following comment:
```
    // We re-declare ERC-1967 events here because they can't be used directly from IERC1967.
    // This will be fixed in Solidity 0.8.21. At that point we should remove these events.
```
As of #4325 which transitioned `ERC1967Upgrade.sol` to the library `ERC1967Utils.sol` this note is no longer needed since the interface `IERC1967.sol` is no longer inherited.

I've already prepared a PR to open.

**Comment by Amxx** [comment]
Thank you @Sabnock01 For finding this. Please go ahead and create a PR is you have a branch ready.
