### ISSUE TITLE
Consider adding block.chainid in ERC2771Forwarder transactions

### ISSUE THREAD

**Issue by inmarelibero** [OpenZeppelin/openzeppelin-contracts#4900]
As defined [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/metatx/ERC2771Forwarder.sol#L53C12-L60), the `ERC2771Forwarder.ForwardRequestData structure` does not include any reference to the chain id.

A potential threat could be using a valid signature that produced a valid transaction on another blockchain. I'm not 100% sure it can be done, but given that nothing referred to the chain is used when signing or making the transaction, I assume is theoretically possible.

I'm aware that the probability is very low, considering that:
- `nonce` should be equal
- `deadline` should allow this attach

But I don't see any reason to make it more secure, as OZ is used by many developers in many contexts.

**💻 Environment**

OZ v.5.0
Solidity 0.8.20 (but the same code can be used in past versions)

**🔢 Code to reproduce bug**

Reproducing a bug is very difficult, I hope the above explanation is sufficient.

**Comment by ernestognw** [comment]
Hey @inmarelibero, the ERC2771Forwarder uses EIP712, which already has the [chainId](https://github.com/openzeppelin/openzeppelin-contracts/blob/7bd2b2aaf68c21277097166a9a51eb72ae239b34/contracts/utils/cryptography/EIP712.sol#L72).

I'm closing because it's a non issue, but thanks for flagging.

**Comment by inmarelibero** [comment]
Thanks for the clarification @ernestognw, I should have read better before submitting 👍
