### ISSUE TITLE
transferFrom, approve, safeTransferFrom function are payable function in the ERC721 Standard

### ISSUE THREAD

**Issue by XdpCs** [OpenZeppelin/openzeppelin-contracts#4950]
Can you explain to me the reasoning behind implementing it in this particular way?
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/8cc7f2dcbf368f2a7ea491389dae41f01c16e352/contracts/token/ERC721/ERC721.sol#L159

ref: https://eips.ethereum.org/EIPS/eip-721

**Comment by Amxx** [comment]
Hello @XdpCs 

Please see this discussion #2610

**Comment by Amxx** [comment]
(closing as duplicate, we can continue the discussion in #1015 if needed)
