### ISSUE TITLE
Consider changing `memory-safe` NatSpec annotations to `assembly('memory-safe')` dialect string

### ISSUE THREAD

**Issue by ernestognw** [OpenZeppelin/openzeppelin-contracts#4971]
**📝 Details**

As pointed out by @ZumZoom in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4941#discussion_r1528458911:

> Should it still be a case though? It seems that after merging https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4288 there is little sense in sticking with comment annotation. assembly ("memory-safe") was introduced in 0.8.13 and current pragma on all the contracts is ^0.8.20.

Given that we're not supporting any Solidity older than 0.8.20, it makes sense to  reconsider changing the NatSpec annotations to the new syntax added in Solidity 0.8.13:
https://github.com/ethereum/solidity/pull/12620

**Comment by ZumZoom** [comment]
Regarding the benefits. The only benefit I see is getting ready for solidity 0.9. As stated in the last paragraph of [memory safety conventions docs](https://docs.soliditylang.org/en/v0.8.25/assembly.html#memory-safety) solidity devs are going to remove the support of NatSpec annotations the next breaking release.

**Comment by ernestognw** [comment]
Right, so we'll **have to** make this change before 9.x is released. Not sure when that's going to happen though but I'm adding the 5.x milestone so we tackle it eventually.

**Comment by Amxx** [comment]
With 0.9, I expect we'll have a lot more than that to change. I would not consider "preparing the codebase for 0.9" something we have to do know.

I do prefer the propose notation over natspec. It feels more natural to me to mark the assembly block directly... but that is very personnal.
