### ISSUE TITLE
Codecov result don't show up in the PR summary anymore

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#4977]
When looking at a PR, we get a summary of all the CI that run, with status. This includes `checkl/coverage`.

- This check will fail if any of the unit tests that run during coverage fails (that is the run coverage part)
- Until recently, the action would check if we meet some threshold for coverage, and report that directly in the PR. This is no longer available. 

The result are still produced. We can click to see the details of the codecov action, and get a to the `resultURL`. However, I'm not sure the PR would be blocked if the requirements are not meet (low coverage of new code)

**Comment by ernestognw** [comment]
This is not an issue anymore. Closing
