### ISSUE TITLE
Add library for RSA signature verification

### ISSUE THREAD

**Issue by federicobond** [OpenZeppelin/openzeppelin-contracts#498]
Ethereum's next hard-fork <sup>[1]</sup> will include support for big integer modular exponentiation, which will enable RSA signature verification.

<sup>1</sup> https://blog.ethereum.org/2017/10/12/byzantium-hf-announcement/

**Comment by nventuro** [comment]
While interesting, and certainly something we could add, I'm closing this for now due to a lack of activity (and perceived interest in the feature).

**Comment by spalladino** [comment]
I'm interested in this feature!

**Comment by nventuro** [comment]
@spalladino could you share a bit of detail as to:

a) what sort of capabilities you'd expect from an OpenZeppelin RSA verifier?
b) what use case you're targeting, and why you need RSA as opposed to e.g. ECDSA?

**Comment by frangio** [comment]
Closing due to apparent lack of interest from the community. If there are use cases they may be very niche.

**Comment by MuhammadWaqas4** [comment]
Hi, I need this RSA to get some privacy. ECDSA can be decrypt or decoded. While RSA needs a private key for decoding or reading certain data.

**Comment by frangio** [comment]
Please post the question in the [OpenZeppelin Forum](https://forum.openzeppelin.com/).

**Comment by MuhammadWaqas4** [comment]
Yes for this we can hide the private key in smart contract and leave the public key as open to view
