### ISSUE TITLE
Incorrect link formatting in NatSpec causing broken URLs

### ISSUE THREAD

**Issue by mcorrig4** [OpenZeppelin/openzeppelin-contracts#4982]
I *think* I have found an issue with (many/all) the website links in NatSpec comments. 

Links in comments are formatted like this: 
`https://example.com/[Example Website]`

I think the links should be formatted like this (using markdown styling):
`[Example Website](https://example.com/)`

Apart from named links not appearing as expected in previews, these trialling square brackets are being included as part of the URL, causing links to break when clicked.

---

**💻 Environment**

I am using the latest v5.0.3 @openzeppelin/contracts

I have tested this in:
1. VS Code using the Juan Blanco solidity extension 
2. VS Code using the Nomic Foundation Solidity Extension
3. Remix IDE

System:
- Windows 10
- WSL2 Ubuntu 22.04
- VS Code 1.87.2
- Microsoft Edge browser

--- 

**📝 Details**

I first noticed this in the ReentrancyGuard while trying to read the "Reentrancy After Istanbul" blog post. Clicking the link got a 404 error because the square brackets were included in the link.
![image](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/1342367/730cef6a-d2b2-482e-8ce0-96bf0a3d4b4b)

Making my suggested change improves the experience in both VS Code, and significantly improves the experience in Remix.

| ![image](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/1342367/dfe20bea-b5b2-4bd6-ad97-1b6a893bafdf) |
| :---: |
| *VS Code before & after* |

| ![image](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/1342367/4769a45d-d918-4fd3-b995-9f17c88e7447) |
| :---: |
| *Remix before & after* |

I was going to submit a quick fix PR but, after scanning the repo, it appears all (most?) links are formatted with trailing square brackets, causing this issue. I am happy to fix them all, but I am hesitant to submit a PR before asking here.

---

**🔢 Code to reproduce bug**

Check out [@openzeppelin/contracts/utils/ReentrancyGuard.sol (line: 20)](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/cb2aaaa04a292887c49839cd958b08a83979d746/contracts/utils/ReentrancyGuard.sol#L20)

I am want to make a PR based on this small change: [my commit fix](https://github.com/OpenZeppelin/openzeppelin-contracts/commit/e377cfa9da77c26f1ddce591b9dc17d72a0f09a0
) but I see this change would be required on many files, so I would like feedback before I make all those changes.

**Comment by ernestognw** [comment]
Hey. This is [AsciiDoc syntax](https://docs.asciidoctor.org/asciidoc/latest/macros/links/#urls-and-links), so the links work on the documentation site that's automatically generated:

https://docs.openzeppelin.com

Thanks for raising, but this is the intended behavior.

**Comment by mcorrig4** [comment]
> Hey. This is [AsciiDoc syntax](https://docs.asciidoctor.org/asciidoc/latest/macros/links/#urls-and-links), so the links work on the documentation site that's automatically generated:
> 
> https://docs.openzeppelin.com/contracts/5.x/api/utils#security
> 
> Thanks for raising, but this is the intended behavior. Still, it's interesting how it shows up in Remix, I might consider finding a way to make it work there but I don't see an easy one rn

Thanks for that clarification! I figured it had to be intentional given the prevalence of that format. Would be cool if you could make both work some day!
