### ISSUE TITLE
Mark AccessManagerUpgradeable abstract or implement initializer function

### ISSUE THREAD

**Issue by imlex** [OpenZeppelin/openzeppelin-contracts#5002]
**🧐 Motivation**
I want to use AccessManagerUpgradeable the same way I can use AccessManager contract.

**📝 Details**
It is impossible to use AccessManagerUpgradeable as is right know. It lacks initializer function, so it is not possible to deploy it correctly. And also it is not marked abstract to force implement initializer function in sub-contract.

**Comment by Amxx** [comment]
Hello and thank you for raising that issue.

The upgradeable version of our contract indeed do not expose the initializer by default, which means that before you deploy them, you need to expose it (and compile that).

@ernestognw @frangio I believe all upgradeable contracts should be abstract. WDYT?
