### ISSUE TITLE
UUPSUpgradeable is not ERC1882 (draft) compatible, but rather only ERC1967 compatible.

### ISSUE THREAD

**Issue by yaronvel** [OpenZeppelin/openzeppelin-contracts#5015]
[EIP 1882](https://eips.ethereum.org/EIPS/eip-1822) was never approved, however [UUPSUpgradable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/utils/UUPSUpgradeable.sol#L19) is declared to be compatible to it.
`abstract contract UUPSUpgradeable is IERC1822Proxiable`

However the proxy implementation storage slot is according to EIP1967, which is `the keccak-256 hash of "eip1967.proxy.implementation` and not `keccak256("PROXIABLE")` like dictated by EIP1882.

As EIP1882 is stagnated, maybe it is just best to remove it from your codebase and avoid confusion.

**Comment by ernestognw** [comment]
Hi @yaronvel, quick note:

> [EIP 1882](https://eips.ethereum.org/EIPS/eip-1822) was never approved,

EIPs are not "approved". It's the author's responsibility to finalize them and gather community consensus. EIPs may become stagnant but can be picked up by anyone in the community if they think it's valuable to move it forward.

Now on the issue:

EIP 1822 never enforces the use of `keccak256("PROXIABLE")` as storage location. In fact, the [proxiable specification](https://eips.ethereum.org/EIPS/eip-1822#proxiable-contract) suggests to change it:

> **`proxiable`**
> Compatibility check to ensure the new Logic Contract implements the Universal Upgradeable Proxy Standard. Note that in order to support future implementations, the bytes32 comparison could be changed e.g., keccak256("PROXIABLE-ERC1822-v1").

The storage location is thought to not collide with regular storage locations derived by Solidity variables. However, EIP-1967 has shown a better rationale for this, and similarly for [EIP-7201](https://eips.ethereum.org/EIPS/eip-7201), so using any of both is still within the EIP-1822 boundaries.

> As EIP1882 is stagnated, maybe it is just best to remove it from your codebase and avoid confusion.

Being stagnant doesn't mean is not still useful and widely adopted. 
Would you mind clarifying how you think this is confusing and if it's causing an issue to our users?
