### ISSUE TITLE
I Can't verified contract in Coredao

### ISSUE THREAD

**Issue by vein451** [OpenZeppelin/openzeppelin-contracts#5022]
I was trying to verifiy contract in remix plug in, but when im trying to paste the API Key of Coredao it says need 34 characters long. Anyone help me to solve this problem? Which i've done wrong? help me to verify contract
![da](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/108234086/37a6a078-9ebc-4bce-822a-a055d83b271d)

**Comment by ernestognw** [comment]
This is related to [Remix](https://github.com/ethereum/remix-project) or Etherscan but not OpenZeppelin.

Closing. Feel free to ask for help in our community forum:

https://forum.openzeppelin.com
