### ISSUE TITLE
LUSD on PulseChain Minting Function

### ISSUE THREAD

**Issue by ronsofficial29** [OpenZeppelin/openzeppelin-contracts#5027]
Actually I was checking Smart Contract of LUSD on Pulsechain token. Seems like minting function is still going on. And after some digging I came here because saw OpenZeppelin mentioned in the contract. So asking if you can help our community to stop the fixing issue.

**Comment by ernestognw** [comment]
Hey, this is an open-source library that's used by thousands of projects. We don't have any relationship with custom tokens deployed using our library so I'm afraid we can't help.

Feel free to share your questions in our [community forum](https://forum.openzeppelin.com) as long as it meets the forum guidelines.

Closing
