### ISSUE TITLE
Weird Error in Openzeppelin AI Wiz

### ISSUE THREAD

**Issue by 0xScratch** [OpenZeppelin/openzeppelin-contracts#5039]
Not sure whether this is the right place to point this issue (but the GitHub link points the official OpenZeppelin repo)

Here's the screenshots:
![Screenshot (7)](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/88618913/30bafa92-0ee4-4c98-9575-5582823227cc)

![Screenshot (8)](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/88618913/ab4f93ed-bde8-49e9-b161-a9da1dde9767)

**Comment by ericglau** [comment]
Thanks for reporting, this is fixed now in https://wizard.openzeppelin.com/
