### ISSUE TITLE
 Agency contract optimization

### ISSUE THREAD

**Issue by Smilestate** [OpenZeppelin/openzeppelin-contracts#5042]
version：5.0.0

**🧐 Motivation**
When I used the above version of the proxy contract, I was surprised to find that deploying the proxy contract would trigger the deployment of the proxyAdmin contract and give the proxy upgrade permission to proxyAdmin. I think it is unreasonable. If there are many proxy contracts in my project, I There are many admin contract addresses to remember.

**📝 Details**
I saw the constructors logic, admin, and data of the transparent proxy in the previous version. Among them, admin is the proxyAdmin contract address. It is possible to manage multiple agency contracts with one admin contract. But in the latest version, I found that the constructor is logic, owner, data, where owner is the manager who automatically deploys admin. That is to say, each agent contract will deploy an admin contract internally for management and upgrade. However, there is no external method to obtain the admin contract address, and it can only be viewed through the released changeAdmin event.

`/**
     * @dev Returns the admin of this proxy.
     */
    function _proxyAdmin() internal virtual returns (address) {
        return _admin;
    }
Added method to obtain proxyAdmin!

constructor(address _logic, address initialOwner, bytes memory _data) payable ERC1967Proxy(_logic, _data) {
        _admin = address(new ProxyAdmin(initialOwner));
        // Set the storage value and emit an event for ERC-1967 compatibility
        ERC1967Utils.changeAdmin(_proxyAdmin());
 }

constructor(address _logic, address admin_, bytes memory _data) payable ERC1967Proxy(_logic, _data) {
      _changeAdmin(admin_);
  }
Or adjust the constructor to the specified proxyAdmin contract address that has been deployed.
`
I hope it can be updated as soon as possible, because it is a headache for users to deploy multiple agents and have multiple management contracts! Hope to adopt!

**Comment by Smilestate** [comment]
@openzeppelin/contracts
The above 5.0.2 version does not provide view, but the source code provides the view method. Please update and sync.
<img width="814" alt="code" src="https://github.com/OpenZeppelin/openzeppelin-contracts/assets/39672519/b40be084-da7e-4176-a102-ebed3999aa39">
<img width="651" alt="npmjs" src="https://github.com/OpenZeppelin/openzeppelin-contracts/assets/39672519/f1949bc2-4f1c-4354-9c33-d2505e982f58">

**Comment by Smilestate** [comment]
Please allow my submission.
Solve the problem of upgrade and transition from 4.0.0 to 5.0.0 agent contract.

The following is my expectation, and I very much look forward to contributors pointing out my shortcomings.

https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5043

**Comment by cairoeth** [comment]
Closing as this is a [deliberate design decision](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5043#issuecomment-2111103894).
