### ISSUE TITLE
Breaking change that TransparentProxy creates its own ProxyAdmin is not mentioned in the doc

### ISSUE THREAD

**Issue by adu-web3** [OpenZeppelin/openzeppelin-contracts#5059]
**🧐 Motivation**

Breaking change not mentioned could easily cause unexpected behavior if latest version is adopted
**📝 Details**

For v5.0, there is a breaking change that the `TransparentProxy.constructor` accept the `initialOwner` as second argument instead of `proxyAdmin`, and an instance of `ProxyAdmin` would be created in constructor. But this behavior is not even mentioned in the release doc and could easily cause unexpected behavior and compatibility issues

**Comment by ernestognw** [comment]
Hi @adu-web3, would you mind clarifying how it can be easy to mess up?

5.0.0 is a major changes so breaking changes are expected as specified in the docs. Also, this change is listed in the CHANGELOG and the [release notes](https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v5.0.0), both on the Proxy section.

> TransparentUpgradeableProxy: Admin is now stored in an immutable variable (set during construction) to avoid unnecessary storage reads on every proxy call. This removed the ability to ever change the admin. Transfer of the upgrade capability is exclusively handled through the ownership of the ProxyAdmin. (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4354)

We also updated the documentation accordingly so it'd be nice to hear if you have comments to make it easier for people to adapt to this new behavior.

**Comment by adu-web3** [comment]
but you didn't mention `TransparentUpgradeableProxy`'s constructor would create a new proxy admin and store that admin, which is totally different behavior compared with previous constructor

**Comment by ernestognw** [comment]
There's no way to store a contract in an immutable variable if it's not during construction. I see it's fair to ignore that.

We can update both the changelog and release docs to get it more explicit.
Right now we already have a warning in [upgrades plugins' documentation](https://docs.openzeppelin.com/upgrades-plugins/1.x/#managing-ownership), also explicitly mentioned the [contract API](https://docs.openzeppelin.com/contracts/5.x/api/proxy#TransparentUpgradeableProxy)
