### ISSUE TITLE
File not found: ERC721URIStorage

### ISSUE THREAD

**Issue by ajinkyablockchain** [OpenZeppelin/openzeppelin-contracts#5064]
**💻 Environment**

**📝 Details**

```
//SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;


import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/utils/counters.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contract/token/ERC721/extensions/ERC721URIStorage.sol";

contract MyNft is ERC721URIStorage, Ownable{
    
    using Counters for Counters.Counter;
    
    Counter.Counter private _tokenIds;
    constructor() ERC721("MY Nft","CRE"){}
    function mintnft(address recipient,string memory tokenURI)public onlyOwner returns(uint264){
      _tokenIds.increment();
    }

}
```

Error: `[{ "resource": "/D:/NFT/contracts/MyNft.sol", "owner": "solidity-language-server", "code": "6275", "severity": 8, "message": "Source \"@openzeppelin/contract/token/ERC721/extensions/ERC721URIStorage.sol\" not found: File not found. Searched the following locations: \"\".", "source": "solidity", "startLineNumber": 8, "startColumn": 1, "endLineNumber": 8, "endColumn": 78 }]`

**🔢 Code to reproduce bug**

**Comment by bektigalan** [comment]
hi @cairoeth i couldnt find Counters.sol https://docs.openzeppelin.com/contracts/5.x/api/utils#Counters in "@openzeppelin/contracts": "^5.1.0",

**Comment by Amxx** [comment]
`Counters` (and `ERC721URIStorage`) was part or version v4.x. It is not available in v5.x
