### ISSUE TITLE
[Docs] Link render issue of contract comment

### ISSUE THREAD

**Issue by xieyuschen** [OpenZeppelin/openzeppelin-contracts#5085]
Hi maintainers, i'm new to the sol and its documentation management, and i got a link rendered wrongly when either reading from the floating window or the code directly, as the images showed below. Once clicking the link, it will jump to site: `https://forum.openzeppelin.com/t/how-to-implement-erc20-supply-mechanisms/226[How` which is 404.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/83c7e45092dac350b070c421cd2bf7105616cf1a/contracts/token/ERC20/ERC20.sol#L18

I'm not sure why we combine the title and the link together without any space. But I believe this might be an mimor issue due as it cannot be rendered properly in the floated window as well. Please correct me if there are some misunderstandings.

![Screenshot from 2024-06-17 19-42-39](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/52945328/24e3c638-2798-4c63-b2b1-43bbfeaa4c0b)

![Screenshot from 2024-06-17 19-44-04](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/52945328/885ea398-6581-41b9-b18b-80c98c9e87c8)

Regards

**Comment by Amxx** [comment]
Hello @xieyuschen 

This format is used by the doc generation system. The outcome  is visible here: https://docs.openzeppelin.com/contracts/2.x/api/token/erc20#ERC20.

I'm sorry your IDE is not processing links the same way, but you'll understand that the generation of the official doc takes priority over support by a variety of IDE/plugins that won't reach consensus anyway.
