### ISSUE TITLE
Enable override on safeTransferFrom

### ISSUE THREAD

**Issue by saingsab** [OpenZeppelin/openzeppelin-contracts#5150]
**🧐 Motivation**
Want to have a similar Souldbon token but with some condition, let's say in the future the token can be transfer but only form the admin or OP role based. 

**📝 Details**

this is the default  safeTransferFrom https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4764ea50750d8bda9096e833706beba86918b163/contracts/token/ERC721/ERC721.sol#L152

after add virtual then we can override.  
I am not sure if this is the best approach,

below  implement no longer work: 
```
function _beforeTokenTransfer(address from, address to, uint256 tokenId)
        internal
        override
    {
        require(from == address(0), "Token not transferable");
        super._beforeTokenTransfer(from, to, tokenId);
    }
```

**Comment by ernestognw** [comment]
Hi @saingsab,

Hooks were removed in 5.0, so `_beforeToken*` won't work anymore. Instead, we recommend overriding the [`_update` function](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4764ea50750d8bda9096e833706beba86918b163/contracts/token/ERC721/ERC721.sol#L242), which is the core of any token transfer within the contract and is `virtual`.

I'd suggest doing:

```solidity
function _update(address to, uint256 tokenId, address auth)
        internal
        override
    {
        require(from == address(0), "Token not transferable");
        super._update(to, tokenId, auth);
    }
```

**Comment by saingsab** [comment]
Wonderful, just had an update and it's working good!
