### ISSUE TITLE
`Address.sendValue` doesn't bubble errors

### ISSUE THREAD

**Issue by CodeSandwich** [OpenZeppelin/openzeppelin-contracts#5184]
**📝 Details**

`Address.sendValue` ignores errors coming from the value recipient and throws a custom error on failure. This doesn't seem very useful, when a smart contract `receive` reverts, it probably has some important details to share about the failure. It seems that the `functionCall` error handling would be better here, bubble the original error and throw a generic one only if the contract has absolutely no details to share.

**Comment by arr00** [comment]
I agree with this and created a PR to fix it.
