### ISSUE TITLE
Tag introduction version in contract comments

### ISSUE THREAD

**Issue by cairoeth** [OpenZeppelin/openzeppelin-contracts#5210]
**🧐 Motivation**

The main contract comments for new contracts in v5.1 should have a note that indicates in what version they were introduced, with the following format: 

```
* 
* _Available since v[major].[minor]._
```

Example: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/structs/MerkleTree.sol#L26

**Comment by mabsattar** [comment]
hi @cairoeth  can I work on this, I'd like to tackle it.

**Comment by cairoeth** [comment]
@mabsattar yes! thanks

**Comment by mabsattar** [comment]
@cairoeth  sent a PR, let me know if any changes needed. thanks
