### ISSUE TITLE
Max Total Supply / Holders

### ISSUE THREAD

**Issue by D33pst4t3** [OpenZeppelin/openzeppelin-contracts#5221]
Hello,

I am trying to add a fixed burn amount of tokens on all transfers using Openzeppelin v5 and the _update function.

When i modify the _update (override) function specificaly "emit Transfer(from, to, value - burnamount);" (the only change in the entire code of the smart contract) by adding a fixed burning of tokens amount i get this problem, i am not sure if it is a bug.

Initial total supply "_mint(msg.sender, 1000000 * 10 ** decimals ());" 1000000.

The correct amount of tokens are burned from the total supply, before i receive the tokens "999,999.5".

I do not receive the tokens even it is reported a success in the transaction hash.

"
Max Total Supply
Filtered by totalsupply(), method returned a zero value.

Holders
0

Total Transfers
1
"

The holders tab reports no entries.

Deployed using hardhat.

I tried adding "function totalSupply()", import ERC20Burnable.sol, pragma solidity ^0.8.20 or ^0.8.24 and other networks none of those changes work.

How to correct this problem/bug, thank you.

![ZeroHolders](https://github.com/user-attachments/assets/0784f0d1-5b32-43e1-a7f5-4c5e187805b4)
![ZeroSupply](https://github.com/user-attachments/assets/253c0a92-3454-4750-9650-c2673d1ef481)

**Comment by Skyge** [comment]
Hi, @D33pst4t3 it seems like your issue is not relative to the OpenZeppelin contract, maybe you can close this issue and ask at the [OpenZeppelin Forum](https://forum.openzeppelin.com/)
