### ISSUE TITLE
Update `solidity-coverage`

### ISSUE THREAD

**Issue by ernestognw** [OpenZeppelin/openzeppelin-contracts#5231]
### Description

On #5218 we're introducing a workaround to coverage issues in the coverage CI for P256. However, this workaround was deprecated in https://github.com/sc-forks/solidity-coverage/releases/tag/v0.8.7

We should update the library and drop the deprecated configuration. However, an attempt of doing so within the PR ended up in the compilation failing with multiple contracts generating unexpected warnings like:

```
Downloading compiler 0.8.24
Warning: Statement has no effect.
  --> contracts/utils/Context.sol:23:68:
   |
23 |     function _msgSender() internal view virtual returns (address) {abi.encode(0x730c7f785d17a153);  /* function */ 
   |                          
```

**Comment by arr00** [comment]
This is a result of using `hardhat-ignore-warnings` with the default that warnings are errors. The injected code for coverage results in the `Statement has no effect` warning and it can be safely ignored in coverage runs.

**Comment by arr00** [comment]
Per the conversation in #5282, the current config is ideal for our coverage--there are new issues that surface with the method for IR coverage in newer versions of `solidity-coverage`.
