### ISSUE TITLE
Move `vendor/erc4337-entrypoint` to mocks (or to other package)

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#5246]

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Amxx** [comment]
Fixed in
- https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5362
- https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5391
