### ISSUE TITLE
ERC20PermitUpgradeable causes clash on function nonces

### ISSUE THREAD

**Issue by naps62** [OpenZeppelin/openzeppelin-contracts#5256]
After creating a bare foundry repo with only `openzeppelin-contracts-upgreadeable`, the following contract fails to compile:

```
import "openzeppelin-contracts-upgradeable/contracts/token/ERC20/extensions/ERC20PermitUpgradeable.sol";

contract Counter is IERC20Permit, ERC20PermitUpgradeable {}
```

**💻 Environment**

openzeppelin-contracts-upgradeable commit `723f8ca`

**📝 Details**

At least intuitively, it doesn't make sense for this function to cause conflicts, but that seems to be the case. Unsure if this is due to a solidity limitation

output:

```
❯ forge build
[⠊] Compiling...
[⠆] Compiling 43 files with Solc 0.8.27
[⠰] Solc 0.8.27 finished in 257.84ms
Error:
Compiler run failed:
Error (6480): Derived contract must override function "nonces". Two or more base classes define function with same name and parameter types.
 --> src/Counter.sol:6:1:
  |
6 | contract Counter is IERC20Permit, ERC20PermitUpgradeable {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: Definition in "ERC20PermitUpgradeable":
  --> lib/openzeppelin-contracts-upgradeable/contracts/token/ERC20/extensions/ERC20PermitUpgradeable.sol:77:5:
   |
77 |     function nonces(address owner) public view virtual override(IERC20Permit, NoncesUpgradeable) returns (uint256) {
   |     ^ (Relevant source part starts here and spans across multiple lines).
Note: Definition in "IERC20Permit":
  --> lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/token/ERC20/extensions/IERC20Permit.sol:83:5:
   |
83 |     function nonces(address owner) external view returns (uint256);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Skyge** [comment]
I think the contract `ERC20PermitUpgradeable` is derived from the interface contract `IERC20Permit`, so in your contract, it has two functions `nonces()` with the same name and parameters, I think you can update your code as follows to solve this error:

```
import "openzeppelin-contracts-upgradeable/contracts/token/ERC20/extensions/ERC20PermitUpgradeable.sol";

contract Counter is ERC20PermitUpgradeable {}
```

**Comment by naps62** [comment]
That is correct. but in my original case, the code looks a bit more like this:

```
contract MyContract is ERC20PermitUpgradeable, IMyContract {
  ...
}

interface IMyCounter is IERC20Permit {
  ...
}
```

I was forced to implement `nonces` explicitly. But this seems like a weird behaviour because the same issue wouldn't happen if I used non-upgradeable openzeppelin (which is what the codebase had prior to my change).

**Comment by Skyge** [comment]
> because the same issue wouldn't happen if I used non-upgradeable openzeppelin (which is what the codebase had prior to my change).

Do you mean the following code without upgradable works well?
```
contract MyContract is ERC20Permit, IMyContract {
  ...
}

interface IMyCounter is IERC20Permit {
  ...
}
```

**Comment by Amxx** [comment]
Hello @naps62 

This is normal. It happens whenever you inherit from multiple contracts or interfaces that share common functions.
In you particular case, inheriting from `IERC20Permit` is superfluous, because `ERC20PermitUpgradeable` already inherits from it.

In other cases, you may have to resolve the override. You can see how the [OZ wizard](https://wizard.openzeppelin.com/) does that.

If you have similar question in the future, please submit them to the [OZ forum](https://forum.openzeppelin.com/).
