### ISSUE TITLE
Enable proposal cancelation by proposer after pending period

### ISSUE THREAD

**Issue by arr00** [OpenZeppelin/openzeppelin-contracts#5260]
**🧐 Motivation**
By default, cancelation is only possible by the proposer during the pending period. There have been many times in governance processes that issues with proposals were discovered during the active or even successful/queued phases. Giving the proposer the ability to cancel during these periods reduces the risk of a buggy proposal being executed.

**📝 Details**
This should be default functionality as it is unlikely a team spinning up governance would explicitly select to allow this behavior--once they know they need it, it would be too late.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fe6249ec2c2dcdbb05e2b6a0d0d3e229f6ffbb37/contracts/governance/Governor.sol#L468

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by arr00** [comment]
We will do #5301 instead.
