### ISSUE TITLE
Implementation does not match the interface: function signatures

### ISSUE THREAD

**Issue by 0xferit** [OpenZeppelin/openzeppelin-contracts#5263]
[ERC1155Holder](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/utils/ERC1155Holder.sol) implements [IERC1155Receiver](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/IERC1155Receiver.sol).

However, function signatures in implementation do not match the interface. See data location **(calldata vs memory)** and visibility **(external vs public)**. This seems wrong, and I wanted to bring this to your attention to make sure this is intended.

**Comment by Amxx** [comment]
Hello @0xferit 

This has been raised many time. I'm sure you'll find an explanation if you run a search.

**Comment by 0xferit** [comment]
Right. Thanks for the response. @Amxx 

Here is one of them: https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4811
