### ISSUE TITLE
Add supportsInterface function for ERC20

### ISSUE THREAD

**Issue by XZSt4nce** [OpenZeppelin/openzeppelin-contracts#5285]
**🧐 Motivation**
> [ERC-165](https://eips.ethereum.org/EIPS/eip-165)
> For some “standard interfaces” like the ERC-20 token interface, it is sometimes useful to query whether a contract supports the interface...

Recently, I needed to know if the contract at some address is an ERC20 token, but I did not find the supportsInterface function

**📝 Details**
Steps to add supportsInterface function:

1. Import ERC165 and IERC165
```soldity
import {IERC165, ERC165} from "../../utils/introspection/ERC165.sol";
```

2. Implement ERC165
```solidity
abstract contract ERC20 is Context, IERC20, IERC20Metadata, IERC20Errors, ERC165 {
    ...
}
```

3. In the function, you need to detect if a contract implements interfaces IERC20, IERC20Metadata and IERC165
```solidity
/**
 * @dev See {IERC165-supportsInterface}.
 */
function supportsInterface(bytes4 interfaceId) public view virtual override(ERC165, IERC165) returns (bool) {
    return
        interfaceId == type(IERC20).interfaceId ||
        interfaceId == type(IERC20Metadata).interfaceId ||
        super.supportsInterface(interfaceId);
}
```

**Comment by arr00** [comment]
Given that the [EIP](https://eips.ethereum.org/EIPS/eip-20) doesn't specify that 165 is not required, it is not added to the standard implementation. One could easily write an extension that makes their ERC20s compliant with 165 by adding the above code.
