### ISSUE TITLE
Documentation for `ExtendingContracts` is not compiled properly

### ISSUE THREAD

**Issue by TilakMaddy** [OpenZeppelin/openzeppelin-contracts#5289]
In the `Calling super` section, we see the following instead of code

`Unresolved include directive in modules/ROOT/pages/extending-contracts.adoc - include::api:example$access-control/AccessControlNonRevokableAdmin.sol[]`

**Comment by ernestognw** [comment]
Hi @TilakMaddy, just put out a PR for this. Thanks!
