### ISSUE TITLE
Use `calldata` instead of `memory`

### ISSUE THREAD

**Issue by abhi3700** [OpenZeppelin/openzeppelin-contracts#5291]
Shouldn't there be `calldata` type instead of `memory` as we are only reading its value?

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/448efeea6640bbbc09373f03fbc9c88e280147ba/contracts/utils/cryptography/ECDSA.sol#L91

Found some more in [cryptography/](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography) folder. Fixed in PR #5293 

```[tasklist]
### Tasks
- [x] Add a PR (if the issue is accepted)
```

**Comment by TheMarvelFan** [comment]
I would like to work on this issue, if possible.

Thanks!

**Comment by Amxx** [comment]
Closed (see PR)
