### ISSUE TITLE
Clock mode is wrong

### ISSUE THREAD

**Issue by EightRice** [OpenZeppelin/openzeppelin-contracts#5346]
I deployed the default Governor contract (no modifications) in `timestamp` mode with a `900` seconds votingDelay as confirmed by the read-only functions on the deployed contract.

After 11 minutes the state changes from 0 to 1 (from pending to active). 

The network is Etherlink-Testnet and the block timestamps are accurate. Contract is deployed at 0x54A2f9A2181237E2D655Ec65A690AC60B1fa5458

I stress the fact that I haven't made any changes to the standard Governor code. It seems this line is responsible for setting the duration 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/Governor.sol#L329

and it seems that the actual implementation is in this contract: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/extensions/GovernorSettings.sol

So what happens is that the voting delay of 900 seconds is added to the block number. The clock() function returns 15394923 which is (now) the block number of the network, **not a timestamp**. 

To reproduce the issue just grab the code from here: https://wizard.openzeppelin.com/#governor, set it to Timestamp and deploy it and then call the clock() function, which will show the block number. 
![image](https://github.com/user-attachments/assets/163764c5-f539-4f5d-857d-2d13de9d4b07)

Any help will be valued

**Comment by Amxx** [comment]
Hello @EightRice 

Can you share which token contract you are using. Governor contracts usually don't use their own clock, but rather inherit the clock from the voting token. This is because the voting checkpoints stored in the voting token are actually the element that decides who lookups should be done.

**Comment by Amxx** [comment]
Note: toggling between timestamp and block number on the wizard changes how the "settings" are initialized, but it doesn't affect how the contract sees time.

**Comment by EightRice** [comment]
Thanks for engaging @Amxx 
This is the token contract: 0x1d6667a9fFeDc7c62788c848aCB590BC2F3589cA and it's implementing ERC20, ERC20Permit, ERC20Votes
and it has this function:
```
   function CLOCK_MODE() public pure override returns (string memory) {
        return "mode=timestamp";
    }
```

Before adding this function to the Token contract, the CLOCK_MODE endpoint on the Governor was returning  `blockNumber` . Now it says `timestamp`. Is there something else I need to do in the Token contract?

**Comment by EightRice** [comment]
> Hello @EightRice
> 
> Can you share which token contract you are using. Governor contracts usually don't use their own clock, but rather inherit the clock from the voting token. This is because the voting checkpoints stored in the voting token are actually the element that decides who lookups should be done.
> 
> Edit: the instance you are using appears to be at "0x1d6667a9fFeDc7c62788c848aCB590BC2F3589cA". When querying "clock()", and "CLOCK_MODE()" on it, I get the same inconsistent results. Can you share the code for it?



> Hello @EightRice
> 
> Can you share which token contract you are using. Governor contracts usually don't use their own clock, but rather inherit the clock from the voting token. This is because the voting checkpoints stored in the voting token are actually the element that decides who lookups should be done.
> 
> Edit: the instance you are using appears to be at "0x1d6667a9fFeDc7c62788c848aCB590BC2F3589cA". When querying "clock()", and "CLOCK_MODE()" on it, I get the same inconsistent results. Can you share the code for it?

code for the token: https://github.com/dOrgTech/homebase-evm-contracts/blob/master/contracts/Token.sol

**Comment by EightRice** [comment]
@Amxx @absi7924  Can you share an example of a governance token implementing your standard that works correctly in Timestamp mode?

**Comment by Amxx** [comment]
> Thanks for engaging @Amxx This is the token contract: 0x1d6667a9fFeDc7c62788c848aCB590BC2F3589cA and it's implementing ERC20, ERC20Permit, ERC20Votes and it has this function:
> 
> ```
>    function CLOCK_MODE() public pure override returns (string memory) {
>         return "mode=timestamp";
>     }
> ```
> 
> Before adding this function to the Token contract, the CLOCK_MODE endpoint on the Governor was returning `blockNumber` . Now it says `timestamp`. Is there something else I need to do in the Token contract?

Changing the `CLOCK_MODE()` function is not enough. You must also change the `clock()` function. This is missing from https://github.com/dOrgTech/homebase-evm-contracts/blob/master/contracts/Token.sol.

If you used the [wizard](https://wizard.openzeppelin.com/) to make a voting token with timestamp, you'll see that the code is
```solidity
contract MyToken is ERC20, ERC20Permit, ERC20Votes {
    constructor() ERC20("MyToken", "MTK") ERC20Permit("MyToken") {}

    function clock() public view override returns (uint48) {
        return uint48(block.timestamp);
    }

    // solhint-disable-next-line func-name-mixedcase
    function CLOCK_MODE() public pure override returns (string memory) {
        return "mode=timestamp";
    }

    // The following functions are overrides required by Solidity.

    function _update(address from, address to, uint256 value)
        internal
        override(ERC20, ERC20Votes)
    {
        super._update(from, to, value);
    }

    function nonces(address owner)
        public
        view
        override(ERC20Permit, Nonces)
        returns (uint256)
    {
        return super.nonces(owner);
    }
}
```

**Comment by EightRice** [comment]
IT WORKED! 
thank you so much  @Amxx !
