### ISSUE TITLE
Coverage and test runs often result in `JavaScript heap out of memory`

### ISSUE THREAD

**Issue by arr00** [OpenZeppelin/openzeppelin-contracts#5363]
On MacOS, vanilla runs of the test and coverage npm scripts often results in a `JavaScript heap out of memory` error. This is a known issue with hardhat https://github.com/NomicFoundation/hardhat/issues/3471.

Increasing the allowed old memory to using the following env var fixes the issue `NODE_OPTIONS="--max-old-space-size=8192"`. We should consider documenting this or even setting the env var by default.

**Comment by Amxx** [comment]
The `.github/workflows/checks.yml` contains 
```
env:
  NODE_OPTIONS: --max_old_space_size=8192 
```

On my machine, I have it set in `~/.env`, which is then sourced by `~/.zshrc`.

I honestly think this is a very frequent error that is very well documented online. Should we make that default for everyone ? If we do so, could that cause issues on machine that have smaller ram ?

**Comment by Amxx** [comment]
For the record, if I type "JavaScript heap out of memory" in google, the first link I get is [this](https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory), which contains all the information to solve that.

**Comment by arr00** [comment]
I think we should set it by default--I'm not sure if it would cause issues on machines with too little memory... but the run would fail regardless for them.

**Comment by Amxx** [comment]
How would you set it ? Shipping a `.env` is considered bad practice

**Comment by arr00** [comment]
We could prepend it to the script in `package.json` such that it would be `"test": "\"NODE_OPTIONS=\"--max-old-space-size=8192 hardhat test"`

**Comment by arr00** [comment]
We could prepend the npm scripts in `package.json` like so: `"test": "NODE_OPTIONS=\"--max-old-space-size=8192\" hardhat test"`
