### ISSUE TITLE
Include support for TPL-compatible tokens

### ISSUE THREAD

**Issue by demibrener** [OpenZeppelin/openzeppelin-contracts#849]
## 🎉 Description

Regulation has become a big pain point for projects in the blockchain space. TPL is a protocol that aims to achieve regulatory compliance for cryptoassets in a decentralized way, a la DNS root zones or SSL certificate authorities. It would be great to have compliant, TPL-compatible token smart contracts in OpenZeppelin, the most popular smart contract library in the space today.

- [ ] 🐛 This is a bug report.
- [X] 📈 This is a feature request.

## 👍 Other Information

https://tplprotocol.org/
https://github.com/TPL-protocol/contracts/

**Comment by frangio** [comment]
Closing as TPL is no longer in active development.
